### ISSUE TITLE
Modal dismiss issue

### ISSUE THREAD

**Issue by johnsmith17th** [mgcrea/angular-strap#100]
I have a modal, and a button inside:

ng-click="doSomething(); dismiss();"

This works.

But when try to dismiss the modal in doSomething()

$scope.doSomething = function() {
    // do something...
    $scope.dismiss();
};

will get error: dismiss is undefined.

**Comment by turka50** [comment]
Hi , 

I couldn't make this work, something I've noticed is that the function you are calling is parentController whereas the function you've declared is parentControllerFn , So how could this work ? 
Even when i used the method @johnsmith17th  used it still didnt work.

I don't know if my case is the same case as what was said here , I have modal and every time i close it i just want it to forget everything that happened on it and just reload the modal as it as without any previously inserted data.

I'd very much appreciate your help.
