### ISSUE TITLE
bs-radio-group doesn't take advantage of ng-change

### ISSUE THREAD

**Issue by k-funk** [mgcrea/angular-strap#1000]
http://plnkr.co/edit/zsoCbS?p=preview
https://docs.angularjs.org/api/ng/directive/ngChange

I'd like a function to fire when this model is changed. Putting ng-clicks on inputs will probably fire before the model is changed.

**Comment by Armaklan** [comment]
+1

**Comment by rzschech** [comment]
+1

**Comment by rzschech** [comment]
I added a check mark by comparing the model value to the choice:

```
<ui-select ng-model="selected">
    <ui-select-match>{{$select.selected.label}}</ui-select-match>
    </ui-select-match>
    <ui-select-choices repeat="choice in choices">
        <span class="fa" ng-class="selected.id === choice.id && 'fa-check'" style="margin-left: -17px"></span>
        <span>{{choice.label}}</span>
    </ui-select-choices>
</ui-select>
```

**Comment by dhairya-avantsoft** [comment]
+1

**Comment by bogusugob** [comment]
+1

**Comment by adam-marshall** [comment]
+1

**Comment by compwright** [comment]
+1

**Comment by DaleWebb** [comment]
Would a `$watch()` suffice?

**Comment by compwright** [comment]
`$watch` does seem to work, but I would still prefer to be able to use ngChange as normal. In theory any ngChange could be replaced with a `$watch` expression in the controller, but for code organization and other reasons it isn't always the most desirable way.

**Comment by jeremyml** [comment]
+1

**Comment by germanoroettgers** [comment]
+1

**Comment by jeremyml** [comment]
+1
