### ISSUE TITLE
Display datepicker inline without input element

### ISSUE THREAD

**Issue by slavafomin** [mgcrea/angular-strap#1019]
Hi!

Thanks for this great library!

I'm trying to use DatePicker directive in my project that is not using Bootstrap at all. So we are in the middle of re-creating styles to display this widget correctly.

Is it possible to render this widget inline (not as a popup) inside of a DIV for example, without using any input elements at all? It will really help with styling and such. Or is it possible to at least prevent popup from closing?

Thanks!

**Comment by jacobvalenta** [comment]
+1

I wanted to place two date pickers side by side. In a high use area, minimizing the need to click would be nice.

**Comment by toymachiner62** [comment]
:+1:

**Comment by rzschech** [comment]
This is a duplicate of #430
