### ISSUE TITLE
DatePicker is not rendered correctly with latest Bootstrap 

### ISSUE THREAD

**Issue by slavafomin** [mgcrea/angular-strap#1020]
Hi! It's me again.

I've created a test-project to see how DatePicker is rendered with Bootstrap out of the box.

Here's how it's rendered in my project:

![screenshot - 29 08 2014 - 23 30 54](https://cloud.githubusercontent.com/assets/1702725/4095317/1348ce30-2fb3-11e4-8d34-1d485e7d0fc8.png)

Obviously it is very different from how it's rendered on the demo page:

![screenshot - 29 08 2014 - 23 34 33](https://cloud.githubusercontent.com/assets/1702725/4095341/92d73c22-2fb3-11e4-8137-04affb7a2b91.png)

Why is that?

Also, I'm trying to display arrows with font-awesome library using this code:

```
angular.extend($datepickerProvider.defaults, {
    iconLeft: 'fa fa-arrow-left',
    iconRight: 'fa fa-arrow-right'
});
```

But icons are not shown in the widget at all. However icons are rendered when I'm adding them to a page manually.

Please advise, thanks!

P/S:

I'm using the following libraries on the page:
- jQuery 2.1.1
- AngularJS 1.2.23
- AngularStrap 2.0.5
- Bootstrap 3.2.0 (only CSS)
- FontAwesome 4.1.0

**Comment by a2sc** [comment]
I had same trouble and I realized that the .switch class used by bootstrap-datepicker was used in another plugin where the .switch class has this property **display: inline-block;** 

You just have to add in your css file lines to get th display as table cell 
```
.datepicker th.switch {
    display: table-cell;
} 
```
It works for me. Hope it helps you
