### ISSUE TITLE
Angular bootstrap typeahead with vertical scrollbar not working with key up/down

### ISSUE THREAD

**Issue by infotechstuff1** [mgcrea/angular-strap#1021]
I need a vertical scrollbar for the typeahead results. I added following to enable a vertical scrollbar
.dropdown-menu {
    width: 300px;
    max-height: 400px;
    overflow-y: auto;
}

Scrollbar shows up fine. It works/scrolls when I use mouse wheel to scroll. However, when I use key up /key down to scroll to an element. It gets selected just fine but does the scroll does not happen and hence the selected element is not visible.

**Comment by usefulBee** [comment]
@infotechstuff1, did you find any solutions so far?
