### ISSUE TITLE
Popover data-container body

### ISSUE THREAD

**Issue by BobbieBarker** [mgcrea/angular-strap#1022]
I have a simple question on using data-container="body" vs data-target="self" with pop overs. 

if I use data-container body my data-placement="top-left" works nicely and the pop over and it's template look great. The problem is that when the user changes the page the popover stays open until the new page is rendered. 

If I use data-container-"self" or basically anything other than body, the popover looks smushed and the date-placement="top-left" does't work at all. The pop over just sits over the top of the button, and covers it up. However, as soon as the user navigates away from the current page the pop over is removed. 

Where is the happy middle ground here?

**Comment by armensg** [comment]
Did you ever get this sorted?
