### ISSUE TITLE
"bs-radio" element doesn't work well with attribute "ng-value" instead of "value".

### ISSUE THREAD

**Issue by benliu723** [mgcrea/angular-strap#1025]
When I use attribute “ng-value” in a "bs-radio" element instead of attribute "value", the element with attribute "bs-radio-group" works wired like:
when you click one of the radio in "bs-radio group" buttons, all of the radio buttons are selected with class "active".

I dig into the code and debug the code in "bsRadio", things go wrong with getting the value of a "bs-radio" element. the detail is listed as followings.

"src/button/button.js", line 140:
var value = constantValueRegExp.test(attr.value) ? scope.$eval(attr.value) : attr.value;

html code:

<div class="btn-group" ng-model="button.radio" bs-radio-group>
              <label class="btn btn-default"><input type="radio" class="btn btn-default" ng-value="0"> First</label>
              <label class="btn btn-default"><input type="radio" class="btn btn-default" ng-value="1"> Second</label>
              <label class="btn btn-default"><input type="radio" class="btn btn-default" ng-value="2"> Third</label>
</div>

when I debug the code in runtime at this line, I found attr.value equals "undefined", which means value haven't been applied while link function is running.

I set the priority of 'bs-radio' to 2, which is higher than 0. cause the priority of 'ng-value' is 0.
so that the linking function of those two directive is running in a right order. but the attr.value is still be "undefined".

I have no clue of what's wrong with it. 

and I find a final way to resolve "ng-value" problem, here is code of how to get the right value:
var value;
if (attr.ngValue) {
      value = scope.$eval(attr.ngValue);
} else {
     value = constantValueRegExp.test(attr.value) ? scope.$eval(attr.value) : attr.value;
}

Problem has been resloved by using this method.

I want to know if this is the right concept with yours.

Looking forward for your reply!

**Comment by JetFault** [comment]
+1 for this! Wouldn't this let value be things like objects and not only string, num, bool?
