### ISSUE TITLE
popover is hidden in ng-grid

### ISSUE THREAD

**Issue by DealerCorp** [mgcrea/angular-strap#1042]
define a cellTemplate in ng-grid:
div class="grid-action-cell" a data-template="{{popover.template}}" bs-popover Delete /a /div'
(< & > are removed in order to post html here)
the popover dialog is cut off (see image attached). 
if set placement to "left", the popover dialog is hidden entirely.
![capture](https://cloud.githubusercontent.com/assets/8525800/4205547/ab26a8e4-3841-11e4-869c-bb6fab3672ec.PNG)

**Comment by anurag01gupta** [comment]
I have the same issue in ag-grid. Could you please help me out.
