### ISSUE TITLE
Closing modal window doesn't re-enable body scrolling

### ISSUE THREAD

**Issue by mzgajner** [mgcrea/angular-strap#1050]
I'm trying to implement a modal which is a direct copy of the simple version (without an external template) from the documentation. When I open it, the `body` element receives a `modal-open` class, which sets `overflow: hidden` to prevent scrolling while the modal is open.

This is expected behaviour, the problem is that when I close this modal, the class doesn't get removed and the page is permanently un-scrollable. I'm using AngularStrap 2.1.0 and Angular 1.3 RC1.

**Comment by maeishoj** [comment]
When is the new version coming out? The above solution doesn't work for me as the event is never triggered :/

**Comment by npearson72** [comment]
@alexkpek 

+1

I'm still seeing this issue

**Comment by denishavranek** [comment]
+1

**Comment by cboden** [comment]
Issue still exists. Using angular-strap#`2.2.4` and angular#`1.3.16`

**Comment by cboden** [comment]
Issue still exists using angular-strap#2.3.1 and angular#1.3.16. Testing in latest Chrome.

**Comment by 1Jesper1** [comment]
Someone has a fix for this issue?

**Comment by Tatiinfo** [comment]
$('#myModal2').on('hidden.bs.modal', function () {
            $('#myModal1').data('bs.modal').handleUpdate();
        })
