### ISSUE TITLE
Modal interaction freezes on Chrome

### ISSUE THREAD

**Issue by ghost** [mgcrea/angular-strap#1051]
When a modal is opened on Chrome (I'm using version 37.0.2062.94), interactive buttons freezes - when you hover them, they stay hovered unless a window is resized.

This doesn't have anything to do with my code - even an example on your website acts the same.

The issue with this bug is if you add an HTML textarea tag, you can't add any text to it (well, unless a window is resized).

By the way, this only occurs when `placement: 'center'` options is used (I'm using BootstrapAdditions).

**Comment by xak2000** [comment]
Updated info about this issue in https://github.com/mgcrea/bootstrap-additions/issues/7#issuecomment-93425295
