### ISSUE TITLE
Trigger manual pop for a popover

### ISSUE THREAD

**Issue by skytracer** [mgcrea/angular-strap#106]
I am trying to get a manual trigger for a popover, because I want to pop it in response to  a http request data call.

However, I get a $apply in progress error.
If I add !$$scope.phase for the scope.$digest(); the popover position is not recalculated

Plunker here (only the manual trigger)

http://plnkr.co/edit/AbEmSsmZB9bJRaczOMhd

Thanks

**Comment by bagadim** [comment]
Hello.
Faced similar problem when I need to show triggered popup on page start.
Probably its not actual any more, but this one worked for me:

**index.html:**

`<div bs-popover data-title="Test" bs-show="$ctrl.showPopover"> </div>`

**controller.js:**
```
function testController($timeout) {
this.showPopover = false;
    // Call bs-show with timeout. Otherwise bs-show is triggered before bs-popover rendered.
    $timeout(function() {
        this.showPopover = true;
        }.bind(this), 50);
}
```
