### ISSUE TITLE
Modal hides the vertical browser scrollbar

### ISSUE THREAD

**Issue by rnrneverdies** [mgcrea/angular-strap#1081]
I'm testing modal window of angular strap 1.2.+ and something unwanted happens. In a large document while the modal is visible the browser scrollbar disappears. Then, when you close the modal, the browser scrollbar is displayed again and the document shrinks a bit.

I was looking at the developer tools by an hour, but I can not find the cause.

It's annoying when the document collapses.

http://plnkr.co/edit/yKZSnn?p=preview

TESTED ON Windows 8.1
      Chrome 36, Firefox 31, Opera 24 - Same results.

**Comment by JetFault** [comment]
Might be related to this: https://github.com/twbs/bootstrap/issues/9855

**Comment by JetFault** [comment]
Yep, need to add a scrollbar width checker + padder into Modal.

Looks like commits: https://github.com/twbs/bootstrap/commit/615dcb5ca068b1290cfd74d0f3b30272328f60fa
and https://github.com/twbs/bootstrap/pull/13103

**Comment by tomasszabo** [comment]
I can confirm that implementing both commits from bootstrap to angular-strap fixed the issue.
