### ISSUE TITLE
Typeahead Keydown Issue on Webkit

### ISSUE THREAD

**Issue by jcq** [mgcrea/angular-strap#1083]
When editing existing text in a bs-typeahead control, the cursor jumps to the end of the text input after every keydown event.  This may be an issue localized to Webkit-based browsers, as I can reproduce it on Chrome and Safari, but not Firefox (tested both Mac and Windows).

While this isn't that much of a problem when entering text when we start with a blank field, it becomes a large problem when making edits to a field with existing text in it. 

This issue can be reproduced using the [default Typeahead examples](http://mgcrea.github.io/angular-strap/##typeaheads).

**Comment by HarelM** [comment]
@vmlf01 Is this closed? I'm still getting it on chrome with latest version of angular and angular strap...?

**Comment by HarelM** [comment]
Any one? any workarounds at least?

**Comment by Kamilius** [comment]
I'm also getting this issue

**Comment by DaleWebb** [comment]
Looks like there was confusion between two pull requests in the past that covered the issue, but it may not have been merged.

I'll see if I can reproduce the bug and take a look at what the fix was in those, then PR a fix (and maybe a temp solution).

**Comment by Kamilius** [comment]
@DaleWebb thanks for info, Dale.

**Comment by Kamilius** [comment]
@DaleWebb currently checking v2.3.6 of Angular-strap, and for me, issue still persists. I'm entering "sample text" into input, and when trying to `delete` ample, symbol by symbol, cursor jumps to the end of input, after first keypress.

**Comment by DaleWebb** [comment]
Release `v2.3.8` doesn't contain the fix, however the `master` branch does

**Comment by Kamilius** [comment]
Ok, thanks :)
