### ISSUE TITLE
Hiding and showing angular-strap modal seems to create new scopes and break modal content's directive's dependencies

### ISSUE THREAD

**Issue by chrisguselle** [mgcrea/angular-strap#1094]
I have a angular-strap modal  which has some very complex directives inside as its content. The first time the modal window opens everything works as expected. However, when I hide the modal and then show show it again, I get Angular compilation errors saying that some of the directives in the modal can not find their 'required' directives' controllers on which they have dependencies and obviously the directives stop working as expected. 

It seems to me that upon hiding and showing the modal, Angular is creating new scopes which is breaking the directives' dependencies. My solution for now is to try and destroy the modal and all its scopes on close rather than hide and then recreate everything in its previous state when reopened. I am not happy with this solution though. 

Does anyone know how to prevent Angular from creating new scopes and thus keep my directives's dependencies from breaking when hiding and showing the angular-strap modal?

**Comment by vmlf01** [comment]
Please re-open with a test case if problem persists.
