### ISSUE TITLE
Affix not initializing on dynamic pages

### ISSUE THREAD

**Issue by keithmancuso** [mgcrea/angular-strap#1105]
it seems when you add bs-affix to elements loaded by a route they dont initialize properly?

is this a known issue?  is there some kind of workaround?  seems to fail on line 80

Cannot read property 'on' of undefined
targetEl.on('scroll', $affix.checkPosition);

im assuming its cause it cant find the element as its not fully loaded yet?

**Comment by tinyfly** [comment]
TargetEl is assigned to options.target which from what I can tell is the parent container target thing. It looks like the code assumes that this is defined but according to the docs it seems like this is totally optional.

By the way, I got this area when trying to use the `$affix` service. When I used the attributes on the directive in the markup I didn't see this issue.
