### ISSUE TITLE
bs-select : the selected text overflows on the caret when the width is fixed and the text is too long

### ISSUE THREAD

**Issue by sirius0607** [mgcrea/angular-strap#1112]
When you use a fixed width for bs-select it doesn't display as nice as bootstrap-select.

Here is a plunker showing the different display between the classical select, bs-select and bootstrap-select when the width is fixed and the selected text is too long.

http://plnkr.co/edit/ZEYHnozptm7Tim5WoscT?p=preview

The bs-select template misses a span element around the selected text to be able to hide the text overflow.

I tested with v2.1.1

**Comment by chielsen** [comment]
We need something like this indeed, without an element around the selected option I see now way to truncate it.
