### ISSUE TITLE
DatePicker style broke when using a different interpolateProvider

### ISSUE THREAD

**Issue by IsaacOliveira** [mgcrea/angular-strap#1115]
The month selector broke when a use a different interpolateProvider(the {{}} is used by django here)

The problem here is in the colspan of the th

Showed Here:
http://plnkr.co/edit/fce9qb6QDwUTp4fnTDKv?p=preview

**Comment by aldarund** [comment]
Why is it closed? its still valid issue, it should use current angular interpolate provider without need to modify templates manually. Look how its solved in other similar libs like angular bootstrap. They dont have this issue. They are replacing {{ and }} in templates with the current interpolate symbol.
