### ISSUE TITLE
bs-show datepicker with custom template is trying to show / hide picker before $datepicker.$element has been set

### ISSUE THREAD

**Issue by jonsamwell** [mgcrea/angular-strap#1129]
Hi,

I have a datepicker with a custom template (that is fetched from the server during dev).  I have the bs-show attribute on the element which is attached to a scope property.

``` language-markup
<div bs-datepicker ng-model="vm.inlineDatepicker.date" data-bs-show="vm.inlineDatepicker.show" data-container="self"></div>
```

The watcher for the bs-show attribute scope value is firing before the template has been fetched from the server and thus the $element for the datepicker hasn't been set so the method it needs to call on the element (on / off) is not there yet as the element hasn't been created.

The solution would be to postpone showing/hiding until the custom datepicker template has been loaded.

Jon

**Comment by leipert** [comment]
+1
