### ISSUE TITLE
Incorrect bottom-right placement of .dropdown-menu

### ISSUE THREAD

**Issue by irnc** [mgcrea/angular-strap#1131]
Please see http://plnkr.co/edit/oBPeRiPPQVWltkbCSEmP?p=preview for test case.

Cause for incorrect placement is miscalculated `tipWidth` caused by positioning of a `.dropdown-menu`.

**Comment by AdrianMF** [comment]
I was able to workaround this issue by setting: data-container="body" to my dropdown button

**Comment by stact** [comment]
hi
+1 i have the same issue but resolved with data-container="body"

**Comment by stact** [comment]
Another workaround. You can specify to the wrapper a fixed width as below:
```html
<li class="dropdown settings" ng-controller="SettingsController as settingsCtrl">
   <a href="#" class="dropdown-toggle" data-placement="bottom-right" bs-dropdown="links">
      My dropdown
   </a>
</li>
```

```css
.settings .dropdown-menu {
    width: 150px;
}
```

Working fine for me. Hope it helps

**Comment by seby321** [comment]
The problem happens when `.dropdown-menu` has a css rule `right:0`. 

When it is hidden from view by adding left:-9999 it will get very wide.

A fix is to reset .dropdown-menu elements to right: auto, as it is not really needed with angular-strap.

So,
<h6>CSS FIX</h6>
``` css
.dropdown-menu {
    right: 0;
}
```
