### ISSUE TITLE
Tool tips not appearing in ng-grid cell template

### ISSUE THREAD

**Issue by Krooted** [mgcrea/angular-strap#1132]
When implementing a ng-grid with custom cellTemplate I am unable to get the angular-strap tool tip to appear.  But I am able to get the Bootstrap-UI tool tip to appear.

tried: 
data-container="body"
cellClass: 'cellToolTip'
And the css:

.cellToolTip {
    overflow: visible;
}
.tooltip {
  top: 0 !important;
}

tooltip-append-to-body="true" 

couldn't get it to work.

Thanks,

**Comment by ocsike** [comment]
Hi,
I have same issue with ui-grid, here is the plunker http://plnkr.co/edit/rHlAmRe7Z5TxfHIqRBTq?p=preview

**Comment by vmlf01** [comment]
Looks like ui-grid is using an isolate scope which means the $scope.tooltip does not get inherited inside the ui-grid and that causes the tooltip text to be empty and not show up.

If you use a field that is in scope, it seems to work. Check the changes in the controller I made to you sample:
http://plnkr.co/edit/wsRVBbWsSt2Qlg1Kn4D0?p=preview

**Comment by ocsike** [comment]
Thank you!
