### ISSUE TITLE
Dynamic placeholder for bs-select

### ISSUE THREAD

**Issue by wingedfox** [mgcrea/angular-strap#1156]
I'll be glad to see an option to change placeholder value in runtime.
This is required for the app localization.
In conjunction with angular-gettext:
`<div bs-select data-placeholder="{{'Noting selected'|translate}}"></div>`

**Comment by flacohenao** [comment]
UP

**Comment by sateesh2020** [comment]
Any Update on this issue. Can we have a watch function for placeholder so that it will update when the locale value is changed
