### ISSUE TITLE
Disable or Hide dropdown menu items

### ISSUE THREAD

**Issue by orlaqp** [mgcrea/angular-strap#1158]
Hi there, first of all great library, thanks for sharing!

I am trying to hide/disable items in the drop down dynamically but I can't find a way to do it. Do you think it could be a good idea to implement something like this:

``` javascript
$scope.dropdown: [
  { 
     text: 'Menu 1', 
     click: 'doSomething()',  
     visible: 'counter === 2',        // only show this item if the condition is true, (default: true)
     disabled: '!actionAllowed' }  // only disable this item if the condition is true (default: false)
]
```

What do you think?

**Comment by gyss** [comment]
+1
