### ISSUE TITLE
angular-strap Alerts not floating until I import libraries.min.css

### ISSUE THREAD

**Issue by yerbie** [mgcrea/angular-strap#1179]
When I tried to use alerts in angular-strap, they were not floating until I imported libraries.min.css.  This css library is not documented and I'm not able to get.
http://plnkr.co/edit/RNbXqRWWJJrpNK4F0Y5h?p=preview

With the libraries.min.css, the alert overlays on top of the text, but when I remove that line, the alert will be displayed below.

If you remove this line, you should see the effect:
    <link rel="stylesheet" href="//mgcrea.github.io/angular-strap/styles/libraries.min.css">

**Comment by Sheshtawy** [comment]
How to use that less file then, I tried to covert it to CSS using and online converter but it gives me an error
