### ISSUE TITLE
Typehead $http cross domain origin error

### ISSUE THREAD

**Issue by arizona2014** [mgcrea/angular-strap#1195]
I'm using typehead as a directive in my HTML code and I also I created in my controller the $http.get call : 

  $scope.getAddress = function(viewValue) {

```
var params = {
    address: viewValue, 
    sensor: false       
};
return $http.get('http://maps.googleapis.com/maps/api/geocode/json', {params: params})
.then(function(res) {
  return res.data.results;
});
```

  };  

The problem is I have the following error : No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://...' is therefore not allowed access. The response had HTTP status code 405.

**Comment by mattgi** [comment]
I got this as well @arizona2014 .. did you ever figure out how the documentation works in plunker, but fails to work when you try to run it yourself?

**Comment by mattgi** [comment]
i just switched to using `maps.google.com/maps/api/js?sensor=false`

```
    var addressTimer;
    $scope.getAddress = function(viewValue) {
      $timeout.cancel(addressTimer);
      var deferred = $q.defer();
      var geocoder = new google.maps.Geocoder();
      addressTimer = $timeout(function() {
        geocoder.geocode({ 'address': viewValue }, function (results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            return deferred.resolve(results);
          } else {
            return deferred.reject();
          }
        });
      }, 600);

      return deferred.promise;
    };
```
