### ISSUE TITLE
bs-select IE11 - clicking on scroler hides dropdown

### ISSUE THREAD

**Issue by DmitryEfimenko** [mgcrea/angular-strap#1202]
If I apply custom css to limit the height of the list of options, it does not let me scroll in IE 11.
The following css is applied:
```
[bs-select] {
    /*position: relative;*/
    overflow: hidden;
    text-align: left;
}

.select.dropdown-menu {
    max-height: 100px;
    overflow-y: auto;
    /*width: 90%;*/
}
```

See [plunker example](http://plnkr.co/edit/17w963fz62PWdHYjmjCO?p=preview)

**Comment by JereStay** [comment]
+1

**Comment by mattklein999** [comment]
+1

**Comment by gizbo** [comment]
I need the same feature
+1
Thanks,
Yves

**Comment by sunilmunikar** [comment]
+1

**Comment by Simble** [comment]
A solution for this bug would be much appreciated.

**Comment by rapitkan** [comment]
+1

**Comment by jukkasi** [comment]
+1

**Comment by jukkasi** [comment]
Maybe the fix used in selectize.js https://github.com/benmj/selectize.js/commit/6e04d7bb6363c878706f9c4dbecdb354e12515a1 helps here?

**Comment by Gabriel0402** [comment]
+1

**Comment by DmitryEfimenko** [comment]
I've tried  multiple solutions suggested by people with similar issues and none worked for me. Did anyone had better luck?

**Comment by meishier** [comment]
+1

**Comment by benbynum** [comment]
+1

**Comment by benbynum** [comment]
I came up with something. Could probably be improved, but it works:

    $scope.dropdownFix = function() {
        var isIE = false;
        if(navigator.sayswho.indexOf('IE') !=-1) isIE = true;
        // navigator.sayswho can be found in link below

        $inputs = document.getElementsByClassName('ie-select-fix');
        for(var i=0;i<$inputs.length;i++) {
          // add blur listeners to all matching inputs
          $inputs[i].addEventListener("blur", blurFunction);
        }
        
        function blurFunction (e) {
          var active = document.activeElement.tagName;
          // if is IE and active element tag name is still UL, don't blur
          if (isIE && active =='UL') {
              e.preventDefault();
              e.stopImmediatePropagation();
          };
        }
      }

I call $scope.dropdownFix from the element's `ng-init`  and added the class name 'ie-select-fix'.

http://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browser

**Comment by jukkasi** [comment]
@benbynum works fine expect select does not close when clicked outside of it..

**Comment by benbynum** [comment]
@jukkasi good catch. It only closes if you haven't yet clicked the scroll bar. Solution: add the following line inside the conditional immediately below `e.stopImmediatePropagation();`:

    setTimeout(function(){
        e.target.focus();
    }, 1);

Should do the trick.

Lastly, I think putting all of this into a directive would be the most acceptable solution since DOM manipulation inside controllers isn't exactly good form.

**Comment by jukkasi** [comment]
@benbynum looks good, what's setTimeout for? At least in my tests it works without it (IE11)

So maybe change bsSelect postLink to be something like

    link: function postLink(scope, element, attr, controller) {        
      function isIE() {
        var ua = window.navigator.userAgent;
        return ua.indexOf('MSIE ') > 0 || ua.indexOf('Trident/') > 0 || ua.indexOf('Edge/');
      };    
      function scrollFixIE(e) {
        if (document.activeElement.tagName === 'UL') {
          e.preventDefault();
          e.stopImmediatePropagation();
          e.target.focus();
        };
      };       
      if (isIE()) {      
        element[0].addEventListener("blur", scrollFixIE);
      };
    ...

**Comment by DmitryEfimenko** [comment]
I tried to apply proposed solution, but when clicking on scroolbar it closes and re-opens right away. Unable to scroll

**Comment by DmitryEfimenko** [comment]
as I stated earlier, the PR does not fix the issue for me... now I can't use the scroller: Once I click it - it quickly hides and re-appears.
Not sure if this is due to the fact that I have animations enabled on drop-down.

**Comment by DmitryEfimenko** [comment]
can anybody confirm this behavior?

**Comment by jukkasi** [comment]
@DmitryEfimenko how about providing plunker example, steps to reproduce, your browser setup etc.

"Does not fix" probably won't get your issue fixed

**Comment by Xrew** [comment]
Hi, I need a help. I have udpated my angular-strap to version to 2.3.6, but the the issue with scrollbar wasn't fix. Can you please help me, what can i do wrong? I have checked library version an the code of the bs-select directive. It seems to be correct, but behaviour is incorrect. Any idea?

**Comment by Xrew** [comment]
I now why it doesnt work. It is because, you check in method $selectScrollFix if the element, that cause blur event is "UL" but i didnt use UL in my bsSelect. Is there any possibility implement bsSelect directive to be more generic, so that i can use "DIV" tag in my select template?

**Comment by Xrew** [comment]
Another one solution could be define special attribute to main element and then if the $selectScrollFix method check the blur event, search if this event has been invoked from the target with this special attribute.
