### ISSUE TITLE
TimePicker - Change Hour/Min by Up-Down Arrow Not Working

### ISSUE THREAD

**Issue by sameer22** [mgcrea/angular-strap#1218]
With AngularJS Version 1.3.0 and Angular-Strap 2.1.2, I am unable to change the time.

Same is working with AnuglarJS version 1.2.10 and Angular-Strap 2.1.2.

**Comment by adrianboimvaser** [comment]
will this get fixed? I'm having the same issue.

**Comment by vmlf01** [comment]
Are you using the latest AngularStrap version? You can see a sample on the current docs pages.

**Comment by sameer22** [comment]
as @vmlf01 mentioned. Working for me.
