### ISSUE TITLE
Datepicker initially shows wrong date

### ISSUE THREAD

**Issue by dready** [mgcrea/angular-strap#1226]
Hi,

i am not sure if it's related to any specific issue therefore i write a new one.

Somehow the model Date Element get's the entered date - 1 day.

For Example if i click on November the 5th of this year: 05/11/2014 then the $scope.fromDate is 2014-11-04T23:00:00.000Z. (see screenshot)

This was tested on the angular-strap demo page as the screenshot suggests.
http://mgcrea.github.io/angular-strap/##datepickers

I am Located in Vienna/Austria/Europe and our timezone is UTC+01:00

The fun part, if i load a model that has a date it works more or less as expected.

Any Ideas? Thanks
![screen shot 2014-11-04 at 13 17 04](https://cloud.githubusercontent.com/assets/454376/4899588/d2ed9376-641d-11e4-981e-d32dafa176bb.png)

**Comment by dsmithco** [comment]
Frustating to save one date and then get another one back....
I was able to do what I needed by setting...

data-date-type="string" data-date-format="M/d/y" data-model-date-format="y-MM-d" 

My model (Rails app) will accept a date format of "2014-1-15"
