### ISSUE TITLE
Tabs makes my form $dirty

### ISSUE THREAD

**Issue by just-boris** [mgcrea/angular-strap#1233]
I have a form divided by tabs, like this

``` html
<form name="form.myform" class="form-horizontal"
      ng-submit="save()">
    <div bs-tabs ng-model="selectedTab">
        <div data-title="Common" bs-pane>
            //some inputs
        </div>
        <div data-title="Extra" bs-pane>
            //some another inputs
        </div>
    </div>
    <div class="pull-right">
            <button type="button" class="btn btn-default" ng-click="close()">Close</button>
            <input type="submit" class="btn btn-default" ng-class="{'btn-success': form.myform.$dirty}" value="Save changes" />
     </div>
</form>
```

I track `form.$dirty` property to show message for user about unsaved changes
Without `ng-model` on tabs all working good, but when I had added it, form remains `$dirty` forever.
What do I do? I think, that is bad idea to bind active tab to model, because it is not actual change which should be saved on server.

**Comment by joaoborsoi** [comment]
I have the same issue with collapse. There is already an open issue at https://github.com/mgcrea/angular-strap/issues/1561 but with no answer. It would be great a similar solution.
