### ISSUE TITLE
Modal dialog allows tab navigation in background

### ISSUE THREAD

**Issue by wingedfox** [mgcrea/angular-strap#1238]
Issue is reproducible on the demo page.
Steps:
1. Open http://mgcrea.github.io/angular-strap/ demo page
2. Open modal dialog
3. Press "Tab" key several times
Expected result:
Tab changes focused items within the modal dialog only
Actual result:
Focus leaves modal dialog and allows to scroll page, activate links, etc

**Comment by vmlf01** [comment]
Duplicate of #839
