### ISSUE TITLE
Picker arrow behavior does nothing with initial value empty

### ISSUE THREAD

**Issue by tinyfly** [mgcrea/angular-strap#1241]
To build off of #603. 

If I start with an initial empty model value and have the behavior type set as picker nothing happens when I click a picker arrow.

**Current behavior:**
When I click a picker arrow first nothing happens. However if I click on the time and then click the arrows everything works just fine.

**Expected behavior:**
On first click of one of the picker arrows, it should select the time too.

[Here is and example plunker](http://plnkr.co/edit/xzDh03baXVn4yztrhXnS?p=preview)

**Comment by daemon1981** [comment]
:+1:

**Comment by lemoigne** [comment]
+1 I have the same problem @tinyfly.
