### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by ThatBritishDeveloper** [mgcrea/angular-strap#1254]
This is great piece of work -  but are there any plans to create Typescript definitions? Perhaps they could be pulled into Boris Yankov's DefinitelyTyped (https://github.com/borisyankov/DefinitelyTyped). 

Thanks,

**Comment by nelsonmorais** [comment]
Hi,

Is there any progress on this issue?

Thanks

**Comment by samherrmann** [comment]
I started working on this. See https://github.com/borisyankov/DefinitelyTyped/issues/2181.
Is there anyone, maybe even someone from the angular-strap main contributors, that could review my work when I'm ready? Let me know if you want me to tag you in the pull request. Thanks!

**Comment by nelsonmorais** [comment]
Great news! Yes, please tag me when you add the pull request. Thanks!

**Comment by ChrisTorng** [comment]
How is it now? Anything that can share with us?

**Comment by samherrmann** [comment]
Ok, I have a "alpha" version on my DefinitelyTyped fork: https://github.com/samherrmann/DefinitelyTyped/pull/1

Can some of you review it and/or try it out before I create a pull request on the DefinitelyTyped repo? Thanks!

@ThatBritishDeveloper 
@nelsonmorais 
@ChrisTorng

**Comment by diwalak** [comment]
+1.
Would be great to have this

**Comment by keithmullins** [comment]
+1
Would love to see this also.

**Comment by samherrmann** [comment]
@mgcrea, this issue can be closed. The type definitions have now been [merged into DefinitelyTyped] (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7061).
