### ISSUE TITLE
Angular Strap: Date Range (Start Date Not Working)

### ISSUE THREAD

**Issue by paulcruse3** [mgcrea/angular-strap#1284]
Everything works great except dynamic date ranges based on angular models.

What I want is quite simple: the second date input STARTS where the 1st input was selected. Heres the code that does NOT work:

Depart Date (1st input) [works fine]

```
<input required name="dapart_date" class="form-control" id="leave_date" placeholder="mm/dd/yyyy" ng-model="flightSearchData.depart_date" data-date-format="MM/dd/yyyy" data-use-native="true" data-autoclose="true" data-min-date="today" bs-datepicker>
```

Return Date (2nd input) [`data-start-date` doesn't work]    

```
<input required name="return_date" class="form-control" id="return_date" placeholder="mm/dd/yyyy" ng-model="flightSearchData.return_date" data-date-format="MM/dd/yyyy" data-use-native="true" data-autoclose="true" data-min-date="{{flightSearchData.depart_date}}" data-start-date="{{flightSearchData.depart_date}}"  bs-datepicker>
```

`data-min-date` works fine but `data-start-date` only works if I hard code a date.

Any suggestions...?

**Comment by baroniparson** [comment]
I'm attempting to do this very same thing.  Any idea how to make this work?

**Comment by paulcruse3** [comment]
@baroniparson  No, I never got it to work.

I had to use use [bootstrap datepicker] (http://eternicode.github.io/bootstrap-datepicker/)

I then did this to get the date values out and into angular:
<code>
$('.input-daterange .dateRangeStart').val()
</code> 
(.dateRangeStart is my custom class I tagged the input with; input-daterange comes from the date-picker)

By default the data format is 'mm/dd/yyy' so you may need to format it with angular before you use it. My exact code was:
<pre>
//customDateFormat is a function that splices on '/' and creates a new format
$scope.dateRangeStart = $scope.customDateFormat($('.input-daterange .dateRangeStart').val())
</pre>

**Comment by baroniparson** [comment]
@paulcruse3 Thanks for the reply.  I decided to use the ng-change directive on another date field to set the value (not the data-start-date value) of another date field to the selected value.  Said another way I used the value in dateField1 to populate the value in dateField2.
