### ISSUE TITLE
Typeahead doesn't highlight matching portion as bold

### ISSUE THREAD

**Issue by hendryluk** [mgcrea/angular-strap#1316]
AngularStrap's typeahead component doesn't seem to match original's bootstrap typeahead behaviour, i.e. marking matching letters within the results with a bold font. (http://getbootstrap.com/2.3.2/javascript.html#typeahead)
Is there any reason this is the case (considering AngularStrap uses bootstrap underneath), and whether there's any way to enable that same behaviour?

Thanks
Hendry

**Comment by jjstrat3** [comment]
You could use a filter.  Bootstrap-UI includes a filter for their typeahead directive.  The code below is exactly what they do.

```
.filter('highlight', function() {
      function escapeRegexp(queryToEscape) {
        return queryToEscape.replace(/([.?*+^$[\]\\(){}|-])/g, '\\$1');
      }

      return function(matchItem, query) {
        return query ? ('' + matchItem).replace(new RegExp(escapeRegexp(query), 'gi'), '<strong>$&</strong>') : matchItem;
      };
    })
```

**Comment by borgogelli** [comment]
Shoud I call it from bs-option like that ?

bs-options="item.desc for item in getItems($viewValue) | filter:highlight"

It does not seem to work. any advice ?

**Comment by glauberramos** [comment]
I suggest you to use the code on your "getItems" function. You can use this code:

```
function escapeRegexp(queryToEscape) {
    return queryToEscape.replace(/([.?*+^$[\]\\(){}|-])/g, '\\$1');
}

function(matchItem, query) {
        return query ? ('' + matchItem).replace(new RegExp(escapeRegexp(query), 'gi'), '<strong>$&</strong>') : matchItem;
 };
```

**Comment by borgogelli** [comment]
query in 'return function(matchItem, query) is always undefined

**Comment by glauberramos** [comment]
can you post your whole code somewhere so I can take a look?
