### ISSUE TITLE
Typeahed not working on Firefox when using objects in model

### ISSUE THREAD

**Issue by fedemoretti** [mgcrea/angular-strap#1319]
Typeahead does not work (on first selection) on Firefox when ng-model is using objects.
I'm using the examples in http://mgcrea.github.io/angular-strap/#/asides#typeaheads

Steps:
- Write "glob" in the second example (icons).
- Select "Globe" option.
- Click outside the input.

Actual result:
- The model transform from an object to the string "Globe"

Expected result:
- The model should remain an object.

Note:
This only happens the first time an option is selected.

**Comment by shabak** [comment]
wating for fix...

**Comment by nick-brown** [comment]
Yikes, ran into this one today and found out I was dropping a bunch of important data from FF users.

Anyone know if [UI-Bootstrap](https://angular-ui.github.io/bootstrap/) has this issue?  Can't wait 6 more months for a fix on this one.

**Comment by moehnen** [comment]
this is a really annoying bug.
i would like to fix it - but it's really hard to debug and i have no clue where to start.
For me this workaround helps:
```javascript
                $scope.$watch('myModel.property',
                    function(newValue,oldValue) {
                        if (newValue !== oldValue) {
                            // revert change if newValue is a string 
                            if (angular.isString(newValue) && angular.isObject(oldValue)) {
                                myModel.property = oldValue; 
                            }
                            ...
                        }
                    });
```

**Comment by proft** [comment]
the same behavior in firefox :(
please, fix

**Comment by just-boris** [comment]
Oh, such a long issue!
+1 from me.
