### ISSUE TITLE
modal backdrop completly black without opacity

### ISSUE THREAD

**Issue by readme42** [mgcrea/angular-strap#1323]
[See this Plunkr](http://plnkr.co/edit/3mMlvsZXTwSlgvXyvWqp?p=preview)

Everything works fine until you remove the script: 
`<link rel="stylesheet" href="//mgcrea.github.io/angular-strap/styles/libraries.min.css">`

Then the backdrop looks like:
![image](https://cloud.githubusercontent.com/assets/1941305/5219212/93bc25ce-7655-11e4-836c-2fc3da52a41f.png)

Is this behaviour intentionally or a bug?

**Comment by acutus** [comment]
Seems like @rzschech fix would be a good one as it seems to mimick bs-behavior, no workarounds needed to your own CSS. Pull-request?
