### ISSUE TITLE
'Today' option on Datepicker

### ISSUE THREAD

**Issue by M21B8** [mgcrea/angular-strap#1330]
Suggestion for an enhancement on the date pickers. It would be really useful, in some situations, to show a button on the date picker to allow a user to jump back to the current day. e.g. they've scrolled through a number of months/years, but now want to get back to where they started.

**Comment by mmouterde** [comment]
+1

**Comment by Simble** [comment]
+1

**Comment by squadwuschel** [comment]
+1

**Comment by kenyus** [comment]
+1

**Comment by Alayode** [comment]
+1

**Comment by aungjcs** [comment]
+1
