### ISSUE TITLE
Datepicker and "maxlength" Bug

### ISSUE THREAD

**Issue by squadwuschel** [mgcrea/angular-strap#1340]
when you use the bs-datepicker Directive like this:

{{ctrl.SearchModel.StartDatum}}

input type="text" class="form-control" name="Startdatum" ng-model="ctrl.SearchModel.StartDatum"
                            maxlength="255" id="Startdatum" bs-datepicker placeholder="Startdatum"

and when you habe the maxlength Attribut in it when you select a Date you will see that the "{{ctrl.SearchModel.StartDatum}}" is "clear" and no Modelvalue is in it, but the datepicker it self shows the selected Date but the Modelvalue is clear.

http://plnkr.co/edit/XbkXLTzUOJZrVEchANKb?p=preview

(I've updated plunker with both Version maxlength and without)

**Comment by fyodorvi** [comment]
Same issue. Note that validation is failing, ng-invalid-max-length.
