### ISSUE TITLE
on initialize, bs-typeahead does not render correct text value when consuming a model object

### ISSUE THREAD

**Issue by jusopi** [mgcrea/angular-strap#1342]
plunker - http://plnkr.co/edit/S7Iy2vNp6AFMS2JAaUjA?p=preview

I'm not sure if this is a bug or just a missing feature.  I have a typeahead input that consumes objects:

``` html
<input type="text" class="form-control" ng-model="data.selected" 
   ng-options="obj.value as obj.name for obj in data.list" bs-typeahead>
```

When the page initially renders, I'd expect that the input would render a text value matching the value against the list of objects and return the name of the match.  Instead it is blank.  

I did not see a label function in the docs.  Please advise.

**Comment by sameer22** [comment]
@jusopi .....Have u came across any solution?

**Comment by jusopi** [comment]
Yeah, I decided to not use this library and build an NPM package for angular bootstrap https://www.npmjs.com/package/angular-bootstrap-npm

**Comment by sameer22** [comment]
okay.

**Comment by avarabei** [comment]
Is any solution planned?

**Comment by saragg** [comment]
This is not exactly an issue. For angular to intialize with the correct option, it needs a reference to one of the objects inside the options list. Same thing happens with the normal angular select and ng-options.

Thanks @ester87 for the solution : )

**Comment by avarabei** [comment]
But what if I need the functionality with dynamic list based on input, like described on http://mgcrea.github.io/angular-strap/#/typeaheads#typeaheads with async via maps.googleapis.com. There is no options list until you enter something. For the time being I've made temporary solution locally:

From:

```javascript
        controller.$render = function () {
          if(controller.$isEmpty(controller.$viewValue)) return element.val('');
```

Changed to:

```javascript
        controller.$render = function () {
          if(controller.$isEmpty(controller.$viewValue)) return element.val(**controller.$modelValue**);
```
I had not time to analyze what this can cause, but for now it works great for me.

**Comment by jusopi** [comment]
@saragg I disagree. Be it a bug or missing feature, it's incumbent upon the component to initialize to a preset value or update to a non-ux initialized value when it renders.

This is the way nearly every other component of this type works, JavaScript or otherwise. In fact the ui.bootstrap, while certainly not free from major issues, does this no problem.

**Comment by imdadul** [comment]
Yes, this is a serious bug. I may want to set my value of the bs-typeahead input field from inside the code, which  seems not happening right now.
My case, can't populate a input field by setting the value of ng-model.

Someone created plunker for that, default value of ng-model is not reflecting! 
http://plnkr.co/edit/ZxmJ012f0FNhG10Zfu6i?p=preview

**Comment by manikantag** [comment]
@sloot14 fix seems working fine.

    controller.$render = function () {
        if(controller.$isEmpty(controller.$viewValue)) return element.val(controller.$modelValue);

**Comment by manikantag** [comment]
@mgcrea @vmlf01 Can you review the change? Thanks

**Comment by sameer22** [comment]
@manikantag As you mentioned, fix from @sloot14 seems working. A review & update request to @mgcrea and @vmlf01 

Thanks

**Comment by manikantag** [comment]
But it causing validation issues. Try to put 'required' validation and see the typeahead text field is marked as $invalid due to 'required' error.

Any solution for this?

**Comment by sameer22** [comment]
In my case, 'required' is not there. Need to check. If so, @sloot14, can look at it?

Thanks.

**Comment by blackpenny15** [comment]
Yeah @sloot14 's fix seems to have nerfed validation

**Comment by blackpenny15** [comment]
Looking at it the field is left $invalid:true after doing this
