### ISSUE TITLE
Multiple modals opened, first one closed clears the 'modal-open' class from body

### ISSUE THREAD

**Issue by hoinarut** [mgcrea/angular-strap#1343]
If one has multiple modals opened at any given time, when first modal is closed it removes the 'modal-open' css class from body, occurring in function leaveAnimateCallback().

As a temp solution for my case i have made a small directive which listens for modal.hide event and checks if any other modals are still on and re-adds the css class to the body element. However that was also an issue as in the above function 1st the event is emitted and then the css class is removed - modified that as well to 1st clean the css classes and only after to trigger the event.

**Comment by Zjaaspoer** [comment]
+1

I'm experiencing this also. Right now the system breaks if you want to work with multiple modals because of the above mentioned reasons.

**Comment by simonered** [comment]
Adding "overflow-y: auto;" to modal CSS class is not a good idea because if main page has vertical scrollbar, it appears next the modal's one, resulting in 2 annoying vertical scrollbars!
![screenshot](https://cloud.githubusercontent.com/assets/11872973/7070092/09327a5c-dedd-11e4-8184-88203c2e793c.png)

Has someone found a solution?

**Comment by matthewdfleming** [comment]
This is what we're doing that seems to work ok.. in a run block we're keeping track of all of the modals that are open (so we can close them on route changes). So we have these listeners..
        
        var modals = [];
        // auto track $modal windows
        $rootScope.$on('modal.show', function (e, $modal) {
            // if modal is not already in list
            if (modals.indexOf($modal) === -1) {
                modals.push($modal);
            }
            if (modals.length >= 0) {
                $document.find('body').addClass('modal-open');
            }
        });

        // un-track $modal windows on hide
        $rootScope.$on('modal.hide', function (e, $modal) {
            var modalIndex = modals.indexOf($modal);
            modals.splice(modalIndex, 1);
            if (modals.length === 0) {
                $document.find('body').removeClass('modal-open');
            }
        });

Seems to be ok.. haven't fully put it through it's paces yet though.

**Comment by pashamesh** [comment]
+1

**Comment by mesouug** [comment]
+1

**Comment by JetFault** [comment]
+1

**Comment by ckris** [comment]
That is bug in bootstrap, for fix adding condition for visibility modal.

replace Modal.prototype.hideModal  with this
...
Modal.prototype.hideModal = function () {
    var that = this
    this.$element.hide()
    this.backdrop(function () {
      
      if (!$('.modal:visible').length) {
        that.$body.removeClass('modal-open')
      }
      
      that.resetAdjustments()
      that.resetScrollbar()
      that.$element.trigger('hidden.bs.modal')
    })
...

**Comment by tobalsgithub** [comment]
We're seeing this too. Trying out a solution similar but simpler to what @matthewdfleming suggests above. In our `run` block, we just have this:

```js
  $rootScope.$on('modal.show', function (e, $modal) {
    $document.find('body').addClass('modal-open');
  });
```

We couldn't see a reason why we needed the logic of keeping track of whether a modal was already open or not. Seems like if any modal is open, the `modal-open` class should be on `body`. And we've never seen an issue with the `modal-open` class getting removed when a modal is closed. So this seemed sufficient and simpler.

If there's a reason not to do this, would love to hear it.

**Comment by equilerex** [comment]
+1

**Comment by andyg2** [comment]
By adding an additional class (e.g. sub-modal) to any secondary modals you can mitigate this problem quite easily.

> 		$(document).on("hidden.bs.modal",".sub-modal.modal", function () {
> 			$("body").addClass("modal-open");
> 		});

**Comment by DaleWebb** [comment]
Are you still running into this problem, @andyg2?

**Comment by andyg2** [comment]
Dale sorry no, I was searching for solutions for regular BS 3.35 (https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js) when I worked out this hack and shared it here without noticing this is a distinct repo. It very possibly doesn't relate to Angular Strap at all. Apologies.

**Comment by majidferdossi** [comment]
late answer, but i think it's worth it ;)

**Comment by robertfernanV** [comment]
Hello, searching in google, I came here, I do not know if it was useful for this repository, but for a web page, what helped me was a setimeout and the second modal shows well with the class
for example
` $('first_modal').modal('hide');`
` setTimeout(function(){ $('second_modal').modal('show'); }, 500);`

**Comment by ayophanz** [comment]
jQuery('.modal').on('show.bs.modal', function (e) {
	    jQuery('body').css('overflow-y', 'hidden');
	})
	jQuery('.close').on('click', function (e) {
	  jQuery('body').css('overflow-y', 'scroll');
	})


**paste that in script and problem solve, it takes me a minute to solve the same problem, I think this is bugs on bootstrap**

**Comment by artdias90** [comment]
would be nice to either: -provide a no-jquery solution for this; - solve the real issue

**Comment by 1Jesper1** [comment]
Someone has a fix for this?
