### ISSUE TITLE
 DatePicker doesn't clear selected item when date field is cleared

### ISSUE THREAD

**Issue by bryantlikes** [mgcrea/angular-strap#1346]
If you select a date using the datepicker and then clear the datepicker textbox, the last date you selected will still be highlighted in the calendar when you click the textbox again. 

This issue is easily replicated and can be tested on the homepage. 
http://mgcrea.github.io/angular-strap/##datepickers

**Comment by yaboi** [comment]
+1

**Comment by maheshchari** [comment]
+1

**Comment by SzilardVigh** [comment]
+1

**Comment by astromac** [comment]
+1

**Comment by rpocklin** [comment]
There is an existing PR that fixes this - https://github.com/mgcrea/angular-strap/pull/1914

**Comment by ChristophWuerzlhuber** [comment]
+1

**Comment by grek-andrian** [comment]
+1
