### ISSUE TITLE
bs-tab random order

### ISSUE THREAD

**Issue by birdcw** [mgcrea/angular-strap#1348]
The order of tabs changes unexpectedly upon different page loads and does not match the order of $scope.tabs. The tab index matches whatever order renders on the page. The tabs are otherwise working as expected.

``` html
<div bs-pane ng-repeat="tab in tabs" data-title="{{tab.title}}" ng-include="tab.page"></div>
```

`````` js
$scope.tabs = [
        {title: "", page: ""},``` ...
``````

**Comment by gedankennebel** [comment]
@vmlf01 The nested div did the trick. Although it´s strange :)

**Comment by LennyLip** [comment]
@vmlf01 
thanks,  nested div with ng-include works 

i think, plnkr must be with nested div. from here:

https://github.com/mgcrea/angular-strap/issues/1182
