### ISSUE TITLE
Opening multiple 'aside'

### ISSUE THREAD

**Issue by ramaraj-karuppusamy** [mgcrea/angular-strap#1353]
When opening a 'aside', if any other 'aside' then it has to move left/right. When changing the url, need to close all the existing aside. Can any one provide the solution?

**Comment by jrgranell** [comment]
I believe I have a similar request, and have asked on SO for advice

http://stackoverflow.com/questions/27827458/angular-strap-get-access-to-containing-element-in-an-aside-modal

I'm creating modal/aside inside a directive injecting $modal/$aside then calling it with some options. I get back an object that contains a number of properties including hide(), show(), toggle() etc. If the element was also returned, then these could be managed / positioned by another service.

**Comment by DaleWebb** [comment]
You can listen for route changes and hide the appropriate asides at that point.

```javascript
var asides = [];

function closeAllAsides () {
    asides.forEach(function(aside) {
        aside.hide();
    }
}

$scope.$on('$routeChangeSuccess' /* or $stateChangeSuccess for ui.router */, closeAllAsides);

```
