### ISSUE TITLE
unknown provider when making build 

### ISSUE THREAD

**Issue by ghost** [mgcrea/angular-strap#1354]
Since I switched to angular strap, when I build the app, it's making the following errors: 

```
Error: [$injector:unpr] Unknown provider: aProvider <- a <- bsCollapseDirective
Error: [$injector:unpr] Unknown provider: aProvider <- a <- bsCollapseTargetDirective
Error: [$compile:ctreq] Controller 'bsCollapse', required by directive 'bsCollapseToggle', can't be found!
```

I am using the files `angular-strap.js` and `angular-strap.tpl.js`. And the build is made with these grunt tasks: `useminPrepare`, `concat`, `imagemin:app`, `processhtml`, `cssmin`, `uglify',`filerev`,`usemin`,`htmlmin`. 

Any idea what's happening? thanks

**Comment by DevankAgarwal** [comment]
Hey ,
I am getting the same error but not at time of build the application.
I have used bscollapse on a modal window and while opening the modal window 2nd time i am getting this error .
Please help on this ..
Thanks..:-)

**Comment by vmlf01** [comment]
You mean the first time it works? Then that probably is not a dependency injection problem. Can you post a plunker with your issue, that would help analyzing the problem.

**Comment by DevankAgarwal** [comment]
No I cant share that on plunker, but i will give the whole detail.

Yes i works fine when i open the modal window first time but won the second time it throws error 
Error: [$compile:ctreq] Controller 'bsCollapse', required by directive 'bsCollapseToggle', can't be found!

I have used angular strap collapse on a html template. That template doesn't have a it's own controller, only data is been passed to that template to display by main controller.
