### ISSUE TITLE
affix docs are wrong about what offsetParent does

### ISSUE THREAD

**Issue by mkoryak** [mgcrea/angular-strap#1356]
here is the code that deals with offsetParent in affix:

``` js
     if (options.offsetParent) {
          if (options.offsetParent.match(/^\d+$/)) {
            for (var i = 0; i < (options.offsetParent * 1) - 1; i++) {
              parent = parent.parent();
            }
          }
          else {
            parent = angular.element(options.offsetParent);
          }
        }
```

So it will either find a parent that is N parents up the tree, or find the parent via a selector provided.

Here is what docs say:

```
Pixels to offset from parent when calculating position of scroll.
```

wat?

**Comment by tsclark** [comment]
Thank you for this. Wasted some hours on it.

**Comment by DaleWebb** [comment]
I recently ran into this problem, definitely a stumbling block for new devs to Angular-Strap, as affix is difficult enough to use already!

PR welcome!

**Comment by madflow** [comment]
@DaleWebb I have no problem writing a doc update. However I really would like to see the official docs updated on a regular basis (alongside with the release - even minor releases). Maybe we can put an automatic deplyoment in place? It is just frustrating if you invest some time and you cannot see the results shortly.

**Comment by mkoryak** [comment]
in our prod code we switched from angular-strap to ui-bootstrap and later ditched both. both projects try to do too much. its easier to write your own (if you have the resources) vs deal with bad docs or bugs.

**Comment by DaleWebb** [comment]
@madflow unfortunately, I don't have significant control over this project - I'm only allowed to resolve issues lol.

For around a year, I think this has been left to contributors to fix bugs and extend functionality and the project owner appears to come back every couple of months or so to create a new release based on the pull requests.

I agree it is frustrating, there is a bottleneck having the project owner as the only person making releases, and we are seeing the effects of that now.

**Comment by DaleWebb** [comment]
@mkoryak I think this project and ui-bootstrap has been good enough for our purposes, I don't think it tries too much (I'm not sure what you mean) as you can pick and choose the modules that you want.

For someone getting started with a project, I think this is perfect to help you do that - as helpful as getting in Bootstrap as a CSS framework.
