### ISSUE TITLE
DatePicker range scenario issue with startDate option

### ISSUE THREAD

**Issue by kinnrot** [mgcrea/angular-strap#1358]
The startDate option unlike minDate and maxDate does not support updates, means if I bind the startDate Option to a field in my scope, it'll read it only once, and won't react to changes.

You can see the issue in the sample page for http://mgcrea.github.io/angular-strap/##datepickers-examples

look at the daterange, if you pick in from a date in one month later than go to the to field you'll see date opens in the current date instead of the next month. in the example there is no usage of startDate, but even if you add it it wont work.

**Comment by tinyfly** [comment]
+1, I'd say this is critical to a properly functioning date range picker.

**Comment by mr-White** [comment]
+1

**Comment by aleksanderzubkov** [comment]
+1

**Comment by michaltresnak** [comment]
+1

**Comment by DavidVotrubec** [comment]
+1

**Comment by JakubSedlacek** [comment]
+1

**Comment by russoturisto** [comment]
+1

**Comment by gkontokotsios** [comment]
+1
