### ISSUE TITLE
Angular Strap tries to include Angular 1.3.7 which breaks code that depends on 1.2

### ISSUE THREAD

**Issue by devonhumes** [mgcrea/angular-strap#1360]
We cannot currently update to Angular 1.3 and so we have a hard dependency on Angular 1.2.28. However, AngularStrap requires ^1.2.21 which is the same thing as 1.x.x. This makes bower think that AngularStrap requires 1.3.7 and `bower i` fails with unresolvable dependencies. 

The workarounds that we have found are `bower i -f` or `bower i angular && bower i`. We do not like either of those alternatives. Is there something that we are missing or is this something that could be fixed in AngularStrap?

**Comment by mgcrea** [comment]
angular-strap requires `^1.2.21` so any version equal or above it excluding majors. It does not force you to use the v1.3 branch.
