### ISSUE TITLE
Feature Request: Split Buttons

### ISSUE THREAD

**Issue by readme42** [mgcrea/angular-strap#1365]
Hi folks, 

are there any plans supporting [Split Buttons](http://getbootstrap.com/components/#btn-dropdowns-split) in the far or near future?

Kind Regards, 
Cornelius

**Comment by jukkasi** [comment]
+1

**Comment by rapitkan** [comment]
+1

**Comment by gwin003** [comment]
+1

**Comment by Gabriel0402** [comment]
+1

**Comment by sumigoma** [comment]
+1

**Comment by DaleWebb** [comment]
Could this be handled by adding the bootstrap html code as normal, then adding `bs-dropdown` as an attribute to the element with the caret?
