### ISSUE TITLE
typeahead two way data binding

### ISSUE THREAD

**Issue by sameer22** [mgcrea/angular-strap#1366]
My HTML is like below 

<-input type="text" class="form-control" ng-model="Visit.ComplaintDesc" ng-options="complaint.Value as complaint.Value for complaint in complaints" maxlength="150" placeholder="Enter Complaint" bs-typeahead->

I am fetching data from server with method below

```
function getComplaints() {
    someFactory.getComplaintData()
    .success(function (data) {
        $scope.Visit= data;
    })
    .error(function (error) {
        $scope.status = 'Error retrieving data! ' + error.message;
    });
};
```

All other other fields are updated with two way data binding but typeahead not updating.

Expecting help.

**Comment by avarabei** [comment]
That is ridiculous without the functionality of the initial value that should come thru ng-model.

**Comment by dinoboff** [comment]
@vmlf01 

I tried to create a plunk, but plunker went down before I could save it. I will try to update it later

Using the async demo example:
```html
<input
  ng-model="selectedAddress" 
  ng-options="address.formatted_address as address.formatted_address for address in getAddress($viewValue)"
  placeholder="Enter address" 
  bs-typeahead
  />
```
and
```
$scope.selectedAddress = 'some address`
```

It seems there's an issue with the $formatter and the option parser:

https://github.com/mgcrea/angular-strap/blob/master/src/typeahead/typeahead.js#L236
https://github.com/mgcrea/angular-strap/blob/master/src/helpers/parse-options.js#L42

The display function parsed out of the option is:
```js
(function(s,l,eso,fe
/**/) {
if(s == null) return undefined; // `s` equals {address: 'some address'}
s=((l&&l.hasOwnProperty("address"))?l:s).address;
if(s == null) return undefined;  // `s` equals 'some address'  
s=s.formatted_address;
return s;  // s in undefined
})
```
And get called with `{address: 'some address'}, undefined, undefined, undefined`.

**Comment by sameer22** [comment]
Just came across a comment in #1342 and #1543  as below

For that issue, fix provided by @sloot14 seems working sloot14@941012a
