### ISSUE TITLE
<input> <textarea> labels does not display in modal when "html" is "true" .

### ISSUE THREAD

**Issue by sxxhlx** [mgcrea/angular-strap#1378]
my colleague told me that he wants me to add some <input> labels in the content of a modal . and i turn the "html" to "true" . here is the questiion , the <div> labels function well in the modal ,but <input> <form> and <textarea> do not display at all . please help

**Comment by vmlf01** [comment]
Maybe you need to use ```contentTemplate``` instead of just setting ```html``` to true?
