### ISSUE TITLE
question: how to fix partially hidden opened datepicker inside angular-bootstrap accordion ?

### ISSUE THREAD

**Issue by guilloche** [mgcrea/angular-strap#1379]
Trying to open datepicker inside angular-bootstrap accordion partially hides datepicker by accordion boundaries. Can someone help me to fix it?

**Comment by inddip** [comment]
Cool. This works.

**Comment by johannesMatevosyan** [comment]
will this for datetimepicker? I tried to add data-container="body" on input but it did not work there.
