### ISSUE TITLE
For shared model date & time pickers set today's date as the default.

### ISSUE THREAD

**Issue by tinyfly** [mgcrea/angular-strap#1388]
**The setup:**
I have a model that is being shared between the date and time pickers that starts with an empty value. 

**Current Behavior:**
- If I pick the time first the date is set to January 1, 1970
- If I pick the date first the time is set to 12:00 AM

**Desired Behavior:**
- It seems more reasonable to set the date to the current day's date instead of 1970. 
- If you pick the date first a reasonable default for the time would be the current time instead of 12:00am

I think this is a feature request rather than a bug but what do you think? Are there valid reasons to keep it at 1970 instead of setting it to the current date?

Here is an [example Plunker](http://plnkr.co/edit/xevRDE46BnpQEyWlTuP3?p=preview)

**Comment by 1Jesper1** [comment]
I would also like to know this.
