### ISSUE TITLE
$modal.hide() should take garbage collection into account

### ISSUE THREAD

**Issue by lowerends** [mgcrea/angular-strap#1391]
When hiding a modal using `modal.$hide()`, the function `$modal.hide()` should take into account that garbage collection of the scope could already have happened. This could happen, for example, when navigating to another state, causing garbage collection of the scope before the `hide` function finishes. The following code then gives an error:

```
// Unbind events
if(options.backdrop) {
    modalElement.off('click', hideOnBackdropClick);
    backdropElement.off('click', hideOnBackdropClick);
    backdropElement.off('wheel', preventEventDefault);
}
if(options.keyboard) {
    modalElement.off('keyup', $modal.$onKeyUp);
}
```

The error is: `"TypeError: Cannot read property 'off' of null";`, since `modalElement` and `backdropElement` have already been destroyed by the garbage collection.

I think a simple solution would be to check for their existence before calling `off()` on them.

**Comment by jnelson** [comment]
Same here. `TypeError: Cannot read property 'off' of undefined` due to modalElement not existing by the time `modalElement.off` is called. Wrapped the `.hide()` in a try/catch band-aid.

Context: Angular 1.2.27, triggering the `.hide()` via ui-router 0.2.10 `$stateChangeStart` event.

**Comment by nesler** [comment]
Another case is having an `$resource` as the source of `bs-modal`, and `$delete`'ing that resource outside the modal scope (eg. the parent controller). This triggers `scope.$destroy`, where the modal service will `null` the `modalElement`, causing `hide` to fail.

Adding a call to `$modal.hide` in the top of the `$modal.destroy` method would fix this, hiding the modal before destroying it.

**Comment by compwright** [comment]
+1
