### ISSUE TITLE
$scope issue with $modal on route change.

### ISSUE THREAD

**Issue by HimanshuSojitra** [mgcrea/angular-strap#1394]
I display modal dialogs from controllers like this - 

	myModal = $modal({
		scope: $scope,
		template: 'template.html',
		show: false,
		backdrop: "static",
		keyboard: false,
        persist: true
	});
	myModal.$promise.then(myModal.show); 

The issue is that it breaks on route change.

Consider `template.html` with content:

    1 + 1 = {{ 1 + 1 }}

When I open the modal from insida a controller for a route say `/screen1`,
it  displays `1 + 1 = 2`.

But now if I close the modal and go to some other route say `/screen2`
and click browser's back button to again go to `/screen1` and on reopen the modal, it displays
`1 + 1 = {{ 1 + 1 }}`

I don't know why the scope gets detached on the second occasion.(I don't see any JS errors.)

Thanks in advance.

**Comment by mgcrea** [comment]
Not sure it has properly been fixed, could you try against latest master ?
