### ISSUE TITLE
Timepicker Timezone Problems between Firefox and Chrome

### ISSUE THREAD

**Issue by squadwuschel** [mgcrea/angular-strap#1395]
When I'm using the bs-timepicker and using the following DateTimeString

2014-12-15T14:59:29.7370000

Then the Time shown in Chrome is: 3:59
the time shown in Firefox is: 2:59

I think its GMT+(1) problem and FF converts it not the same like Chrome. But there are no GMT values in the String and I would think it should be shown 2:59 as time.

Example:
http://plnkr.co/edit/fqmdYf9KIFsvjT1MdDm2?p=preview

**Comment by vmlf01** [comment]
Seems like you have the same problem as this: http://rupertmaier.wordpress.com/2014/04/25/parsing-c-datetime-without-timezone-indication-to-a-cross-browser-valid-date-object-2/

I guess the best solution would be to include the timezone information in the time value string.
