### ISSUE TITLE
Input Box Will Not Work in Select Directive (bs-select) Custom Template

### ISSUE THREAD

**Issue by baroniparson** [mgcrea/angular-strap#1399]
I created a custom template for the AngularStrap Select directive but I am unable to type inside of the textbox that I have added to the template for some reason. I would like to use this textbox to filter the list items.

**Custom HTML Template (/dist/select.html)**

The only thing that I added here from the default template was another `<li>` element that includes the textbox. Said another way, I basically copy & pasted the default template and added the `<li>` and `<input>` elements.

```
<ul tabindex="-1" class="select dropdown-menu" ng-show="$isVisible()" role="select">
    <li>
        <input type="text" class="form-control input-sm" ng-model="iconFilter" />
    </li>
    <li ng-if="$showAllNoneButtons">
        <div class="btn-group" style="margin-bottom: 5px; margin-left: 5px">
            <button class="btn btn-default btn-xs" ng-click="$selectAll()">All</button>
            <button class="btn btn-default btn-xs" ng-click="$selectNone()">None</button>
        </div>
    </li>
    <li role="presentation" ng-repeat="match in $matches" ng-class="{active: $isActive($index)}">
        <a style="cursor: default;" role="menuitem" tabindex="-1" ng-click="$select($index, $event)">
            <i class="{{$iconCheckmark}} pull-right" ng-if="$isMultiple && $isActive($index)"></i>
            <span ng-bind="match.label"></span>
        </a>
    </li>
</ul>
```

**HTML**

This is the actual HTML that includes the call to the bs-select directive.

```
<button ng-if="path() === '/contacts/people'"
    type="button"
    class="btn btn-default btn-sm"
    ng-model="selectedIcon"
    data-html="1"
    data-multiple="1"
    data-template="/dist/select.html"
    ng-options="icon.value as icon.label for icon in getIcons()"
    bs-select>
        Action <span class="caret"></span>
</button>
```

[StackOverflow.com Question](http://stackoverflow.com/q/27786482/209275)

**Comment by vmlf01** [comment]
If I press the right mouse button on the input box it does get focus and then I can type, but otherwise I cannot focus the input, so I guess it has something to do with the mouse/keyboard event handlers inside the select.

**Comment by baroniparson** [comment]
Thanks for your reply.  When I right-click, I do **not** get focus and I am **not** able to type as you were able to do.  I only get the contextual menu for my web browser.  So you are saying that perhaps lines 164-190 in select.js are to blame?

I think that it's obvious that I'm trying to add a textbox to the dropdown in order to filter the list of options for situations where you have a very long list of options.  Thoughts?

**Comment by vmlf01** [comment]
An quick alternative might be to use a typeahead instead if that works for you.

**Comment by baroniparson** [comment]
So you are suggesting to use bs-typeahead instead of using the bs-select directive or are you saying to add the bs-typeahead directive the textbox that I have added to the bs-select directives custom template?

**Comment by vmlf01** [comment]
The first one :) using a typeahead instead of the select. I know it's not the same thing, but might be a workaround.

**Comment by baroniparson** [comment]
Gotcha. This would be great if the typeahead had multi-select capabilities.

**Comment by vmlf01** [comment]
The problem lies in https://github.com/mgcrea/angular-strap/blob/master/src/select/select.js#L170
because it is preventing the mouse down default behavior. This is to prevent the select element from losing focus, which would cause the dropdown to close.

@mgcrea Maybe it should only do that when the trigger is focus? That way you could change the trigger to click and then your template should work, but then the select dropdown would not autoclose when clicking outside.
