### ISSUE TITLE
how to pass model's data to modal 

### ISSUE THREAD

**Issue by ghost** [mgcrea/angular-strap#14]
How can I pass data from a specific model to modal ? 
For example: I have a list of product, I click on product's image, it should pass that product information to the opened modal

**Comment by brutalhonesty** [comment]
```
modal.$scope.item = {value: 1}
modal.$scope.onSave = function() {
  modal.hide()
};
```

Been looking all over for this documentation. Wish it was within the angular-strap docs! Thank you!

**Comment by timelf123** [comment]
>A new scope is created regardless of the scope passed in. Variables assigned to the scope in the controller will be visible using the $parent variable.

Modal.js
`var scope = $modal.$scope = options.scope && options.scope.$new() || $rootScope.$new();`

Is it possible to change this so it does not create a new scope?

**Comment by mgcrea** [comment]
@mg-dev If you don't use primitives (eg. if you use dots in your variables expressions), you won't need to traverse the scope hierarchy with $parent. Using primitives values directly on your scope is considered bad practice.

@timelf123 Regarding not creating a scope, it would leak the inner implementation to your parent scope (publish some private props, etc.), that could somehow conflict with your code, or another directive. Also creating scope is a safe way to manage memory as we can correctly cleanup everything when the modal get's destroyed.
