### ISSUE TITLE
Adding carousel support

### ISSUE THREAD

**Issue by wesleycho** [mgcrea/angular-strap#140]
Bootstrap uses [carousels](http://twitter.github.io/bootstrap/javascript.html#carousel), and it would be nice to have it available in this plugin with control through Angular.

**Comment by imdadul** [comment]
+1

We need it in angular-strap without any doubt!

**Comment by bpceee** [comment]
angular-ui has it...

**Comment by cardimajs** [comment]
+1 carousel

**Comment by SolStis86** [comment]
+1 Carousel

**Comment by andreaslarssen** [comment]
+1

**Comment by cjnimes** [comment]
+1, I need this

**Comment by meishier** [comment]
+1

**Comment by akuznetsov-gridgain** [comment]
+1 from me

**Comment by georgschlenkhoff** [comment]
+1

**Comment by navid-dada** [comment]
+1 Carousel

**Comment by NickToye** [comment]
Do you think they are listening?

**Comment by SolStis86** [comment]
This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of MV Digital.
If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone.
Please contact the sender if you believe you have received this email in error.

**Comment by dara0418** [comment]
+1

**Comment by ChandanBP** [comment]
Any alternative to use carousel in angular strap? I can use it with help of bootstrap, but that requires using bootstrap.js inturn jquery.js. leading tocreating dependencies for those libraries.
