### ISSUE TITLE
concatenating dynamic content on AngularStrap $alert (?)

### ISSUE THREAD

**Issue by maketroli** [mgcrea/angular-strap#1403]
hello guys I have an Angular Strap alert where I want to put some dynamic content.

Look, this is the html I have so far:

``` html
    <div ng-repeat="lineItem in lineItems">
      <div class="panel panel-primary" ng-repeat="lineLeague in lineItem">
        <div class="panel-heading">
           <h3 class="panel-title">{{:: lineLeague[0].leagueName}}</h3>
        </div>
```

as you can see there is a class named `panel-title` which is the same parameter that I want to show on my alert, I thought that only placing `{{:: lineLeague[0].leagueName}}` was enough, but once the alert shows up, the result is **Sorry, no lines for {{:: lineLeague[0].leagueName}} at this moment :(** and this is my code:

``` javascript
    var noLinesAlert = $alert({
      title: 'Sorry, no lines for {{:: lineLeague[0].leagueName}} at this moment :(',
      container: '.no-lines-alert',
      type: 'danger',
      dismissable: false,
      show: false
    })
```

so what are your suggestions ?

**Comment by vmlf01** [comment]
You will need to construct the title string yourself and pass it to the $modal. The title is just a string and it doesn't support using angular expressions.

**Comment by maketroli** [comment]
@vmlf01 but I am not using a $modal, I am just using $alert.

I do not have an idea, can you help me?

**Comment by vmlf01** [comment]
Sorry, my mistake, I meant $alert.
