### ISSUE TITLE
Date Picker: First day of the week is Sunday although locale is "de" (German)

### ISSUE THREAD

**Issue by frankthelen** [mgcrea/angular-strap#1407]
Hi there,

EXPECTED BEHAVIOUR
If the Browser's locale is "de" or "de-DE" etc. (in AngularJS provided by its $locale service), the first day of the week as displayed in the date picker is Monday (first column in the month table). 

ACTUAL BEHAVIOUR
The first day of the week displayed by the date picker is Sunday. That is not correct for German.

REPRODUCTION
1. Setup your browser with locale "de" or "de-DE".
2. Load angular.js, angular-locale_de.js, angular-strap.js into your app.
3. Check which day of the week is displayed by the date picker in the left-most column. Should be Monday.

Thank you very much.

Best regards,
Frank

**Comment by vmlf01** [comment]
The default date formatter service used by angular-strap uses the ```$locale``` service to get date settings, but there is no first day of week info in angularjs that I can find, so there isn't an easy way to provide this out of the box. If anyone knows how to get that, let us know.

You can however use the ```startWeek``` option of the datepicker to set to the day you want (0-Sunday, 1-Monday, etc). The default is 0 - Sunday, but the docs pages initialize the ```$datepicker``` provider default to 1 - Monday, so if you navigate to the docs pages you should see Monday.
