### ISSUE TITLE
Modal not getting along with class="col-sm-2"

### ISSUE THREAD

**Issue by AdamGorkoz** [mgcrea/angular-strap#1410]
It seems like any element inside an element with class="col-sm-2" is not getting darkened when modal shows. 
![image](https://cloud.githubusercontent.com/assets/10440278/5652643/fa6d91b0-96ba-11e4-834d-df859635b60d.png)
P.S
After checking with other col-sim sizes i see the problem still occurs.

Regards,
Turka50.

**Comment by vmlf01** [comment]
I think this was caused by the changes in Bootstrap 3.3.x releases to the modal behavior so it needs some fixing to work with all versions.

**Comment by turka50** [comment]
Any suggestions how this fix issue locally ?

**Comment by vmlf01** [comment]
Can you go back to Bootstrap 3.2 until the issue is fixed?

**Comment by vmlf01** [comment]
@turka50 please check again if problem is fixed with next release of angular-strap. (includes PR #1508)
