### ISSUE TITLE
Missing options in select link function directive

### ISSUE THREAD

**Issue by Jisay** [mgcrea/angular-strap#1412]
iconCheckmark is missing in array of options at : https://github.com/mgcrea/angular-strap/blob/master/src/select/select.js#L245

Option is not affected when rendering and default option value is the final rendering.

Also, please change doc. The option is not "iconCheckmark" but "icon-checkmark" :-)

Thanks for fix it and thanks for the big job you made

**Comment by vmlf01** [comment]
Landed in 3cbc2b9.

The option name is correct, please see AngularJS attribute normalization rules: https://docs.angularjs.org/api/ng/type/$compile.directive.Attributes

**Comment by Jisay** [comment]
Yes it is correct, but others options are spelled like so : max-length or all-none-buttons. It's just a bit confuse but I agree it's correct.

Thanks for yout fix.

**Comment by vmlf01** [comment]
I see what you mean, the docs should be updated to use one single naming style and be consistent.
