### ISSUE TITLE
Keyboard usage for dropdown

### ISSUE THREAD

**Issue by readme42** [mgcrea/angular-strap#1413]
Hello again :)

See this [plunkr](http://plnkr.co/edit/biMCFFDTEGGAOj7Xa0H3?p=preview).

It would be nice to select elements from the dropdownlist by using up or down keys and select an item by pressing enter.

**Comment by RamonDonnell** [comment]
Seems the dropdown element is not being focused when shown, so keyboard events are not kicking in.
Beginning of a fix here https://github.com/RamonDonnell/angular-strap/commit/83bb3620add422713758939326383fb1c4f77e05. 
More will need to be done for a PR

**Comment by jeroentradecast** [comment]
+1
