### ISSUE TITLE
popover/tooltip incorrect position with custom container

### ISSUE THREAD

**Issue by lnu** [mgcrea/angular-strap#1415]
I try to specify a custom container for a popover/tooltip. 
The ng-app is defined on the body of the page and the popover/tooltip should be inserted in a div inside the body.
here's a plunk:http://plnkr.co/edit/XUzNCOgdVviiZG4V8YCR?p=preview
The top and left is always wrong. It comes from this code(line 485 in tooltip.js):

``` javascript
if (options.container === 'body') {
  elPos = dimensions.offset(el);
} else {
  elPos = dimensions.position(el);
}
```

Maybe it's not a good practice to insert the popover/tooltip somewhere else than in the body or near the element itself?

**Comment by bstruthers** [comment]
This should be fixed by the changes in #1472

See http://plnkr.co/edit/3Al1k2DL0jIUJyQrsVPP?p=preview using v2.2.0
