### ISSUE TITLE
Timepicker should support seconds and milliseconds in the dropdown

### ISSUE THREAD

**Issue by kkirsche** [mgcrea/angular-strap#1417]
Currently, the timepicker can only give an option to display a dropdown for hour, minutes, and AM/PM if it is 12 hour based (as I understand it). In the timeFormat option though, you offer the ability to set much more complex times such as `h:mm:ss.sss` which would include milliseconds. At the moment though, I haven't been able to find through the provided options how to easily support those more complex times for users through the dropdowns.

E.g.:
![screen shot 2015-01-08 at 2 48 24 pm](https://cloud.githubusercontent.com/assets/947110/5669434/6f8ab8da-9745-11e4-897f-2d38f481b4a4.png)

Am I missing something or is this something which would need to be added?

**Comment by vmlf01** [comment]
Currently the timepicker dropdown only has support for manipulating hours/minutes.

**Comment by honkskillet** [comment]
+1 for seconds.

**Comment by honkskillet** [comment]
To elaborate, this would be very useful as an elements for selecting arbitrary amounts of time (instead of just times of the day).  5 minutes and 30 seconds, 30 hours and 30 minutes, 15 seconds, etc.    This could be used as a picker for a timer, for example.

**Comment by mgcrea** [comment]
Landed in e1edb9a.
