### ISSUE TITLE
feat: keeping the order in which items are clicked in multi-select

### ISSUE THREAD

**Issue by graphicsxp** [mgcrea/angular-strap#1421]
In the multiselect sample if I click on 'Camera' and then 'Heart', the order of the items in the selectedIcons array is :  'Heart', 'Camera'.

Is there a way to keep the order in which they were clicked ?

**Comment by vmlf01** [comment]
Looks like there is a default ```sort``` option that seems related to what you want to do, but in the end the handler for selecting an item ends up sorting the selected items no matter what value the sort option has. Also, there is currently no attribute for setting this option on a particular instance.

I guess it needs some changes to make it work like you want.
