### ISSUE TITLE
model: title and content are not shown

### ISSUE THREAD

**Issue by sebeichholz** [mgcrea/angular-strap#1423]
When I create a very simple modal, the defined title and text are not shown.

Check out this plunker to see the error:
http://plnkr.co/edit/sWdH9NYhJHi3vTbK1Upw?p=preview

Am I doing something wrong?
![modal_error](https://cloud.githubusercontent.com/assets/1885936/5692690/aca1dc42-98ff-11e4-8c79-b1da911cb2d5.png)

**Comment by vmlf01** [comment]
You have the modal button outsider the controller div, so the modal variable does not exist.
Besides that, you will probably need to use ngSanitize, ngAnimate and angular-motion (angular-strap dependencies) to get the full expected modal behavior.

**Comment by sebeichholz** [comment]
Thanks for the hint with the "button outside the controller div".
Sorry that I didn't see that :-(
I updated the plunker and now it works.

ngSanitize, ngAnimate and angular-motion are not needed to see the text, but of course nothing is animated etc.
