### ISSUE TITLE
dropdown border doesn't expand to length of item text

### ISSUE THREAD

**Issue by jfraboni** [mgcrea/angular-strap#1424]
The borders of the dropdown box should include the length of the text, no?  Seems the dropdown is sizing itself based on the parent item to which it belongs, and not its contained item's text.

Expected, even if text is stupidly long (and in our case it was only three words "Manage Social Accounts"), the box should expand or size itself width-wise to contain the text.

Keep up the great work! Thanks!

**Comment by vmlf01** [comment]
Have you tried using ```data-container="body"```?

**Comment by jfraboni** [comment]
@vmf01 : Nope, not sure how that functions, don't see that in the docs for dropdown nor in any examples.  Can you provide an example?

Expected results, I'd figure, is that the dropdown box should size itself the text of the items, without devs having to configure anything.

**Comment by vmlf01** [comment]
Can you please post a plunker with your issue?
