### ISSUE TITLE
cannot disable dates in datepicker

### ISSUE THREAD

**Issue by longilineo** [mgcrea/angular-strap#1432]
I'm trying to disable all italian festivities in angularstrap datepicker but data-disabled-dates attributes is ignored

Here is how I'm generating array with festivities:

    function ListaFestivita(anni){
      var feste = [];
      for(x in anni){
        for(y in festefisse){
          feste.push({start: new Date(anni[x], festefisse[y].m-1, festefisse[y].g), end: new Date(anni[x], festefisse[y].m-1, festefisse[y].g)});
        }
      }
      return feste;
    }

    var festefisse = [
      {g: 1, m: 1, n: "capodanno"}, {g: 6, m: 1, n: "epifania"}, 
      {g: 25, m: 4, n: "liberazione"}, 
      {g: 1, m: 5, n: "lavoratori"}, 
      {g: 2, m: 6, n: "repubblica"}, 
      {g: 15, m: 8, n: "assunzione"}, 
      {g: 1, m:11, n: "santi"}, 
      {g: 8, m: 12, n: "immacolata"},
      {g: 25, m: 12, n: "natale"},
      {g: 26, m: 12, n: "santo stefano"}
    ];

Inside a controller I've:

    $scope.festivita = new ListaFestivita([2015,2016]); 

In html:

    <input class="form-control" type="text" name="ritiro" placeholder="gg-mm-aaaa" data-ng-model="ritiro" id="ritiro" 
                 bs-datepicker="true" data-date-format="dd-MM-yyyy"
                 required="true" 
                 data-days-of-week-disabled='06'
                 data-start-date="{{startDate}}"
                 data-min-date="{{minDate}}" 
                 data-max-date="{{maxDate}}" 
                 data-disabled-dates="{{festivita}}" />

**Comment by longilineo** [comment]
Am I wrong? No one could provide a working example?

**Comment by longilineo** [comment]
Any way to disable dates?

**Comment by KaneConnor** [comment]
Hi all,
I've same problem here. I'm using: 
$scope.nodates={ start: new Date(1999, 11, 24), end: new Date(2010, 11, 25) };
but these dates remain selectable.
The longilineo solution doesn't work for me.
Any suggestion?

**Comment by vmlf01** [comment]
For @longilineo case, I added the disabled-dates attribute with the scope variable without the interpolation (no {{ }}).
In @KaneConnor case, the disabled-dates actually takes an array of objects, so just putting the object inside an array did it for me.

Check this plunker for example:
http://plnkr.co/edit/BVsm4OaxF6vNT3oy8lQc?p=preview

**Comment by vmlf01** [comment]
If you come across more issues, feel free to re-open.
