### ISSUE TITLE
Github Page Side Menu Doesn't Link Properly

### ISSUE THREAD

**Issue by kkirsche** [mgcrea/angular-strap#1435]
The left menu at http://mgcrea.github.io/angular-strap/ doesn't work correctly. You have to click a link once before you can click again to jump to the correct section. See this youtube video for an example of the issue:

http://youtu.be/st2khX5ZhYU

**Comment by vmlf01** [comment]
I had noticed this also recently, I think it was some change in one of the last 2 versions or so.
