### ISSUE TITLE
Datepicker : 6 weeks displayed

### ISSUE THREAD

**Issue by mmouterde** [mgcrea/angular-strap#1438]
The datepicker popup shows to much weeks for a month ?!

Here is a capture from the [demo](http://mgcrea.github.io/angular-strap) :
![6weeks](https://cloud.githubusercontent.com/assets/733538/5754523/46679018-9c9a-11e4-9895-022ed2231004.jpg)

**Comment by vmlf01** [comment]
Looks like a bug, I don't think the last row should appear.

**Comment by vmlf01** [comment]
Oh sorry, even though it might seem unnecessary in this case, the datepicker will always generate 6 rows, so this is by design, not a bug.

**Comment by cookednoodles** [comment]
I'm confused, why is this the design ? It doesn't make sense to show an 'invalid' week at the end of each month.

**Comment by vmlf01** [comment]
Some months will need the 6 rows do display. 4 rows will get you 7*4 = 28 days. If you have a month with first day starting at the end of the week, you will need the 6th row to display the last days of the month.

The alternative would be to have the picker display a variable number of rows depending on the month.
