### ISSUE TITLE
Affix Example Code (where to find?)

### ISSUE THREAD

**Issue by divramod** [mgcrea/angular-strap#1442]
Hey, i cant find the Affix example code, ie no live-example-plunkr.
Could you tell me, where to find it?

https://github.com/mgcrea/angular-strap/tree/master/src/affix isnt including a real world example.

thx

edit 
-----
- do i have to add specific css for it?

**Comment by vmlf01** [comment]
Maybe this can help you:
http://plnkr.co/edit/J0kh5z5q9kTVGzPe34xe?p=preview
