### ISSUE TITLE
Single-select select control highlights first item when nothing has been selected

### ISSUE THREAD

**Issue by sumigoma** [mgcrea/angular-strap#1443]
![image](https://cloud.githubusercontent.com/assets/1646359/5785838/ce093124-9d90-11e4-97a2-9f3eea104dcc.png)

Despite the placeholder being visible, the first item in the dropdown appears selected. For multiselect, the behavior is different, and nothing is highlighted initially in the dropdown. The latter behavior is preferable.

**Comment by sumigoma** [comment]
Is this as straightforward as setting the initial $activeIndex to -1 instead of 0 (as well as the fallback in  updateActiveIndex)? 

Was the single select designed to behave this way for a reason?

**Comment by meandavejustice** [comment]
@sumigoma did you ever find a workaround for this?

**Comment by sumigoma** [comment]
No - for my particular app/use case, it was ok for me to initialize the model to the first item in the list, but that's not really a workaround.

**Comment by meandavejustice** [comment]
bummer, thanks for the feedback @sumigoma
