### ISSUE TITLE
Tooltip module not working on IE8

### ISSUE THREAD

**Issue by JoshSchreuder** [mgcrea/angular-strap#1447]
The tooltip module is no longer working in IE8 following the changes to auto position tooltips (specifically commit @adb68eeba66cddede9afe897c04764afb75440e9)

This also breaks anything that uses tooltip, eg. datepicker / timepicker.

The line that causes issues in IE8 is:
https://github.com/mgcrea/angular-strap/commit/adb68eeba66cddede9afe897c04764afb75440e9#diff-e8665eb306ddd26399e5b80f00dae5bbR468

This goes through Angular's ForEach which fails when it tries to iterate the IHTMLRect object `elRect`.

This line can be confirmed to be responsible by simply returning elPos instead of the concatenated object, which returns behaviour back to pre-auto-position standard.

**Comment by JoshSchreuder** [comment]
@bstruthers any ideas on this one? I'm not sure if it's an issue with Angular or not. My first workaround was to try something like:
```
var pos = {
  top: elPos.top || elRect.top,
  bottom: elPos.bottom || elRect.bottom
  ...
}
```

which is an ugly way of copying the two objects together, but it seemed to work. You'll probably have a better fix in mind.

**Comment by bstruthers** [comment]
@JoshSchreuder What version of Angular are you using?  I'll try to recreate on my machine, so far I've been unsuccessful with getting IE8 to work at all :)

**Comment by JoshSchreuder** [comment]
Whatever the latest Angular 1.2 is, I'll check when I'm at work.

Angular.extend goes into Angular.forEach which is where the issue occurs, with the `for key in obj` loop

**Comment by vmlf01** [comment]
Seems related to this:
https://github.com/angular/angular.js/issues/5201

**Comment by JoshSchreuder** [comment]
@vmlf01 I found that ticket too, but they seemed resigned to the fact it was only happening on emulated IE8 through document standards. 
This is happening to me on actual IE8.

**Comment by JoshSchreuder** [comment]
@bstruthers using Angular 1.2.28. I will try and put together a minimal Plnkr case and post it to angular/angular.js#5201 and see what they say.

**Comment by JoshSchreuder** [comment]
OK, posted a test case to that Angular ticket.
http://plnkr.co/edit/q876cl6Dkr5OowkL2nWO?p=preview

**Comment by bstruthers** [comment]
Here's what I've learned, in IE8 getBoundingClientRect is a read-only object. In other browsers, the object can be manipulated.

If the rect's values are copied into a new object, calling angular.extend no longer throws an exception. See http://plnkr.co/edit/Wvf5A3VL6vRPeJh2YDE3?p=preview.  I'd have to dig into the angular.extend source to see exactly what it's trying to do to the rect object.  

Seems like the angular-strap fix, so we can continue supporting IE8, would be to grab the rect and copy its values into a new object.  I'll pull together the change.

**Comment by JoshSchreuder** [comment]
Thanks @bstruthers, tested and working in v2.2.1 :smile:
