### ISSUE TITLE
In datepicker when datetime is in shortDate format, it always returns the current year

### ISSUE THREAD

**Issue by siulung4073** [mgcrea/angular-strap#1450]
Hi. I'm using version 2.1.6 from the datepicker. If you use the 'shortDate' format and you choose a date before 2000/1/1, for example: 1995/1/1, after you select the date, it turns back to the 2000 year, for example: 2095/1/1.

please see this plunker for demo: http://plnkr.co/edit/QAU70rZcxnq5VrsIZItr?p=preview

the key is the 'shortDate' format, because it has only yo digits for the year. if you use 4 digits for the year ('yyyy'), it works just fine.

thanks!

**Comment by vmlf01** [comment]
In you case I think you will need to use the 4 digits so it is not ambiguous.
