### ISSUE TITLE
Combobox functionality

### ISSUE THREAD

**Issue by geemang2000** [mgcrea/angular-strap#1451]
I'm looking for combobox functionality. Something that combines the typeahead and select. 

Is there such as way to configure this?

**Comment by vmlf01** [comment]
There is a typeahead ```selectMode``` option that will only accept input that is in the list of suggestions, so you might give that a try.

**Comment by geemang2000** [comment]
I'd like the UI control to look / behave like a select and have the typeahead matching. Let the user enter in a value that does not exist in the list or select a value from the list.  Its important for a usability perspective that this looks like a textbox / select.

**Comment by DaleWebb** [comment]
For future reference, if you use the `bs-typeahead` then you can specify the attributes `<... data-filter="false" data-min-length="0" bs-typeahead>` and that should let users see all of the options, while being able to type their own.
