### ISSUE TITLE
popover automatically hides when I show it

### ISSUE THREAD

**Issue by Tobbe** [mgcrea/angular-strap#1453]
Based off of the code provided in the plnkr link in the documentation I wrote this: http://plnkr.co/edit/iaXhWb1SEn9BUjP5BLwW

As you can see, when you click the button to show the popover it first appears, just to immediately disappear again.

This looks like a bug to me. (Either in the documentation/example or in the actual code)

**Comment by Tobbe** [comment]
Looks like it's an issue with the example in the "documentation". The example should have trigger set to 'manual'. Like this: http://plnkr.co/edit/KN4iloExAD7ERtkmezwo

**Comment by Tobbe** [comment]
@vmlf01 Sorry about not getting to creating the pull-request sooner. Would have spared you the trouble

**Comment by vmlf01** [comment]
no problem, yours is much better :)
