### ISSUE TITLE
Empty template file causes Angular error

### ISSUE THREAD

**Issue by tah** [mgcrea/angular-strap#1457]
In (at least) tooltip.js and modal.js, the compile stage after loading a template with empty content has been resolved, will complain with a `"Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite!"` message in the console. 
A sanity check and a warning or error message from Angular-strap would greatly help developers who's facing this issue to pinpoint what's causing this error from deep inside Angular.

--Tomas

**Comment by vrcod** [comment]
+1

**Comment by vmlf01** [comment]
Can you provide a test case please?

**Comment by tah** [comment]
Basically setting template property to an non-existing url, e.g. template: "foo.html"
