### ISSUE TITLE
Support for angular-translate

### ISSUE THREAD

**Issue by egel** [mgcrea/angular-strap#1458]
Did `angular-strap` support [`angular-translate`](https://github.com/angular-translate/angular-translate) module? For the time of writing this issue current version of `angular-strap` is `v2.1.6`

> For example: I tried to combine `angular-strap`'s dropdown menu with `angular-translate` and also some  approaches for authorizations features using [`angular-client-side-auth`](https://github.com/fnakstad/angular-client-side-auth). But probably this combination isn't possible without interference with native angular-strap directives.

But if  **support** this nesty features, then how can be implemented? Into [docs site](http://mgcrea.github.io/angular-strap/) there aren't any information about it.

Is there any plans to achieve this feature?

**Comment by LennyLip** [comment]
+1, I'm using angular-translate and my data-template (bs-modal="modal") of modal work strange. $translateProvider.use('en') is set in main config of app, but data-template load other language (may be it get from web browser native language)....

**Comment by LennyLip** [comment]
ok, i think it was my fault. I forgot change lang key before page refresh
$translate.storage().put($translate.storageKey(), lang);
and after reload page (i have a multipage app and several controllers) angular-translate using old value.

so, as i can see, angular-strap support angular-translate...
