### ISSUE TITLE
bs-alert $timeout breaks Protractor tests (fix included)

### ISSUE THREAD

**Issue by mremmik** [mgcrea/angular-strap#1470]
Hello,

Using an alert with a timeout (any timeout) makes Protractor E2E tests time out and fail. 

That is a [well known issue/limitation](https://github.com/angular/protractor/blob/master/docs/timeouts.md) of Protractor and/or Selenium Webdriver, which stems from the way alert.js continuously polls $timeout at alert.js:50. Basically Protractor attempts to wait until Angular has finished processing and timeouts on the page are complete, yet in a case like this it fails to recognize the stable state and keeps waiting forever. 

Fortunately, there is a simple drop-in fix: instead of $timeout, use $interval to achieve the same thing and more. Instead of

```
$timeout(fn, delay, invokeApply);
```

use

```
$interval(fn, delay, 1, invokeApply);
```

for exactly the same functionality, yet with nice and functional Protractor tests. :)

**Comment by jshemas** [comment]
@mremmik: Can you post an example of a Protractor test for your alerts? I've been having a lot of trouble getting this to work. Thanks!

**Comment by vladgurovich** [comment]
Upvoting this issue since this prevents any reasonable automation testing of ng-strap components.
I would say that any optional transition that happens after timeout, should be using the $interval service instead
