### ISSUE TITLE
Incorrect Use of NgOptions throughout Angular-Strap directives

### ISSUE THREAD

**Issue by kkirsche** [mgcrea/angular-strap#1473]
Hey,

I was taking a look at the implementation of Angular-Strap and into how it uses NgOptions and found that it is incorrect. While not a major issue in 1.2.x/1.3.x (as it doesn't throw a fatal error when this occurs) it does throw fatal errors in 1.4.x which stops their execution as now it is more strict about requirements and ensuring they are there.

Specifically, NgOptions directive requires the `select` controller which is found on `<select>` elements.

This can be seen in 1.3.x here:
https://github.com/angular/angular.js/blob/v1.3.x/src/ng/directive/select.js#L202

and in 1.4.x here:
https://github.com/angular/angular.js/blob/master/src/ng/directive/ngOptions.js#L325

This incorrect use will throw the following error on the 1.4.x branch:
` Error: [$compile:ctreq] Controller 'select', required by directive 'ngOptions', can't be found!` because it's being used for non-select elements.

The documentation they point to for this is:
https://docs.angularjs.org/error/$compile/ctreq?p0=select&p1=ngOptions

**Comment by mgcrea** [comment]
@k-funk good find, we'll have to switch to a more private `bs-options` for the next minor.

**Comment by kaiserkoenig** [comment]
any ideas when this will be done? thx
