### ISSUE TITLE
minDate/maxDate not working through config options

### ISSUE THREAD

**Issue by nick-brown** [mgcrea/angular-strap#1479]
`data-max-date="today"  data-min-date="01/01/2010"` works fine but

```
angular.extend($datepickerProvider.defaults, {
    dateFormat: 'MM-dd-yyyy',
    autoclose: 1,
    minDate: '01/01/2010',
    maxDate: 'today'
});
```

Does not achive the same effect.

**Comment by vmlf01** [comment]
Please use real date object values instead when setting the provider defaults.

**Comment by nick-brown** [comment]
Gotcha - recommend making this clearer in the docs.  I greatly appreciate the response.
