### ISSUE TITLE
ng-required="true" stops working when the typeahead directive is added

### ISSUE THREAD

**Issue by mbates** [mgcrea/angular-strap#1481]
All the required fields in my form get a 'has-error' class if they are invalid. When I use bs-typeahead with one of these fields, that functionality stops working.

    <div class="form-group" ng-class="{ 'has-error': form.name.$invalid }">
        <label>Name</label>
        <input type="text" class="form-control" ng-model="form.name" ng-options="person.name for person in people" placeholder="Enter name" ng-required="true" bs-typeahead>
    </div>

**Comment by vmlf01** [comment]
I did a small test case for this and it seems to work. Can you please provide a similar test case demonstrating your issue?

http://plnkr.co/edit/CsrqXcqQhzaEHGUw1pFh?p=preview

**Comment by vmlf01** [comment]
If you still have this issue, please re-open with a test case.

**Comment by mbates** [comment]
Sorry I've not responded to this sooner.

I got it working okay when I built a small test case for you based on my code. I found out I had missed out the name attribute on the <input>

**Comment by vmlf01** [comment]
Great!
