### ISSUE TITLE
affix doesn't work propertly

### ISSUE THREAD

**Issue by zhekaus** [mgcrea/angular-strap#1482]
Hello!
I have a hardship with sticky sidebar using your library.
I hapilly accidantly met this library when I was searching a way to use bootstrap’s sticky affixed sidebar within angular views.
However I’ve caught a couple issues:
1)	sidebar overlaps the main content when you click an anchor in it to navigate a part of a page,
2)	affix is not automaticaly cancelled when browser’s window becomes too narrow.

**Comment by vmlf01** [comment]
Those 2 functionallities are present in the angular-strap docs pages, so you might take a look there at how it is being done.
Those are things that are not part of the affix directive responsibilities and as such need custom implementation.
