### ISSUE TITLE
Tooltips and Popovers do not accept all options when passed as an object 

### ISSUE THREAD

**Issue by rcrisp** [mgcrea/angular-strap#1485]
When creating tooltips and popovers initializing with an object, for example:

     <button bs-popover="popover">Click to toggle popover</button>

Most options are not supported.  It appears it only accepts title and content.  When specifying any other options, for example trigger, it takes no effect.  Those attributes must be set manually through data- attributes on the element itself.

  $scope.popover = {
    title: 'Hover Test',
    content: 'The trigger for this is set to hover via this object, but it does not work',
    trigger: 'hover'  // <-- Does not work
  };

Here is an example plunkr with the trigger passed in the object:  http://plnkr.co/edit/aEP7akD7mC0hAPc9y5fu?p=preview

**Comment by FindBoat** [comment]
+1

**Comment by vmlf01** [comment]
This is by design, when using object it is for setting the scope of the directive, not the options.

**Comment by losadaem** [comment]
Is there any way to pass all the configuration options as an object? For example 

```
data-options="tooltipType1" or data-defaults="tooltipType1"
```
