### ISSUE TITLE
Custom build of Angularstrap

### ISSUE THREAD

**Issue by mwils-bp** [mgcrea/angular-strap#1488]
How could I make a custom build of Angularstrap like on the Bootstrap website?
http://getbootstrap.com/customize/

For example - I only want to use the modal and aside directives?

Many thanks in advance!

**Comment by vmlf01** [comment]
I don't think there is an automated way, but you can pick the modules you need from the dist/modules folder on github. You will need to check the dependencies needed by each module.

**Comment by mwils-bp** [comment]
Would there ever be a chance of an automated builder being on the documentation site?

I think its a good idea because not everyone wants the whole of Angularstrap, its a pretty big dependency.

I cant speak for anything else, but the reason I'm using Angularstrap is to defeat the jQuery dependency. But theres not much difference if your using a whole library which is not needed.

**Comment by miketeix** [comment]
+1
