### ISSUE TITLE
bs-typeahead: $viewValue is not $viewValue, but Object when hitting return

### ISSUE THREAD

**Issue by qqilihq** [mgcrea/angular-strap#1489]
I'm using a `bs-typeahead` with objects and dedicated view values, like so (I need to keep the complex address objects):

`<input type="text" ng-model="selectedAddress" ng-options="address as address.formatted_address for address in getAddress($viewValue)" bs-typeahead>`

This works fine; the typeahead shows `address.formatted_address`, as expected. However, when I select one entry from the menu, the `getAddress($viewValue)` is invoked again with `$viewValue` being the complete object (i.e. `address` instead of `address.formatted_address`).

Theoretically, I can just perform some check, like `if (typeof viewValue === 'object') return;`, but it would feel more clean, if that was done by angular-strap itself.

Example on Plunkr: http://plnkr.co/edit/pK1jrlJp43yBM30dI519

**Comment by readme42** [comment]
:+1:

**Comment by episodeyang** [comment]
if you use 
```javascript
ng-options = "address.formatted_address as address.formatted_address for address in getAddress($viewValue)" 
```

then it would work. $modelValue and $viewValue are supposed to be the object when you use 
```javascript
ng-options="address as address.formated_address"
```

**Comment by qqilihq** [comment]
(sorry for getting back late) Yes, I feel that `$viewValue` should always be a string. However I have to admit, that we went for a library at the end, so I cannot verify whether your suggestion would solve my issue. Thank you anyways!

**Comment by rzschech** [comment]
+1
