### ISSUE TITLE
momentjs dates

### ISSUE THREAD

**Issue by demee** [mgcrea/angular-strap#1490]
Hi, 

We are using moment.js dates in our project. Angular strap date picker is using plain javasript Date object. That makes us convert that date back and forward for each place where we use it. 

Is there a way to use moment.js object, or is there a plan to support it? 
Would you accept a pull request with that support implemented? 
What would be the acceptance criteria for such support?

Thanks. 
demee

**Comment by vmlf01** [comment]
Checkout commit https://github.com/mgcrea/angular-strap/commit/4050364609323ebad72c7463d23c39a719d0af96, which introduced the possibility to have other date parsers/formatters. @tepez might have some more details on how to do it.

**Comment by vmlf01** [comment]
Any luck implementing this? Maybe you can share a sample?

**Comment by mgcrea** [comment]
You should have a look at [this plunker](http://plnkr.co/edit/wGVxTg0rwizLLGBeypmO?p=preview) from https://github.com/mgcrea/angular-strap/pull/1163#issue-45962417?
