### ISSUE TITLE
data-placement position incorrect

### ISSUE THREAD

**Issue by MillerRen** [mgcrea/angular-strap#1491]
The dropdown menu with display 100% when i set `data-placement="bottom-left"`

**Comment by vmlf01** [comment]
From the docs:

>This module supports exotic placement options!

>You can position your dropdown in corners (such as bottom-left) or any other combination two.

>Exotic placement options are not part of the Bootstrap's core, to use them you must use bootstrap-additions.css from the BootstrapAdditions project. This project being not yet fully released, meanwhile, you can use the development snapshot compiled for theses docs.

Are you including these custom CSS styles?

**Comment by bstruthers** [comment]
@vmlf01 there's no styling for the dropdown menu with the bootstrap additions, so I don't think that's the issue.

@MillerRen could you pull together a plnkr or so code so I can help troubleshoot?

**Comment by mgcrea** [comment]
Looks like https://github.com/mgcrea/bootstrap-additions/blob/master/src/tooltip/tooltip.less#L66 should contain tooltip-like plugins.

**Comment by bstruthers** [comment]
Unless I'm missing something, the dropdown does not add the .tooltip class when it renders.  

    <ul class="dropdown-menu am-flip-x bottom-left" role="menu" tabindex="-1" style="top: 115px; left: 15px; display: block; visibility: visible;">
    </ul>

**Comment by MillerRen** [comment]
duplicate issue #1131
