### ISSUE TITLE
I don't see any possibility to set a datepicker in an other language.

### ISSUE THREAD

**Issue by michaelhoes** [mgcrea/angular-strap#1492]
I don't see any possibility to set a datepicker in an other language. Is there a way to set the language of a datepicker, by an extra configuration file or something?

**Comment by vmlf01** [comment]
From docs: You just have to load the proper i18n file to seamlessly translate your datepickers.
But that would apply to whole application, I don't think there is a way to change just a particular picker.

**Comment by sxxhlx** [comment]
please load the proper i18n file in your <head></head> ,you can get it on http://angularjs.org/   .And don't forget to set a proper lang="your language" in your html
