### ISSUE TITLE
data-start-collapsed="true" not evaluate as a boolean

### ISSUE THREAD

**Issue by drano** [mgcrea/angular-strap#1496]
When using collapse directive using data attributes like that
`<div bs-collapse data-start-collapsed="true"></div>`, startCollapsed is not evaluate as a boolean.

In collapse.js,
` self.$targets.$active = !self.$options.startCollapsed ? 0 : -1;` 
`self.$options.startCollapsed` is 'true' as a string

How using a data-attribute as a boolean ?

**Comment by vmlf01** [comment]
In this case, you can leave out the attribute because the default is to not start collapsed.

**Comment by drano** [comment]
Ok, but I need to have "false" in some cases.

**Comment by tibor-kulcar** [comment]
Yeah, how can I set it to collapsed at start?

**Comment by DaleWebb** [comment]
Can you produce a plunkr that shows that it isn't working?
