### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by stact** [mgcrea/angular-strap#1500]
Hi,

Do we have a way to disable animation on xs view? Or on a particular element?

Thank you for your feedback :)

**Comment by vmlf01** [comment]
I don't exactly understand the question, but I guess you can specify a different animation class using the animation option on most angular-strap directives or just override the default animation class definition.

**Comment by stact** [comment]
Oh i get it.
I can specify a "no-animation" class for example, where "no-animation"  does not exist :)

``` html
<a href="#" class="dropdown-toggle" data-animation="no-animation" bs-dropdown="links">
   My dropdown
</a>
```
Thank you for your feedback. Hope this will help someone

**Comment by stact** [comment]
You could also override defaults globally:

``` javascript
angular.module('myApp')
.config(function($dropdownProvider) {
  angular.extend($dropdownProvider.defaults, {
    animation: false
  });
});
```
