### ISSUE TITLE
Typeahead service expample

### ISSUE THREAD

**Issue by Hrafnkellos** [mgcrea/angular-strap#1502]
Can you create a typeahead service example. im trying to create one but its not going to well.

**Comment by vmlf01** [comment]
Can you be more specific? What kind of problems are you facing? Have you looked at the docs sample that uses the async google API?

**Comment by jjstrat3** [comment]
I'd be interested in seeing an example where you can use the `$typeahead` service to create a callback on selecting a suggested match.

**Comment by vmlf01** [comment]
See if this helps:
http://plnkr.co/edit/6FDMugh3j0rVt6p42vVA?p=preview

It is using the typeahead 'select' event.

**Comment by renato** [comment]
I'd like to see an example as well, but using `$show`/`$hide` with `data-trigger="manual"`.

Actually, something like the tooltip's `bsShow` would be great. Is something like this planned for typeahead?

Thanks.

**Comment by angelxmoreno** [comment]
@vmlf01 that pluck is not found
