### ISSUE TITLE
How can I reuse my same  modal template with different callback? 

### ISSUE THREAD

**Issue by rahil471** [mgcrea/angular-strap#1505]
For example !
I want to use a modal with custom template at multiple places that will have the same UI.
But the callback/function on click of button(confirm) will be different .

Can any one help me with this ?

**Comment by kkirsche** [comment]
Not sure what the issue is here. This sounds like all you want to do is set the `data-template` to the same template or if using the JSON starter, the `template` key

**Comment by vmlf01** [comment]
Here is a sample using a modal service we created for one of our projects:
http://plnkr.co/edit/Zb1ZrfXbqkNzeUglj2Z5?p=preview

The modal service can be injected into part of the application and it will use the angular-strap $modal provider to display the modal. You can use the same principle.
