### ISSUE TITLE
Angular-strap Bug with hashtag (#) in Url.

### ISSUE THREAD

**Issue by Hazarapet** [mgcrea/angular-strap#1512]
Lets I tell you an example,to understand me.I have a form which action is "#".during saving,the back-end side redirects to another page.In Url apears hashtag (#) and when angular-strap sees it in url,it automatically refresh(reload) the page without hashtag.The problem is it.

**Comment by vmlf01** [comment]
can you provide a test case? versions you are using? what directive? not sure how angular-strap relates to the url change.

**Comment by Hazarapet** [comment]
I'm using the last version.

**Comment by bstruthers** [comment]
@Hazarapet what version of angular are you using?  I don't think angular-strap is causing your issue.  

Angular 1.3.13 has a fix for "prevent page reload if initial url has empty hash at the end".  If your form is posting to the server, this could be your issue.

As @vmlf01 stated, a test case (plnkr or something) would help track the issue down.

**Comment by Hazarapet** [comment]
my angular version is 1.3.13
