### ISSUE TITLE
popover: creation from service example by button in the docs not working

### ISSUE THREAD

**Issue by dankahle** [mgcrea/angular-strap#1514]
This is only in the "gulp serve" docs, the button doesn't show up in the gh-pages docs. I tried to fire up one from the service and nothing came up. Didn't try too hard though, but think something's broken.

**Comment by bstruthers** [comment]
I this issue was introduced with commit https://github.com/mgcrea/angular-strap/commit/148ce5bfa18c25c497450bbd1f2592c61d77bdb8.  It looks like all toggle does is hides myPopover.

**Comment by dankahle** [comment]
Nice fix. The docs fix (148ce5bfa18c25c497450bbd1f2592c61d77bdb8), doesn't show the code to support the button. I think the add of the  manual trigger (a613d6a19448da6edd2aa75f0c67973cbcddb2d7) was good enough. I don't see the use if you can't see the code and I'm not sure we want the code there as it's kind of verbose:

  var asAServiceOptions = {
    title: $scope.popover.title,
    content: $scope.popover.content,
    trigger: 'manual'
  }
  
var myPopover = $popover(angular.element(document.querySelector('#popover-as-service')), asAServiceOptions);
    
  $scope.togglePopover = function() {
    myPopover.$promise.then(myPopover.toggle);
  };
'''

**Comment by vmlf01** [comment]
You will get the code if you use the plunker option, so it's useful for people to play around.

**Comment by dankahle** [comment]
@vmlf01 I don't see it in the plunker. Am I missing something?

**Comment by vmlf01** [comment]
I'll try it later, maybe you are seeing the current docs samples that don't have the changes yet? Remember, the docs pages are only updated when a new release is made.

**Comment by dankahle** [comment]
I was looking at the latest (gulp serve)

**Comment by vmlf01** [comment]
Looks like the plunker generator uses the files on rawgit.com instead of the local sources, so it will only update when a new version is published:
https://github.com/mgcrea/angular-strap/blob/master/docs/scripts/app.js#L18
