### ISSUE TITLE
slim down the bower install?

### ISSUE THREAD

**Issue by dankahle** [mgcrea/angular-strap#1516]
Not sure how this is done, i.e. you're supposed to point bower at a git tag, but then you get "all" the files in the repo. If I look at lodash/lodash, their tags appear to be all the files, yet when I do a "bower install lodash", all I get is:
bower.json, license.txt, lodash.js, lodash.min.js 
How do they even do that? jQuery has a slimmer set on bower too. Seems all you want on bower is your dist directory and not even in a directory, top level angular-strap.js with modules directory underneath it sounds about right. Should be able to path: bower_components/angular-strap/angular-strap.min.js I'm thinking.

**Comment by mgcrea** [comment]
They are probably using a separate repo, I'm not fond of this one repo per package manager per project practice as it pollutes github.

**Comment by dankahle** [comment]
Maybe it can be a separate branch, like gh-pages where you wipe it clean and then add the dist files only, then could tag that instead? And maybe a special tag like bower_v1.0 or something? That wouldn't be as bad as another repo. No biggy though, can just close this. If I try that out and it works I'll let you know.

**Comment by jmdobry** [comment]
In `bower.json` you could change

```json
"ignore": [
  "docs",
  "test",
  "CONTRIBUTING.md"
]
```
to
```json
"ignore": [
  "docs",
  "src",
  "test",
  "gulpfile.js",
  "package.json",
  "CONTRIBUTING.md",
  ".*"
]
```

**Comment by dankahle** [comment]
Nice. Wonder if it takes not ! globs so you could do:
*, !dist/, !bower.json, !readme.md
then when someone adds another file, it won't show up
