### ISSUE TITLE
popover directive wont work when minified

### ISSUE THREAD

**Issue by snimavat** [mgcrea/angular-strap#1517]
Popover.js

    .directive('bsPopover', function($window, $sce, $popover) {

It does not specify the dependencies explicitly.

It should be
        .directive('bsPopover', ["$window", "$sce", "$popver", function($window, $sce, $popover) { }])

**Comment by bstruthers** [comment]
All the directive's source is that way.  Take a look at the gulp file, you'll see that it's using ng-annotate. https://github.com/olov/ng-annotate#ng-annotate

**Comment by vmlf01** [comment]
If you are having a problem with minification, it probably has a different cause.
As @bstruthers is saying, angular-strap auto-annotates the dependencies during build process.

**Comment by snimavat** [comment]
May be because we are using a quite old release of 0.xx line ? But it definitely does not have the annotations

**Comment by vmlf01** [comment]
Could be, have no idea how those versions work.

**Comment by bstruthers** [comment]
Looking at the legacy source, it was using ngMin -> https://github.com/btford/ngmin

Same concept as ng-annotate.  If you're trying to minify the files yourself, you're better off executing the grunt task to generate the dist files.
