### ISSUE TITLE
Popover gives attempting to use an unsafe value in a safe context.

### ISSUE THREAD

**Issue by MateenKadwaikar** [mgcrea/angular-strap#1518]
Got this error while using popover http://errors.angularjs.org/1.3.10/$sce/unsafe

This is how I am using angular strap in my html
 <button id="confirmRemove" 
                      class="btn btn-red" 
                      data-animation="am-flip-x" data-auto-close="1" 
                      bs-popover
                      data-template="popover/docs/popover.tpl.demo.html>
              Remove
</button>

Can you please tell me what wrong I am doing?

**Comment by vmlf01** [comment]
Are you including ngSanitize in your dependencies?

**Comment by MateenKadwaikar** [comment]
No , 

Can you please give me some example how can I use it.

**Comment by bstruthers** [comment]
@MateenKadwaikar the popover docs give an example. See "Custom Popover (using data-template)" in the source https://github.com/mgcrea/angular-strap/tree/master/src/popover/docs

If you still can't get it to work, could you post more code or a plnkr of your issue?
