### ISSUE TITLE
Tooltip prevents ng-click on buttons on mobile devices

### ISSUE THREAD

**Issue by j-ulrich** [mgcrea/angular-strap#1522]
Using the `bs-tooltip` directive on a button prevents that `ng-click` is triggered on mobile devices.
Here is a Plunker demonstrating the issue:
http://plnkr.co/edit/nzcCe6PJno7pNRgnwTxk?p=preview

Works fine when clicking the button with the mouse but using a touch, only the tooltip is shown and the button action cannot be triggered.
The issue can be fixed by setting the trigger to `'hover'` (e.g. `data-trigger="hover"`).

I saw that there is a special case for this situation in [`bindTriggerEvents()`](https://github.com/mgcrea/angular-strap/blob/master/src/tooltip/tooltip.js#L426) but since `$tooltip.$onFocusElementMouseDown()` calls [`evt.preventDefault();`](https://github.com/mgcrea/angular-strap/blob/master/src/tooltip/tooltip.js#L411), this makes buttons unusable on mobile devices.

**Comment by bstruthers** [comment]
Seems like the easiest fix is to change from `touchstart` to `touchmove`.  See http://plnkr.co/edit/92hSukMZQuVaxAgPgMsO?p=preview.  I'm basing this off of: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Touch_events#Handling_clicks

I've tried the fix out with Chrome and Firefox on Android.  If it looks like a viable solution, I'll pull together the PR.
