### ISSUE TITLE
Modal directive does not support `data-` prefix for options.

### ISSUE THREAD

**Issue by monokrome** [mgcrea/angular-strap#1535]
When creating a modal, the `modal` directive specifically checks for attributes with a list of option names. Since these option names do not contain data-prefixed names (such as **dataTemplate**), the directive does not support attributes such as `data-template` although it does support `template` as an attribute. This is contrary to [the documentation][doc], which recommends using a `data-` prefix specifically.

https://github.com/mgcrea/angular-strap/blob/master/src/modal/modal.js#L303-L305

[doc]: https://mgcrea.github.io/angular-strap/#/modals#modals-examples

**Comment by vmlf01** [comment]
This is related to angularjs normalization of attribute names, the checks are correct, angularjs handles the processing of the attribute name variations.
