### ISSUE TITLE
Tooltip doesn't allow an autoclose option

### ISSUE THREAD

**Issue by dankahle** [mgcrea/angular-strap#1538]
Popover has an autoclose option and shares the same tooltip code. Just curious, but why was it decided to only enable this option for popover and not in tooltip?

**Comment by noordawod** [comment]
A very good question, @dankahle. Did you find a solution for this, eventually, as I'm in the same boat?

**Comment by vmlf01** [comment]
I guess it was just because tooltip tipically uses mouse over/leave, so there is no need for autoClose. But you can always submit a PR adding the option if that is something you need and find it useful :)

**Comment by noordawod** [comment]
There's actually an `auto-close` option for tooltip, but sometimes it's not working. I'm investigating this matter and will probably submit a pull request when I fix it.

**Comment by mr-White** [comment]
+1 for auto close feature

It would be good for touch devices. Tap to open, then auto close after a few seconds

**Comment by dankahle** [comment]
It isn't a delay-then-close feature (that would be a new feature), it's simply "click anywhere outside the popup closes it". You can see it on the third popover example. I was going through all the boolean attributes and noticed the inconsistency as the tooltip and popover are essentially the same control. The name is confusing as you have to do something to make it close. If you look at it as "they do something else on the page and it automatically closes" then the name fits.

**Comment by mr-White** [comment]
Ah, I understand. That would be nice, too! The ability to click anywhere outside the tooltip to close the tooltip is behavior I expected out of the box.
