### ISSUE TITLE
Incrementing Date and Hours on minute changes

### ISSUE THREAD

**Issue by rexthepenguin** [mgcrea/angular-strap#1539]
Hi, 
I don't know if this will help anyone, but I made some small changes to Angular-Strap JS to move date on when time moves past midnight either way. It also changes the Hour when minutes move past the hour mark, so I thought I would share:
        $timepicker.$setTimeByStep = function(value, index) {
          var newDate = new Date($timepicker.$date);
          var subDate = newDate;
          var hours = newDate.getHours(), hoursLength = formatDate(newDate, hoursFormat).length;
          var minutes = newDate.getMinutes(), minutesLength = formatDate(newDate, minutesFormat).length;
          if (index === 0) {
            newDate.setHours(hours - (parseInt(options.hourStep, 10) \* value));
            if((value==-1)&&(subDate.getHours() == 0)) {
              $timepicker.$date.setDate($timepicker.$date.getDate() + 1);
            }else if((value==1)&&(subDate.getHours() == 23)) {
              $timepicker.$date.setDate($timepicker.$date.getDate() - 1);
            }
          }
          else {
            newDate.setMinutes(minutes - (parseInt(options.minuteStep, 10) \* value));
            subDate = newDate;
            if((value==-1)&&(subDate.getMinutes() == 0)){
              $timepicker.$date.setHours($timepicker.$date.getHours() + 1);

```
        } else if((value==1)&&(subDate.getMinutes() == 55)){
          $timepicker.$date.setHours($timepicker.$date.getHours() - 1);

        }

      }
      $timepicker.select(newDate, index, true);
    };
```

Thanks for a great library
chise.derrick@gmail.com

**Comment by kkirsche** [comment]
Would you be able to wrap your entire code block with three backticks so it properly gets displayed as syntax highlighted code. It would be done like so:

    ```javascript
    code goes here
    ```

**Comment by vmlf01** [comment]
I suggest you make it into a new option for the timepicker and create a PR ;)

**Comment by rexthepenguin** [comment]
I'm not sure how to do a PR, but the code changes inside angular-strap.js are:
```javascript 3765
        $timepicker.$setTimeByStep = function(value, index) {
          var newDate = new Date($timepicker.$date);
          var subDate = newDate;
          var hours = newDate.getHours(), hoursLength = formatDate(newDate, hoursFormat).length;
          var minutes = newDate.getMinutes(), minutesLength = formatDate(newDate, minutesFormat).length;
          if (index === 0) {
            newDate.setHours(hours - (parseInt(options.hourStep, 10) * value));
            if((value==-1)&&(subDate.getHours() == 0)) {
              $timepicker.$date.setDate($timepicker.$date.getDate() + 1);
            }else if((value==1)&&(subDate.getHours() == 23)) {
              $timepicker.$date.setDate($timepicker.$date.getDate() - 1);
            }
          }
          else {
            newDate.setMinutes(minutes - (parseInt(options.minuteStep, 10) * value));
            subDate = newDate;
            if((value==-1)&&(subDate.getMinutes() == 0)){
              $timepicker.$date.setHours($timepicker.$date.getHours() + 1);


            } else if((value==1)&&(subDate.getMinutes() == 55)){
              $timepicker.$date.setHours($timepicker.$date.getHours() - 1);

            }

          }
          $timepicker.select(newDate, index, true);
        };
```
This assumes a minute step of 5 mins hence (subDate.getMinutes() == 55). I did the same with the keyboard controls and my code for this is:
...
          // Update values (up, down)
          var selectRange = [0, hoursLength];
          if(selectedIndex === 0) {
            if(evt.keyCode === 40){
              newDate.setHours(hours - parseInt(options.hourStep, 10));
              if(newDate.getHours() == 23) {
                $timepicker.$date.setDate($timepicker.$date.getDate() - 1);
              }
            }
            else if(evt.keyCode === 38){
              newDate.setHours(hours + parseInt(options.hourStep, 10));
            if(newDate.getHours() == 0) {
                $timepicker.$date.setDate($timepicker.$date.getDate() + 1);
              }
            }
            // re-calculate hours length because we have changed hours value
            hoursLength = formatDate(newDate, hoursFormat).length;
            selectRange = [0, hoursLength];

          } else if(selectedIndex === 1) {
            if(evt.keyCode === 40) {
              newDate.setMinutes(minutes - parseInt(options.minuteStep, 10));
               if(newDate.getMinutes() == 55){
                $timepicker.$date.setHours($timepicker.$date.getHours() - 1);

              }
            }
            else if(evt.keyCode === 38){
              newDate.setMinutes(minutes + parseInt(options.minuteStep, 10));
              if(newDate.getMinutes() == 0){
                $timepicker.$date.setHours($timepicker.$date.getHours() + 1);
              }
            }
...

To make it a new option, the code would need a variable indicating the minute and hour step, but this works for my purposes

**Comment by george3447** [comment]
+1
