### ISSUE TITLE
Dynamically added tabs always been pushed at end

### ISSUE THREAD

**Issue by just-boris** [mgcrea/angular-strap#1540]
I need to create tab view where some tabs should be visible or not.

Here is plunker with example: http://plnkr.co/edit/H0QWlrblViPJHauP2104?p=preview
Then I need to keep its order. In example the "Edit" always appears at end, but it should be right after the "Overview".

**Comment by just-boris** [comment]
As a workaround, I can add `ng-if="true"` to other tabs and then it will be placed correctly.
But it's a bit tricky

**Comment by joaoborsoi** [comment]
+1
