### ISSUE TITLE
Typeahead: Intial Value Reset if Using Object for ngModel

### ISSUE THREAD

**Issue by teohjk** [mgcrea/angular-strap#1543]
Here is the example derived from angular-strap example.
http://plnkr.co/edit/ZHZYriVO4jFRuuxXx5nv?p=preview

I am trying to get array of object dynamically, and my model is attribute of parent object. But it keep reset my initial value.

Ex: 

app.controller('mainCtrl',function($scope){
    $scope.content = {id:1,name:'abc'};
    $scope.getContent = function(viewValue){
        $http.post(....
       .....
        // return array of object ie. [{id:2,name:'sddd'},{id:3,name:'sddfg'}]
    };
});

<//input type="text" ng-model="content.name" ng-options="con.name as con.name in con for getContent($viewValue)" bs-typeahead />

The initial value of input is reset.

Do have a look on this issue.

**Comment by manikantag** [comment]
Can this be same as https://github.com/mgcrea/angular-strap/issues/1342?

Fix provided by @sloot14 seems working https://github.com/sloot14/angular-strap/commit/941012a8e6bc7097b41f20a7d9bd741526514075
