### ISSUE TITLE
Datepicker closes when using the month navigation buttons

### ISSUE THREAD

**Issue by mbates** [mgcrea/angular-strap#1544]
This issue only happens in PhoneGap, in a browser the datepicker will stay open when the navigation buttons are used.

But when I put the app into PhoneGap the 3 buttons used to navigate the months close the datepicker. The month does change, but it makes the datepicker hard to use if you want to select a date from a different month as you have to keep re-opening the datepicker.

I tried to put in an alert into angular-strap.js wherever $datepicker.hide() is called, but they are not shown in this case.

Are those 3 buttons doing anything unusual behind the scenes that could cause the date input to lose focus, and trigger the datepicker to close?

**Comment by mbates** [comment]
after playing around I've discovered that adding a timeout to $datepicker.$build fixes the issue. I don't know why though:

old method


        $datepicker.$build = function(pristine) {
          // console.warn('$datepicker.$build() viewDate=%o', viewDate);
          if(pristine === true && $picker.built) return;
          if(pristine === false && !$picker.built) return;
          $picker.build.call($picker);
        };

new method


        $datepicker.$build = function(pristine) {
          // console.warn('$datepicker.$build() viewDate=%o', viewDate);
          if(pristine === true && $picker.built) return;
          if(pristine === false && !$picker.built) return;
          $timeout(function() { $picker.build.call($picker); });
        };

**Comment by vmlf01** [comment]
Might have some relation with #854 and #882
