### ISSUE TITLE
collapses template?

### ISSUE THREAD

**Issue by maeishoj** [mgcrea/angular-strap#1546]
Hey guys,

I was wondering if it's possible to use the "collapses" by passing an html file as template to the body. 
This would be extremely useful..

Appreciate it..

**Comment by ppdg** [comment]
:+1:  interested by that ! 
 
like tabs : 
template / path false  / If a remote URL is provided, overrides the default template

**Comment by LAKnoKAL** [comment]
+1

**Comment by Icidis** [comment]
+1

**Comment by shafi-shaikat** [comment]
+1
