### ISSUE TITLE
RegExp flags as array?

### ISSUE THREAD

**Issue by dedlfix** [mgcrea/angular-strap#1547]
Why is the flag 'i' in angular-strap/src/navbar/navbar.js line 49 written in an Array?
var regexp = new RegExp(pattern, ['i']);

e.g. new RegExp('foo', ['i', 'g']) will throw a syntax error, although I can see a sense in writing it this way.
new RegExp('foo', ['ig']) will not, but in this case I can't see any sense in using the []-brackets.

See http://www.ecma-international.org/ecma-262/5.1/#sec-15.10.4.1
"...and let F be the empty String if flags is undefined and ToString(flags) otherwise.
...
If F contains any character other than "g", "i", or "m", or if it contains the same character more than once, then throw a SyntaxError exception."

The result of ['i'].toString() is 'i', which is fine according to the rules.
The result of ['i','g'].toString() is 'i,g', but the comma is a charachter "other than..."

**Comment by mgcrea** [comment]
Good catch ;-).
