### ISSUE TITLE
Docs are back and forth on normalized attributes vs dashed attributes

### ISSUE THREAD

**Issue by dankahle** [mgcrea/angular-strap#1548]
Should be one or the other, but it's "what to enter" right? So should be dashed then? Devs know what's going on though and it's devs that are using it, and... devs my have another weird way they want the attribute to be? From the ng docs, these are equivalent:
<span ng:bind="a" ng-bind="a" data-ng-bind="a" x-ng-bind="a">

So maybe they should all be normalized then, not dashed? Just confusing as they go back and forth. I'm only looking at select right now, but surely there's others.

**Comment by vmlf01** [comment]
I think it should display the normalized names because there are several ways you can write the attribute names depending on project conventions being used.
