### ISSUE TITLE
Stop /#/(Whaterever the href is)

### ISSUE THREAD

**Issue by Bana0615** [mgcrea/angular-strap#1558]
is there a way so i can still use normal bootstrap tabs and have it not put the /#/(Whatever the href is) in the URL bar because it is causing problems and it isn't useful for me personally

**Comment by vmlf01** [comment]
Can you please provide a sample? I don't see the tabs putting anything in the url, so not sure what you are refering to.

**Comment by Bana0615** [comment]
sorry i think i figured it out. It was becasue i had bootstrap.js being called also
