### ISSUE TITLE
data-prefix-event is not used for bs-modal

### ISSUE THREAD

**Issue by Tobbe** [mgcrea/angular-strap#1559]
The documentation says

> If provided, prefixes the events '.hide.before' '.hide' '.show.before' and '.show' with the passed in value. With the default value these events are 'modal.hide.before' 'modal.hide' 'modal.show.before' and 'modal.show'

But no matter what I specify for data-prefix-event on the html element, the event name is always modal.*, e.g. modal.show.before

Either the code needs to be updated, or the documentation :smile:

**Comment by Tobbe** [comment]
This can be worked around by using `data-id`, and checking for the correct id in the event handler. If this workaround is the official, and only, way to solve this, the section about `prefixEvent` should be removed from the documentation.

**Comment by vmlf01** [comment]
The id option is a recent addition to angular-strap intended to make it easier to identify the events source instances.
I guess it can work together with prefixEvent option, but I think the default prefix will suit most cases, if not all.

But back to original question, you are right, there is no code in bs-modal to process the prefixEvent option, so you can only change it if you change the provider defaults, so in this case the code needs updating.

**Comment by Tobbe** [comment]
I'm working on a pull-request to fix this

**Comment by vmlf01** [comment]
Fixed by  d781c14 .
