### ISSUE TITLE
parseOptions fails on proper ng-options syntax

### ISSUE THREAD

**Issue by lopex** [mgcrea/angular-strap#1562]
ng-options="v.value for v in action.load($viewValue)" is a proper syntax which is not being matched by angular-strap parseOptions module regexp.
Why not use the regexp (NG_OPTIONS_REGEXP) from ngOptions angular ships ?

**Comment by mgcrea** [comment]
@lopex IIRC that's what we used initially, angular may have changed it along the way. Too bad all of this is private and not easily reusable. 

https://github.com/angular/angular.js/blob/master/src/ng/directive/ngOptions.js#L204

**Comment by Greenek** [comment]
@mgcrea is there any known workaround?
