### ISSUE TITLE
from 2.1.6 to 2.2.0 works, but 2.2.1 breaks

### ISSUE THREAD

**Issue by chino23** [mgcrea/angular-strap#1564]
I've updated from 2.1.6 to 2.2.0 and saw no problem.

Then the 2.2.1 was out, and it suddenly broke lots of layouts and spitted out errors. How's that possible for a patchlevel?

I've seen the changelog, it's kind of cryptic. Saying 2.2.1 acting as a proper 2.2.0 release but there are no real release notes, but the diff is massive.

Am I missing something here?

**Comment by mgcrea** [comment]
Unfortunately, v2.2.0 was released with the v2.1.6 build files. By the time I realized that it was too late to fix, (was published on cdn's, etc). So the only option was to re-release v2.2.0 as v2.2.1.

**Comment by chino23** [comment]
Thanks @mgcrea for the clarification.

Is there a way to see a list of breaking changes, to fix the issues I have with the 2.2.1?

**Comment by mgcrea** [comment]
@chino23 check the commit patches listed here:

https://github.com/mgcrea/angular-strap/compare/v2.1.6...v2.2.0

**Comment by chino23** [comment]
ok thanks!
