### ISSUE TITLE
typeahead broken in 2.2.1

### ISSUE THREAD

**Issue by manikantag** [mgcrea/angular-strap#1569]
Hi, seems typeahead is broken in AngularStrap 2.2.1 (using AngularJS 1.3.14).

Getting below error:

	TypeError: Cannot read property '2' of null
	    at Object.ParseOptionsFactory.$parseOptions.init (https://rawgit.com/mgcrea/angular-strap/master/dist/angular-strap.js:2345:35)

Plunkr: http://plnkr.co/edit/v3aAPBRpBFdelmpkvuHD?p=preview

**Comment by mattgoldspink** [comment]
I just hit the same issue - turns out there was a change in 2.2.0 which requires you to use bs-options instead of ng-options. Seems to work after I change that: http://plnkr.co/edit/jEwBbu?p=preview

**Comment by mgcrea** [comment]
Yep, breaking change to support angular@v1.4, I've updated the release changelog.

**Comment by manikantag** [comment]
Oh, thanks.

**Comment by dacio** [comment]
just in case this helps others, this fix seems to also apply to bs-select as well. 2.2.1 broke all of the bs-selects I had with ng-options. changing to bs-options got 'em to work again.

also, fwiw, my typeaheads *__with bs-options__* were broken until I changed references to $tooltip to $bsTooltip (as recommended in https://github.com/mgcrea/angular-strap/issues/826) I had to do this to avoid conflicts with UI Bootstrap.

**Comment by bionets** [comment]
This still occurs even when I'm using bs-options.

**Comment by DaleWebb** [comment]
What's your `bs-options` statement?

**Comment by bionets** [comment]
Here is my bs-options statement:
model.name for model in getModels($viewValue)

**Comment by DaleWebb** [comment]
It needs to be:
`model.name as model.name for model in getModels($viewValue)`
