### ISSUE TITLE
Typeahead Bug in IE When Selecting Item Using Keyboard

### ISSUE THREAD

**Issue by usefulBee** [mgcrea/angular-strap#1570]
I created a BenCode example to demonstrate the issue. When the user (in IE) selects an item using the Enter key, the $scopes quickly lose binding.

http://codepen.io/anon/pen/azROdJ

**Comment by davidamitchell** [comment]
this is also a problem just using the demo on: http://mgcrea.github.io/angular-strap/#/typeaheads-examples

if one selects an icon via the keyword arrow and enter keys than the `$scope.selectedIcon` value breifly holds the selected object but then is overwritten with the `value` of that selected object.
