### ISSUE TITLE
options for all directives

### ISSUE THREAD

**Issue by Hrafnkellos** [mgcrea/angular-strap#1572]
When populating options for directives like the TypeAhead

```
// Directive options
var options = {scope: scope};
angular.forEach(['placement', 'container', 'delay', 'trigger', 'keyboard', 'html', 'animation', 'template', 'filter', 'limit', 'minLength', 'watchOptions', 'selectMode', 'comparator', 'id'], function(key) {
   if(angular.isDefined(attr[key])) options[key] = attr[key];
});
```

Options like minLength,delay and limit which are numbers, they are seen as strings witch is not correct. if i were to set these options they would be translated in the options object like so 

```
{
    minLength: "0",
    limit: "0",
    delay: "0"
}
```

we would like to have

```
{
    minLength: 0,
    limit: 0,
    delay: 0
}
```

this causes incorrect logic when doing things like !"0" // output: false witch should be !0 //output: true

**Comment by Hrafnkellos** [comment]
that exact logic for !"0" can be found in the code. b.t.w.

**Comment by Hrafnkellos** [comment]
you could fix this by gathering the options input like this 

        angular.forEach(['placement', 'container', 'delay', 'trigger', 'keyboard', 'html', 'animation', 'template', 'filter', 'limit', 'minLength', 'watchOptions', 'selectMode', 'comparator', 'id'], function(key) {
            if(angular.isDefined(attr[key])) options[key] = key == ("minLength" || "limit" || "delay") ? Number(attr[key]) : attr[key];
        });

**Comment by DaleWebb** [comment]
I think with the gathering options, it would be best to do two for loops.  One for loop for `string` values and the other for `int` values.

e.g.
```javascript
...
angular.forEach(['placement', 'container', 'delay', 'trigger', 'keyboard', 'html', 'animation', 'template', 'filter', 'limit', 'minLength', 'watchOptions', 'selectMode', 'comparator', 'id'], function(key) {
   if(angular.isDefined(attr[key])) options[key] = attr[key];
});
angular.forEach(['delay', 'limit', 'minLength'], function(key) {
   if(angular.isDefined(attr[key])) options[key] = Number(attr[key]);
});
...
```
