### ISSUE TITLE
Modal on top another modal, can't scroll 

### ISSUE THREAD

**Issue by JetFault** [mgcrea/angular-strap#1577]
On mobile:

Layout of page: body is scrollable, first modal is scrollable, 2nd modal is not long enough to be scrollable 

1. Open a modal
2. From that modal, open another modal that is on top of the previous one. 
3. Close topmost modal 
4. Scrolling scrolls the body and not the first modal

**Comment by JetFault** [comment]
Here is a plunker illustrating the problem: http://plnkr.co/edit/NQZBR0kt2DHVnaUR7Lap?p=preview

**Comment by Zjaaspoer** [comment]
Isn't this the same issue as #1343?

**Comment by pashamesh** [comment]
@Zjaaspoer looks like yes
