### ISSUE TITLE
prefixEvent not considered for typeahead

### ISSUE THREAD

**Issue by manikantag** [mgcrea/angular-strap#1578]
Hi, `prefixEvent` is being considered in typeahead code.

     .directive('bsTypeahead', ["$window", "$parse", "$q", "$typeahead", "$parseOptions",
           function($window, $parse, $q, $typeahead, $parseOptions) {

    var defaults = $typeahead.defaults;

    return {
      restrict: 'EAC',
      require: 'ngModel',
      link: function postLink(scope, element, attr, controller) {

        // Directive options
        var options = {scope: scope};
        angular.forEach(['placement', 'container', 'delay', 'trigger', 'keyboard', 'html', 'animation', 'template', 'filter', 'limit', 'minLength', 'watchOptions', 'selectMode', 'autoSelect', 'comparator', 'id'], function(key) {
          if(angular.isDefined(attr[key])) options[key] = attr[key];
        });

But while emiting event, prefixEvent is being used.

    scope.$emit(options.prefixEvent + '.select', value, index, $typeahead);

Any reason for that?

**Comment by vmlf01** [comment]
Similar to #1559

**Comment by EliSnow** [comment]
Also note it is not available in `Popovers` and possibly `Datepickers`, `Timepickers` and `Selects`, which all utilize `Tooltip`.

**Comment by vmlf01** [comment]
Fixed by  d781c14 .
