### ISSUE TITLE
Angularstrap Modal not show content when click open with $modal service twice

### ISSUE THREAD

**Issue by sangnv** [mgcrea/angular-strap#158]
I found a problem in the overview and example of Modal popup. When I click  the first time the modal popup is show the content correctly "Hello Modal", but when I click the second times the content was show wrong "{{modal.content}}". Can any one help me to fix this problem. Thanks in advance!

**Comment by Vinodang** [comment]
you should remove 'ng-show="title"' , ng-show="content" or ng-bind="title" from the template. You should make sure that the template has no 'ng-show'.
