### ISSUE TITLE
Select and touch events on IOS

### ISSUE THREAD

**Issue by kenborge** [mgcrea/angular-strap#1580]
There seems to be a bug with the Select implementation on IOS (tested version 8). If you click right on the text inside the dropdown menu nothing happens, the element isn't selected. But if you click outside the text then the element gets selected. 

This happens with the select box on the angular demo page too if viewed with an iphone

**Comment by cookednoodles** [comment]
I am seeing the same thing; this doesn't appear to be happening on the chrome emulator so 
I presume it's localized to ios

**Comment by kenborge** [comment]
The reason for it not happening in the chrome emulator would be that the "isTouch" check that angular-strap does is still false if when you emulate touch events in the browser. 

I tracked the problem down to a handler that is registered on 'touchstart' and prevents and stops propagation of this. This causes the click event that happens after the touch event to never fire, so the element is never clicked. There is code that tries to handle this:
````
if(isTouch) {
  var targetEl = angular.element(evt.target);
  targetEl.triggerHandler('click');
}
```
But triggerHandler does not propagate the event so if text inside the element is clicked the parent element with the onClick is not triggered

**Comment by kenborge** [comment]
There does not seem to be a reason to stop propagation of the touchstart event on select box, so my current solution is to just register the handler on onMouseDown and not on touchstart

**Comment by kenborge** [comment]
Didn't turn out to be as simple as stopping to listen for touchstart, ended up breaking clicking in some cases

**Comment by benbenwilde** [comment]
There are some poor decisions happening here.
Why would you ever trigger a `click` on `mousedown`, or `touchstart`?

You should `click` on `touchend`.
If `touchmove` happens after `touchstart`, you should not `click` on `touchend`.
You should not stop propagation on `touchstart`.
You also should not stop propagation on `mousedown`.
You also should not close the select box when the input loses focus. You should close the select box when both the input AND the dropdown lose focus. You should additionally close it after clicking inside the dropdown if it is not a multiselect.

**Comment by darkobits** [comment]
:+1: 

This directive is completely hosed on iOS.

**Comment by antonvp** [comment]
Any updates on the issue?
