### ISSUE TITLE
bs-typeahead auto select first option issue - 2.2.0

### ISSUE THREAD

**Issue by peteringram0** [mgcrea/angular-strap#1586]
If you upgrade from an earlier option to get typeahead to auto select the first option available you now need to specify auto-select="true" as part of the directive.

Please can this also be added to the docs as it fails to mention this.

**Comment by ansonkao** [comment]
Hey there. The docs have been updated but haven't been deployed - the live site is still showing 2.1.6. Bower also needs to get updated.

**Comment by ansonkao** [comment]
Duplicate of #1585

**Comment by peteringram0** [comment]
thanks
