### ISSUE TITLE
popover $isShown property returns faulty value

### ISSUE THREAD

**Issue by episodeyang** [mgcrea/angular-strap#1590]
It is really weird. Suppose you have the following popover:

``` javascript
$scope.popover = $popover(
        $scope.popoverButtonElement,
        {
            scope: $scope,
            template: 'textEditor/settings',
            show: false,
            animation: 'text-settings am-fade-and-slide-top',
            placement: 'bottom',
            container: '#text-editor-panel-content',
         });
```

Now if you run

``` javascript
$scope.popover.$show()


// and then after running some other stuff for a little while, like in a different callback etc. 

// run this, and it gives `true`. This is correct.
console.log($scope.popover.$isShow);

// Now let's close the popover! 
$scope.popover.$hide()
// and check what the value is:
// Holly cow!! it is still `true`!!
console.log($scope.popover.$isShown)

// now if you print out the entire popover (not just the $isShow attribute)
console.log($scope.popover)
// In the console, it actually shows `false` correctly!!

// and you can console.log the $isShown again. It is always `true`.

```

it always returns `true`.

This causes the `$toggle` method to fail as well.

It turns out if instead of asking for the `$isShown` property direction, but instead print out the `popover` object, in the console you see that the $isShown property is already set properly to `false`. 

However, if you try to print again, it shows `true`.

Does anyone have this issue?

**Comment by vmlf01** [comment]
Can you post a sample? Not sure how you are implementing the "// and then after a little white run" part.

**Comment by episodeyang** [comment]
Hey @vmlf01,

Aha there was a typo in there!! Somehow my hands are typing slower and slower these days. Really wierd.

So I just updated the script above! Does the current form make more sense?

Best, Ge
