### ISSUE TITLE
Only `button` tag works with `bs-select`

### ISSUE THREAD

**Issue by witrin** [mgcrea/angular-strap#1593]
It seems only the `button` tag works with the `bs-select` directive. I've tried `div` and `bs-select` tags but the items do not appear: http://plnkr.co/edit/BEi4SJjeIIVqAufCLMqg?p=preview. I'm using Firefox 36 under GNU/Linux.

**Comment by DaleWebb** [comment]
Is there a reason why you would not use a `button` tag?

I guess we should have some way of saying that the `bs-select` should only be used on `button` or `select`.
