### ISSUE TITLE
How to close modal in controller

### ISSUE THREAD

**Issue by tushariscoolster** [mgcrea/angular-strap#1595]
How to close modalbox in controller when i opm modal box as 
   <button type="button" class="btn btn-success" data-container="body" data-animation="am-fade-and-slide-top" data-template="configuration/providergroup/providergroup.modal.html"  bs-modal="modal">

Please help me

**Comment by vmlf01** [comment]
Try using the scope $hide() helper method or calling the .hide() method if using the modal provider.
