### ISSUE TITLE
Datepicker updates model to 1 day before selected date

### ISSUE THREAD

**Issue by montyBazBaz** [mgcrea/angular-strap#1597]
Hi, I noticed this when using your datepicker, and it looks to be reproducible on the demo in the docs website.

Dates selected after the 30th March 2015 updates the model to be the day previous,
e.g selecting 30th March 2015 in the fromDate Datepicker of the Date Range demo,  will set: 
$scope.fromDate = "2015-03-29T23:00:00.000Z";

**Comment by vmlf01** [comment]
This is because of your timezone. The date value you are seeing is in UTC time.

**Comment by montyBazBaz** [comment]
thanks, as mentioned in the docs i needed to add the relevant i18n file.

**Comment by vmlf01** [comment]
I don't understand what including the i18n file did to solve this. Did it change the value you were getting on ngModel? Sorry to bother you with this, but can you post more details?

**Comment by montyBazBaz** [comment]
HI, yes you're right it isn't the i18n file, for some reason though it has started working in chrome but not the other browsers.  

What you say about the time zone makes sense as when it does work correctly the time value is set to T00:00:00.000Z, however in Firefox, 1 hour is subtracted from that time giving T23:00:00.000Z of the previous day.

I will update you when I have found what the difference is between chrome and the other browsers.
