### ISSUE TITLE
select : Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context.

### ISSUE THREAD

**Issue by yankuangshi** [mgcrea/angular-strap#1598]
Hi, I'm trying to use the bs-select but I keep getting the error : 
Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context.

For information, I'm using:
angular 1.3.8
angular-strap : 2.1.6
I'm using the same code to the single select example in the documentation with the config : 

```
config(function($selectProvider) {
	angular.extend($selectProvider.defaults, {
	    animation: 'am-flip-x',
	    sort: false
	});
});
```

**Comment by vmlf01** [comment]
Are you including ngSanitize? Can you post a sample?

**Comment by leoetlino** [comment]
The issue is most probably failing to include ngSanitize into the app − this happens when you fail to include ngSanitize and have data-html="true".

**Comment by yankuangshi** [comment]
I confirme that the issue is failling to include ngSanitize module into my app. Thanks.
