### ISSUE TITLE
Docs for older versions

### ISSUE THREAD

**Issue by franleplant** [mgcrea/angular-strap#1601]
Hi!
    Where can I find documentation for older version, say 0.7.8 ?

Thanks!
Fran

**Comment by atav32** [comment]
+1

**Comment by iagopiimenta** [comment]
+1

**Comment by luzfcb** [comment]
It would be extremely, incredibly good.

**Comment by mgcrea** [comment]
You can find the oldest doc available at http://mgcrea.github.io/angular-strap/1.0/

**Comment by aschriner** [comment]
how about 2.1.2?  or, any arbitrary version... pretty important to have docs that correspond to the version one is actually using

**Comment by DaleWebb** [comment]
The docs are in the repository.  So if you have version 2.1.2, you can run your own version of the docs on something like your local machine.
