### ISSUE TITLE
bs-select with associative array

### ISSUE THREAD

**Issue by detten** [mgcrea/angular-strap#1602]
I experience problems to combine a bs-select dropdown with an associative array.

Example here : http://plnkr.co/edit/RyXk6CBFhrePQKMXsFom?p=preview

error = TypeError: Cannot read property 'match' of undefined

Is this a bug or am I doing something wrong?

**Comment by lloudier** [comment]
I experience the same issue with angular 1.4 and angular strap 2.2.1 (with or without parse options filter).

**Comment by vmlf01** [comment]
I don't think bs-select supports that particular syntax, I think it only recognizes normal arrays.

**Comment by hisham** [comment]
running into this as well...
