### ISSUE TITLE
directive-select, has some issues

### ISSUE THREAD

**Issue by Jonas-Worker** [mgcrea/angular-strap#1603]
![1](https://cloud.githubusercontent.com/assets/11519592/6818097/dd0f0796-d2e4-11e4-9e5b-0f6457690467.PNG)
![2](https://cloud.githubusercontent.com/assets/11519592/6818096/dd0d8c5e-d2e4-11e4-8b31-70cd86a86a41.PNG)
![3](https://cloud.githubusercontent.com/assets/11519592/6818098/dd1fbdde-d2e4-11e4-969b-95d7139752f9.PNG)

**Comment by vmlf01** [comment]
can you provide a plunker test case with the problem?

**Comment by Jonas-Worker** [comment]
Thank you for answer. This issue has been resolved . I found some of my configuration , and references is wrong. Thank you again.
