### ISSUE TITLE
Typeahead removes spaces

### ISSUE THREAD

**Issue by svet007** [mgcrea/angular-strap#1604]
http://mgcrea.github.io/angular-strap/#/typeaheads#typeaheads

Type "fasdfasd asdfasdfas" quickly in the Address typeahead. You can type any two sequences of letters, separated by space

Expected: "fasdfasd asdfasdfas" in the typeahead field

Actual "fasdfasdasdfasdfas" in the typeahead field (space removed)

**Comment by andremetzen** [comment]
Same issue here.

**Comment by vmlf01** [comment]
Might be fixed with PR #1439?

**Comment by albertldlan** [comment]
Not sure if this has been addressed or not, but the space can be somewhat retained if you wait a bit before entering the next sequence of characters. So in your example, if you typed "fasdfasd asdfasdfas" in a smooth sequence it would return as "fasdfasdasdfasdfas", but if you typed "fasdfasd", waited for a few seconds, then hit space and typed "asdfasdfas", you would get "fasdfasd asdfasdfas," as expected. It's definitely not ideal and a weird issue.

This is on 2.2.1, the latest available version on bower.

**Comment by jindalsyogesh** [comment]
I just download v2.2.4 from bower and I am facing the same issue. Any update on when it will be fixed?

**Comment by mgcrea** [comment]
Use the `trimValue` option landed in #1439

**Comment by daniel-nalbach** [comment]
I see the trimValue code in the 2.2.4 source but am still experiencing the space trimming issue after updating from 2.0.5 to 2.2.4 like jindalsyogesh mentioned. 

Looking at the code, I believe the problem is that in line 157 the watchOptions code is still using trim() on the match parsing. So trimValue will not work if also using watchOptions.  :(

**Comment by jindalsyogesh** [comment]
daniel-nalbach, I used the following two attributes on my input box and it worked on version 2.2.4: 
data-trim-value="false" ng-trim="false"

**Comment by qqilihq** [comment]
Can confirm this, `data-trim-value="false"` alone didn't suffice, adding `ng-trim="false"` works. Thank you, @jindalsyogesh.

If that's the intention that both attributes need to be added, it should be documented like this.

**Comment by iceboxX** [comment]
It was working very weirdly, this fixed however `data-trim-value="false" ng-trim="false"`.
Thanks
