### ISSUE TITLE
Datepicker set as ng-invalid despite not being required

### ISSUE THREAD

**Issue by maciejjankowski** [mgcrea/angular-strap#1605]
scenario:
I have a datepicker which is required conditionally. But the datepicker says it is is invalid no matter if set it as required or not.

When it is not required it should not be set as ng-invalid, because it blocks the whole form from being submitted and this sucks really bad.

"regular" fields show the correct behavior, i.e. ng-pattern validation kicks in _only_ when the fields is set as required

**Comment by vmlf01** [comment]
Can you please provide a test case?

**Comment by maciejjankowski** [comment]
http://jsfiddle.net/mjankowski/9d69Lvx8/
problem occurs with 1.3.0
With 1.2.1 it working as expected

**Comment by equilerex** [comment]
Any update on this? ran ito the same issue after upgrading
