### ISSUE TITLE
Angular-strap v2.2.1 not compatible with angular v1.3.15

### ISSUE THREAD

**Issue by fedemoretti** [mgcrea/angular-strap#1606]
At the moment of writing this issue, both versions are the latest.

This plunker shows the angular-strap example for select (modified to include the last angular and angular-strap versions):
http://plnkr.co/edit/n26qQikOZZ2Bbgc4A76n?p=preview

**Comment by ttonyh** [comment]
I had the same problem; reading through the source I discovered that they changed the "ng-options" attribute to "bs-options" in the "select" directive. The docs haven't been updated to reflect the change.

**Comment by tritonresearch** [comment]
Thank you so much, @fedemoretti, you saved me a headache. :)

**Comment by zxdong262** [comment]
happened to typeahead doc too:
http://mgcrea.github.io/angular-strap/#/alerts#typeaheads

**Comment by mgcrea** [comment]
Docs have been properly updated to reflect the changes. Thanks.
