### ISSUE TITLE
bs-options does not handle circular dependencies

### ISSUE THREAD

**Issue by kenborge** [mgcrea/angular-strap#1607]
On elements like bs-select when using bs-options with elements that have circular dependencies angular will throw a ```RangeError: Maximum call stack size exceeded```error. ng-options with native selects handles this just fine.
Ex
```javascript
var entity1 = {
    label: "First"
};
var entity2 = {
    label: "Second"
};

var entityList = [entity1, entity2];

// Create a cycle
entity1.ref = entity1;
```

Jsfiddle demonstrating the issue, also includes a native select with ng-options that does not throw the error: http://jsfiddle.net/tn102eh8/1/

**Comment by kenborge** [comment]
The difference is that ngOptions uses $watchCollection while bsOptions uses watch with deep comparison activated. The watch just infinitely follows the circular dependency while $watchCollection only does one level deep.

**Comment by mgcrea** [comment]
@kenborge nice find.
