### ISSUE TITLE
`Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'` occurs while using `2.2.1`

### ISSUE THREAD

**Issue by leftstick** [mgcrea/angular-strap#1608]
Once i install the latest version `2.2.1`, i found that `bs-tooltip` doesn't work any more.

My code is very simple as following:

    <span data-animation="am-flip-x" bs-tooltip data-type="success" data-title="{{ report.report_name }}">
                                      {{ report.report_name }}
    </span>

And it works properly with version `2.1.6`

**Comment by leftstick** [comment]
Conflict with `bootstrap.js`

**Comment by chuanxd** [comment]
@leftstick how to resolved it ?

**Comment by leftstick** [comment]
@chuanxd I end up with the latest version `2.3.0`. And be aware that do not import `bootstrap.js`
