### ISSUE TITLE
positioning popover via service

### ISSUE THREAD

**Issue by DealerCorp** [mgcrea/angular-strap#1609]
after upgrade to 2.2.1, my popover positions went wrong.
even the sample on angular-strap, the popover is not positioned correctly. 
![image](https://cloud.githubusercontent.com/assets/8525800/6903927/6bf9d364-d6eb-11e4-8ccb-52e1158ab15d.png)

**Comment by etiennejsnippets** [comment]
+1

**Comment by kamekazemaster** [comment]
+1

**Comment by DanielSchuech** [comment]
+1

**Comment by phymous** [comment]
Worked better in v2.0.1:
![auswahl_066](https://cloud.githubusercontent.com/assets/7686856/8132703/e77fef1a-1123-11e5-88f1-6b77260a4040.png)

**Comment by AzadMemon** [comment]
Not to badger you, but +1 for me as well.

**Comment by evillemez** [comment]
+1 Same... does anyone know what specifically changed?

**Comment by sebastientromp** [comment]
+1

**Comment by vmlf01** [comment]
duplicate of #1566
