### ISSUE TITLE
can't turn off useNative through element attributes

### ISSUE THREAD

**Issue by arteme** [mgcrea/angular-strap#1615]
There seems to be no way to turn off `useNative` flag for either datepicker or timepicker widgets through the attributes on the element.

For example, since datepicker has `useNative = false` default, all of the following will enable `useNative` on the element:
```
<input type="text" bs-datepicker data-use-native="true"/>
<input type="text" bs-datepicker data-use-native="1"/>
<input type="text" bs-datepicker data-use-native="false"/>
<input type="text" bs-datepicker data-use-native="0"/>
``` 

For timepicker, since its default is `useNative = true`, there is no way to turn it off. None of these work:
```
<input type="text" bs-timepicker data-use-native="false"/>
<input type="text" bs-timepicker data-use-native="0"/>
```

**Comment by arteme** [comment]
I'm actually having the same problem with "data-autoclose" attribute. I'm on AngularJS 1.3.8.

**Comment by arteme** [comment]
If I read #966 correctly, this is the correct current behavior. The problem is then that doing things like https://github.com/dmtw/schema-form-datetimepicker/blob/7c9a164104875f4b61d437a85b9a5b6560aa81e3/src/datepicker.html is plain wrong. It would be extremely useful to have that attribute value evaluated instead of simply attribute's presense checked for.

**Comment by vmlf01** [comment]
Maybe PR #1612 fixes this?
