### ISSUE TITLE
getAddress() had been removed from the typeahead documentation

### ISSUE THREAD

**Issue by blackpenny15** [mgcrea/angular-strap#1618]
Yeah not much more to write, it was there a few days ago before the bg switch so I assume it got knocked out after that.

**Comment by squadwuschel** [comment]
On the Website the example is still there with getAddress or what do you mean?

**Comment by blackpenny15** [comment]
http://mgcrea.github.io/angular-strap/#/typeaheads the getAddress method is gone from the example code in the scope

**Comment by vmlf01** [comment]
Checked the git history and it has been like that for a long time. Maybe you saw that in the plunker sample source code? It is still there.
