### ISSUE TITLE
Prevent default select action on typeahead

### ISSUE THREAD

**Issue by alexborisov** [mgcrea/angular-strap#1621]
Currently when i select a prediction it causes an API request to the typeahead service to fire. How can i disable this? The value is already there and i just want the model to be updated.

A bit more background, i have an interceptor that transparently signs requests to the endpoint via oauth. On selecting the typeahead it seems to make a request that bypasses the interceptor and i get an error in my console log.

**Comment by vmlf01** [comment]
I think this as been talked about before in the issues, it looks like a nice enhancement to reduce server requests. However, I don't see how that would cause the error you are seeing, so there must be another reason for that.

**Comment by alexborisov** [comment]
Right so investigating further: basically selecting an item causes an API request with the typeahead response value. In my case the response is a json object and so this causes the whole object to be passed as a parameter to my typeahead service on select. This naturally is an invalid request and causes an error response. The part I am trying to understand is why there is a request in the first place - I'm selecting a value i already have received. why do i need to request it again?

**Comment by smurugavel** [comment]
I agree with @alexborisov and this is a problem. 
Here is a plunk: http://plnkr.co/edit/tzEbroAWxYd0pOQGfx2C?p=preview
use ajax request on google api example and check console. you will notice that request is made after typeahead selection .

not sure if it needed to be treated as enhancement, but suggest it be treated as a bug to be fixed.
