### ISSUE TITLE
datepicker minDate 'today' broken

### ISSUE THREAD

**Issue by alexborisov** [mgcrea/angular-strap#1622]
The documentation lists you can specify `today`as a string to `minDate`. This doesnt work. Using `new Date()` does. I'm setting options via `$datepickerProvider`

**Comment by vmlf01** [comment]
The ```today``` special value is only recognized if used in the directive html attributes.

When using the provider defaults, you need to use Date values, like you did.

**Comment by alexborisov** [comment]
Ok I suspected as much! Perhaps update the documentation though to make this clear? Thanks :+1:

**Comment by brycepj** [comment]
+1 to improving documentation on this.
