### ISSUE TITLE
Typeahead - No Keyboard Scrolling When Increasing the Limit

### ISSUE THREAD

**Issue by usefulBee** [mgcrea/angular-strap#1623]
Plunker: http://plnkr.co/edit/tXORiPDyszwRfT6SFf3n?p=preview
I added the following config code to increase the typeahead result limit:

angular.module('mgcrea.ngStrapDocs')

```
.config(function ($typeaheadProvider) {
    angular.extend($typeaheadProvider.defaults, {
        //animation: 'am-flip-x',
        minLength: 1,
        limit: 500
    });
})
```

If the result list is not visible to the browser, page scrolling using the keyboard is not possible.

What are the suggestions in a situation like this?

I also attempted to add a scroll bar using css and limit the height but still the keyboard fails to scroll.

**Comment by vmlf01** [comment]
Duplicate of #1021
