### ISSUE TITLE
Datepicker dropdown width issue in safari

### ISSUE THREAD

**Issue by sameer22** [mgcrea/angular-strap#1625]
Below image shows datepicker dropdown when opened in safari (http://mgcrea.github.io/angular-strap/#/datepickers)

![img1](https://cloud.githubusercontent.com/assets/9525289/6980131/ec566906-da0a-11e4-9bb5-3254bdc0b67f.png)

Below image is of plunker generated and viewed in safari. you can see the width issue. (http://plnkr.co/edit/?p=preview)

![img2](https://cloud.githubusercontent.com/assets/9525289/6980174/6560e9c0-da0b-11e4-8e56-e74f7368446b.png)

Request for solution.

Regards
Sameer

**Comment by vmlf01** [comment]
Looks like it is missing the bootstrap-additions [https://github.com/mgcrea/bootstrap-additions/blob/master/src/datepicker/datepicker.less] styling.

**Comment by sameer22** [comment]
Ok...Will give a try.

**Comment by sameer22** [comment]
Thanks. Solved Issue.

Can I ask one more browser related query that daepicker shows current date in Chorme but not in Safari?
