### ISSUE TITLE
Alert - How to clear all alerts /close all modals automatically?

### ISSUE THREAD

**Issue by hiepthai** [mgcrea/angular-strap#1627]
For example!
I want to clear all alerts/close all modals after user was redirected to another page by clicking on a button.

Can any one help me with this?

**Comment by DaleWebb** [comment]
You can listen for route changes and hide the appropriate modals at that point.

```javascript
var modals = [];

...

function closeAllModals () {
    modals.forEach(function(modal) {
        modal.hide();
    }
}

$scope.$on('$routeChangeSuccess' /* or $stateChangeSuccess for ui.router */, closeAllModals);

```
