### ISSUE TITLE
Cannot override content in $alert

### ISSUE THREAD

**Issue by anudeepjusanu** [mgcrea/angular-strap#1635]
I was trying to use $alert for alert messages in my app. Created a service to use $alert through out the app by calling the service whenever needed. When I call the service for the 1st time with a message the alert is displayed properly, now when I try to override the content it is not getting updated, showing the initial content only. Please Correct me if I am wrong anywhere.

This is how i was trying to call the $alert
var userMsg = "";
if (userMsg == "") {
       userMsg = $someService.alertMsg('Hola!', message, 'success', '#showMessage', 5);
       setTimeout(function() {
             userMsg.show();
       }, 500);
 } else {
     userMsg.$options.content = "Random content";
     userMsg.show();
  }

This is my alert Service
this.alertMsg = function(title, content, type, container, duration) {
        if (!duration) {
            duration = 0;
        }
        if (!container) {
            container = 'body';
        }
        
        alertObj = $alert({
            title: title,
            content: content,
            placement: 'top-middle',
            type: type,
            duration: duration,
            container: container,
            show: false
        });
       return alertObj;
    }

**Comment by vmlf01** [comment]
Try to create a new $modal each time you need to display a message instead of changing the content property, because that property is not listening to changes.

**Comment by anudeepjusanu** [comment]
In that case there will be multiple alerts
