### ISSUE TITLE
typeahead select list bug

### ISSUE THREAD

**Issue by Gabriel0402** [mgcrea/angular-strap#1637]
I'm not sure whether this is a bug, so for the angular strap, when I input something not in the select list, when I click away and click it again, the select list will pop up. However, if I choose the item in the select list and click away and click back, the select list won't show up. Is there any solution to make the select list show up?
The plunker is here:

http://plnkr.co/edit/NwFqsdUWcSi5RyKOAMkt?p=preview

So I want the function that when I input Alaska in the Icon input and select Alaska from select list, when I click away and click back the select list will show up with Alaska. Thanks.

**Comment by Gabriel0402** [comment]
I looked into the code and find the following code:
            var isVisible = typeahead.$isVisible();
            isVisible && typeahead.update(values);
            // Do not re-queue an update if a correct value has been selected
            if(values.length === 1 && values[0].value === newValue) return;
            !isVisible && typeahead.update(values);
            // Queue a new rendering that will leverage collection loading
            controller.$render();
I'm not sure whether this is an issure as I have to use ng-blur to trigger some function to replace the object and it works fine.

**Comment by ftrossbach** [comment]
I have the same issue. How did you fix it exactly?

**Comment by andras-tim** [comment]
+1

**Comment by Gabriel0402** [comment]
I'm using ng-blur to trigger a function to replace the original object. As if we don't replace the object, it would have this problem

**Comment by DaleWebb** [comment]
I couldn't reproduce the bug, so I am going to assume that this is fixed
