### ISSUE TITLE
Template path when loaded in bower

### ISSUE THREAD

**Issue by Oliv** [mgcrea/angular-strap#1639]
Hello there,

I have some issue with template file loading :

The GET query on, for exemple, alert, hits alert/alert.tpl.html, instead of bower_components/angular-strap/src/alert/alert.tpl.html
Did I miss something ? 

Best regards

**Comment by vmlf01** [comment]
You should be loading two different files:
- angular-strap.js: library javascript code
- angular-strap.tpl.js: default HTML inline templates used by the directives

The templates are then retrieved from the inline templates loaded into cache using that path, it should not hit the server.

But maybe you are using individual component files? In that case, you would need to load the component template file also along with the js.

**Comment by Oliv** [comment]
Hello,

This is clearer now, it works while doing :
```
require('angular-strap');
require('angular-strap/dist/angular-strap.tpl');
```
This is better in my opinion than including js file in the html

Closing the issue, best regards !
