### ISSUE TITLE
Popover custom template image

### ISSUE THREAD

**Issue by josh-compeat** [mgcrea/angular-strap#1641]
When the popover is first triggered, it will be in the wrong position because its dimensions were calculated prior to loading the image.

Plunkr: http://embed.plnkr.co/AbZ7iuTA6jIF4IjcinpQ/preview

**Comment by vmlf01** [comment]
Probably same as #399?

**Comment by josh-compeat** [comment]
Yeah pretty sure.
Duplicate of #399
