### ISSUE TITLE
Please update Developer intro to fix a bug

### ISSUE THREAD

**Issue by dmitriz** [mgcrea/angular-strap#1644]
The current Development environment seems to have a bug - when running `gulp test`, there is error:

    INFO [karma]: Karma v0.12.31 server started at http://localhost:8080/
    INFO [launcher]: Starting browser PhantomJS
    ERROR [launcher]: No binary for PhantomJS browser on your platform.
    Please, set "PHANTOMJS_BIN" env variable.

I have found the following solution (http://stackoverflow.com/a/28400706/1614973) that worked for me:

     //install globally
     npm install -g karma-phantomjs-launcher

     //temporary path.. set the path
     export PHANTOMJS_BIN=/usr/local/lib/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs

Please update the Developer Guide!

**Comment by vmlf01** [comment]
Closing this as it's related to phantom js usage. If more people faced the same problem, please report here so we get a feel for the need to reference it in docs.
