### ISSUE TITLE
DatePicker not showing today date in safari

### ISSUE THREAD

**Issue by sameer22** [mgcrea/angular-strap#1645]
I'm not able to view the current date in safari while same code is working in Chrome/IE.

Help needed.

Thanks.

**Comment by vmlf01** [comment]
Please post a test case so others can have a look and test it.

**Comment by sameer22** [comment]
I created plunker from website and found working. I checked the code again. Below is the code, which I have corrected

momentDate = moment(serverDateTime, "DD-MM-YYYY HH:mm");

Incorrect
$scope.ConsultantAppointment.dt = momentDate.format("MM-DD-YYYY");

Correct Code
$scope.ConsultantAppointment.dt = momentDate;

Thanks again.
