### ISSUE TITLE
Using UI Bootstrap Modal with angular-strap asides

### ISSUE THREAD

**Issue by damogallagher** [mgcrea/angular-strap#1653]
Hi

I am trying to use the modals from the UI Bootstrap library.
I am already using the aside functionality from your library 

I import it into my code as follows - 'mgcrea.ngStrap.aside'
When I try to open a modal as follows

            `var modalInstance;

            modalInstance = $modal.open({
                templateUrl: "components/modals/showWarningMessageModal.html",
                controller: 'WarningModalInstanceCtrl',
                resolve: {
                	message: function () {
                      return message;
                    }
                  }
            });`

I get the following error in the chrome console 
TypeError: $modal.open is not a function

When I remove the 'mgcrea.ngStrap.aside' reference, this code works
Is there any qay I can use your aside plugin along with he UI boostrap modal functionality?

Cheers
Damien

**Comment by vmlf01** [comment]
Probably not an easy thing to do, see #521

**Comment by damogallagher** [comment]
is it a valid answer to say something is easy and then close the ticket?

**Comment by vmlf01** [comment]
Feel free to try it out and please continue discussion on #521 as this is a more general issue.
Closed this just to prevent spreading of information accross multiple issues.

**Comment by shadywattay** [comment]
just removed angular-strap from my project after realizing its a "Probably not an easy thing to do". 
If This issue could have been fixed, a great mix of best directives could be achieved.

**Comment by mgcrea** [comment]
@shadywattay It's been fixed already: A compat build landed in d063b44. Released in v2.3.3. You can now use both UI and ngStrap components easily, just use the compat build and require `$bsModal`.

**Comment by shadywattay** [comment]
I hope it will be smooth with the new naming convention. thanks for quick reply @mgcrea
