### ISSUE TITLE
Typeahead model value customization

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mgcrea/angular-strap#1658]
Hello,

I have got scenario where i have to list typeaheads into multiple rows. 

```
Json might look like: [
{tvalue: 1}, {tvalue: 2}, {tvalue: 3}
]
```

where ng-model of typeahead is tvalue and datasource of bs-options might look like:

```
[{value: 1, text: 'test 1'}, {value: 2, text: 'test 2'}]
```

so I got from the server only values but not objects. I cannot get typeahead selected only by value it looks for an object. And I need post to server only values not objects. 
Is there any way to specify model binding property?

e.g. in angular-strap.js there is a code line like:

```
scope.$modelValue = newValue;
```

if it could be converted to some

```
scope.$modelValue = newValue['objectproperty name comming from directive options'];
```

user could specify which property will be value of ng-model.

**Comment by vmlf01** [comment]
Have you tried something like:
```
bs-options="item.value as item.text for item in options"
```

**Comment by vytautas-pranskunas-** [comment]
Yes, i did. But it shows item value after selection is made not the text.
