### ISSUE TITLE
January 1st Does Not Work in Date Picker

### ISSUE THREAD

**Issue by benrosamond** [mgcrea/angular-strap#1665]
There's something magical about January 1st with the date picker.  If you open the date picker and choose a date on a different month, say February, and then go back to January and choose Jan. 1st, the date picker will not show it highlighted as the selected date.  It corrects itself if you toggle to another  month and back.

This was tested in Chrome 42.0.2311.90 on the angular-strap site - http://mgcrea.github.io/angular-strap/#/datepickers

**Comment by vmlf01** [comment]
Actually, it seems to do that with any month, unless you select a different day form that month first or change months.
