### ISSUE TITLE
$modal animation not work

### ISSUE THREAD

**Issue by guanxudong** [mgcrea/angular-strap#1671]
`<link rel="stylesheet" href="/static/css/angular-motion.min.css">`

`<script src="/static/vendor/angular.min.js"></script>`
`<script src="/static/vendor/angular-animate.min.js"></script>`
`<script src="/static/vendor/angular-strap.min.js"></script>`
`<script src="/static/vendor/angular-strap.tpl.min.js"></script>`

**html**

`<button class="btn btn-sm btn-success" ng-click="query(line)"><i class="fa fa-search"></i></button>`

**controller.js**

``` 
  $scope.query = function (line){
      SQLQuery.post($.param({sql: line.sql_string}), function (response){
        if (response.action === true){
          $scope.modalData = response.data;
          var modal = $modal({
            scope: $scope,
            show: true,
            animation: 'am-fade-and-scale',
            placement: 'center',
            template: '/templates/sql-dba-request-list-group.html'
          }); 
        }   
      }); 
    }; 
```

if I do wrong way? thank you very much

**Comment by vmlf01** [comment]
I adapted the essential of your code to a plunker and it seems to work.
It didn't work when I specified the template, because I don't have that file, so maybe check if you have the right path?

http://plnkr.co/edit/fHgAfRrruhChtyVuBrBE?p=preview

**Comment by guanxudong** [comment]
Hi vmlf01, template path is right, because it can show the page that I want,
I also try to set the defaults as below:
```
myApp.config(['$modalProvider', function($modalProvider) {
  angular.extend($modalProvider.defaults, {
    animation: 'am-fade-and-scale',
    placement: 'center'
  });
}]);
```
but no animation.

**Comment by vmlf01** [comment]
I updated the plunker to use a custom template, and it still works.
Please check your dependencies path again, your animation class for any typos and make sure you include ngAnimate in your module dependencies.

Try it without specifying the custom template and see how that goes.

**Comment by guanxudong** [comment]
I tried, but no way...
use data-x will be okay, but $modal not work...
It's confusing

**Comment by LeeDaiHung** [comment]
I have the same problem, have any idea to fix it?

**Comment by vmlf01** [comment]
Please provide a test case for your issue, you can use the plunker linked above as a base to play around.

**Comment by LeeDaiHung** [comment]
the code as below:
button:
```
<button type="button" class="btn btn-primary" ng-click="Save()">Save</button>
```
script:
```
$scope.Save = function () {
	$http.post('/SaveAction', $scope.data).
	success(function(data, status, headers, config) {
		$modal({
			animation: 'am-flip-x',
			placement: 'center',
			title: 'Save Action', 
			content: 'Save success.',
			show: true
		});
	}).
	error(function(data, status, headers, config) {
	});
}
```

The `placement` is work, but the `animation` is not okay

for other button, if set property`data-animation="am-flip-x"` is work too.
