### ISSUE TITLE
Auto close for popover not working correctly on touch screens

### ISSUE THREAD

**Issue by jacobjlevine** [mgcrea/angular-strap#1674]
So far it seems like everything works fine with auto close for popovers when I'm using a computer w/ a mouse, but on my phone, it seems like I have to click a link or button in order for the directive to register the click and close the popover. I want to be able to click on anything outside the popover and have it close. Am I missing something or is that a bug?

**Comment by aleksays** [comment]
Faced with the same problem on mobile devices popover not closes. Doesn't anyone help?
