### ISSUE TITLE
datepicker looks weird when the parent is not large enough

### ISSUE THREAD

**Issue by diego-vieira** [mgcrea/angular-strap#1680]
http://plnkr.co/edit/mVr62ppM4XhdTk6L3Qde?p=preview

![screen shot 2015-05-06 at 11 31 18](https://cloud.githubusercontent.com/assets/930792/7495305/78874674-f3e3-11e4-9f84-da79c3876d9f.jpg)

As you can see, if we use any class like col-md-2 and the user is on a  tablet or 1024x768, the datepicker looks a bit weird. That doesn't affect the angular strap demo site tho

![screen shot 2015-05-06 at 11 33 09](https://cloud.githubusercontent.com/assets/930792/7495364/c28952f8-f3e3-11e4-9f9d-9a327a1b8e6a.jpg)

**Comment by diego-vieira** [comment]
adding 
```css
.dropdown-menu.datepicker {
  width: 300px;
}
```
seems to be a workaround.

**Comment by vmlf01** [comment]
You might also try to use ```data-container="body"``` to have the datepicker placed inside the body instead of the element.

**Comment by diego-vieira** [comment]
ah, thanks for that @vmlf01

**Comment by diego-vieira** [comment]
@vmlf01 that didn't worked nicely for me, because I'm opening a modal and the datepicker shows on the back of the modal.
![screen shot 2015-05-06 at 12 10 31](https://cloud.githubusercontent.com/assets/930792/7496183/f9564f0c-f3e8-11e4-9fb9-3aee078df05c.jpg)



So the CSS is still the fix for me.

**Comment by vmlf01** [comment]
Actually, you can specify any element using the ```data-container``` option, it doesn't have to be ```body```, I think you can use a class or an id. Anyway, it's just another possiblity to fixing it, just a note for future readers :)
