### ISSUE TITLE
Styling?

### ISSUE THREAD

**Issue by xtrasmal** [mgcrea/angular-strap#1687]
Where are the CSS files for the components?
The styling is partially loaded. But it doesnt look like in the docs

**Comment by sumigoma** [comment]
From the website:
Some components are not part of the Bootstrap's core, to use them you must use bootstrap-additions.css from the [BootstrapAdditions](http://github.com/mgcrea/bootstrap-additions) project.

**Comment by xtrasmal** [comment]
nice to know!!!
