### ISSUE TITLE
Datepicker yyyy validation > 3000

### ISSUE THREAD

**Issue by trevcor** [mgcrea/angular-strap#1688]
Is there a standard I'm not aware of or specific reason that year must be between 1000 and 3000?

This is the current regex in the datepicker directive.

'yyyy'  : '[1]{1}[0-9]{3}|[2]{1}[0-9]{3}',

Could the plugin be updated to allow those regex's to be overridden in the default config?

**Comment by vmlf01** [comment]
I think if you change those expressions, it might have other impacts, like the parsing code, so you would probably just override the '$dateParser' provider with your own implementation.

That said, I also don't see a reason why the default regex for 'yyyy' should not be changed to be similar to 'y', like ```'-?0*[0-9]{1,4}'```. That would allow any 4 digit year.

I don't think it would cause breaking changes and it seems a more sensible default.
