### ISSUE TITLE
Angular-strap, modal, $scope.emit

### ISSUE THREAD

**Issue by Aeyos** [mgcrea/angular-strap#1689]
Hello,

I'm running into an exception while trying to show a modal with .show();

here's the code
<code>
     var modal = $modal({
          scope: $scope,
          template: 'views/modal.delete.items.tpl.html',
          title: 'Apagar itens',
          show: false,
          placement: 'center',
          container: 'body',
          backdrop: 'static'
        });
        modal.$promise.then(function () {
          modal.show();
        });
</code>

Here's the output

<code>
"Error: scope.$emit(...) is undefined
</code>

Here's the bower.json

<code>
{
  "name": "sistema-ic",
  "version": "0.0.1",
  "dependencies": {
    "fullcalendar": "~2.2.6",
    "angular-ui-calendar": "0.9.0-beta.1",
    "angular-loading-bar": "~0.6.0",
    "jquery.slimscroll": "~1.3.3",
    "angular-http-auth": "~1.2.1",
    "ng-idle": "~0.3.5",
    "bootstrap-file-input": "~1.0.0",
    "ngInfiniteScroll": "1.1.2",
    "angular-mask": "~2.0.0",
    "iCheck": "~1.0.2",
    "angular-i18n": "~1.2.25",
    "angular-sticky-footer": "~0.0.1",
    "blueimp-gallery": "~2.15.1",
    "moment": "~2.8.3",
    "moment-range": "~1.0.5",
    "angular-summernote": "~0.3.1",
    "angular-waypoints": "~1.0.0",
    "jquery-waypoints": "~2.0.5",
    "bugsense": "~2.2.0",
    "jQuery-Mask-Plugin": "~1.10.12",
    "fontawesome": "~4.3.0",
    "agilib-angularjs": "git@dev.agivis.com.br:agilib-javascript",
    "angular-ui-sortable": "~0.13.3"
  },
  "devDependencies": {
    "bootstrap-sass-official": "~3.2.0"
  },
  "appPath": "app",
  "resolutions": {
    "fullcalendar": "~2.1.6",
    "jquery": ">=1.7",
    "angular-animate": "1.3.15",
    "angular": "1.3.13",
    "angular-resource": ">=1.3.15",
    "angular-cookies": ">=1.3.15",
    "angular-sanitize": ">=1.3.15",
    "angular-touch": ">=1.3.15",
    "angular-strap": ">=2.2.1",
    "angular-route": ">=1.3.15",
    "angular-messages": ">=1.3.15",
    "angular-i18n": ">=1.3.15",
    "sifter": "0.4.x"
  }
}
</code>

Anyone has any idea what is happening and how to solve the issue? Thanks!

**Comment by winiciuswanderlei** [comment]
modal.$promise.then(modal.show);
já tentou assim? se não rolar faz um plunker com um exemplo.

**Comment by vmlf01** [comment]
A plunker reproducing the problem would be best. Have you checked that the template path is ok and it loads?

**Comment by Aeyos** [comment]
@winiciuswanderlei ainda dá o erro do $emit :(

@vmlf01 I tried with a explicit basic template but it doesn't work either, my guess it's a problem with angular-strap configuration in my project, but I can't pin-point exactly what is causing it

**Comment by vmlf01** [comment]
Have you got ngAnimate and ngSanitize included in your angular module required dependencies?
