### ISSUE TITLE
Datepicker ignores specified date formatting when using 'useNative'

### ISSUE THREAD

**Issue by brycepj** [mgcrea/angular-strap#1690]
https://github.com/mgcrea/angular-strap/commit/ab182ac37f46d6053f92b4f9c926fdb105b0c176 sets a default date format for `useNative`. This causes the specified `dateFormat` to be ignored.

**Comment by JoshSchreuder** [comment]
Copied from my repo comments:

@brycepj I didn't do the original work for this `useNative` stuff, just this fix, but I think the reasoning is that to use the native mobile components, the input must be `type="date"`, and the format in the RFC for date type inputs is `yyyy-MM-dd`.

For more info see:
http://www.w3.org/TR/html-markup/input.date.html#input.date.attrs.value
https://tools.ietf.org/html/rfc3339#section-5.8

This only affects the view value, not the model value, which can still be whatever format you choose in the datepicker options.

**Comment by brycepj** [comment]
Thanks for filling me in on that. Where I work, products folks are sticklers on date formats, so sadly, this might mean we can't use native datepickers. I appreciate your help.
