### ISSUE TITLE
Feature request: Lightbox

### ISSUE THREAD

**Issue by budkin76** [mgcrea/angular-strap#1692]
Any chance you can modify modal to provide a lightbox for images that supports prev, next, and captions?

**Comment by bstruthers** [comment]
I definitely like the idea of a lightbox component, I just don't think it should be part of the core angular-strap library.  I my mind, I see angular-strap as the library that provides the building blocks (similar to bootstrap) and with those building blocks, we can create more complex directives.

You've got my mind thinking about creating an angular-strap-lightbox repository or something along those lines...

**Comment by mgcrea** [comment]
@bstruthers I agree and would gladly feature any project alike in the "official" docs.

**Comment by budkin76** [comment]
@bstruthers Makes total sense to me. I'm kind of using modal as a semi lightbox right now but would love to see what other devs come up with. I may flesh mine out soon and share.
