### ISSUE TITLE
"contextmenu" trigger for dropdown (via tooltip)

### ISSUE THREAD

**Issue by BrandonLWhite** [mgcrea/angular-strap#1694]
I'd like to use the bs-dropdown directive to implement a right-click context menu.  Would it make sense to incorporate a "contextmenu" option for the trigger on tooltip's bindTriggerEvents()?  Also, for touch I was considering a long press to activate the context menu.

Also, a bs-dropdown that is currently visible will not automatically hide/dismiss if you right-click somewhere else on the page.

**Comment by bstruthers** [comment]
I wonder if the right approach would be to open up the trigger option to support any event.  This would be similar to the direction Angular 2.0 is taking.

**Comment by lightswitch05** [comment]
I believe this ticket was solved by pull #2018 and can be closed.
