### ISSUE TITLE
How to $modal (angular-strap) unit test? 

### ISSUE THREAD

**Issue by winiciuswanderlei** [mgcrea/angular-strap#1695]
In my unit test when I call the function that has called the modal get the following error:
TypeError: Cannot read property '$promise' of undefined

In the controller I have:
$scope.showModal = function(){
  $scope.addModal = $modal({ scope: $scope, template: 'form.tpl.html', show: false });
  $scope.addModal.$promise.then($scope.addModal.show);
}

In my test I have:
it('Show modal', function(){
      Controller.showModal();
});

**Comment by vmlf01** [comment]
On the modal tests spec, there is a test for using the $modal service, which is very similar to what you are doing, except that the call to show is not done right after the creation of the modal:
https://github.com/mgcrea/angular-strap/blob/master/src/modal/test/modal.spec.js#L152

Not sure why your test is failing.

**Comment by vmlf01** [comment]
Have you solved this?

**Comment by winiciuswanderlei** [comment]
not the test was taken from the sprint, as was holding me, tomorrow begins another I return to work in this test.
