### ISSUE TITLE
Modals dialogs allow tabbing into the background document.

### ISSUE THREAD

**Issue by MihaiBalint** [mgcrea/angular-strap#1697]
A modal dialog should restring tab cycling to the modal content rather than the whole document.

Easily reproduced on http://mgcrea.github.io/angular-strap/#/modals by clicking to open the modal and then using the tab key repeatedly until focus is given to elements behind the modal.

**Comment by andras-tim** [comment]
+1

**Comment by vmlf01** [comment]
Duplicate of #839
