### ISSUE TITLE
bs-select on a select element with ng-disabled

### ISSUE THREAD

**Issue by gweax** [mgcrea/angular-strap#1699]
When I enhance a native select element with bs-select and I have a ng-disabled directive on that select element, it does not influence the button generated by bs-select. That is, the select (now hidden) is disabled, but the button is not. Since I don't have access to the generated button, I cannot disable bs-select elements.

The work-around is to not use select elements but button elements instead.

**Comment by DaleWebb** [comment]
Looks like the when the `<select />` is replaced, it doesn't take along the attributes with it.
