### ISSUE TITLE
Datepicker: cannot pick minDate

### ISSUE THREAD

**Issue by gweax** [mgcrea/angular-strap#1705]
I have an issue with the minDate of the datepicker not being pickable. I set the minDate to "2014-10-01", the parsed minDate now is `Wed Oct 01 2014 02:00:00 GMT+0200 (CEST)`, with a timestamp of 1412121600000.

However, I cannot pick Oct 1, 2014 from the datepicker, since the parsed date for it is `Wed Oct 01 2014 00:00:00 GMT+0200 (CEST)`, with a timestamp of 1412114400000, the parsed date is two hours before the minDate.

I see two possible solutions: (1) fix the parsing and (2) do not compare timestamps but year, month and date directly. I prefer (2) since the datepicker deals with dates and could ignore the time.

**Comment by gweax** [comment]
Well, another workaround is to use timestamps instead of date strings. This is especially easy using momentjs:

    $scope.minDate = moment("2014-10-01").startOf("day").valueOf();
    $scope.maxDate = moment("2014-10-31").endOf("day").valueOf();

and in the template

    <input ng-model="startDate" min-date="{{ minDate }}" max-date="{{ endDate }}" bs-datepicker date-type="number">
    <input ng-model="endDate" min-date="{{ startDate }}" max-date="{{ maxDate }}" bs-datepicker date-type="number">

**Comment by marcalj** [comment]
I'm using Datepicker + Timepicker and it's also not working properly. If I want to choose ```from: now at 3:00 --> to: now at 4:00``` it's not working properly.

**Comment by fibinger** [comment]
+1

**Comment by fibinger** [comment]
The other solution to this problem is to use $dateParser to parse min or max value (I am using 'string' date type). Internally $dateParser is used to parse model value itself.

I simply use $dateParser service:
```
var dateParser = $dateParser({format: 'yyyy-MM-dd'});
$scope.minDate = dateParser.parse("2014-10-01");
```

I am just wondering why isn't this service being used internally to parse min|max dates.

**Comment by nav12neo** [comment]
there will be dirty hack as well
$scope.minDate = new Date(new Date().getTime()-86400000);

**Comment by tinyfly** [comment]
I'm having basically the same problem. I'm trying to create date range pickers like in the demo docs but I'm using `dateType = 'string'` and `modelDateFormat: 'yyyy-MM-dd'` and I'm unable to pick the same day in both fields. Apparently if you don't use `dateType = 'date'` then the min-date and max-date settings don't work properly.
