### ISSUE TITLE
popover

### ISSUE THREAD

**Issue by wormen** [mgcrea/angular-strap#1706]
tell me how to get content without title ... I have not got to do ...

**Comment by vmlf01** [comment]
Do not specify the ```title``` option and it should work.

**Comment by wormen** [comment]
In fact of the matter is that is not working, how do you recommend ... I have checked

**Comment by vmlf01** [comment]
Have a look at this working sample, maybe it can help identify why yours is not working.
http://plnkr.co/edit/3qlwRtROg7FzHrbTYY26?p=preview

If it's still not working after that, please post a sample reproducing the problem.

**Comment by wormen** [comment]
it did so, but I somehow did not work and there were no errors
