### ISSUE TITLE
Add an option for disabling setting width in affix

### ISSUE THREAD

**Issue by vladferix** [mgcrea/angular-strap#1708]
Setting width of affix element is not always needed and creates glitches sometimes. There is a need for optionally disabling setWidth flag here:

if(setWidth) {
  element.css('width', element[0].offsetWidth + 'px');
}

**Comment by vmlf01** [comment]
Do you have a sample of the glitches you mention? Maybe that can help sort them out.

**Comment by vladferix** [comment]
I cannot provide full example now, but the point is that in my project that set width is breaking updating my set media css queries. Another solution is to check somehow set width in css instead of style attribute here
setWidth = !element[0].style.width;

**Comment by tinyfly** [comment]
This plugin setting the width is problematic when you want a full width navbar to resize properly with screen resizes. I always have to set `width: auto !important;` in my css to override the inline styles added. then add `left: 0; right: 0` to the affixed element will keep it full width no matter if the screen width is resized. 

I wish this plugin just wouldn't set any inline styles at all. IMO, It should only handle changing css classes to give us hooks to use our own styling.
