### ISSUE TITLE
Aside leaks memory by not destroying its own scope when closed

### ISSUE THREAD

**Issue by jametsi** [mgcrea/angular-strap#1715]
I use the current version of angular-strap (2.2.2) with angular 1.3.15 and noticed that the aside's scope never gets destroyed when using data-template. 
This can be reproduced by using the default template with a controller that only has the listener for $destroy-event -> It never gets fired.

**Comment by vmlf01** [comment]
Not sure what is your exact setup. I have created a plunker with an example following your description and the destroy is triggered when the aside DOM element is destroyed, as expected.
http://plnkr.co/edit/0sOUcGNVky6uUhdX4z1v?p=preview

**Comment by jametsi** [comment]
In your example the $destroy-event doesn't get triggered when I close the aside, so if I open & close it multiple times, I have several instances of the controller in memory. If I click the destroy-button to manually trigger the $destroy-event, I get multiple alerts from those controllers.

I can of course force the destroy by replacing the close-button's ng-click="$hide()" with ng-click="$hide(); $destroy();". 

So is this expected behavior? It surprised me, at least :)

**Comment by vmlf01** [comment]
Ah, I see what you mean now, I didn't test the plunker enough.
The same thing happened with tooltip, but aside/modal is not based on tooltip, so this needs to have a similar fix applied to prevent the memory leak. Will try to come up with a PR in the next few days.
Thanks for the follow up.

**Comment by lookfirst** [comment]
@vmlf01 close this?

**Comment by vmlf01** [comment]
thanks.
