### ISSUE TITLE
AngularStrap  change tab when next button clicked

### ISSUE THREAD

**Issue by rrishiraj** [mgcrea/angular-strap#1716]
My Tab Html
 
![capture](https://cloud.githubusercontent.com/assets/844909/7954200/e593b870-09ea-11e5-8fb3-cbed098ccc8a.PNG)

I have my tab object like
```javascript
 vm.tabs = [
			{
			    title: "FirstPage",
			    template: "F.html",
			    tabOrder: 0
			},
			{
			    title: "Second",
			    template: "s.html",
			    tabOrder: 1
			}];
```
On these f.html and s.html i have next and back button. I wish to change the tab on click of those buttons. How can i do this using JQuery / Angular.

**Comment by vmlf01** [comment]
One way would be for the tab pages to emit an event when you click next/back buttons and then on the controller you would update an active tab variable that would be binded to the bs-tabs bs-active-pane attribute.
Have a look at the docs pages on tabs, there you have a sample using buttons to control the current tab pane shown.
