### ISSUE TITLE
Datepicker 

### ISSUE THREAD

**Issue by peteringram0** [mgcrea/angular-strap#1718]
There is an issue with the datepicker's data-min-date and data-max-date not working when data-date-type is set to 'unix'

**Comment by kjaquier** [comment]
I have a similar issue using `data-date-type="date"`. My code includes two inputs for `begin` and `end`, with `end` as the maximum value for `begin` and vice versa. 

I made a plunker to illustrate the case and show how it behave : http://plnkr.co/edit/MR8mpX?p=preview
