### ISSUE TITLE
bootstrap-additions and angularStrap conflict

### ISSUE THREAD

**Issue by mtrabelsi** [mgcrea/angular-strap#1722]
I found that bootstrap-additions CSS is conflicting with angularStrap's Modal(components inside the modal), the behavior of text field inside a modal is quite strange - clearly it's a CSS conflict

![screenshot from 2015-06-04 22 16 01](https://cloud.githubusercontent.com/assets/7538862/8012067/3623a53a-0bb6-11e5-9dd3-a03599f3afac.png)

I've posted a question in SOF for more details: http://stackoverflow.com/questions/30654621/aside-is-conflicting-with-modal-ngstrap

**Comment by vmlf01** [comment]
I took your modal template and created a plunker, but I don't see a problem with it:
http://plnkr.co/edit/hlDkw8Om7HH8sZSzE8Xq?p=preview

Please try it out and see if you can change it to reproduce your problem or identify the cause.
