### ISSUE TITLE
$alert dosen't work without template 

### ISSUE THREAD

**Issue by mohamednagy** [mgcrea/angular-strap#1723]
When i used `$alert` as the following : 
`$alert({
            template: false,
            title: 'Holy guacamole!',
            content: 'Best check yo self, you\'re not looking too good.',
            placement: 'top',
            type: 'info',
            show: true
          });`

an error fired on the console: 
`Uncaught TypeError: el.focus is not a function
(anonymous function) @ angular-strap.js:1902`

**Comment by vmlf01** [comment]
Not sure what you are trying to do, but the alert needs a template. If you don't want to specify a custom one, just don't include the template attribute and it will use the provider's default.

**Comment by mohamednagy** [comment]
When i ignored `template` option, it used the default one provided, so i have to set `template: false`.
When i used `template: 'views/template/alert.tpl.html', `placement` option has no effect.

**Comment by DaleWebb** [comment]
The `placement` option requires `angular-motion` or your own custom CSS
