### ISSUE TITLE
typeahead does not work with angular 1.2

### ISSUE THREAD

**Issue by fcandre** [mgcrea/angular-strap#1732]
I am trying to use the typeahead directive (version 2.2.4) in combination with angular 1.2.28. This does not work: the dropdown does not appear. With domNode inspection I see the dropdown being put with negative top/left styles which puts it out of the screen. When alt-tabbing it sometimes appears. I put the reproduction scenario in Plunker:

http://plnkr.co/edit/31Hm3WZJMxCacjy9lgOf

It does work when I use angular-strap-2.1.4 (and use ng-options instead of bs-options). But I assume that using angular 1.2 with the latest version (2.2.4) is also supported(?).

**Comment by proft** [comment]
You can find solution [here](https://github.com/mgcrea/angular-strap/issues/1588).
