### ISSUE TITLE
Programmatic use of typeahead

### ISSUE THREAD

**Issue by dcortes92** [mgcrea/angular-strap#1737]
Reading the docs, I noticed that some directives are not clearly documented on how to use them programmatically. I recently created a tooltip directive which wraps the $typeahead directive. It looks something like this:

```javascript
var myTooltip = $tooltip($element, options);
```

The structure of the options object is:
```json
options = {
 "title": "the title",
 "trigger": "auto",
 "placement": "top",
 "container": "body",
 "visible": "true",
 "template": "cachedTemplate.html"
}
```
And then I open it:
```javascript
myTooltip.$promise.then(myTooltip.show());
```

This works quite well, but I had to figure out how to pass the object to the service containing all the settings.

However, with the typeahead service documentation all I can see is that to use it programmatically I have to do this:
```javascript
var myTypeahead = $typeahead(element, {controller: someModelController});
```
Nevertheless, I can't see how can I pass the bs-options object to this service, and I don't know what the controller really means.

Any help will be appreciated, thank you.

**Comment by mgcrea** [comment]
`myTooltip.$promise.then(self.tooltip.show());` should be `myTooltip.$promise.then(self.tooltip.show);`, otherwise, you're calling the show function right away and not using the deferred state of the promise.

**Comment by dcortes92** [comment]
Thanks for your reply, but that's not what I meant. My question was how can I pass the bs-options to a programmatic typeahead?

**Comment by vmlf01** [comment]
The typeahead provider signature is
```
 var typeahead = $typeahead(element, controller, options);
```
where the controller parameter is the ngModel controller, so it looks like the docs entry is outdated.

Maybe the best approach would be to take a look at the typeahead source file and see how the directive interacts with the provider.
