### ISSUE TITLE
Modal is affecting ngRepeat

### ISSUE THREAD

**Issue by Basemm** [mgcrea/angular-strap#1738]
Hi,

First the test case, http://plnkr.co/edit/IVRAUEdljS53cDg3G95s?p=preview

**Details:**

When using ngRepeat inside a modal, looping over a list that increase each time the modal is opened, 
Then inside ngRepeat we use a directive on form elements that require a parent "form" directive

- The first time it opens correctly

- The second time it opens, the list increase by 1, an error indicating the parent "form" directive is not found

- The third time it opens, the list increase by 1, The same error is repeated **twice**, and so on

From my inspection, it appears that ngRepeat is tracking DOM elements "form inputs" that no longer exists before applying the directive on the correct DOM element "the form input"

It looks like the modal is not being destroyed completely

**Why I think this issue is related to angularstrap not angular itself:**

I tried to use ngIf to show/hide same modal content to emulate modal behavior, It worked correctly.

**Comment by vmlf01** [comment]
Maybe PR #1727 will fix this?

**Comment by Basemm** [comment]
Thanks so much @vmlf01 that fixed the problem!
