### ISSUE TITLE
Polyfill <input type="date"> and friends

### ISSUE THREAD

**Issue by tkrotoff** [mgcrea/angular-strap#1739]
Would be nice to have an option to polyfill HTML5 form inputs.
E.g one writes `<input type="date">` and AngularStrap datepicker pops-up if there is no native support.

This would be particularly helpful on mobile devices and remove bloat on desktop when the native datepicker is available.
- following the standards is always a good idea.

Polyfills exist already but they look ugly and do not use AngularJS/Bootstrap: http://jsfiddle.net/trixta/SWQme/ (taken from http://stackoverflow.com/questions/9067536).

**Comment by nwhittaker** [comment]
+1
