### ISSUE TITLE
Datepicker only months and years

### ISSUE THREAD

**Issue by dcortes92** [mgcrea/angular-strap#1742]
Is there any way to set the display of the datepicker to show only months and years? I've tried with the modelTimeFormat, timeType and timeFormat attributes with no luck.

Also, I tried with the maxTime and minTime but it didn't work either. What I'm trying to accomplish is something like this http://jsfiddle.net/bopperben/DBpJe/

Thanks in advance, 

Daniel.

**Comment by vmlf01** [comment]
Try using the ```data-min-view="1" data-date-format="MMM yyyy"``` options.
http://plnkr.co/edit/klo1VdUsJ5vb1p6zoWl8?p=preview

**Comment by dcortes92** [comment]
Perfect, just what I needed thank you very much.
