### ISSUE TITLE
Timepicker displays extra colon for HH:mm format

### ISSUE THREAD

**Issue by nikarh** [mgcrea/angular-strap#1754]
Timepicker unconditionally shows table column to display *timeSeparator* to separate minutes and seconds, even if *showSeconds* is set to false. This behavior could be observed in timepicker example on projects homepage — http://mgcrea.github.io/angular-strap/#/timepickers

![2015-06-26 10_45_30-angularstrap - angularjs 1 2 native directives for twitter bootstrap 3](https://cloud.githubusercontent.com/assets/5517011/8372916/860edd22-1bf0-11e5-9e25-02cbffd70401.png)

**Comment by mfc-julius** [comment]
+1

**Comment by george3447** [comment]
+1

**Comment by phhien203** [comment]
+1

**Comment by humpedli** [comment]
+1

**Comment by mgcrea** [comment]
Fixed in e6f02bf.
