### ISSUE TITLE
data-multiple="anything" works all the time in bs-select

### ISSUE THREAD

**Issue by AlexanderKozhevin** [mgcrea/angular-strap#1755]
When I put value "0" or undefined or null - property still works. 
It it normal at all?
Can I set the property and set value "0" so it didn't worked?

**Comment by vmlf01** [comment]
Did a test from docs and it seems to work as expected when we put data-multiple="0", it only allows one selected item.
http://plnkr.co/edit/mL2ASLNfjgxlkaaBNVY6?p=preview

Maybe you are talking about some other case? Can you please provide a sample?

**Comment by AlexanderKozhevin** [comment]
oops, my fault. sorry 
Put a model the wrong way.

**Comment by AlexanderKozhevin** [comment]
I cannot use variables to set up "multiple" property in bs-select. 

http://plnkr.co/edit/u60iohvxZiooiM5c5wl0?p=preview
