### ISSUE TITLE
Feature Request: Allow unsetting of option in bsSelect

### ISSUE THREAD

**Issue by tinyfly** [mgcrea/angular-strap#1756]
I have a bsSelect restricted to single selections but the fields is optional. I would like the ability to unselect by clicking on an item in the dropdown that is already selected.

**Comment by tinyfly** [comment]
Or if I could set multiple=true and set the max number of selections to 1 that would accomplish the same thing.

**Comment by DaleWebb** [comment]
Both options seem quite useful enhancements (being able to toggle and maximum selection)
