### ISSUE TITLE
Feature Request: bsButton - Allow unselecting options when in radio mode

### ISSUE THREAD

**Issue by tinyfly** [mgcrea/angular-strap#1757]
I'm using bs-radio-group but would like to be able to unselect an option by clicking on it again. 

I have a list of salutations (Mr., Mrs., Ms.) that are optional in my form. But once the user has selected one there is no way to unselect it.

**Comment by DaleWebb** [comment]
bs-checkbox could be used for this case, where you can set the value to be put into the model, via the attributes, when the checkbox is selected

**Comment by tinyfly** [comment]
Except I only want the user to be able to select one thing. It is my understanding that if I use bs-checkbox it'll allow multiple selections.

**Comment by DaleWebb** [comment]
If you set the ng-model to be the same variable on each bs-checkbox, then each will overwrite the value in the model.  That should give you the behaviour of only being able to select one thing.
