### ISSUE TITLE
angular-strap aside don't display properly on navbar-fixed-top

### ISSUE THREAD

**Issue by NgYueHong** [mgcrea/angular-strap#1759]
I am using angular-strap aside to display menu which is open from the button on navbar using bootstrap 3. Everything is working properly. However, after I put in navbar-fixed-top class to navbar, it don't display properly.

http://jsfiddle.net/8ceuca0o/

How can I get it works?

Thank you

**Comment by vmlf01** [comment]
Use the *container* option, like the docs pages use, so the aside is placed inside the ```body``` of the page:
```
        <button type="button" class="navbar-toggle collapsed" bs-aside="aside" data-placement="left" data-container="body">
```
