### ISSUE TITLE
Date Picker Validation

### ISSUE THREAD

**Issue by GrahamWalters** [mgcrea/angular-strap#1760]
The date picker doesn't change its validation state when a valid date is set via the scope variable. Here's a [demo](http://plnkr.co/edit/BcntFmEJxp8J7GWYbn79?p=preview) of the problem.

Steps to reproduce:
- Enter a valid date OR select a valid date OR click the fill button. The state will change to valid and the submit button will enable.
- Manually change the date so it's invalid (example being change "2004" to "20"). The state will change to invalid and the submit button will disable.
- Click the fill button. The fill button will update the date and the date picker shows the correct value if you open it, but the state stays invalid and the button stays disabled.

**Comment by GrahamWalters** [comment]
While creating the above example I forgot I had the dateType attribute set to ISO. I've updated the code so that the modal receives an ISO date like so `$scope.form.date = new Date(2004, 4, 2).toISOString();`

Here's the new plunker: http://plnkr.co/edit/sxQsaASRs5JqqtQJbN9E?p=preview

**Comment by mightydes** [comment]
+1
