### ISSUE TITLE
angular-strap aside does not kill watcher when closed

### ISSUE THREAD

**Issue by NgYueHong** [mgcrea/angular-strap#1763]
I am using angular-strap aside with data-template.

```
<button type="button" class="btn btn-lg btn-danger" data-template="aside/docs/aside.demo.tpl.html" data-placement="left" data-animation="am-slide-left" bs-aside="aside" data-container="body">
    Custom aside
    <br>
    <small>(using data-template)</small>
</button>
```

Everything works fine. Except, every time when the aside showing, the watcher count keep on increasing. Watcher does not get deducted / removed when aside is closed. This result in accumulated watcher on the application over time.

How can I get watcher to be removed when it is closed?

**Comment by NgYueHong** [comment]
Today I try again with the original code example from the website to show angular-strap aside with object. Again, I found that the watcher keep increasing every-time when I open and close the aside panel. I believe this is something a bug with it.

Hope to see the problem solved ASAP. Otherwise, please show us the workaround way to remove the watcher when it is closed.

**Comment by vmlf01** [comment]
Maybe PR  #1727 fixes this, have you tried with latest version directly from git?

**Comment by NgYueHong** [comment]
Tried with latest version (2.2.4), but didn't help at all.

**Comment by vmlf01** [comment]
This PR has not been included in a release yet, so you would need to get the files directly from git master branch to try it out.
