### ISSUE TITLE
Masking feature for Datepicker

### ISSUE THREAD

**Issue by sistemanick** [mgcrea/angular-strap#1764]
Is there any plan to include a masking feature for datepicker? For the life of me I can't get ui-mask to play nice with either ui-bootstrap or angularstrap's datepicker.

**Comment by MayGo** [comment]
Need this feature also.

**Comment by cgiacomi** [comment]
+1

**Comment by gearsandcode** [comment]
+1 this would be nice

**Comment by ryanray** [comment]
+1

**Comment by JairAviles** [comment]
+1

**Comment by Sir-J** [comment]
+1
