### ISSUE TITLE
modal with `.center` placement hangs when modifying content

### ISSUE THREAD

**Issue by ilovett** [mgcrea/angular-strap#1769]
Using center placement on the modal

```
    angular.extend($modalProvider.defaults, {
      'animation': 'am-fade-and-scale',
      'placement': 'center'
    });
```

With custom CSS:

```
// Support center placement
.modal {
  &.center {
    .modal-dialog {
      position: fixed;
      top: 40%;
      left: 50%;
      min-width: 320px;
      max-width: 630px;
      width: 50%;
      transform: translateX(-50%) translateY(-50%);
    }
  }
}
```

If you place a select or radios inside the modal, the changes are not rendered until you resize the window which seems to "unhang" it.  You can even manually modify html of the modal using chrome dev tools... the changes don't apply until after you resize the window -- then you can make all the changes you want.

I'm guessing it has something to do with the animation and positioning css conflicting.

The problem does not show up when using default placement :

```
    angular.extend($modalProvider.defaults, {
      'animation': 'am-fade-and-scale',
      // 'placement': 'center'
    });
```

**Comment by rhclayto** [comment]
I am experiencing the same issue. In my case I have an ng-repeat list that can be dragged & sorted the with ng-sortable module. With 'placement: center' the items disappear when dragging, with default placement everything works.
