### ISSUE TITLE
tooltip‘s container is not working.  Cannot read property 'lastChild' of undefined

### ISSUE THREAD

**Issue by meishier** [mgcrea/angular-strap#1772]
<input type="text" class="form-control"  name="area" ng-model="vm.entity.area"
                       data-bs-typeahead=""
                       data-container="typeahead-container"
                       data-bs-options="a.name as a.name for a in vm.areaInfo.areas">
<div id="typeahead-container"></div>

        $tooltip.show = function() {
          if (options.container) {
            parent = tipContainer;
            if (tipContainer[0].lastChild) {  //error here, Cannot read property 'lastChild' of undefined
              after = angular.element(tipContainer[0].lastChild);

**Comment by davidkonrad** [comment]
Have the same problem. Only if I am using datepicker or timepicker within a directive template. What is the cause of this error ...?
