### ISSUE TITLE
$modal service - ability to specify buttons and their handlers

### ISSUE THREAD

**Issue by sistemanick** [mgcrea/angular-strap#1774]
Would be nice be able to define buttons and handlers when using the $modal service, like this:
```
$modal({
    title: 'My Title',
    content: 'My Content',
    show: true,
    buttons: [
        {
            text: 'Yes',
            cls: 'primary',
            handler: function() {
            }
        },
        {
            text: 'No',
            cls: 'default',
            handler: function() {
            }
        }
    ]
});
```

**Comment by manikantag** [comment]
+1

**Comment by cemeng** [comment]
You could easily create your own $modal wrapper for this though? We have done something similar on our project.

**Comment by manikantag** [comment]
Yeah, in fact I m planning to do the same. But as this is trivial requirements, good to have it with the library itself.

**Comment by srsgores** [comment]
+1

@manikantag, @cemeng, if you could share your solutions, that would be appreciated.  I'm not sure how to go about extending the service...

**Comment by cemeng** [comment]
@srsgores - I don't have the code anymore - we are using angular-ui modal now. 

But if you look at the angular-strap docs, look at the $modal service section, you could create a wrapper around $modal?
Look also at the options section, so you at least need 2 options:
- template / templateURL - the template would contain your custom buttons
- controller - which will have the handlers for your custom buttons

Maybe look at this fiddle - see the openModal method for ideas https://jsfiddle.net/ryanray/pf2Ls800/

**Comment by DaleWebb** [comment]
I could write you a solution if you would like @srsgores.

I'd create a custom template and (from the example) inject the `buttons` array into the scope and `ng-repeat` over some `button` elements.

**Comment by DaleWebb** [comment]
I think specifying the elements through the model could get messy, so I would recommend that the framework stick to being the default basic layout (just a close button) - then for more experienced people, they should know how to specify another template and read the elements from the scope.
