### ISSUE TITLE
Make angular-strap.tpl HTML5 compatible

### ISSUE THREAD

**Issue by Vayvala** [mgcrea/angular-strap#1775]
Regular Angular attributes are not HTML5 compatible:
https://stackoverflow.com/questions/15767279/angularjs-app-not-passing-official-w3c-html5-validation

To make them compatible you should use `data-` prefix: `ng-app` would become `data-ng-app`, `ng-repeat` - `data-ng-repeat`, etc.

You can use `gulp-angular-htmlify` to create valid HTML5 output for deployment:
https://github.com/pgilad/gulp-angular-htmlify

**Comment by kyrylkov** [comment]
+1
