### ISSUE TITLE
Typeahead async broken with Angular 1.4

### ISSUE THREAD

**Issue by climberwoodi** [mgcrea/angular-strap#1776]
When i am using Angular 1.4 the async function for typeahead is not working. Can be reproduced with the official plunker when changing the Angular version. (http://plnkr.co/edit/GtZGWgtpO2yjRKmopwDB?p=preview)

**Comment by mgcrea** [comment]
Can confirm, somehow this slipped pass through the unit tests. Will fix it asap.

**Comment by mgcrea** [comment]
Closed by 2d3eb29.
