### ISSUE TITLE
typeahead with objects doesn't work with Angular 1.4.1

### ISSUE THREAD

**Issue by pedrusky** [mgcrea/angular-strap#1783]
If you update the typeahead plunker demo with the latest AngularJS release, the Google maps example no longer works. It still works with Angular 1.3.9, but as of 1.4.1 it fails.

See: http://plnkr.co/edit/t3TmAweKIgxtgCx36v60?p=preview

**Comment by mgcrea** [comment]
Already fixed by 2d3eb295ab23034e2f5838a2c68674d404d69028. Release coming soon.

**Comment by pedrusky** [comment]
Works in version 2.3.1! Thank you for the release!
