### ISSUE TITLE
Backdrop overflow not working with stacked modals

### ISSUE THREAD

**Issue by palortoff** [mgcrea/angular-strap#1787]
Open a modal dialog.
Without closing dialog, open new modal dialog.
close second dialog.

==> overflow is no longer hidden.

Closing the second dialog removed classes from body. This should happen on last dialog closed.

See [Plunker](http://plnkr.co/edit/kPiFDK?p=info)

**Comment by DaleWebb** [comment]
Fixed in 2.3.7
