### ISSUE TITLE
Typeahead default value is not empty when used complex 'select as' syntax

### ISSUE THREAD

**Issue by irsick** [mgcrea/angular-strap#1792]
When I use complex ngOptions 'select as' concatenation syntax  like 

``` javascript
bs-options="request as '#' + request.id + ' : ' + request.name for request in requests"
```

I got '# : ' as default value but I expect an empty string to be a default value.

Here is a [Plunker](http://plnkr.co/edit/Af0WNPVEAL1iTN65hlha?p=preview)

**Comment by spencerwi** [comment]
Any activity on this? I'm seeing the same issue.

**Comment by DaleWebb** [comment]
It appears as though it is treating '#' and ':' as constants to have for each element.  Have you tried putting parenthesises around that part of the expression (if that compiles)?
