### ISSUE TITLE
buttons (bs-radio-group) change value twice when clicked?

### ISSUE THREAD

**Issue by adam-marshall** [mgcrea/angular-strap#1795]
If I edit the plunker, app.js, as follows:

Add the following line into the controller:
`$scope.$watch("button.radio", function (value) { alert(value); });`

You will get 2 alerts every time you click a button.

In my environment, the first one is a string, the second is an integer.
I am reacting to the value being changed, triggering further actions, these actions get triggered twice. Working around this would be quite difficult.

Is this a defect?
Any ideas what I can do to get around this?

**Comment by vmlf01** [comment]
Looks like the bsRadio code is converting the value to a numeric if it is all digits. Maybe you can use non-numeric values to work around the issue?

**Comment by DaleWebb** [comment]
Perhaps if you use a comparator as a guard, it won't fire the rest of the code:

e.g.

```javascript
$scope.$watch('button.radio', function(value, oldValue) {
    if(value != oldValue) {
        ...
    }
});
```
