### ISSUE TITLE
$modal service leaking scope

### ISSUE THREAD

**Issue by vicricker** [mgcrea/angular-strap#1805]
I'm not sure if this is a bug, or I'm using $modal incorrectly, but it appears to be leaking scopes when modals are hidden, if I use the scope property when showing a modal with the $modal service.

```
var myModal = $modal({title: 'My Title', content: 'My Content', show: true, scope: $scope});
```

Repeatedly opening and closing modals with complex content can cause performance to degrade significantly.  I can work around the issue by watching for modal.hide and doing myModal.destroy(), but it seems like a hack.

Example: http://plnkr.co/edit/sVpjUuma7voFr5F5UfRt?p=preview

Sounds similar to issue #1715

**Comment by episodeyang** [comment]
I'm having exactly the same issue.

**Comment by chino23** [comment]
same here, getting pretty slow after a while
