### ISSUE TITLE
dropdown doesn't show on focus with async data 

### ISSUE THREAD

**Issue by hamdipro** [mgcrea/angular-strap#1808]
i m using angularstrap ~2.1.6 version 
i want to show data dropdown when http service complete fetching data 
when i use static array of data it works with data-min-length="0"
but when the data from http call it doesn't work 
any suggestion !

**Comment by vmlf01** [comment]
Are you referring to the typeahead directive?

**Comment by Mr-Developer** [comment]
Im having the same problem, i'll try my best to explain.

I use a regular call e.g.
`<input type="text" ng-model="selectedClient" data-min-length="0" bs-options="client as client.client_name+' - '+client.location.name for client in clients" placeholder="Select Client" bs-typeahead>`

This works perfectly if "clients" is defined as a local variable. i.e. On focus of the input with data-min-length="0", the full list shows up.

However: in my case I have to fetch clients from the server and then polpulate.
After "clients" is fetched from the server however, it is not reflected in the dropdown on focus. It will show only after you input data and then delete then the.

i.e. "clients" is fetched but on focus on the input nothing shows. Upon typing, then the list shows. I need the full list to show after client is updated and I focus on the element/input.
