### ISSUE TITLE
Deprecated use of `template` option to pass a file. Please use the `templateUrl` option instead.

### ISSUE THREAD

**Issue by maketroli** [mgcrea/angular-strap#1809]
I am getting that message twice in my browser console and I already delete `template` and put `templateUrl` instead.

Now, in the html, I have: `data-template`, should I put `data-template-url` instead ?

**Comment by vmlf01** [comment]
Probably, since the html attribute will be mapped to directive options.

**Comment by AlexanderKozhevin** [comment]
True. 
I changed all **data-template** to **data-templateUrl* and message is gone.
You can close an issue.
