### ISSUE TITLE
Allow all options to be defined on the modal object (and any other directive)

### ISSUE THREAD

**Issue by 43081j** [mgcrea/angular-strap#1811]
Correct me if im wrong, but it seems the only options available through an object (`bs-modal="someObject"`) are `title` and `content`, with the rest being discarded and only available through attributes.

Is there a reason for this? It makes no sense to have to re-specify the `templateUrl` for example, on each button which triggers the modal. It seems over the top to also create `$modal` in the controller for this purpose.

I may be wrong but it does seem `templateUrl` is ignored from the object.

**Comment by igler** [comment]
Having the same issue that I cannot modify <code>templateUrl</code> afterwards.

**Comment by vmlf01** [comment]
Same question as #1917 I think. The directive attribute is used to pass in the scope only, not the options.
Maybe a custom modal service can help you simplify things? Have a look at #1505.

**Comment by igler** [comment]
Thanx for your suggestion. I finally found a workaround using a dedicated service that sets up the modal  information and returns this to the controller. The templateUrl is included within these informations.
