### ISSUE TITLE
Datepicker don't select months ended in 31 if I use only year and month in calendar [bug] [directive-datepicker]

### ISSUE THREAD

**Issue by rafaela2689** [mgcrea/angular-strap#1812]
I use the calendar to show only year and month, and when is 31 it don't select the month that not end on 31.

**Comment by vmlf01** [comment]
Does this plunker represent your issue? http://plnkr.co/edit/YptFXhVDFb4T3O0Be7of?p=preview

**Comment by rafaela2689** [comment]
Yes, that´s right. When a month ends in 31, don't select the other months that don't end in 31. Thank you.
