### ISSUE TITLE
Modal: breaking changes reg footer when contentTemplate is used

### ISSUE THREAD

**Issue by manikantag** [mgcrea/angular-strap#1814]
Seems 2.3.1 brings one more breaking changes reg `modal-footer` when using `contentTemplate` _(I m not sure if this is documented or not, though)_

Till 2.3.0, modal footer is removed when `contentTemplate` is used: https://github.com/mgcrea/angular-strap/blob/v2.3.0/dist/angular-strap.js#L1306

But from 2.3.1, this code is removed. This is asked as a question earlier: https://github.com/mgcrea/angular-strap/issues/1498

Previous behavior seems good to me, but it is just my use case. I can use `templateUrl` which is okay. But if this is not documented (yet), good to document this in release notes.

**Comment by bstruthers** [comment]
This bit me too.  I added my own modal.tpl.html with the footer removed and had to make sure all my modals had a templateUrl.  

I don't think this change is a negative one.  It just needs some better documentation.

**Comment by mgcrea** [comment]
It should indeed have landed in the minor `v2.3.0` update, did update the changelog to reflect the breaking change.

**Comment by bstruthers** [comment]
I'm thinking adding something to the documents will help for when exactly the footer will be present and when it won't.

**Comment by mgcrea** [comment]
After looking a bit more into it I'm not sure where this is exactly coming as the line still exists in master: https://github.com/mgcrea/angular-strap/blob/master/src/helpers/compiler.js#L115. Anyway I think it's the way to go.
