### ISSUE TITLE
bs-select not working when nested inside ng-repeat

### ISSUE THREAD

**Issue by BradyLiles** [mgcrea/angular-strap#1817]
I think I found a bug, When editing a bs-select inside a ng-repeat the model is not affected, however when editing a bs-select with the same model outside of ng-repeat the model does get updated.

http://plnkr.co/edit/twTpduih4KLIlEEr91As

**Comment by jukkasi** [comment]
This is probably because your model is outside ng-repeat and ng-repeat creates a new scope, then you should point your model to $parent.selectedIcon

**Comment by vmlf01** [comment]
Like @jukkasi pointed out, solved using the 'always have a dot in there' rule :)
http://plnkr.co/edit/CZq1zzbesBpEAuX8KeZn?p=preview
