### ISSUE TITLE
Way to add a class to bs-collapse-toggle when target collapse is active/open (collapse)

### ISSUE THREAD

**Issue by jacquesdancona** [mgcrea/angular-strap#1821]
I'm facing the problem of needing to know on the bs-collapse-target element if the target collapse-element is active/opened. 

A quickfix I'm currently using is setting up the ngModel on the bs-collapse element, and for every bs-collapse-toggle use `ng-class="{'someActiveClass': activePanel === some$index}"`. 

I'm curious if the added number of ngClass watchers, and the use of ngModel is really necessary.

**Comment by jafetbjarkar** [comment]
Also trying to solve this. I tried your solution but it fails after the panels are reordered. Then the index won't match with activePanel.
