### ISSUE TITLE
Modal template can't be set from html string content

### ISSUE THREAD

**Issue by lookfirst** [mgcrea/angular-strap#1824]
I'd like to do something like this:

```
// use systemjs text plugin to load content of file into fooTpl
import fooTpl from 'fooTpl.html!text'

$modal({template: fooTpl})
```

This would effectively be the entire .modal content template.

Unfortunately this doesn't seem to work. I get errors about angularstrap trying to load the default 'modal/modal.tpl.html'. Setting `templateUrl: false` doesn't work either. I'm also not interested in using `content:` because that is just the modal body.

So, the question/issue is... can I load the entire template content if it isn't part of the `$templateCache`?

**Comment by psi-4ward** [comment]
Seems the implementation differs from the docs: http://mgcrea.github.io/angular-strap/#/modals-usage
Theres no `templateUrl` in the source.

For now i workaround this using the `$templateCache` but it should be implemented according the docu.

Workaround:
```javascript
import confirmTpl from './psi-dialog-confirm.html';

app.run(function($templateCache) {
  $templateCache.put('psi-dialog-confirm.html', confirmTpl);
});

confirmModal = $modal({
  scope: scope,
  show: true,
  backdrop: true,
  container: 'body',
  template: 'psi-dialog-confirm.html',
  title: msg,
  content: content
 });
```

**Comment by vmlf01** [comment]
Looks like this is working for both cases described - using ```template``` and fetching ```templateUrl``` from server:
http://plnkr.co/edit/jQBDtkZRtbGs7mBjx9p0?p=preview
