### ISSUE TITLE
Typeahead onKeyDown fires twice in some case

### ISSUE THREAD

**Issue by Niaro** [mgcrea/angular-strap#1825]
Good time of day!
I'd like to know about implementing of this [part of typeahead](https://github.com/mgcrea/angular-strap/blob/master/src/typeahead/typeahead.js#L151), why is there doesn't exist some checks on some sort of multiple attachments of handler to element? In some cases i got two or more handlers of keyDown  event on same element, thus i have ruined logic of selecting by keys...

I will be very grateful! Thank you!

PS Big apologies for my english ^_^'

**Comment by elgerm** [comment]
+1

**Comment by oladon** [comment]
Has there been any progress on this? We're experiencing an issue that seems likely to be caused by this; namely, we're frequently seeing a single down arrow press resulting in the second (or even last) item being selected.

**Comment by DaleWebb** [comment]
We need a test case for this.  If you can make one, that would be great.  If you think you can solve the problem, a PR would be fantastic

**Comment by oladon** [comment]
Hi Dale, appreciate your response.

I haven't managed to track down the cause, or whether there's some user behavior that prompts it... it seemed for a while that it was errantly catching Enter presses and that kicked it off, but it's not reliable.

I'm happy to look into it if I have some free time, but it seems like a significant enough issue to warrant some investigation by people who already know the code base.

**Comment by RonenA** [comment]
We're having the same issue. Anyone ever find out any more details about this?

**Comment by oladon** [comment]
@RonenA We ended up patching the minified JS locally and just freezing our version. It's been nearly a year, so I don't recall the details, but iirc there was some place in the code that kept adding the event handler without caring if it already existed.

Hope that helps.
