### ISSUE TITLE
Typeahead autocomplete="false" should be autocomplete="off"

### ISSUE THREAD

**Issue by jukkasi** [mgcrea/angular-strap#1828]
In Chrome I get browser autofill for typeahead because typeahead adds attribute autocomplete with value "false" instead of "off". After changing value to "off" everything works fine.

According to W3C the value should be "off"

http://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#the-autocomplete-attribute

Firefox agrees it should be "off"

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

IE agrees it should be "off"

https://msdn.microsoft.com/en-us/library/ms533486(v=vs.85).aspx

**Comment by MathieuLorber** [comment]
Chrome is the troublemaker here : https://github.com/mgcrea/angular-strap/pull/1768
I'm not sure which is the better choice right now, "false" currently works for Chrome / FF / Safari, "off" don't work for Chrome.
