### ISSUE TITLE
bs-select bs-options do not update when updating the $scope bs-options source option more than once

### ISSUE THREAD

**Issue by binarysamurai** [mgcrea/angular-strap#1833]
Having a problem figuring out why one can't update the displayed values in the bs-options more than once. You can edit one of the properties of a bs-option to be different, then edit the same bs-option again and the bs-option's value does not get updated in the display, but does get updated in the $scope. 

Please see the plunker:
http://run.plnkr.co/plunks/Ca69CM/

**Comment by binarysamurai** [comment]
Submitted over a month ago, can I please get a response?

**Comment by vmlf01** [comment]
Looks like it's been fixed ;)

**Comment by binarysamurai** [comment]
nicknissen, thanks for the update! Works great!
