### ISSUE TITLE
Tooltip - Unable to specify placement target using angular expression after upgrading to 2.3

### ISSUE THREAD

**Issue by eternalthinker** [mgcrea/angular-strap#1835]
I was using an angular expression to specify data-target for angular strap tooltip.
`data-target="{{'#target' + item.id}}"`
This worked fine with angular 1.3 and angular-strap 2.1  

Now the libraries are upgraded to angular 1.4 and angular-strap 2.3  
The above code now throws an error:
`Failed to execute 'querySelectorAll' on 'Document': '{{'#target'+item.id}}' is not a valid selector.`  

What is causing the angular expression to be interpreted as a string?

**Comment by M21B8** [comment]
I've just hit the exact same issue. It looks like as a result of #1454 the value passed in is no longer being interpolated, as it is now being read via element.attr('data-target'), instead of attr['target'].

This is also happening on popovers.

**Comment by wrtlbrmpft** [comment]
I can confirm - data-target with expression no longer works for popovers and breaks my app.
Are there any workarounds/plans to fix this?

**Comment by hemlok** [comment]
Any news on this? 👎
