### ISSUE TITLE
Typeahead - put cursor at start and type jumps cursor to the end

### ISSUE THREAD

**Issue by mattgoldspink** [mgcrea/angular-strap#1837]
Reproduction here:

http://plnkr.co/edit/7AFxRlQwfqaqTf9m45ql?p=preview

Looks like calling controller.$render() each time causes the value to be reset on the input and then the cursor jumps to the end. I'll submit the patch separately to maintain the cursor position

**Comment by mgcrea** [comment]
Fixed by #2079
