### ISSUE TITLE
Cannot read property 'insertBefore' of null - bug appears during fast shows of tooltips

### ISSUE THREAD

**Issue by Niaro** [mgcrea/angular-strap#1842]
Hello everyone!
I'd like to report a some nasty bug, it has been reproduced on this [plunkr](http://plnkr.co/edit/xQVRhW).
The bug doesn't ruin app, or visual experience - but it continuously spams to raygun.

The bug appears only if tooltips has one common container.

For reproducing the bug you'd need fast moving the cursor above elements.

**Comment by edgar0011** [comment]
Hello,

got the same issue with dropDown:
TypeError: Cannot read property 'insertBefore' of null at forEach.after (http://localhost:9000/dev/lib/angular/angular.js?v=tbc1447109302188:3448:13) at Object.JQLite.(anonymous function) [as after] (http://localhost:9000/dev/lib/angular/angular.js?v=tbc1447109302188:3532:17) at TooltipFactory.$tooltip.show (http://localhost:9000/dev/lib/angular-strap/dist/angular-strap.js?v=tbc1447109302188:362:25) at Object.DropdownFactory.$dropdown.show (http://localhost:9000/dev/lib/angular-strap/dist/angular-strap.js?v=tbc1447109302188:2826:11) at HTMLAnchorElement.TooltipFactory.$tooltip.enter (http://localhost:9000/dev/lib/angular-strap/dist/angular-strap.js?v=tbc1447109302188:328:29) at eventHandler (http://localhost:9000/dev/lib/angular/angular.js?v=tbc1447109302188:3293:21) at HTMLAnchorElement.<anonymous> (http://localhost:9000/dev/lib/angular/angular.js?v=tbc1447109302188:3349:15) at HTMLAnchorElement.eventHandler (http://localhost:9000/dev/lib/angular/angular.js?v=tbc1447109302188:3293:21)

**Comment by vinogradov** [comment]
I have the same issue with $popover with `trigger: "hover"` setting.

**Comment by alalonde** [comment]
+1

**Comment by celineotter** [comment]
my team is experiencing the same :(

**Comment by DaleWebb** [comment]
Are you able to come up with a solution and PR?

**Comment by egor-manjula** [comment]
Issue still exists till now

**Comment by paxa1887** [comment]
+
