### ISSUE TITLE
angular2-strap

### ISSUE THREAD

**Issue by sumigoma** [mgcrea/angular-strap#1850]
I know it's still very early and many things in Angular2 are still in flux, but others have already started working on porting angular+bootstrap to the new framework (e.g. http://valor-software.github.io/ng2-bootstrap/), even with bootstrap v4 alpha. So far I've found rewriting things in Angular2 to be quite pleasant despite it being unstable (although with occasional hangups here and there). @mgcrea are there plans for this project to move to Angular2?

**Comment by mgcrea** [comment]
There are plans to perform a full rewrite for Angular2+Bootstrap4, I've started to play with Angular2 for a while but I'm waiting for a proper beta to really start committing time to it. Might push an `angular2` branch in the coming weeks.

**Comment by sumigoma** [comment]
@mgcrea have you started a branch for this yet? I'd be willing to create one or contribute if it already exists.

**Comment by mgcrea** [comment]
@sumigoma I've tried a few things, but nothing serious yet, I've been mostly playing with react+webpack lately to better understand the eco-system. I'd gladly accept any help moving angular2-strap forward. I've just pushed an issue to centralize and track Angular2 progress/discussion in #2016.
