### ISSUE TITLE
Datepickers option: modelDateFormat = "yyyy-MM-dd" doesn't work

### ISSUE THREAD

**Issue by hellofeiwu** [mgcrea/angular-strap#1851]
Datepickers option: modelDateFormat = "yyyy-MM-dd" doesn't work

**Comment by Astray-git** [comment]
According to the code , the `modelDateFormat` only works if you set `dateType` to `string`
https://github.com/mgcrea/angular-strap/blob/master/src/datepicker/datepicker.js#L398

This should be put in the document.
