### ISSUE TITLE
Dropdown with data-template not working with 2.3.x version

### ISSUE THREAD

**Issue by ptsavdar** [mgcrea/angular-strap#1854]
Hello,
I've tried updating today to the latest angular-strap version (that is 2.3.1) but I've noticed that my dropdowns stopped showing. An empty dropdown is shown instead. It seems like the template's content is not taken into account... So I return to my previous version v2.2.4 where I works fine. 

Here is the plunk for 2.2.4 (dropdown works fine)
http://plnkr.co/edit/WlTFfgnGU9iZyS3GZmlI?p=preview

and here's the one with 2.3.1
http://plnkr.co/edit/4zdHVxOoRnqJgZbh4clt?p=preview

**Comment by octavioamu** [comment]
Try test-use-case-template.html like the docs of angular
http://plnkr.co/edit/zs0PlAdObh6UNtCcwkiD?p=preview

**Comment by shotcowboystyle** [comment]
The documentation just needs to be updated. You need to use `templateUrl` option instead of `template`.
