### ISSUE TITLE
bs-collapse expands the wrong group if static groups are added after ng-repeat

### ISSUE THREAD

**Issue by tad9ab** [mgcrea/angular-strap#1856]
Probably best explained here: http://plnkr.co/edit/77EXPsmNmusI5bylKh65?p=preview

I would imagine that the first grouping in the ng-repeat would be expanded, not the first group outside of the ng-repeat.  Please let me know if this is expected behavior, and if so, are there any workarounds?

**Comment by vmlf01** [comment]
You will need to separate them into different ```bs-collapse``` containers, otherwise, they are all part of the same logical group.

http://plnkr.co/edit/Q7OSYtSG6UcT9R12tCwm?p=preview

**Comment by tad9ab** [comment]
But I need them to be part of the same logical group.  That's where the bug lies.
