### ISSUE TITLE
bs-select tab key causes error if no value is selected

### ISSUE THREAD

**Issue by jukkasi** [mgcrea/angular-strap#1857]
This can easily be reproduced with select demo

1. http://mgcrea.github.io/angular-strap/#/selects
2. Click "Choose among the following" to get focus
3. Press "Tab" key on keyboard
4. Error Uncaught TypeError: Cannot read property 'value' of undefined in console

**Comment by fayzaan** [comment]
I have a fix for this, but how do I push it?

**Comment by Trial-In-Error** [comment]
Hey! This was never merged & I'm still encountering this issue, both on the demo page (http://mgcrea.github.io/angular-strap) and in my own project. Is there anything I can do to help?

**Comment by DaleWebb** [comment]
You could fork your own version for now and apply the simple change like the commit referenced above.

Then I'd welcome a pull request with the change :+1:

**Comment by Trial-In-Error** [comment]
Hey! Thanks for the pull request; I'd been meaning to get to it, but been busy. Sorry. :(
