### ISSUE TITLE
bs-typeahead does not render object correctly

### ISSUE THREAD

**Issue by jukkasi** [mgcrea/angular-strap#1866]
See plunker for details http://plnkr.co/edit/NvYt2PT5XCYydId7DrXW?p=preview

The problematic line is 
``
if (values.length === 1 && values[0].value === newValue) return;
``
which is located in typeahead component scope.$watch(attr.ngModel) function

**Comment by jukkasi** [comment]
@mgcrea any ideas how to change this line so that the issue will be fixed but still some optimization would take place? 

The problem is that currently displayed label is not available anywhere so it would be possible to do 
``
if (values.length === 1 && values[0].label === currentLabel) return
``

Otherwise this optimization has to go

**Comment by jukkasi** [comment]
I have included a very simple and basic test case in pull request which does not pass in current version of AngularStrap (2.3.2)

**Comment by Spriz** [comment]
Is this only a problem on certain Angular versions?
