### ISSUE TITLE
Documentation should explain that aside & modal container needs to be inside ng-app

### ISSUE THREAD

**Issue by blaind** [mgcrea/angular-strap#1870]
Spent quite a while figuring why animations were not working. I had a non-standard config where ng-app was inside a body as in:

    <body>
       <div ng-app="myApp" id="appDiv"></div>
    </body>

and because aside "container" defaults to body, animations did not work when instantiated from javascript.

I moved ng-app to body tag, then it started working. Another option was to have 

    $aside({ container: '#appDiv'});

Should maybe document this better. Or if not, at least here's a searchable issue about the case :)

**Comment by punkologist** [comment]
Thank you so much, that was my issue, I have been pulling my hair out trying to figure out why the animations didn't work from JS code but worked fine using directives. The documentation for this is one of the most brief and unhelpful of any library I have used. The number of open issues here is also a huge worry.

**Comment by DaleWebb** [comment]
We're trying our best now to address the issues as fast as we can.  Expect a prompt response from now on!

I was going to say that the animations are using ngAnimate which will only work within an Angular app, but I feel as though that it should still work as the aside is controlled by Angular
