### ISSUE TITLE
the simple select demo  can't run ,throw an error ,when i click option 

### ISSUE THREAD

**Issue by yichengjie** [mgcrea/angular-strap#1871]
the simple select demo  can't run ,throw an error 
![image](https://cloud.githubusercontent.com/assets/11714828/9932264/f4354c12-5d74-11e5-93a2-438e538ca597.png)

js file content 
  $scope.icons = [
    {value: 'Gear', label: '<i class="fa fa-gear"></i> Gear'},
    {value: 'Globe', label: '<i class="fa fa-globe"></i> Globe'},
    {value: 'Heart', label: '<i class="fa fa-heart"></i> Heart'},
    {value: 'Camera', label: '<i class="fa fa-camera"></i> Camera'}
  ];

html file content 
<button type="button" class="btn btn-default" ng-model="selectedIcon" data-html="1" bs-options="icon.value as icon.label for icon in icons" bs-select>
                                    Action <span class="caret"></span>
                                </button>

**Comment by jefferykhan** [comment]
You need to load the ngSanitize module to prevent this.

**Comment by vmlf01** [comment]
see #1598
