### ISSUE TITLE
\n character

### ISSUE THREAD

**Issue by utiq** [mgcrea/angular-strap#1873]
A \n characters are showing in the modal.
Angular version: 1.4.5
template: custom template

_Modal configuration:_
angular.extend($modalProvider.defaults, {
   html: true
});

![screen shot 2015-09-18 at 1 29 05 am](https://cloud.githubusercontent.com/assets/1144196/9952542/04071096-5da5-11e5-9249-40c49236e612.png)

**Comment by vmlf01** [comment]
I tried the docs sample and it works, the newline characters don't show up. Maybe your content has escaped '\' inside the string?
Check out http://plnkr.co/edit/lfPQz7d1ZYCluAMJk5Nc?p=preview
