### ISSUE TITLE
Datepicker unpickable on iOS Chrome when in an iframe

### ISSUE THREAD

**Issue by dplepage** [mgcrea/angular-strap#1874]
When I'm using Chrome on my iPad, a datepicker inside an iframe doesn't work - when I click any date, the picker dismisses instantly and the click registers on whatever element was underneath the picker.

It doesn't happen on Chrome on my desktop, or on Safari on the iPad, just iOS Chrome.

I can reproduce it consistently with these two files and any static webserver:

_foo.html_ - the simplest ngStrap datepicker

``` html
<html>
<head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.6//angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-strap/2.3.2/angular-strap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-strap/2.3.2/angular-strap.tpl.js"></script>
  <script type="text/javascript">
    angular.module('failure', ['mgcrea.ngStrap.datepicker'])
  </script>
</head>
<body ng-app="failure">
  <input type='text' bs-datepicker="" ng-model="data">
</body>
</html>
```

_bar.html_ - just an iframe around foo.html

``` html
<html>
<head></head>
<body>
  <div style='border:1px solid black; padding:10px'>
    <iframe src="foo.html">
  </div>
</body>
</html>
```

**Comment by dplepage** [comment]
Update: disabling [line 417 of tooltip.js](https://github.com/mgcrea/angular-strap/blob/master/src/tooltip/tooltip.js#L417) makes this stop happening, so Chrome must be sending a spurious blur event when clicking on the datepicker. The blur event is processed before the click, with the result that the datepicker is hidden and then the click hits whatever's now at the click location.

**Comment by groner** [comment]
Here is a jsbin demonstrating the the issue (iframe not included, because jsbin already has one):
http://jsbin.com/maxovelaxu/edit?html,output
