### ISSUE TITLE
Unable to change hour in timepicker by up arrow button in Firefox

### ISSUE THREAD

**Issue by phhien203** [mgcrea/angular-strap#1877]
![screenshot](https://cloud.githubusercontent.com/assets/8808535/10010883/e3380382-611b-11e5-91cf-dbb08a38b3df.png)

In the home page of angular strap http://mgcrea.github.io/angular-strap/#/timepickers, the example for timepicker, I am not able to change the time from 6:30 to 7:30 by clicking the up arrow button. 

Further more, if I click the down button to change time, the time will decrease but when it reaches 8 and I click down button one more time, then time value change directly from 8 to 6.
This only happends in Firefox, in Chrome it's ok. 

I'm using RHEL 6.7, Firefox 41.0.1 and current timezone is GMT+7.
Any ideas could help. Thanks.

**Comment by vmlf01** [comment]
Maybe has something to do with daylight savings day changes? Have you tried again since then?

**Comment by phhien203** [comment]
@vmlf01 , I have tried today but same issue happens.
