### ISSUE TITLE
modal.$hide() should better carry variable

### ISSUE THREAD

**Issue by stanleyxu2005** [mgcrea/angular-strap#1880]
When I close a modal dialog, I call `$scope.$hide()`. In parent scope, I listen to 'modal.hide'. It seems the event is triggered with a scope object. Actually, it is hard to distinguish, whether user has closed the dialog by having clicked which button. 

I am looking for a straightforward way to do that. Here is my use case with my imagination: 
1. User click "Cancel", we call `$scope.$hide();`.
2. User click "Save", we call `$scope.$hide(data);`.

In parent scope, we listen `$scope.$on('modal.hide', function(data) { });`. 
1. When data is not null, we know user has changed something, we might do extra handling in this case. 
2. When data is null, we know user has clicked "Cancel".

Does it make sense, or I have missed some important functions of $modal.

**Comment by rickxie** [comment]
agree
