### ISSUE TITLE
A little advice about the Multiple Select

### ISSUE THREAD

**Issue by quanwuhui** [mgcrea/angular-strap#1886]
Find when I using the Multiple select and select a different option,the button's width is different.The question is  When I have a lot of options to select this button may be beyond the width of the width of the screen.I don't want my button width is changing.I hope more the style of the box and select box in HTML 5.Give the user a input text and when user focus the input text,the options is show,When the user to select multiple option,the result show in the input text with a value string which split with the dot.

**Comment by DaleWebb** [comment]
You should modify the style via CSS to suit your needs, in this case :)
