### ISSUE TITLE
ngModal: Call destroy method from a controller / directive

### ISSUE THREAD

**Issue by Kimera2015** [mgcrea/angular-strap#1889]
Hi,

I need to call the destroy() method from a controller associated with a newly created modal.

I see that $show(), $hide() and $toggle() are injected in the scope reference, but I couldn't find a simple way to access destroy(). I came up with this solution:

app.register.controller('myController', ['$scope', 'myModal',
    function ($scope, $modalInstance) {
        $scope.$modal = $modalInstance();
        $scope.destroy = function () {
            $scope.$modal.destroy();
        }
    }
 ]);

 var myModal = $modal({
                controller: 'myController',
                templateUrl: '/app/myTemplate.html',
                locals: {
                    myModal: function () { return myModal;}
                }
            });

Did I miss something? Is there another less intricate way to access destroy()?

Thank you in advance.

**Comment by 1Jesper1** [comment]
I'm also interested.
