### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. occurs while setting global params

### ISSUE THREAD

**Issue by zhang421755327** [mgcrea/angular-strap#1893]
this.mod.config(["$httpProvider", function($httpProvider) {
                	$httpProvider.interceptors.push(['$translate',
                        function($translate) {
                            return {
                                'request': function(config) {
                                    if (!config.params) {
                                        config.params = {};
                                    }
                                    config.params.lang = $translate.use();
                                    return config;
                                }
                            };
                        }
                    ]);
                }]);

**Comment by vmlf01** [comment]
Not sure if this relates to AngularStrap or is just Angular.js related and posted here by mistake?

**Comment by vmlf01** [comment]
Please re-open if appropriate
