### ISSUE TITLE
Binding to id instead of object

### ISSUE THREAD

**Issue by Cyber1000** [mgcrea/angular-strap#1894]
Typeahead: 
- I have a binding against a id not object (user.locationId), if I select something from the list, the binding is correctly updated and my id becomes 1,2, ...
- If I set user.locationId to my id from code ($scope.user.locationId=1) the id "1" is in my input-field instead of the value (from location.name).

Am I mssing something or using this control in a wrong way? Sorry I'm new to angular(-strap).
Thanks a lot

```html
<input type="text" class="form-control" id="location" name="location" ng-model="user.locationId" required bs-options="location.id as location.name for location in user.locations" data-auto-select="true" bs-typeahead/>
```

**Comment by jukkasi** [comment]
I believe your issue is same I have created pull request for

https://github.com/mgcrea/angular-strap/pull/1867
