### ISSUE TITLE
fullDate format not working in Spanish

### ISSUE THREAD

**Issue by overloadnn** [mgcrea/angular-strap#1897]
Datepicker does not work when using spanish locale. The problem is with the "d" character in the fullDate entry in the locale file.

For example: angular-locale_es-ar.js  --> **fullDate: "EEEE, d 'de' MMMM 'de' y"**

In $dateParser.parse the valid date **martes, 13 de octubre de 2015** cannot be resolved with the regex **/^(domingo|lunes|martes|miércoles|jueves|viernes|sábado), (0?[1-9]|[1-2][0-9]|3[01]) '(0?[1-9]|[1-2][0-9]|3[01])e' (enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre) '(0?[1-9]|[1-2][0-9]|3[01])e' (-?0*[0-9]{1,4})$/i**

**Comment by sdoran** [comment]
I'm seeing the same issue for Spanish and Portuguese. The regex generated by date-parser.js doesn't take into account 'de'. 

I've reproduced the issue in Plunkr http://plnkr.co/edit/oY8jiGXXGTnKUAaUiGFC?p=preview

**Comment by vmlf01** [comment]
It looks like the $dateParser is blindly replacing the ```d``` token with the day parsing regex when it should ignore the ```'de'``` token because it is escaped inside the quotes. 

In fact, $dateParser should ignore all literals inside the format string. I'll have a look and see it I can come up with a quick fix.

**Comment by sdoran** [comment]
That would be awesome thanks Victor. Even a workaround would do but I've come up short trying to find one.
