### ISSUE TITLE
Problem with object binding, wenn I change focus and type in full name of selection

### ISSUE THREAD

**Issue by Cyber1000** [mgcrea/angular-strap#1898]
See this plunker: http://plnkr.co/edit/K9ymzdFjFoXxxdWOmlOb?p=preview
1) Type in the complete name, not only part of a state: Alabama
2) Press enter
3) Now the state (see on top of plunker) is $scope.selectedState = "{"id":1,"name":"Alabama"}";
4) Press tab to switch to the next input field
5) Suddenly the state changes to $scope.selectedState = "Alabama";

So I dont have the full object any more.

This works only, if I try this on a newly refreshed plunker page not on subsequent tries.
If I only enter part of the state (e.g. Ala) and press enter and tab I don't have this effect. Only if I write the full name.
Tested with last chrome and firefox.

Thanks

**Comment by andras-tim** [comment]
At first, I can not find your problem. But when I reload the page and tried your scenario again I have got this too. Nice catch!

**Comment by andras-tim** [comment]
@Cyber1000 This issue has a 0. step:
have to empty the input filed before write or past the complete name of state

**Comment by andras-tim** [comment]
I spend a lot of time to debug this bug, but I can't find the root cause.

However **Ray Bateman** solved / workarounded this problem in mgcrea/angular-strap/#2061 pull request. I'm waiting for integrate this fix.
