### ISSUE TITLE
Hard coded z-index for modal backdrop

### ISSUE THREAD

**Issue by oknechirik** [mgcrea/angular-strap#1900]
Why? :'(
backdropElement.css({position:'fixed', top:'0px', left:'0px', bottom:'0px', right:'0px', 'z-index': 1038});
And there is no place to change it to value I want!

**Comment by DaleWebb** [comment]
This is because we need to ensure that it is less than the modal's z-index value. You could override it with CSS and append the !important keyword after.

Why would you want to change it?
