### ISSUE TITLE
activeTab is not updating

### ISSUE THREAD

**Issue by vapits** [mgcrea/angular-strap#1902]
Hi, i'm using the 2.3.3 version of Angular Strap and i've got an issue with tabs (well i do believe it's an issue).

I've got some tabs let's like this:
````html
<div class="nav nav-tabs" bs-active-pane="activeTab" bs-tabs>
    <div title="tab1" name="tab1" bs-pane>Tab 1</div>
    <div title="tab2" name="tab2" bs-pane>Tab 2</div>
    <div title="tab3" name="tab3" bs-pane>Tab 3</div>
</div>
````
and in my controller a scope:
````javascript
$scope.activeTabe = 'Tab1';
````
I do not have buttons or menu for those, i use the headings created by the plugin.

What's my issue, when i click on tab 2 heading my activeTab scope stays the same, the same of course if i click tab 3 etc.
How can i change it? I want to know which tab is clicked to open without using different buttons for this. 
Or at least is there any callback when changing tabs (can't find something in docs).

**Comment by vapits** [comment]
Btw even if i work with numbers in scope instead ob name the issue is the same.
Anyone else solve it?

**Comment by ricardoduarte** [comment]
I'm stuck with the same problem here.

**Comment by vapits** [comment]
@ricardoduarte you have to provide the tabs to your domr be a tabs $scope. if you did this like i did it's not working.

So in my case i change my above dom with something like that in my controller:
````javascript
$scope.tabs = [
                {
                    name: 'Tab 1',
                    url: 'templates/tabs/tab1.html'
                },
               {
                    name: 'Tab 2',
                    url: 'templates/tabs/tab2.html'
                },
                {
                    name: 'Tab 3',
                    url: 'templates/tabs/tab3.html'
                }
            ];

$scope.tabs.activeTab = 0;
````

And so my dom now is:
````html
<div bs-tabs bs-active-pane="tabs.activeTab" class="nav nav-tabs" ng-show="dataSet">
     <div ng-repeat="tab in tabs" title="{{tab.name}}" name="{{tab.name}}" bs-pane>
          <div ng-include src="tab.url"></div>
     </div>
</div>
````

Now the activeTab works fine.

**Comment by ricardoduarte** [comment]
@vapits Thank you so much. It worked fine now!
