### ISSUE TITLE
Tooltip does not hide from meantime disabled object

### ISSUE THREAD

**Issue by andras-tim** [mgcrea/angular-strap#1905]
### Please check the following steps

1. Move mouse to the firt button for show tooltip.
2. Pleas, click on the Button with tooltip button for disable it with ng-disable after the tooltip shown.
3. Move out mouse from the button, and the tooltip will never hide.

-

4. Make re-enabled the Button with tooltip button with the second one.
5. Move mouse to the first button again (noting will be happened).
6. However, when I moved out the mouse from the re-enabled button, the toolt will hide automatically.

### Demo environment
http://plnkr.co/edit/i24IJ3lIND390bqBz9Q5?p=preview

**Comment by andras-tim** [comment]
I think, this is a watch() for ng-disabled, what force hide() the tooltip.

**Comment by vmlf01** [comment]
The test is using bs-enabled and you are using ng-disabled, which are different things, so that explains differences.
