### ISSUE TITLE
Mobile scrolling

### ISSUE THREAD

**Issue by AndersonDev** [mgcrea/angular-strap#1908]
Hi. I tried to realized ngStrap.select with scrolling.

css:

```
max-height: 200px;
overflow: hidden;
overflow-y: auto;
```

On PC works fine, but on mobile - doesn't. When I try to scroll select chosing the wariant. Help please

**Comment by DmitrySkripkin** [comment]
Having same issue. Fun thing is that you can scroll if you select an item and then scroll while dropdown fade out.
