### ISSUE TITLE
Datepicker and Timepicker Demos on the Demo Page Icons Brocken

### ISSUE THREAD

**Issue by squadwuschel** [mgcrea/angular-strap#1912]
Hi,

when you use the Date or Timepicker directly on the page:

http://mgcrea.github.io/angular-strap/#/datepickers

then the Arrows for Navigation are not shown.
On the Live Demo Page (Plunkr) everything looks fine.

**Comment by vmlf01** [comment]
Looks like the font file links on the docs pages are 404:

http://mgcrea.github.io/angular-strap/fonts/glyphicons-halflings-regular.woff2
http://mgcrea.github.io/angular-strap/fonts/glyphicons-halflings-regular.woff
http://mgcrea.github.io/angular-strap/fonts/glyphicons-halflings-regular.ttf
