### ISSUE TITLE
define bs-tooltip options in scope and pass object

### ISSUE THREAD

**Issue by ilovett** [mgcrea/angular-strap#1917]
```
$scope.tooltipDef = {
  'title': 'this currently gets set',
  'placement': 'right', // this does not seem to override
  'trigger': 'click' // does not override either
}
```
```
<button bs-tooltip="tooltipDef">hello</button>
```

I thought I would be able to pass in the options to override the default config options, but they don't seem to get included (except title, title will work)

**Comment by vmlf01** [comment]
If you pass an object into the bs-tooltip attribute it will use that as the scope, but all the attributes are not read from scope, except title. The other attributes need to be specified using the specific tooltip options attributes, like data-placement, data-trigger, etc.
