### ISSUE TITLE
Rebuilding the datepicker when locale is changed

### ISSUE THREAD

**Issue by daviddutch** [mgcrea/angular-strap#1922]
I'm using https://github.com/lgalfaso/angular-dynamic-locale to load the locale dynamically. My problem is that the datepickers that are already loaded don't get the new locale. How can I force the datepickers to refresh?
Thank you

**Comment by esbakker** [comment]
I think this is the same issue: #919
I fixed it by creating a directive with an ng-if that recreates the content of the directive (in this case the datepicker):

````javascript
angular.module('DynamicLocalePatch', []).directive('dynamicLocalePatch',
		function() {
			return {
				transclude: true,
				restrict: 'A',
				template: '<div data-ng-if="showElement"><div data-ng-transclude></div></div>',
				link: function(scope) {
					scope.showElement = true;

					scope.$on('$localeChangeStart', function() {
						scope.showElement = false;
					});

					scope.$on('$localeChangeSuccess', function() {
						scope.showElement = true;
					});
				}
			};
		});
````

The $localeChangeSuccess is triggered by angular-dynamic-locale. $localeChangeStart you have to broadcast yourself before the locale is changed.
