### ISSUE TITLE
minView (min-view) for bs-datepicker is not in the docs

### ISSUE THREAD

**Issue by genuinefafa** [mgcrea/angular-strap#1923]
I'm not sure why, but, is there a `minView` attribute asociated with the __bs-datepicker__?

I found that it works, but not entirely sure how. :) @vmlf01 did a plunkr not so long ago in #1196 and it works with the latest version of AngularStrap.

Cheers and thanks!

**Comment by vmlf01** [comment]
The minView attribute is listed in the datepicker options, it allows you to restrict the date resolution the user can pick:
0 - day
1 - month
2 - year
