### ISSUE TITLE
How can I inject variables to aside controller(Typesrcript)??

### ISSUE THREAD

**Issue by billkim84** [mgcrea/angular-strap#1926]
Hi, i'm trying to inject local variables to aside controller but I don't know to can I achieve this.

I create aside with controller as options and want to inject some values into the controller.
```
this.productAside = $aside({
    controller: "App.Controllers.ProductCrudController",
        controllerAs: "vm",
        templateUrl: "product-create.html",
        locals: {
            mode: "create"
        },
        show: false
    });
```
This is the controller I want to use for aside.

```
 export class ProductCrudController {
    static $inject = ["$scope", "ProductService", "TaxService"];

    constructor(private $scope: any,
                private ProductService: App.Services.ProductService,
                private TaxService: App.Services.TaxService) {

         // how can i get values here??
    }
```
any help will be appreciated

**Comment by vmlf01** [comment]
Looks like you can use the "locals" to pass values, either by injecting them into the controller function or binding them directly to the controller instance:

    *   - `locals` - `{object}`: The locals which will be passed into the controller once `link` is
    *     called. If `bindToController` is true, they will be coppied to the ctrl instead
    *   - `bindToController` - `bool`: bind the locals to the controller, instead of passing them in.

Have a look at the angular-material compiler service tests, which is being used, to have an idea on how to use it:

https://github.com/angular/material/blob/master/src/core/services/compiler/compiler.spec.js#L114

**Comment by billkim84** [comment]
Thank you for help
