### ISSUE TITLE
Dependency on ngMotion not documented

### ISSUE THREAD

**Issue by amahfouz** [mgcrea/angular-strap#1931]
Inside my controller I have a function that uses the alert service:

```
		    var missingInputAlert = {
			  "title": "Missing Input", 
			  "content": "Enter the player name and shirt number.",
			  "type": "danger",
			  "placement": "top",
			  "animation": "am-fade",
			  "duration": 3,
			  "show": true
		    };

		    $alert(missingInputAlert);
```

A button on my HTML calls this function via `ng-click`.

The result is that the alert does appear but no animation, in or out, is shown (it just disappears). I have added ngAnimate as a module dependency but that did not make a difference.

**Comment by amahfouz** [comment]
Do I need to include 'mgcrea.ngMotion' as well?

**Comment by vmlf01** [comment]
The Getting started | Animations section mentions you need custom CSS to power the animations and provides instructions to install AngularMotion as a possible implementation, but you already found that out by yourself ;)
