### ISSUE TITLE
popover placement is not working correctly

### ISSUE THREAD

**Issue by inZaCz** [mgcrea/angular-strap#1933]
After update from 2.2.1 to 2.3.2 the placement of popover can't handle the combination of placements.

Any combination of two placements displays popover on top. Especially the auto something combination. And it seems to also ignoring the containers.

**Comment by dandoyon** [comment]
I upgraded from 2.0.5 to latest 2.3.5 and all my previously working popover placements are not working properly. I first notice them auto hiding, and then found that ones that didn't auto-hide shifted

![image](https://cloud.githubusercontent.com/assets/475217/11223192/8b9519d8-8d23-11e5-8ec4-36be489c63cf.png)

**Comment by dandoyon** [comment]
![image](https://cloud.githubusercontent.com/assets/475217/11223203/99f149b6-8d23-11e5-8919-90db95cacc00.png)

**Comment by dandoyon** [comment]
![image](https://cloud.githubusercontent.com/assets/475217/11223215/a59df80e-8d23-11e5-9eda-5c9f15e97605.png)

**Comment by dandoyon** [comment]
I used bower and upgraded all my libraries, I'm on angular 1.4.7
