### ISSUE TITLE
Old state in Buttons with onclick

### ISSUE THREAD

**Issue by Carw** [mgcrea/angular-strap#1934]
<button type="button" ng-click="setResourceProcess(resource)" ng-model="resource.process" bs-checkbox>

In function *setResourceProcess()* variable *resource.process* has old state. But ng-change works correct.

**Comment by vmlf01** [comment]
Can you please elaborate more on your issue? Preferably with a code sample.

**Comment by vmlf01** [comment]
Can you please elaborate more on your issue? Preferably with a code sample.

**Comment by vmlf01** [comment]
Please re-open if you can add more information.
