### ISSUE TITLE
bs-select Add action on select

### ISSUE THREAD

**Issue by vapits** [mgcrea/angular-strap#1940]
That would be a great feature. Trigger an action (Ex a function) when an option is selected (well something like ng-click but in options).

**Comment by vmlf01** [comment]
Maybe you can use the '.select' event triggered when an item is selected. Have a look at
http://plnkr.co/edit/8IaJEu5cnm2U1kvQdPGT?p=preview

**Comment by vapits** [comment]
@vmlf01 thx, i already did that, i opened the issue so maybe that will become a future feature :) ;)
