### ISSUE TITLE
angular strap + bootstrap-rtl

### ISSUE THREAD

**Issue by tomerz012** [mgcrea/angular-strap#1943]
when using angular-strap on top bootstrap-rtl css, some of the functionality of the components are ruined.

for ex. I've tried to use the Datepicker placement attribute without any luck.
none of the strings are applied with the bootstrap-rtl css

**Comment by tomerz012** [comment]
in order for it to work, i had to override bootstrap-rtl's dropdown-menu class

**Comment by vmlf01** [comment]
Relates to #1862?

**Comment by tomerz012** [comment]
#1862 is part of it....I'm guessing there are more components with this issue.

**Comment by vmlf01** [comment]
OK, just linking issues together so they stay related
