### ISSUE TITLE
Tooltips not appearing in ui-grid cell template

### ISSUE THREAD

**Issue by ocsike** [mgcrea/angular-strap#1944]
Hi,
The tooltip must be showing when the input get focus.
The tooltip showing when outside the grid, but when it is inside the grid it not shows. No error or something happened. 

Here is the plunker http://plnkr.co/edit/rHlAmRe7Z5TxfHIqRBTq?p=preview

**Comment by vmlf01** [comment]
Duplicate of #1132 
Please see my comment there
