### ISSUE TITLE
Datepicker needs maxView property

### ISSUE THREAD

**Issue by hackel** [mgcrea/angular-strap#1949]
The Datepicker widget needs the ability to set a maximum view level.  In particular, I want to use it _only_ to select a month, no day nor year.  I could also see someone wanting to use it to pick a day in a specific month.

It looks like this is already supported by [smalot/bootstrap-datetimepicker](https://github.com/smalot/bootstrap-datetimepicker), but I don't know how easy it would be to import that functionality.

Thanks!

**Comment by vmlf01** [comment]
For now, the best option seems to be a combination of minView with minDate/maxDate to restrict what the user can select.
