### ISSUE TITLE
contentTemplate does not work with popovers using object notation

### ISSUE THREAD

**Issue by SteffanLong** [mgcrea/angular-strap#1950]
Here's a plunk demonstrating the issue. http://plnkr.co/edit/QQZTfH1LvoH6oxKAMfSD?p=preview

This seems to happen across all of AngularStrap. We have the same issue with modals and tooltips.

**Comment by SteffanLong** [comment]
templateUrl seems to suffer from the same problem.

**Comment by vmlf01** [comment]
If you pass in an object to the directive attribute, it will be used as scope with attributes you can bind to in the template, like ```title``` or ```content```.

The directive options are not read from the scope, so what you are seeing is currently expected behaviour.

**Comment by SteffanLong** [comment]
Why would this be expected behavior? There's no reason we should be forced to use attributes and the object syntax for the directive. Further, there is absolutely no mention of this in the docs.

**Comment by vmlf01** [comment]
When I say it is expected I mean it's the way it's currently coded. This usage is exemplified in the docs demos and the options section under the directive.

With this I don't mean it shouldn't change, I just mean it's how it works

**Comment by RobertVogt** [comment]
Thank you for posting this!!! I spent a whole day trying to figure out what I was doing wrong and it turns out NOTHING!!!  This aspect should be changed to be more in line with how developers develop OO solutions.
