### ISSUE TITLE
Insight on Confirmation Modal Factory Question

### ISSUE THREAD

**Issue by stillfire** [mgcrea/angular-strap#1957]
Hi, I was wondering if any of you could help with a question I have on Stackoverflow.

http://stackoverflow.com/questions/33656509/returning-data-with-angularjs-bootstrap-modal-confirmation-factory

I made a confirmation modal factory using AngularStrap - and everything is working but I just can't get a proper return value from the factory.

Any insight is appreciated! Cheers.

**Comment by vmlf01** [comment]
Have a look at #1505, I have a sample there of a modal service with promises.

**Comment by stillfire** [comment]
Thank you! Got it working :)
