### ISSUE TITLE
It's possible show options in groups?

### ISSUE THREAD

**Issue by serloal** [mgcrea/angular-strap#1959]
II'm trying last versión ot angular-strap http://plnkr.co/edit/zujdouvB4bz7tFX8HaNu?p=preview, in this sample, it's possible to group options by model property. 

It's possible achieve this behaviour in last version?
Desired Behaviour:
* When user click/focus at input bs-typeahead, the grouped options are shown.
* User can select one or type to filter

**Comment by vmlf01** [comment]
AngularStrap does not currently support this grouped items feature.

**Comment by serloal** [comment]
Thanks for your answer.

I'll search for other solutions
