### ISSUE TITLE
Collapse panels open by default

### ISSUE THREAD

**Issue by NickToye** [mgcrea/angular-strap#1960]
It would be really awesome if we can have the option to have the panels open or closed, and all open or all closed.

I know we can specify a number from an array index, but it's not going to work if there is an endless amount of panels in the collapse group.

I'm quite new at Angular so not really sure how I could achieve this, but I'll see if I can see how.

**Comment by vmlf01** [comment]
There is a "Multiple open panels sample" in the docs under the Collapse directive, have you tried it out?

**Comment by NickToye** [comment]
Yes, but you have to specify a number from an array index which I have mentioned in my original comment.

**Comment by DaleWebb** [comment]
There is a `data-start-collapsed` attribute, would that solve your issue?
