### ISSUE TITLE
Datepicker throws TypeError when user enters date less than minimal in a blank control

### ISSUE THREAD

**Issue by oliverhanappi** [mgcrea/angular-strap#1961]
The datepicker throws an error when the user manually enters a date that is less than the minimum configured date. The error only occurs when the datepicker has not been touched yet, hence if the input is the first one. Furthermore, the model type needs to be set to iso.

The error is:

```
TypeError: Cannot read property 'toISOString' of null
```

For reproduction, you can use the following jsFiddle: http://jsfiddle.net/hj8tvjcd/
1. Open the jsFiddle
2. Enter "2014-01-01" into the text box / datepicker
3. Inspect the browser console

==> The above listed error is reported

**Comment by vmlf01** [comment]
Probably not restricted to the "iso" model type, looks like it is this block of code:
https://github.com/mgcrea/angular-strap/blob/master/src/datepicker/datepicker.js#L384
