### ISSUE TITLE
Incorrect validation in case of maxDate less than model value.

### ISSUE THREAD

**Issue by dmitry-dedukhin** [mgcrea/angular-strap#1973]
http://embed.plnkr.co/kd1sHOL6REdWWz9x6W3o/

Datepicker field is marked as invalid by maxDate at the app startup - it's ok.
But if I clear input manually, datepicker stays invalid by maxDate.
This happens because of condition on https://github.com/mgcrea/angular-strap/blob/master/src/datepicker/datepicker.js#L362 is true and validation against max dates is not re-run.
When maxDate is larger than model value - all is ok.

Seems that this behaivor also applicable to minDate.

**Comment by cegiraud** [comment]
+1

**Comment by shanoy** [comment]
+1 @mgcrea Could you please look at this bug? It is critical and opened for two years
