### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by stanleyxu2005** [mgcrea/angular-strap#1984]
I'm using 2.3.6. I noticed (since long), that datepicker will display 6 rows. You can see the last line of dates are actually belong to next month. They should not be shown at all. Could you confirm if it is a bug? A live example can be found here http://mmjd.com/dashing/examples/#/forms/forms

![untitled](https://cloud.githubusercontent.com/assets/5162687/11744269/db9e1d24-a049-11e5-8adf-5b92c8e02cb2.png)

**Comment by chino23** [comment]
It's not a bug, it's a feature. The datepicker has to be the same height all the time for switching months.

The reason it's 6 lines: Check May 2016. There you have all 6 lines occupied by active month dates. 

If it was confined to 5, you'd either have some months not showing all days of the current month, or you'd have a really annoying jump in height sometimes.

**Comment by stanleyxu2005** [comment]
Got it.
