### ISSUE TITLE
Angular strap future? Abandoned?

### ISSUE THREAD

**Issue by mnemanja** [mgcrea/angular-strap#1991]
Is Angular Strap abandoned? Last update was a year ago, and there are 412 opened issues, where the oldest issue still open is 3 years old.

I'm using it fully in a project which went to production recently, and I would like to know should I look for alternatives in the near future or not.

**Comment by chino23** [comment]
Last update a year ago? Where did you get that?

https://github.com/mgcrea/angular-strap/commits/master check this out, it's quite active, last update a month ago. Been using it for over a year and it's quite stable.

**Comment by mnemanja** [comment]
My mistake.
