### ISSUE TITLE
bs-tooltip contentTemplate is ignored

### ISSUE THREAD

**Issue by cudasteve** [mgcrea/angular-strap#2007]
At version 2.3.6 (current) bs-tooltip appears to be completely ignoring the contentTemplate attribute.

#1306 sort of gets at a similar issue except back then the contentTemplate was working, just required the title.  [Here's a plunkr](http://plnkr.co/edit/2b1VTyM7AaN8S5FbKupM) I forked from that and just changed the version numbers for angularStrap.  As you can see, it's completely ignoring the contentTemplate.

Seems like it might have gotten completely removed [back in July](https://github.com/mgcrea/angular-strap/commit/623bfe0a94f34862c6a9df1eceeae6ebdba31862#diff-e8665eb306ddd26399e5b80f00dae5bbL90).  Perhaps that was unintentional since the commit seems to be about something else?

**Comment by mgcrea** [comment]
It was not removed but refactored away in https://github.com/mgcrea/angular-strap/blob/master/src/helpers/compiler.js#L110

Not sure why it does not work, this should be tested.

**Comment by cudasteve** [comment]
https://github.com/mgcrea/angular-strap/blob/master/src/tooltip/test/tooltip.spec.js#L912

**Comment by cudasteve** [comment]
I think I figured it out.  The compiler is looking for `[ng-bind="content"]` when the tooltip would match `[ng-bind="title"]`
https://github.com/mgcrea/angular-strap/blob/master/src/helpers/compiler.js#L115

I'll submit a PR shortly though I'm not sure if you'd rather bring tooltip inline with the rest of the library by having it use a `content` attribute instead of a `title` one.

**Comment by mgcrea** [comment]
Thanks! Landed in a9db388.
