### ISSUE TITLE
Typeahead issue with Chinese input method

### ISSUE THREAD

**Issue by webyom** [mgcrea/angular-strap#2017]
I use "Pinyin - Simplified" input method of OSX 10.10.5 as below:
<img width="516" alt="screen shot 2016-01-18 at 5 17 53 pm" src="https://cloud.githubusercontent.com/assets/899652/12387569/806856b8-be08-11e5-9947-bbbd357f9e0b.png">

The input result with typeahead input box is
<img width="516" alt="screen shot 2016-01-18 at 5 18 16 pm" src="https://cloud.githubusercontent.com/assets/899652/12387589/9a0be26a-be08-11e5-990e-98c323f3f1a9.png">

The expected input result shouldn't contain the leading "ni hao".

If I remove "controller.$render();" at line263 in the "Watch model for changes" block of typeahead.js, it works as expected.

**Comment by pmint93** [comment]
Same problem with Mac OSX Simple Telex in Vietnamese language. When type `đ` and press space, expected input has  value `đ` but it doubled to `đđ`.

**Comment by technizhang** [comment]
met the same problem, webyom's method is ok
