### ISSUE TITLE
datepicker and local timezone

### ISSUE THREAD

**Issue by martunta** [mgcrea/angular-strap#202]
I might be missing something very simple, but somehow I can not get angular-strap to show correct date in datepicker. 

If I change default example to have date '2012-09-01T23:00:00.000Z' then I expect datepicker to show 2012-09-02 as I am in GMT+3 timezone, but datepicker shows 2012-09-01 instead

http://plnkr.co/edit/jyy2DNR2heHALzET74bH?p=preview

Is there a simple config, or other workaround for this? 
p.s. I am trying to set today's date in datepicker.

**Comment by jorgefranciscogil** [comment]
Format date without T :)

**Comment by senthilsendhil** [comment]
Still Same present ,
