### ISSUE TITLE
2.3.7 and Popover Placement?

### ISSUE THREAD

**Issue by bazeli** [mgcrea/angular-strap#2021]
Hello,

I'm trying to grasp the logic behind popover placement in v2.3.7.   For some reason, "auto bottom-left" isn't applied in the same way as it was previously.  Specifically, it appears that the "auto" keyword is not being applied when there is a preference for placement after the auto keyword.  "auto" alone works fine.

Example:

https://plnkr.co/edit/evQTQoE1IZe63HgCmm95

Any ideas on a workaround here?  Ideally I would like to have "auto bottom-left" working as it was previously, where the arrow indicator on the top of the popup is placed appropriately.

**Comment by mgcrea** [comment]
This commit might be the culprit: 8fd6735a7a40f3f2943ca2d8cdd81380f5a3ff7b

We had numerous issues regarding incorrect positioning: #1970 #1988 #1989 

Looks like it may have introduced a regression, could you try to hack around the code to see if you can get back your wanted behavior.

**Comment by fracz** [comment]
+1, v.2.3.8 ignores the `auto`, too.
