### ISSUE TITLE
bs-popover title overload with content

### ISSUE THREAD

**Issue by waqasraz** [mgcrea/angular-strap#2022]
using data-content-Template overload the title with "content" so we get content in title and content in title. In other words content show up twice. Here is plunker showing the problem

https://plnkr.co/edit/ALDwTUXJY22efsygWhb1

**Comment by trampi** [comment]
It is a regression, originating from the change made in #2007.

**Comment by trampi** [comment]
Submitted a pull request (https://github.com/mgcrea/angular-strap/pull/2023) which fixes this issue. A test, reproducing this issue, is included.
