### ISSUE TITLE
Collapse Panels - Expand/Collapse All

### ISSUE THREAD

**Issue by neiloler** [mgcrea/angular-strap#2024]
I'm trying to implement a "expand all" and "collapse all" kind of functionality for angular-strap:

I tried inserting into the array given by `multiplePanels.activePanels`, but it seems like this is a one way binding, and doesn't change anything about which panels are collapsed or not.

I'm making sure to enable having multiple panels open at once, too.

Is there currently a way to do this?

**Comment by antoinebrault** [comment]
You have to change the array reference.
If you simply push a value into the same array it won't work.

Something like this should work:
```javascript
multiplePanels.activePanels = multiplePanels.activePanels.concat([1])
```
