### ISSUE TITLE
Can't click item with icon on mobile using the Select control.

### ISSUE THREAD

**Issue by LBobirca** [mgcrea/angular-strap#2047]
If have an icon or insert additional HTML on a select item you cannot click on that item.  There is a fork in the code for a touch event that expects the element to be passed in be the anchor tag, however this is not the case if you have an icon.  This can be duplicated with the docs, if you open the http://mgcrea.github.io/angular-strap/#/selects demo on a mobile device you can reproduce this.  All that needs to happen is that the DOM needs to be walked until it finds the first anchor tag.  I think this should work on the $select.$onMouseDown event.  I'm sure there is a more efficient way to write this, but this is my stab at it.  I have this as a work around, but I would love to see this bug fixed.

              $select.$onMouseDown = function (evt) {
                  // Prevent blur on mousedown on .dropdown-menu
                  evt.preventDefault();
                  evt.stopPropagation();
                  // Emulate click for mobile devices
                  if (isTouch) {
                      var targetEl = angular.element(evt.target),
                          anchor;

                      if (evt.target.nodeName == 'A') {
                          anchor = targetEl;
                      }
                      else {
                          var anchors = targetEl.parents().toArray().filter(function (obj) {
                              return obj.nodeName == 'A';
                          });

                          if (anchors.length > 0)
                              anchor = anchors[0];
                      }

                      if (anchor != null) {
                          angular.element(anchor).triggerHandler('click');
                      }
                  }
              };

**Comment by DaleWebb** [comment]
Which line has the fork for a touch event that expects an anchor tag?

**Comment by otterfuller** [comment]
It's on line 1609-1612 of angular-strap.js (version 2.3.8).
