### ISSUE TITLE
contentTemplate overrides title in modal

### ISSUE THREAD

**Issue by arteme** [mgcrea/angular-strap#2049]
Hi,

I have:
    1) content template specified using the ``contentTemplate`` option, and
    3) title specified using the ``title`` option.

In this setup, the title is lost and ``<div ng-bind="title">`` produces the same content as ``<div ng-bind="content">``. See plunker demo: http://plnkr.co/edit/2o6KJz8MhiI8ANSBmJJe?p=preview

**Comment by Karankang007** [comment]
Able to replicate this

**Comment by theatlasroom** [comment]
Having the same issue too

**Comment by blaind** [comment]
Seems to be fixed by #2022

**Comment by RonenA** [comment]
Having this issue as well

**Comment by DaleWebb** [comment]
If this is fixed by #2022 then you should be able to see those changes by referencing from master branch, as we don't have a 2.3.8 release yet

**Comment by mgcrea** [comment]
Just Released 2.3.8! :tada:
