### ISSUE TITLE
select does not honor "track by" properly

### ISSUE THREAD

**Issue by nesler** [mgcrea/angular-strap#2051]
When using native AngularJS select with ng-options, the following is possible when using `track by`:
```
// Model with "complex" objects
$scope.model = [{id: 1, name: 'Test'}, {id: 2, name: 'Hello'}];
// Simple object with the id of the complex object I want to select
$scope.selected = {id: 1};

<select ng-options="item.name for item in model track by item.id" ng-model="selected"></select>
```
That just works.

It does not using bs-options, since a simple `equals` is used to see if `model` contains `selected`, when it should see if `model` contains `item.id` (to simplify a lot!)

Is this a known issue, something that can be implemented, or not a priority?

**Comment by DaleWebb** [comment]
The `bs-options` is a custom written watch, so I guess the `track by` wasn't a requirement at that time.

I don't believe anyone has requested the functionality of `track by` before here.  I will put this as review-future incase that something like this pops up again.

In the meantime, I would suggest pre-populating the value of `$scope.selected` by getting the whole, original object from `$scope.model` by looping through or maybe using `$scope.selected = _.findWhere($scope.model, {id: 1});` (if you're using underscore in your project).

**Comment by nesler** [comment]
Yea, I had to resort to that (fortunately, I already knew what the selected object would be), but it's a lot more convenient to do the same way as original `ng-options` when using `track by` ;)

**Comment by DaleWebb** [comment]
Yeah, with a similar name it would seem like you could use all the features of ng-options in bs-options.  I've added this as a review-future for a feature in the future.

If you put 'item.id as item.name for item in items', you should be able to make $scope.selected = 1;
