### ISSUE TITLE
Typeahead does not accept value with id 0

### ISSUE THREAD

**Issue by kanikagupta13** [mgcrea/angular-strap#2053]
Hi,

While working with typeahead I came across the issue that if it has an object with id 0, then it is not able to select that object if I am trying to set the model value from controller. I also tried it on plunker and it gave the same error. Due to this, the required validation is also failing on it. Following is the plunker that I have created:

http://plnkr.co/edit/l34zB6?p=preview

In this I modified icons list to have id's and initialized the model to id 0 by default. As you can see, it does not select the value in the list.

If I repeat the above process with id 1, then it works fine. Please find the update plunker with updated value below:

http://plnkr.co/edit/eqmBWy?p=preview

**Comment by stevehipwell** [comment]
+1

**Comment by DaleWebb** [comment]
Thanks @kanikagupta13, it looks like [this line](https://github.com/mgcrea/angular-strap/blob/master/src/typeahead/typeahead.js#L286) is causing the issue.  Where the `modelValue` is 0, it will not populate the typehead view.

Submitting a fix and pull request now
