### ISSUE TITLE
Translate Select lable

### ISSUE THREAD

**Issue by h6784rfg6** [mgcrea/angular-strap#2055]
Hi,

I am trying to solve a translation problem. Image you use your example in an app
```
$scope.selectedIcon = "";
$scope.selectedIcons = ["Globe","Heart"];
$scope.icons = [{"value":"Gear","label":"<i class=\"fa fa-gear\"></i> Gear"},{"value":"Globe","label":"<i class=\"fa fa-globe\"></i> Globe"},{"value":"Heart","label":"<i class=\"fa fa-heart\"></i> Heart"},{"value":"Camera","label":"<i class=\"fa fa-camera\"></i> Camera"}];
```

How can it be possible, to translate the text (Gear, Globe, Heart ...) in the lable variable?

**Comment by DaleWebb** [comment]
Which library are you using for translation?

**Comment by h6784rfg6** [comment]
I use angular translate and I already managed to solve the problem. I close it here.

**Comment by gatperdut** [comment]
how did you solve it exactly?
