### ISSUE TITLE
Typeahead Watch Options

### ISSUE THREAD

**Issue by stevehipwell** [mgcrea/angular-strap#2056]
The typeahead does not currently support watching options that come from a function. I don't understand why this check is required when a property getter is a function in its own right? The use case that I have is that we have function to load the options that is memoized, at the present I need to write a custom directive to trigger a model change to get this to work correctly.

Please can the unnecessary ignoring of functions for watch options be removed even if we have to provide an extra attribute to allow it to watch functions.

**Comment by DaleWebb** [comment]
Are you referring to this line, https://github.com/mgcrea/angular-strap/blob/master/src/typeahead/typeahead.js#L245 where function parentheses are removed from the `bs-options`?
