### ISSUE TITLE
Select placement set to top when placement option is empty string

### ISSUE THREAD

**Issue by joelwkent** [mgcrea/angular-strap#2057]
Using the placement option on a select, if the placement option is set to an empty string the the select placement is "top" whereas I thought it would default to bottom-left which is the default placement

`<button type="button"
  class="btn btn-default"
  data-placement=""
  ng-model="selectedIcon" 
  data-html="1"
  bs-options="icon.value as icon.label for icon in icons"
  bs-select>
    Action <span class="caret"></span>
</button>`

Example:
https://plnkr.co/edit/GHkwdjvNKOCTuJM0nwuj

**Comment by DaleWebb** [comment]
Looks like it's taking the default position from `bs-tooltip` rather than its own defaults!
