### ISSUE TITLE
Can typeahead display the result as partial match?

### ISSUE THREAD

**Issue by suteec** [mgcrea/angular-strap#2058]
I'm having and issue with angular-strap typeahead as the plunker

http://plnkr.co/edit/v2BdeoqNFLJV4QRkXYxC?p=preview

In the Address (async via maps.googleapis.com) input text ,

I'm filled "bangkok, thailand" the result displaying correctly.

Anyway if I filled "Thailand bangkok" there're no result even in the console log return result correctly 

Can I edit the matching function or override somewhere to display all the returned result?

Thanks,

**Comment by DaleWebb** [comment]
#2059

**Comment by DaleWebb** [comment]
I think this is related to #2059

**Comment by DaleWebb** [comment]
@mgcrea Looks like the `bsAsyncFilter` is causing this behaviour.  Is that right?

**Comment by DaleWebb** [comment]
@suteec You could create a custom filter which just returns all of the results, then pass the name of that filter in through the `data-filter=""` attribute to your `bs-typeahead` element.  That should return all of your results.

**Comment by suteec** [comment]
I've done by override the bsAsyncFilter

    function CustomTypeaheadFilter ($filter)  {
        return function(array, expression, comparator) {
       
      if(array && angular.isFunction(array.then)) {
        return array.then(function(results) {
            console.log(results);
         // return $filter('filter')(results, expression, comparator)
         return results;
        });
      } else {
        //return $filter('filter')(array, expression, comparator);
        return array;
      }
        }
      }

But I saw the data-filter="false" committed now, this will helpful!!!
Thank you,
Sutee
