### ISSUE TITLE
Typeahead, support for full text search

### ISSUE THREAD

**Issue by signalkuppe** [mgcrea/angular-strap#2059]
Maybe i'm doing something wrong, but I can't figure out how to search for plurals
If I search for "tables" I can see the matched results in the response from the server, but the typeahead doesn't display the results since the document found contains the word "table".
Typeahead seems to filter the results matching the $viewValue.
Is there a way to avoid this?

Thanks!

**Comment by DaleWebb** [comment]
Hmm, this shouldn't be the case, as `bs-typeahead` basically just allows a dropdown to show results.  Whatever those results are is based on the array you return from `$http` call.

Could you show me the function that is meant to return the results and the HTML element that `bs-typeahead` is connected to?

**Comment by DaleWebb** [comment]
This might be to do with the `$filter` that `bs-typeahead` has called `bsAsyncFilter`. https://github.com/mgcrea/angular-strap/blob/master/src/typeahead/typeahead.js#L186

**Comment by DaleWebb** [comment]
@signalkuppe You could create a custom filter which just returns all of the results, then pass the name of that filter in through the `data-filter=""` attribute to your `bs-typeahead` element.  That should return all of your results.

**Comment by signalkuppe** [comment]
Thanks Dale for your reply!
I'll give it a try.
