### ISSUE TITLE
Number of open and unanswered issues here is quite scary.

### ISSUE THREAD

**Issue by mnemanja** [mgcrea/angular-strap#2060]
What would be the reason for 452 unresolved issues? Was I really mistaken when I wrote this? https://github.com/mgcrea/angular-strap/issues/1991

Soon I'll be starting a new project, and I'm reviewing if angular-strap is a viable option.

In this project I'm using it for 3 modules out of 7 in total: `modal`, `tabs`, `alert`, where as the remaining 4 modules I've used from `angular ui bootstrap` project just because those modules weren't satisfactory here. Main reason why I've used other library is because of the either API and mostly because of the callbacks.

Hope things get better here. Best of luck @mgcrea.

**Comment by mgcrea** [comment]
@mnemanja I get your concern, I'm stil actively merging acceptable PRs (with test-case and unit-tests) so I'd say the project is still maintained. However clearly it's in maintenance mode. I haven't built and angular v1 app for a few months now, and I don't plan to write in the foreseeable future, for me it's time to move on.

But I'll be glad if the project can still live on, being useful to other people, and I'll keep merging PRs to make sure it stays alive. There is a lot of work to triage/close issues and new maintainers are always welcomed as collaborators to help.

**Comment by DaleWebb** [comment]
I'm happy to help in any way I can

**Comment by mgcrea** [comment]
@DaleWebb I've added you to the list of collaborators, feel free to tag/triage/close any issue/pr. Just don't merge/push any code in the master branch. Thanks!

**Comment by mnemanja** [comment]
@mgcrea Thanks for the update, and best of luck.

**Comment by DaleWebb** [comment]
@mgcrea Thanks, I'll limit myself to answering and handling issues for now
