### ISSUE TITLE
Popover doesn't fetch new HTML with dynamic templateUrl

### ISSUE THREAD

**Issue by SHDavies** [mgcrea/angular-strap#2066]
I'm using dynamic templateUrls on ng-repeated popovers like so:

`<li ng-repeat="field in fieldOptions | filter : search | orderBy:'displayName' track by $index" 
      data-template-url="scripts/popovers/{{ field.template }}.html" data-html="true"
      data-placement="{{ field.dataPlacement }}" data-trigger="hover" bs-popover>`

When `search` changes, the templateUrl values are correct for each filtered `field`, but the actual HTML that is displayed in the popover is the HTML at the templateUrl for the `field` that was originally at that position in the ng-repeat.

**Comment by DaleWebb** [comment]
Could you create a plunkr to reproduce this?
