### ISSUE TITLE
How to restrict the width of tooltip 

### ISSUE THREAD

**Issue by stanleyxu2005** [mgcrea/angular-strap#2070]
I found the width of a tooltip is random. If I have a long text, it might show in one line which will occupy 50% page width, sometime it might break into multiple lines which will occupy 20% page width. Is there anything I've missed to configure this properly. Thanks

**Comment by DaleWebb** [comment]
I think the way to do this is via CSS.  As this follows Bootstrap's css styling, Angular-Strap doesn't modify the look of elements (like tooltips) by default.

**Comment by stanleyxu2005** [comment]
Really? Okay. I think the width is random. Anyway thanks for the reply.
