### ISSUE TITLE
Tooltip's viewport does not recognize right padding

### ISSUE THREAD

**Issue by stanleyxu2005** [mgcrea/angular-strap#2071]
I have set

```
  // configure angular-strap
  .config(['$tooltipProvider', function($tooltipProvider) {
    angular.extend($tooltipProvider.defaults, {
      viewport: {
        selector: 'body',
        padding: 20
      }
    });
  }])
```

If I have a tooltip at screen left (`<div bs-tooltip="foo" placement="top"><div>`), I can clearly see a 20px padding to the screen left edge. But if the tooltip text is extremely long, the padding to the screen right edge is 0. Is it a bug?

**Comment by DaleWebb** [comment]
Could you attach an image of this?

Thanks
