### ISSUE TITLE
minuteStep not working on mobile

### ISSUE THREAD

**Issue by sakshigargit15** [mgcrea/angular-strap#2075]
Hi,

I am using minuteStep in the project. It is working fine on web but on mobile it is not using minuteStep either it showing all the values of minutes.

**Comment by DaleWebb** [comment]
Which mobile browser are you using?

I just tried on Safari and Chrome on the iPhone 6S and the behaviour is to fall back to native by default.  Are you not using the native input for mobile?

Can you attach a screenshot of this?
