### ISSUE TITLE
Typeahead: call function on selection

### ISSUE THREAD

**Issue by spencerwi** [mgcrea/angular-strap#2080]
When a value is selected from a typeahead, it would be nice to be able to call a function (e.g. `on-change="ctrl.fetchData($selection)"` distinct from a simple ng-change function (which would trigger on every keypress).

For example, I have a project where the typeahead is used as a entry/search field across product codes. I want to allow people to manually enter a product code, but when a value is selected from a set of "known" product codes that populates the typeahead's list, I want to be able to fetch more details about the "known" product.

In a single page, there may be anywhere from 1 to 50 of these product code fields, so to go with an event-listening approach would mean that not only would I have to become dependent on injected `$scope` (which harms migration-readiness to Angular2 in my app and [diverges from Angular best practices](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y030)), but I also would have to write quite a bit of boilerplate code to identify _which_ typeahead triggered the event and thus _which_ backing model should be updated with _what_ new value.

**Comment by DaleWebb** [comment]
So when a typeahead option is selected, you want `ctrl.fetchData($selection)` to be fired?

Would a event be sufficient to satisfy the usecase?  So rather than putting your function call in the attribute, you can listen to an event fired by the typeahead and you would do: 

```javascript
...
$scope.$on('typeahead.selected', $scope.fetchData);
...
```

**Comment by spencerwi** [comment]
In a single page, there may be anywhere from 1 to 50 of these product code fields, so to go with an event-listening approach would mean that not only would I have to become dependent on injected $scope (which harms migration-readiness to Angular2 in my app and diverges from Angular best practices), but I also would have to write quite a bit of boilerplate code to identify which typeahead triggered the event and thus which backing model should be updated with what new value.

**Comment by DaleWebb** [comment]
Sorry, I should learn to read the whole thing...

You can attach the `data-prefix-event=""` attribute and give each field a specific name.

**Comment by spencerwi** [comment]
Yeah, I assumed that was possible (otherwise the boilerplate code wouldn't be annoying boilerplate but would instead be giant horrible tightly-coupled DOM-querying code :stuck_out_tongue: ).

Still means that instead of adding a single attribute in my DOM that calls a controller function, I need to inject `$scope`, set up a listener on it, build a giant switch-case (or some other prefix-to-context-data mapper), _then_ call the function I was going to write in the first place.

As my team is evaluating a migration to Angular2, introducing new dependencies on `$scope` are rightly to be resisted, so a solution that is simpler and doesn't require a new usage of practices that are becoming deprecated would be preferable.

**Comment by DaleWebb** [comment]
Okay, either that or you would end up with 1 to 50 event listeners!

It makes sense to have that event function specified as an attribute.  So I would agree.  Do you have a solution for yourselves in the meantime? I was thinking that you could add a directive with the same name and higher priority and overwrite the `$typeahead.select` function.

**Comment by spencerwi** [comment]
In the meantime I've just gone with a separate button having an `ng-click` to fire off the search manually. It's not ideal, but it's on a power-user screen, so some friction in the near-term is okay.
