### ISSUE TITLE
Having trouble with $tooltip with ui-bootstrap

### ISSUE THREAD

**Issue by rcholic** [mgcrea/angular-strap#2083]
I am trying to use the `$popover` server in angular bootstrap, but I encounter the following issue. From my search on the internet, I found that the issue is caused by the conflicting name `$tooltip` being used by ui-boostrap same time. I have checked the issue #826, and the solution seems to be renaming `$tooltip` to `$bsTooltip`.

**Errors:**
```
angular.js:12783 TypeError: Cannot read property 'toLowerCase' of undefined
    at TooltipFactory (angular-strap.js:45)
    at ui-bootstrap-tpls.js:5834
    at Object.invoke (angular.js:4560)
    at angular.js:7359
    at forEach (angular.js:341)
    at Object.<anonymous> (angular.js:7357)
    at Object.invoke (angular.js:4560)
    at Object.enforcedReturnValue [as $get] (angular.js:4412)
    at Object.invoke (angular.js:4560)
    at angular.js:4377
```
I tested the renaming and it works in my local machine, however, our project/CI environment uses `bower` to install the dependencies for each build, and I don't think renaming the `$tooltip` in our CI environment is an easy option. So I am wondering if such renaming solution has been incorporated in the official release of your bower module. 

Thanks

**Comment by DaleWebb** [comment]
Can you only load the modules that you need from ui-bootstrap, so that you don't load the tooltip?

**Comment by rcholic** [comment]
@DaleWebb , yes. Below is what I have loaded from ui-bootstrap, but the problem persists:

```
'ui.bootstrap.modal',
        'ui.bootstrap.datepicker',
        'ui.bootstrap.accordion',
        'ui.bootstrap.buttons',
        'ui.bootstrap.typeahead',
        'ui.bootstrap.pagination',
        'ui.bootstrap.alert',
```

**Comment by mgcrea** [comment]
@rcholic You can use the `compat` build to address this specific issue: https://github.com/mgcrea/angular-strap/blob/master/dist/angular-strap.compat.js
