### ISSUE TITLE
Up and down keys not working as expected in timepicker in version 2.3.7

### ISSUE THREAD

**Issue by JaiL81** [mgcrea/angular-strap#2086]
Hello,

I am using timepicker and I have seen an strange behavior in tumepicker directive when using up/down arrow keys. My expectation is that the up/down arrow key works the same way the arrow up/down button works, this is adding/subtracting hours/minutes. 

However they work the other way around, up arrow key subtracts and down arrow key adds. I have checked the code and yes, that's the case and it looks weird for me, does it have any explanation? and is it configurable in some way?

I am using AngularJS 1.4.9 and angular-strap 2.3.7.

Thanks and best regards.
Jaime

**Comment by DaleWebb** [comment]
Hi @JaiL81,

The up and down is to navigate the UI of the timepicker, rather than thinking about adding and subtracting.

This behaviour isn't configurable.

**Comment by JaiL81** [comment]
Hi @DaleWebb ,

Thanks for your quick response. But don't you think that this behavior can be a little bin confusing for the user? If you have a timepicker with a length = 1 a and the arrow-behavior = picker, the user will see just one row in the UI tooltip and both actions of the up arrow and up key will behave in a different way and I as a user I would expect that both actions behave the same way, don't you think it would be a good feature that this would be at least configurable?

Thanks and best regards.
Jaime

**Comment by DaleWebb** [comment]
Hmm, I'm not quite sure what you mean.  I think the arrows are for skipping sections of the numbers, whereas the keys are for selection.

**Comment by JaiL81** [comment]
Hi @DaleWebb ,

Maybe with this plunkr I can explain myslef better: http://plnkr.co/edit/6NVx3OqpK3J4PcK5ce2S?p=preview

In this example extracted form the documentation you can see a timepicker with length = 1, and I think that a normal user would expect that in this case the up arrow button and the up arrow key behaves the same way, don't you think?

Thanks and best regards.
Jaime

**Comment by DaleWebb** [comment]
Ah! I see.  I wasn't aware of the `data-arrow-behaviour="picker"` attribute. 

Yes, you're right, this behaviour should be reversed.
