### ISSUE TITLE
No longer able to set bsActivePane in controller constructor

### ISSUE THREAD

**Issue by hackel** [mgcrea/angular-strap#2091]
I used to be able to set the active tab by simply setting `this.activeTab = 'tabName'` from my indexCtrl constructor.  With a recent update (I'm not sure exactly when), this is no longer working.  I have:
`<div bs-tabs bs-active-pane="indexCtrl.activeTab">`
If I log this.activeTab in my constructor, I see that it is changed to what I want, but then gets changed back to the default automatically somehow.

Were there any changes made recently that might have caused this regression?  I've double-checked that I'm not setting it anywhere else in my code that can find.

Note that if I set indexCtrl.activeTab _later_, the tabs switch just as they are supposed to.  It's only after the controller constructor that it gets overwritten.

Edit: I did upgrade Angular from 1.4.10 to 1.5.3 recently, could this possibly be related?  Also, I'm using angular-strap 2.3.7.

**Comment by hackel** [comment]
I was finally able to work around this issue by setting this.activeTab inside of a `$timeout(fn, 0)`.  I don't know whether this is the intended behaviour or if it's still a bug, but that still feels a bit clunky to me.

**Comment by DaleWebb** [comment]
Could you make a plunkr for this please?

**Comment by hackel** [comment]
I went through all the trouble of making this, but so far I haven't been able to figure out how to reproduce my issue...seems to be working fine.  I'm setting the activeTab with a ui.router query parameter, so perhaps the cause lies there, I'm not sure.

https://plnkr.co/edit/p4TImIyg803bMDh5Q1Z6

**Comment by DaleWebb** [comment]
Ah okay, I guess we can't see without the plnkr.  What version of Angular-strap were you using when this was working?

**Comment by hackel** [comment]
Unfortunately I don't know when it stopped working.  I try to check some old versions and see if I can narrow it down.

I tried updating the Plunker to more closely reflect what I'm doing with ui-router, but it still works perfectly.
https://plnkr.co/edit/i4VSbco6vkwSITyqGx3C?p=preview

**Comment by 1Jesper1** [comment]
@hackel Thanks for the fix!
