### ISSUE TITLE
datePicker start-date attribute not updated dynamically

### ISSUE THREAD

**Issue by Trial-In-Error** [mgcrea/angular-strap#2094]
Datepickers with a dynamically bound data-start-date do not update when the referred-to variable changes.

See [this plunkr](http://embed.plnkr.co/gNbSYxiznNXycmZPCean/), editable [here](http://plnkr.co/edit/gNbSYxiznNXycmZPCean?p=preview).

If the startDate is defined initially, it works correctly, but any change after the datepicker's instantiation is not seen. 

Is this intended behavior? Additionally, is there a convenient / recommended way to delete and recreate the datepicker to work around this behavior?

Thanks!

**Comment by DaleWebb** [comment]
Yes this is the intended behaviour. Attributes prepended with `data-` take the value, the `bs-` prepended attributes bind to the variable.
