### ISSUE TITLE
Popover with another popover or aside - hide issue

### ISSUE THREAD

**Issue by balajeek** [mgcrea/angular-strap#2101]
I have a popover open with a click of a button, then inside the popover there is a 'Add' button that opens another popover.  This all works fine but when i close one both are closed.  I have ng-click="$hide()" in the 'Close' button on both the popovers.  What i like is it should close only the popover that i press close.

Same issue again, a link inside a popover opens aside.  The aside panel show behind the popover and clicking close on the popover also closes the aside panel.

any help would be appreciated. thanks.

**Comment by balajeek** [comment]
Also this is how i call:

<button` type="button" title="Seats" class="btn btn-primary dropdown-toggle"
container="body" placement="bottom" id="POP1"
data-content="{{aSeats}}" data-template-url="popoverSeats.tpl.html"
animation="am-flip-x" data-auto-close="1" bs-popover>
</button>

And inside the popover template, i have close button like this:
<button type="button" class="btn btn-danger" ng-click="$hide()">Close</button>

**Comment by DaleWebb** [comment]
Could you create a plunkr for this?

**Comment by balajeek** [comment]
First time tried to create plunkr and i did the best i could, here it is
http://plnkr.co/edit/LSnCsf6eSjR7asbqjPgB

Click on the button to popver, then click on 'Show slide'.
What i expect is the slide open hiding the popover, but in my case the slide open behind the popover and you try to close the popover it closes both popover and slide.

**Comment by balajeek** [comment]
Any fix?
