### ISSUE TITLE
not able to type 1, e, y, o and z in bs-select , if i use type in input tag for making it searchable dropdown

### ISSUE THREAD

**Issue by sahilosheal** [mgcrea/angular-strap#2102]
* angular-strap
 * @version v2.3.8 - 2016-03-31
not able to type 1, e, y, o and z in bs-select , if i use type in input tag for making it searchable dropdown
 in source code of bs-select

line# 1617
due to method $select.$onKeyDown
test link: [plunker](http://plnkr.co/edit/kXzZVJMajT0kwiocom92?p=preview)

it is checking keyCode with regex
[if (!/(9|13|38|40)/.test(evt.keyCode)) return;](url)

i think there should be better handling of this as it is restricting me to use many of functionalities.
 instead of regex you can do exact matching with keyCode

**Comment by DaleWebb** [comment]
Why are you not using `bs-typeahead` for this? The `bs-select` is a dropdown, whereas the typeahead module seems to be the most appropriate for items being searchable

**Comment by sahilosheal** [comment]
but i need a SEARCHABLE dropdown, and i can not search in bs-select

**Comment by DaleWebb** [comment]
Re-read my previous comment.  Use `bs-typeahead`.
