### ISSUE TITLE
Plunker examples not working

### ISSUE THREAD

**Issue by mickodo** [mgcrea/angular-strap#2104]
There seems to be an issue with the CDN serving the Plunker examples - from the web console (the GET's below all result in 404 not founds:

(index):15 GET http://cdn.jsdelivr.net/angularjs/1.5.3/angular-sanitize.min.js 
(index):14 GET http://cdn.jsdelivr.net/angularjs/1.5.3/angular-animate.min.js 
(index):13 GET http://cdn.jsdelivr.net/angularjs/1.5.3/angular.min.js 
angular-strap.js:11 Uncaught ReferenceError: angular is not defined(anonymous function) @ angular-strap.js:11(anonymous function) @ angular-strap.js:4338
angular-strap.tpl.js:10 Uncaught ReferenceError: angular is not defined(anonymous function) @ angular-strap.tpl.js:10(anonymous function) @ angular-strap.tpl.js:43
angular-strap.docs.tpl.js:10 Uncaught ReferenceError: angular is not defined(anonymous function) @ angular-strap.docs.tpl.js:10(anonymous function) @ angular-strap.docs.tpl.js:31
app.js:1 Uncaught ReferenceError: angular is not defined

I've seen this on multiple networks. The main angular-strap page examples all work fine.

Looking at http://www.jsdelivr.com there does not seem to be any angularjs/1/5/3 files.

**Comment by jimaek** [comment]
1.5.5 is now live  http://cdn.jsdelivr.net/angularjs/1.5.5/angular-sanitize.min.js

**Comment by mickodo** [comment]
The Plunker examples use 1.5.3 explicitly it seems, so are still creating 404's at the moment.

**Comment by jimaek** [comment]
Not sure why. jsDelivr never had 1.5.3 hosted

**Comment by nrcssilos** [comment]
Is this prblem plunker - angularjs solved?  I cant find one example that could work  (Oct 6, 2016)
