### ISSUE TITLE
Popover templateUrl not working

### ISSUE THREAD

**Issue by mnemanja** [mgcrea/angular-strap#2105]
If I include the partial with contentTemplate, that works, but then I have to define the partial in an inline script... that would be the only one in the application.

So I would prefer the templateUrl, but providing the path to that property simply doesn't work. It shows the default popup template, as if the path is not correct.

**Comment by DaleWebb** [comment]
Could you provide a plunkr example where this doesn't work

**Comment by mnemanja** [comment]
Hi @DaleWebb,
I'm no longer actively working on the project using the angular-strap so I suggest closing this for now.
