### ISSUE TITLE
Get Value from modal service after close

### ISSUE THREAD

**Issue by tianxu0836** [mgcrea/angular-strap#2108]
I'm using the modal service

What I want to do is pass the value to the modal controller and after user make some changes in the modal, return the object back to after the modal is closed.

I've been search this for the whole day, all I found is pass value to modal controller

Pass value into modal is easy and every modal server out there can do this.

However, why there is no solution to get value from the modal controller?

**Comment by DaleWebb** [comment]
Why do you mean? Is this modal created via the directive or service?

**Comment by tianxu0836** [comment]
Modal service not the directive.

**Comment by DaleWebb** [comment]
Are you attaching a controller to the service function? e.g. `$modal({..., controller: function(){}})`

You could attach a scope instead? or use the `controllerAs` option to bind the scope to `this` of the controller, then get your value.
