### ISSUE TITLE
Angular 2 

### ISSUE THREAD

**Issue by nicklasb** [mgcrea/angular-strap#2110]
Hi,

In #1766, it was mentioned that an Angular 2 version of this component is being planned.
There is a huge momentum behind A2, and I we will make an A2/Typescript version of [angular-schema-form-dynamic-select](https://github.com/OptimalBPM/angular-schema-form-dynamic-select) which is based(amongst others) on this library.

Are there any more concrete plans for angular-strap migration?

**Comment by DaleWebb** [comment]
Discussions around Angular2 are here: #1850, #2016 

I don't believe there has been any work on this, or any other discussion on the matter.
