### ISSUE TITLE
Error removing typeahead on change (e.g. on-select) "Cannot read property 'selectMode' of null"

### ISSUE THREAD

**Issue by melcher** [mgcrea/angular-strap#2112]
Plunkr: 
http://plnkr.co/edit/hujwUy4e5spCiTXiLqTu?p=preview

Bug:
Using a bs-typeahead with asynchronous results in a way that removes the bs-typeahead from the dom when a selection is made throws 'Cannot read property 'selectMode' of null' from https://github.com/mgcrea/angular-strap/blob/master/src/typeahead/typeahead.js#L276. Expected behavior would be that it should not throw an exception.

This comes up frequently for us as we often hide the input field once a selection is made.

For synchronous selection, there is a different error thrown with this pattern, but using a $timeout works around the exception.

The reason is the model watch is firing after the $destroy callback runs and sets options = nil... so presumably this could be fixed by adding a `if(!options) { return; }` or even just `options && options.selectMode` to https://github.com/mgcrea/angular-strap/blob/master/src/typeahead/typeahead.js#L276

**Comment by DaleWebb** [comment]
PR?

**Comment by xoneill** [comment]
I am getting the same issue. Plz fix
