### ISSUE TITLE
Question about $modal and onHide attribute.

### ISSUE THREAD

**Issue by NicolasDubois** [mgcrea/angular-strap#2113]
Hello everybody,
I use the modal service and I try to invoke a function when closing the modal with the parameter onHide.
```
var _modal = $modal({
                templateUrl: "app/pages/fee/modals/historic/fee.historic.html",
                controller: "HistoricController",
                controllerAs: "vm",
                keyboard: true,
                show: false,
                onHide: function() {
                    console.log("Close !");
                },
                onShow: function() {
                    console.log("Open !");
                }
            });
 _modal.$promise.then(_modal.show);
```
But when I close my modal nothing happens, I do not see any of my log in the console.
Thank you in advance to any one who may be able to give me some ideas !

**Comment by DaleWebb** [comment]
Does it log to the console when the modal is opened?

**Comment by NicolasDubois** [comment]
Nothing, there's no log in the console.

**Comment by DaleWebb** [comment]
Just created a plunkr to reproduce.  It seemed to work for me.

http://plnkr.co/edit/kuTCSgScekpTXzNm5TFL

**Comment by NicolasDubois** [comment]
Indeed it works with a plunkr, but not in my project ... I started watching the angular-strap files and I have a stupid question.
In the angular-strap.js of the plunkr I have the function

```
function leaveAnimateCallback() {
          scope.$emit(options.prefixEvent + '.hide', $modal);
          if (angular.isDefined(options.onHide) && angular.isFunction(options.onHide)) {
              options.onHide($modal);
          }
          bodyElement.removeClass(options.prefixClass + '-open');
          if (options.animation) {
              bodyElement.removeClass(options.prefixClass + '-with-' + options.animation);
          }
}
```
And I think with the part that interests me !
```
 if (angular.isDefined(options.onHide) && angular.isFunction(options.onHide)) {
            options.onHide($modal);
          }
```
But in the angular-strap.js in my project I have just that.
```
function leaveAnimateCallback() {
          scope.$emit(options.prefixEvent + '.hide', $modal);
          bodyElement.removeClass(options.prefixClass + '-open');
          if (options.animation) {
            bodyElement.removeClass(options.prefixClass + '-with-' + options.animation);
          }
        }
```

I uninstall and reinstall the bower components, I checked the bower.json and this is the version 2.3.8 of angular-strap. Did I miss something?

**Comment by DaleWebb** [comment]
That is weird!  The commit for this feature was by me - https://github.com/mgcrea/angular-strap/commit/ce5047257114ed863cd3f2dbe638143821255420

I think what has happened is that the commit didn't make it into the `2.3.8` release but it is on the `master` branch.  The docs page on http://mgcrea.github.io/angular-strap is pulling information from the `master` branch - so the documentation that I added for the feature is there, but the latest released referenced is `2.3.8`.

If you use the `master` version of angular-strap, you should be able to use this feature.

**Comment by NicolasDubois** [comment]
I tested it works. Thank you !

**Comment by DaleWebb** [comment]
Great!

**Comment by LennyLip** [comment]
Spending 2 hours to found it. Where i can find min.js dist version of master branch?

**Comment by DaleWebb** [comment]
The `master` branch doesn't have the compiled (dist) files of the src, only the releases (tags) do

**Comment by LennyLip** [comment]
@DaleWebb ok, thank you! 

Now, i'm using 
`tooltip1.$scope.$on('tooltip.show.before', function() {})`
instead
`onShow`
while waiting new release.
