### ISSUE TITLE
Please release 2.3.9

### ISSUE THREAD

**Issue by cudasteve** [mgcrea/angular-strap#2114]
In particular, I could really use the fix in 97697c271ab54feef0032e81a31ef2518a6604d6.

Thanks!

**Comment by DaleWebb** [comment]
There are a few PRs outstanding to be reviewed and merged by @mgcrea, but I don't think @mgcrea has been active on this project for around 18 days.

As that commit is on the `master` branch, you could reference `master` in your version of angular-strap - rather than `2.3.8`.

**Comment by cudasteve** [comment]
Thanks @DaleWebb. Unfortunately, just referencing master won't work as the files in the dist folder aren't updated except during release.

I actually ended up forking, building, and releasing myself for now (https://github.com/cudasteve/angular-strap/releases/tag/v2.3.9-cudasteve), so no pressure from my end anymore.
