### ISSUE TITLE
/modal is out of sync in recent distributed versions

### ISSUE THREAD

**Issue by davidkonrad** [mgcrea/angular-strap#2116]
Hey mgcrea and contributors,

It seems that the modal source is out of sync in the distributed versions (bower, npm). Take a look at the output of a `bower install angular-strap#2.3.8` (or 2.3.7 etc) and compare the source of `/modal` with the current version in master.  

The distributed versions lacks completely support for `onShow`, `onHide` etc, but both the documentation and the source at master include the features.  

The reason for the discovery is this question at SO -> http://stackoverflow.com/q/37464620/1407478 
Have used angular-strap for a long time, I actually believed `onHide` etc was an abandoned idea in angular-strap, since it is not part of native bootstrap. But it turns out that` /modal` in recent versions at bower / npm just is out of sync.

**Comment by DaleWebb** [comment]
Thanks for raising the issue.  The SO was also posted as an issue here.

I will look to see if there is a way to reference the latest release, rather than master for the docs and then propose a solution.

**Comment by kedarv** [comment]
any ETA on this fix?

**Comment by mgcrea** [comment]
There is nothing wrong going on here, the `v2.3.8` source code does not include the `onShow`/`onHide` support that landed in the master ([with this commit](https://github.com/mgcrea/angular-strap/commit/ce5047257114ed863cd3f2dbe638143821255420))  after the release.

You can check the actual source code here:
- https://github.com/mgcrea/angular-strap/blob/v2.3.8/src/modal/modal.js

It will be available with the next patch release (soon).

**Comment by DaleWebb** [comment]
@mgcrea, the `onShow` and `onHide` is documented in the options table here: http://mgcrea.github.io/angular-strap/#/modals
