### ISSUE TITLE
UTC TZ usage

### ISSUE THREAD

**Issue by andreaslarssen** [mgcrea/angular-strap#2118]
The documentation says you can get the datepicker date in UTC rather than local time by using the "timezone" attribute. I can not for the life of me get it working. Does anyone have a working example / plunkr?

**Comment by DaleWebb** [comment]
Can you create a Plunkr with what you are trying to do, then we'll go from there?

**Comment by andreaslarssen** [comment]
Hi.

So, check this out: https://plnkr.co/edit/7NgkGX85k6dvaDm47xvM

If you click the btn after selecting a date, you can see that the date is in local time. I thought that adding data-timezone="'UTC'" would do the trick, but I can not see that the date is any different with or without this attribute. It says in the docs that the value should be a string, but I've tried data-timezone="UTC", and I've tried without the data- prefix to see if that would do it.

What am I doing wrong?

**Comment by andreaslarssen** [comment]
Moved on
