### ISSUE TITLE
In document download v2.3.8 source code is the old version.

### ISSUE THREAD

**Issue by LeeChingYin** [mgcrea/angular-strap#2119]
I download v2.3.8 source code in the document and want to try something about Modal options that are new options.I use options that is onHide, but it is not working.It is ok in plnkr, but local is not working. I try again and again. When i see the source code, i find that the version of the source code is different. Plnkr used is the newest.I guest the source code in the document is not update.You can not found options that onHide, onShow, onBeforeShow, onBeforeHide anywhere.

You can get the new version from here.They  works~!

http://mgcrea.github.io/angular-strap/dist/angular-strap.js
http://mgcrea.github.io/angular-strap/dist/angular-strap.tpl.js

**Comment by DaleWebb** [comment]
This issue has come up a few times, I'm going to see if there is a way to get the docs to reference the current stable version of AngularStrap, rather than `master`.

#2113
