### ISSUE TITLE
Typeahead onSelect doesn't seem to fire when item is selected

### ISSUE THREAD

**Issue by vincentw56** [mgcrea/angular-strap#2121]
Using the bs-on-select with Typeahead doesn't fire when an item is selected.

http://plnkr.co/edit/Gn5g0RNgSP0vq560nWbx

It fires as soon as the page is loaded, but it won't fire after that. Am I doing something wrong?

**Comment by vincentw56** [comment]
This was my fault. I thought this was called like a click function (ng-click). Instead of using:

`bs-on-select = "test()";`

I needed to remove the parenthesis.

`bs-on-select = "test";`

Works great now!

**Comment by jamespsterling** [comment]
@vincentw56 Thanks, I had this issue too.

**Comment by liuhuiiris126** [comment]
Thanks!
