### ISSUE TITLE
bs-datepicker Problem showing wrong date

### ISSUE THREAD

**Issue by adepusai123** [mgcrea/angular-strap#2123]
selected date : 7/24/92,
Showing date: "2092-07-23T18:30:00.000Z" 

I selected Jul 24 1992, its show Jul 23 2092 .
How can i solve this ?

**Comment by piyush-sukhadiya** [comment]
Provide steps to reproduce, plunker or jsfiddle would be better.

**Comment by senthilsendhil** [comment]
https://github.com/mgcrea/angular-strap/issues/2148 , I have rasied same
