### ISSUE TITLE
Data match route equals  "/chatroom/1" ->  "/chatroom/11"  

### ISSUE THREAD

**Issue by hugotown** [mgcrea/angular-strap#2127]
i draw a list dynamically based on chatrooms ID's

when i clicked on chatroom ID 11 also make me  ( chatroom ID 1 ) menu active

Data match route equals  "/chatroom/1" ->  "/chatroom/11"  
make me two menus active
 "/chatroom/1"  active
"/chatroom/11"  active

**Comment by DaleWebb** [comment]
The data-match-route takes a regular expression.  Try putting `$` at the end of the value.
