### ISSUE TITLE
popover position is different when clicking manually vs programmatically 

### ISSUE THREAD

**Issue by takaooo** [mgcrea/angular-strap#2131]
Popovers are appearing in the wrong position when they are triggered by an angular.element(search-term).triggerHandler('click') compared to when clicking it manually. At least when using a popover in an ngTable. 
Please see [this plunkr](https://plnkr.co/ldwuoWNi9DGCk5k73CAp) 
(clicking on the 'show all Host popovers' - which actually triggers a click rather than showing all popovers - makes them appear in a different location vs clicking the table cells)

**Comment by DaleWebb** [comment]
Have you tried adding the popovers via the service, then adding a manual trigger?
