### ISSUE TITLE
bs-enabled displays tooltip when property chain includes undefined,null or is falsey

### ISSUE THREAD

**Issue by mcshaz** [mgcrea/angular-strap#2132]
if an element is similar to

`<a href="#" bs-tooltip bs-enabled="vm.foo.bar" data-title="Hello" data-trigger="hover">Click</a>`

but foo is null or undefined, to my way of thinking at least (and happy to be corrected) the angular way is to NOT have the tooltip enabled

similarly

`<a href="#" bs-tooltip bs-enabled="vm.foo && vm.foo.bar" data-title="Hello" data-trigger="hover">Click</a>`

displays if vm.foo is null or undefined

the way around this at the moment is to use a ternary which directly returns false:
`<a href="#" bs-tooltip bs-enabled="vm.foo?vm.foo.bar:false" data-title="Hello" data-trigger="hover">Click</a>`

thus not high priority, but the expressions would be a lot cleaner if this were fixed.

**Comment by DaleWebb** [comment]
So if the value is null or undefined, then it is being evaluated as true?

Could you create a plunkr for this?

**Comment by mcshaz** [comment]
plunkr is up at [http://plnkr.co/edit/kqdaijN5J8u0vdTMo2vA?p=preview](http://plnkr.co/edit/kqdaijN5J8u0vdTMo2vA?p=preview). as stated it is not really a bug, but anything that is falsey fails to disable the tooltip - it is more unpredicted behaviour, (but I note it should be predicted as the documentation states the attribute must have a value of true/false or 0/1).
