### ISSUE TITLE
Documentation for bs-on-* attributes not clear

### ISSUE THREAD

**Issue by cudasteve** [mgcrea/angular-strap#2133]
I love the addition of the on-\* attributes added in #2082! :)

Unfortunately, when trying to use it, it took me a good bit of debugging all the way down to the source code to figure out that I had to append "bs-" to the beginning because the docs just say onShow, onHide, etc.  I think it would be clearer to put them down as bsOnShow, etc. in the docs.

Or was the idea to have the "bs-" part optional?  Because if so, it currently does not work without the "bs-" part.

I'm happy to make a PR if there's no objections.

**Comment by DaleWebb** [comment]
Ah that sucks! My mistake!

The `bs-*` part is required, so yes the docs should include that.  A PR would be more than welcome! 👍

**Comment by cudasteve** [comment]
Actually wait a minute, is that true though?  I was only using DOM attributes.  If you use the services to build the objects, do you pass onShow or bsOnShow?

**Comment by DaleWebb** [comment]
If you use the services, it's onShow
