### ISSUE TITLE
Last space gets trimmed when typing fast with in asynchronous typeahead

### ISSUE THREAD

**Issue by roelywoely** [mgcrea/angular-strap#2134]
When you type something in an input with an asynchronous typeahead attached to it, then the last space is trimmed when you type the space before the AJAX call completes. This also happens in the live demo: http://mgcrea.github.io/angular-strap/#/typeaheads-examples

Type "street " very fast in the "Address" input, then the last space gets truncated when you type the space before the AJAX call completes. You probably won't see it every time because the Google Maps API responds very fast. But if you limit your internet connection (in Chrome dev tools in the network tab you can do that) then you can properly reproduce this.

I looked at https://github.com/mgcrea/angular-strap/issues/1604 but it seems that the problem isn't fixed.
I also set the "trimValue" option to false but this also doesn't fix the problem.

**Comment by SpoinkyNL** [comment]
This is because the typeahead directive uses ngModel internally. To opt out of this use ```ng-trim="false"``` on the input element you're also applying the typeahead to.

For more info see: https://github.com/angular/angular.js/issues/2010
