### ISSUE TITLE
$tooltip/$popover auto positioning issue

### ISSUE THREAD

**Issue by lucipacurar** [mgcrea/angular-strap#2136]
Take the following plunker from the AngularStrap examples: https://plnkr.co/edit/CnlyhafeLosdKPNH0zPB?p=preview

The only difference from the official example is that I've changed the position of the first popover from "bottom-left" to "auto bottom-left". The end result is that the popover position is changed to bottom-right, which is wrong.

I had a look at the code computing the position:

```
if (/left/.test(originalPlacement) && elementPosition.left - tipWidth < viewportPosition.left) {
    placement = placement.replace('left', 'right');
}
```

In that code `elementPosition.left` is the target element left offset, which is less than 100px because the target element is close to the edge of the viewport, `tipWidth` is about 200px, and `viewportPosition.left` is 0. In this case `elementPosition.left - tipWidth < viewportPosition.left` is `true`, the position is changed to `bottom-right`, even though the popover doesn't go out of the viewport. And, in this case, this will always be `true` unless `elementPosition.left > tipWidth`.

Shouldn't this condition just check that `tipPosition.left` is not smaller than `viewportPosition.left`?

**Comment by DaleWebb** [comment]
Hi, could you write a test that proves this: https://github.com/mgcrea/angular-strap/blob/master/src/tooltip/test/tooltip.spec.js
