### ISSUE TITLE
Model value goes null if you select same value again

### ISSUE THREAD

**Issue by sarfarazansari** [mgcrea/angular-strap#2145]
Hey,
am facing a issue while using `bs-select`,
And I've cross checked on library home page. And it exist in library.

Scenerio: If you select a value and then select again the same value then your model value goes `null`

for more info check screenshots
Before
![image](https://cloud.githubusercontent.com/assets/3416989/17164718/7e8a229c-53e8-11e6-82e7-16c4a98b1118.png)

After click on again selected value
![image](https://cloud.githubusercontent.com/assets/3416989/17164723/89ed4ea2-53e8-11e6-9466-7c10661bd8dd.png)

**Comment by DaleWebb** [comment]
I believe this is a de-select behaviour.  Did this behaviour change from previous versions or is this just something you didn't expect to happen?

**Comment by sarfarazansari** [comment]
Hey @DaleWebb ,
This is just something I didn't expect to happen?

**Comment by DaleWebb** [comment]
There is a option to disable the behaviour through the attributes.  `data-toggle="false"`
