### ISSUE TITLE
datepicker display wrong

### ISSUE THREAD

**Issue by app-lab** [mgcrea/angular-strap#2146]
I use angular-strap 2.3.6, bootstrap 3.3.7, angularjs 1.5.8. when I use datepicker whit "bs-datepicker" directive in a input tag. I displayed wrong. I also try to find the answer on stackoverflow and this repo's issues.I tried add plugin dependency( bootstrap-additions).
My app init use: "var app = angular.module("appNeoBayWeb",["ui.router","mgcrea.ngStrap"]);";
And the html code:
`<input data-model-date-format="yyyy-MM-dd" data-date-format="yyyy-MM-dd" ng-model="data.selectedDate" data-placement="bottom" bs-datepicker placeholder="出生年月" ng-attr-placeholder="出生年月" class="nb-input-padding nb-input-min-width nb-input-normal-height nb-input-bottom-space nb-border-radius" />`

It display like below:
![2016-08-02 09 45 17](https://cloud.githubusercontent.com/assets/17821216/17314454/1c066d66-5897-11e6-8a1f-eab6f9efd4aa.png)

**Comment by app-lab** [comment]
@markbates @dinoboff @joshk @melcher @sh

**Comment by DaleWebb** [comment]
You have a lot of extra CSS classes attached to that element.  Do any of the classes have any styling that refer to child elements? If so, remove it to the point where it looks like normal Angular-Strap, then add the styling back in until you find the problem.

**Comment by vicary** [comment]
This is my version of the prob. same issue, did I miss anything?

I have bootstrap-additions.css linked already.

![screen shot 2017-01-25 at 15 26 22](https://cloud.githubusercontent.com/assets/85772/22281591/a8ba783c-e312-11e6-87e0-047764cda018.png)

**Comment by DaleWebb** [comment]
What is the problem, @vicary?

**Comment by vicary** [comment]
Because it doesn't look the same as live demo, or am I missing the bootstrap theme part of all these?

**Comment by DaleWebb** [comment]
It looks like you have styling on those.  If you inspect the element, the days and are just `.btn` elements, so you have some styling on the `.btn` that is also effecting this.  To isolate that, you can reference the most outer parent class and define the styling with that e.g. `.datepicker .btn {`
