### ISSUE TITLE
Animations aren't working when I use a custom object $modal:

### ISSUE THREAD

**Issue by rafaelss95** [mgcrea/angular-strap#2147]
Well, the problem is that if I use a custom object $modal, like this:

```
$modal({
    title: 'Some title'
    content: 'Some content'
    templateUrl: 'Some template'',
    animation: 'am-flip-x',
    show: true,
    html: true
});
```

The animation won't work. However, it works if I use the modal like this:

`<button type="button" class="btn btn-info btn-xs" data-title="Some title" data-content="Some code" data-template-url="Some template" data-animation="am-flip-x" bs-modal="modal">`

What is happening?

**Comment by DaleWebb** [comment]
Could you paste the actual code that you used?
