### ISSUE TITLE
user change the timezone and date Select Wrongly

### ISSUE THREAD

**Issue by senthilsendhil** [mgcrea/angular-strap#2148]
Hi Demo site, IF i change the time zone to (UTC+13:00) Samoa and if select date and its shows one day less 
![image](https://cloud.githubusercontent.com/assets/3470633/17401016/a7339280-5aa7-11e6-8d1b-f0725f14c4bb.png)

**Comment by adepusai123** [comment]
angular.module('app')
.config(function($datepickerProvider) {
  angular.extend($datepickerProvider.defaults, {
    dateFormat: 'dd/MM/yyyy',
    startWeek: 1
  });
});

Use this .
