### ISSUE TITLE
Modal backdrop does not display when ngView is applied to the body element

### ISSUE THREAD

**Issue by compwright** [mgcrea/angular-strap#2154]
It appears that ngView replaces the body element in the DOM? At any rate, the modal backdrop doesn't show when you have this:

```
<html>
<body ng-view></body>
</html>
```

Setting the backdrop and container options have no effect.

It does work if you don't apply ngView to the body element itself. This is my current workaround:

```
<html>
<body>
  <div ng-view></div>
</body>
</html>
```

It would be nice to have this fixed since this behavior is an inexplicable gotcha that may not be all that uncommon.

**Comment by DaleWebb** [comment]
Plunkr please!
