### ISSUE TITLE
feat(popover): Add bsEnabled (data-bs-enabled in template) option

### ISSUE THREAD

**Issue by matthewdfleming** [mgcrea/angular-strap#2156]
Presently the tooltip has bsEnabled support but no other components do. It is a handy feature. Please migrate it to the other components.

**Comment by DaleWebb** [comment]
Which components specifically?

As some of the components such as bsSelect attaches to a native HTML button, you can use the built-in attribute `disabled="true"` to the same effect - or `ng-disabled`

**Comment by matthewdfleming** [comment]
I was thinking loosely all of the visual window like components that extend from tooltip that are not currently disable-able.. i.e. modal, aside, popover, and possibly collapse.

**Comment by DaleWebb** [comment]
What would it mean to disable a modal, aside and popover?  Those elements would be triggered by something else (e.g. timer, a button).

**Comment by matthewdfleming** [comment]
Same use case as the tooltip. You have the ability to define the tooltip in the partial, and the triggering of the visual is orthogonal to it being 'enabled' or not. So the trigger could be a mouseover but the enabling is dependent upon something else e.g. the user has more work to do in a section.

**Comment by DaleWebb** [comment]
Okay, that makes sense.  I just found the PR that put in the feature so that I could see the conversation around it #1176.

Can you submit a PR for this?

**Comment by matthewdfleming** [comment]
I'll do a PR for each component.. that way we can make sure you like the change before going all in.
