### ISSUE TITLE
Modal - Potential leaking of scopes when show is called multiple times

### ISSUE THREAD

**Issue by michaelfdeberry** [mgcrea/angular-strap#2157]
There are a couple potential issues.
1. The $modal.show function creates a new scope, this scope will exist and continue to execute watchers after the modal is hidden. 
2. It is also possible to leak the scope if you open a modal and then close it and open it again with the show function. If the modal is destroyed the first scope will still continue to exist and execute the watchers. 

However, if the toggle function is used to reopen the modal the first scope will be destroyed. This is a little puzzling since all toggle does is either call hide or show.

This is a pretty rough example, but it should illustrate the issues. The scopes will log the scope id to the console on every digest. 
https://embed.plnkr.co/ToCAMe/

**Comment by DaleWebb** [comment]
If you can fix this, feel free to submit a PR 👍

**Comment by michaelfdeberry** [comment]
@DaleWebb, After looking at it again this is probably me using it other than the way it was intended. I am creating a new modal every time so the previous modal will continue to exist since it wasn't destroyed. 

The scope will continue to exist after the modal is closed, but since destroy is publicly accessible it's probably the users responsibility to clean up after the modal. 

I suppose there is potential to reuse the initial scope if one exist, but if the modal is managed correctly it's not as big of an issue.

**Comment by DaleWebb** [comment]
A similar issue was brought up in the past #1805
