### ISSUE TITLE
bs-select: dropdown-menu is not scrolled with select, when container attribute is defined

### ISSUE THREAD

**Issue by stdemon** [mgcrea/angular-strap#2158]
Assume we have a modal window (bs-modal) with 'modal-body' class attribute {overflow: hidden} and fixed height - content should be scrolled.

.modal-body {
    overflow-x: hidden;
    overflow-y: auto;
    max-height: 80.5vh;
}

When we put bs-select inside such modal, dropdown content visibility is cropped by modal-body div container.

If we apply container attribute into bs-select directive (e.g. data-container = 'body'), issue with dropdown-menu visibility is solved, however any scrolling events do not affect dropdown menu (it stays frozen to the DOM element we append it to),

**Is there any decision to have a possibility to attach dropdown-menu to scrolled element, but have a possibility to see content outside container (e.g. modal-body)?**

**Comment by DaleWebb** [comment]
Would a native HTML dropdown menu have this behaviour?

Are you trying to make the dropdown-menu fixed in the same position on the page?

**Comment by stdemon** [comment]
Yes, it would.

**Comment by DaleWebb** [comment]
Just to reiterate, when you scroll the body of the modal did you want the dropdown-menu to remain in the same initial position?

**Comment by stdemon** [comment]
@DaleWebb, no, it should be bind to select input control and be scrolled with the body of the modal, but its size larger than modal-body, it should be visible above modal.

**Comment by DaleWebb** [comment]
I'm not sure if that would be possible.

A solution that comes to my head would be for the dropdown-menu to watch for the referenced container's scroll event, then update its positioning to match the difference in scroll.  However, I don't believe jqlite can do this (as we don't have a dependency on Jquery for Angular-Strap).

Can you think of a way?

**Comment by DaleWebb** [comment]
I've just been exploring the tooltip class that contains the method of choosing the position of the element.  It has the option of automatically positioning the element via `data-placement="auto"`, by its description, it should position the dropdown in a way so that the contents are visible within the viewport.  I'm not certain if this would help your issue though.

Could you try setting `data-placement="auto"`.

**Comment by Nodarii** [comment]
Hello,

the native select closed on any mouse wheel event, even if it is placed in non scrollable area. I would expect this component behave in the same way

**Comment by DaleWebb** [comment]
I think that behaviour would be browser-dependent

**Comment by Nodarii** [comment]
Is there any w3c standard for such case?

**Comment by DaleWebb** [comment]
https://www.w3.org/TR/html401/interact/forms.html section 17.6 covers `<select>`.

No mention of that behaviour however.  Which makes sense to me, as it would have to cover all different types of devices (e.g. mobile devices with touch screen, touchtable devices).
