### ISSUE TITLE
Typeahead stays open after selecting an item, you need to click again to close it

### ISSUE THREAD

**Issue by robertsaliba** [mgcrea/angular-strap#2159]
The issue exists on the AngularStrap site as well http://mgcrea.github.io/angular-strap/#/typeaheads

Under the Address (async via maps.googleapis.com)

To reproduce it type 1 inside the input 
![1](https://cloud.githubusercontent.com/assets/700796/17702719/073c9e4e-639d-11e6-9bf9-f8849f8e063e.jpg)

then select the item in the dropdown, the dropdown closes and reopen with the selected item, 

![2](https://cloud.githubusercontent.com/assets/700796/17702745/2074d322-639d-11e6-9294-09c830f4953b.jpg)

I think it shouldn't open again
I am using AngularStrap v. 2.3.9 Chrome 51.0.2704.103
Thanks

**Comment by DaleWebb** [comment]
Have you tried to use the `data-auto-select="true"`?

**Comment by DaleWebb** [comment]
Possible link #2160

**Comment by robertsaliba** [comment]
@DaleWebb yes i tried, same problem

**Comment by DaleWebb** [comment]
Which version of Angular are you using?

**Comment by robertsaliba** [comment]
1.5.7

**Comment by DaleWebb** [comment]
It looks similar to this issue: #2160, but the issue didn't exist with Angular 1.5.x
