### ISSUE TITLE
Have to select value twice from drop down [typeahead] for angular 1.2.29

### ISSUE THREAD

**Issue by alimalik91** [mgcrea/angular-strap#2160]
Hi,

I am using angular 1.2.29, and couldn't resolve this issue.
See the plunkr: http://plnkr.co/edit/tCdBGkeEB7frDcKQdJgE?p=preview

In this plunkr, select any value from the "Icon" either by clicking or typing, you'll see you need to select it twice for no reason. If you change to angular 1.5, it will work fine on a single click.
Please resolve this soon :)

**Comment by DaleWebb** [comment]
In the plunkr that you linked, it seems like this issue also exists with Angular 1.5.

**Comment by alimalik91** [comment]
Did you change version of animate and sanitize to 1.2.29 as well?
Maybe when they're all on 1.5 the issue isn't reproducible!

**Comment by DaleWebb** [comment]
Ah, I thought the plunkr was using 1.5. My mistake!

The issue does not exist with 1.5

**Comment by DaleWebb** [comment]
I tried versions 1.4 and 1.3 too, the issue does not exist with those either.

**Comment by robertsaliba** [comment]
if you go on the angulastrap website http://mgcrea.github.io/angular-strap/#/typeaheads, it is using angular v 1.5 and the error is reproducable

**Comment by mihaibogdan10** [comment]
This is still an issue on angular v1.6.4.
