### ISSUE TITLE
bs-on-select for typeahead fires when page is loaded

### ISSUE THREAD

**Issue by lsimmons2** [mgcrea/angular-strap#2163]
Hi, I'm using `bs-on-select='myFunction()'` as an attribute for a typeahead which is repeated with `ng-repeat`. Instead of `myFunction()` being fired when I select something from any of the typeaheads, it is fired 8 times (the number of typeaheads in `ng-repeat`) when the page starts.

Any idea why this is happening?

Thanks!

**Comment by DaleWebb** [comment]
The attribute gets evaluated when the directive is compiled.  So by referencing the function with the parenthesises, it is invoking the function.

Instead you should just put a reference to the function e.g. `bs-on-select="myFunction"`

**Comment by lsimmons2** [comment]
Ok, so I'm using the typeahead in a nested `ng-repeat` and when something is chosen from the typeahead I want to pass the index of the typeahead in both the parent and the child `ng-repeat` and also the `$scope` object of the typeahead in the nested `ng-repeat` - the scope object being the fourth argument, `elem` from the solution given in this forum: https://github.com/mgcrea/angular-strap/issues/81. Is there a way to do that?
