### ISSUE TITLE
NuGet Package is on version 2.3.1

### ISSUE THREAD

**Issue by bryantlikes** [mgcrea/angular-strap#2170]
Any chance we could get an update to the Nuget package? 

https://www.nuget.org/packages/angular-strap/

Thanks!

**Comment by geskill** [comment]
@khellang, is there a chance for updates soon?

There is some service called [MyGet](https://www.myget.org/) doing this automatically. It is free for open source projects. Some more info [here](https://weblogs.asp.net/bsimser/automatically-publishing-nuget-packages-from-github) and [here](http://stackoverflow.com/questions/22707731/how-to-auto-publish-my-github-branch-on-nuget).

**Comment by khellang** [comment]
Pushed a 2.3.9 version. I'm not sure how much time I have to look into automating this. Especially pusing it to NuGet.org.
