### ISSUE TITLE
Popover does not appear on demo page when using $popover service

### ISSUE THREAD

**Issue by Jokero** [mgcrea/angular-strap#2179]
You can check it here http://mgcrea.github.io/angular-strap/#/popovers-examples

Chrome 53.0.2785.116

```
TypeError: e.preventDefault is not a function
    at F.toggle (angular-strap.js:4440)
    at angular.js:15961
    at n.$eval (angular.js:17229)
    at n.$digest (angular.js:17045)
    at n.$apply (angular.js:17337)
    at HTMLButtonElement.<anonymous> (angular.js:25023)
    at Qf (angular.js:3456)
    at HTMLButtonElement.d (angular.js:3444)
```

**Comment by LennyLip** [comment]
+1 no errors, last Firefox, Chrome, Opera, Explorer 11

**Comment by cycold** [comment]
Yeah, there is no `preventDefault method` in  `evt`  see below pic 
```
if (evt) {
     evt.preventDefault && evt.preventDefault();
 }
```
![image](https://cloud.githubusercontent.com/assets/2446601/22924244/5d42fbc2-f2df-11e6-85f3-610bdf2cb2bd.png)

**Comment by xeroxoid** [comment]
Hi all, as I do not see the pull request being merged any time soon, a workaround is to use:

```myPopover.toggle();```

i.e. directly instead of after the promise as the example

```myPopover.$promise.then(myPopover.toggle);```
