### ISSUE TITLE
Datepicker disabled dates fires validation on mobiles

### ISSUE THREAD

**Issue by darkestblue91** [mgcrea/angular-strap#2184]
Hi,

I'm having troubles with datepicker on mobiles, when I select a disabled day (less than minDate, for example) the input does not change (stays in today or actual selected date) but the validator still set the errors $error.date $error.min so ng-messages show the errors.

How can I prevent that validation? I can use the native picker because in my project block dates is important, i can not receive in my form dates before today.

**Comment by anatoliy-ovchinnikov** [comment]
Hi,

Use on-show function to disable touchstart event, for example:

`<input data-on-show='{{onShow}}'>`

In controller/directive:

`var onShow = function () {
            $('.datepicker button:disabled').bind('touchstart', false);
        };`
