### ISSUE TITLE
Selecting elements in a bs-select dropdown using protractor selenium testing

### ISSUE THREAD

**Issue by joshdion** [mgcrea/angular-strap#2188]
I'm doing automation testing of a webpage and I can't figure out a way to select these elements. I am using protractor selenium testing. 

I tried this:

element(by.model('selectedAvailable')).click();
element(by.xpath('..//ul//li[1]')).click().

and this:

element(by.repeater('match in $matches').row(0)).click();

and was recommended to try this from people over at stackoverflow which isn't working either
http://stackoverflow.com/q/40292488/6636535

element(by.cssContainingText('[ng-repeat="match in $matches"]', 'Streamer')).click();

**Comment by jcdesousa** [comment]
I had the same issue.

You can try doing:
element(by.model('selectedAvailable')).click();
element(by.linkText('Inactive')).click();

**Comment by AnthonyMDev** [comment]
Did anyone ever get this working? I'm having a similar issue now.
