### ISSUE TITLE
bs-tooltip touchscreens issue

### ISSUE THREAD

**Issue by vadim-zverugo** [mgcrea/angular-strap#2194]
Inside `$tooltip` provider `bindAutoCloseEvents()` and `unbindAutoCloseEvents()` functions are failed on the touchsreens, because `click` event is not available.

Consider the following fixes:
```
tipElement.on(isTouch ? 'touchend' : 'click', stopEventPropagation);
$body.on(isTouch ? 'touchend' : 'click', $tooltip.hide);
```
and
```
tipElement.off(isTouch ? 'touchend' : 'click', stopEventPropagation);
$body.off(isTouch ? 'touchend' : 'click', $tooltip.hide);
```

**Comment by DaleWebb** [comment]
Cheers @vadim-zverugo! Submit a PR with the fixes 👍
