### ISSUE TITLE
Most animations do not work on iOS or Safari

### ISSUE THREAD

**Issue by tomof** [mgcrea/angular-strap#2199]
Most animations do not work on iOS or Safari.

The demo of the official site below can also confirm that animation does not work on iPad or Mac's Safari.

It should have operated without problems around October 2016.
Is it due to iOS or Safari update?

Does anyone know the cause?

**Comment by mrjrdnthms** [comment]
I am seeing this as well. Animations do not work running in safari. I use cordova to deploy app to iOS and none of the animations work in the app anymore. :(

What happened?

**Comment by DaleWebb** [comment]
Just looked back at the last 2 releases briefly, I couldn't see anything related to animations.  I believe this could be something to do with Safari (but I didn't do much of an investigation).

Have you tried an earlier version (the one you claimed worked last) of Angular-Strap, then see if that works?

**Comment by tomof** [comment]
Yes, of course I tried it.
I have been using 2.3.6 since about September 2016, and I have not changed that.
At the beginning of the year, when I checked on the iPad or iOS, the animation stopped working.

I also believe that Safari, or iOS (ver 10.2) has a cause.

**Comment by DaleWebb** [comment]
I just tried to compare it to http://mgcrea.github.io/angular-motion another project created by @mgcrea.  The animations work there, so I'm not sure what is going on.

**Comment by tomof** [comment]
angular-motion is used in the dependency of bower.json and, as you say angular-motion is working normally on Safari or iOS.

It seems to occur only with angularstrap and iOS or safari, it is very strange.

I am investigating the cause, but I can not identify it.

**Comment by sxxhlx** [comment]
still unsolved?

**Comment by GabrielMSharp** [comment]
Any progress on this?

**Comment by sxxhlx** [comment]
Did a little trick on this

**Comment by GabrielMSharp** [comment]
@sxxhlx Can you share?

**Comment by sxxhlx** [comment]
@GabrielMSharp I changed the libraries.css file.  Change 'animation-play-state' and '-webkit-animation-play-state' from paused to 'running'

**Comment by GabrielMSharp** [comment]
For anyone still having this issue, this is my temporary fix thanks to sxxhlx:

`div[class^="am-"], div[class*=" am-"] {
  &.ng-enter,
  &.ng-leave {
    animation-play-state: running;
  }
}`

**Comment by sxxhlx** [comment]
cheers

**Comment by Jokero** [comment]
Safari is the new Internet Explorer :smiley:
