### ISSUE TITLE
All/None select box performance on large collections

### ISSUE THREAD

**Issue by dustinsmith1024** [mgcrea/angular-strap#2201]
No sure this classifies as a bug, but I am experiencing really bad performance with long select boxes when using the All/None options.

Made a plunker to show the issue.
http://plnkr.co/edit/pWpkMPxFgczMueMy4hKY?p=preview

The fix for me seems to just be handle the add/remove outside manually in my own controller code.

**Comment by DaleWebb** [comment]
Could you define "bad performance"?  The selection of all items appeared to rendered instantly in the plunkr for me.
