### ISSUE TITLE
(typehead) Bug since update to Chrome v56 (I have to select twice)

### ISSUE THREAD

**Issue by rokbani-wael** [mgcrea/angular-strap#2203]
Since updating Chrome from 54 to 56, when I select an item in typehead, the selection is lost whenever I click on the screen. I have to select it a second time in order to persist my selection.
I'm using angular-strap 2.3.6 and AngularJS 1.5.7

**Comment by nihsmik** [comment]
I also have the same issue in Chrome 56.

**Comment by dperkovic** [comment]
I also have the same issue in Chrome 56., and in Firefox  51.0.1.
Ms Edge working OK.
