### ISSUE TITLE
How to pass DOMElement to target attribute in Angular bootstrap popover.

### ISSUE THREAD

**Issue by maruthi1255** [mgcrea/angular-strap#2205]
How to pass DOMElement to target attribute in Angular bootstrap popover.

For example:

<a  data-target="" bs-popover data-template="../first.html"></a>

Here in the data-target I want to send DOMElement reference(the element itself), how to send the current element DOM reference using the popover. I cannot use the id or class for target as there can be multiple elements in the page.

**Comment by maruthi1255** [comment]
This is not possible in html.
Hence closing this.

**Comment by DaleWebb** [comment]
Why did you want to do this?

The popover should appear on the DOMElement itself (without specifying `data-target`), if you created it via html.  Is that the behaviour you wanted?
