### ISSUE TITLE
How to align the bsPopover position dynamically

### ISSUE THREAD

**Issue by maruthi1255** [mgcrea/angular-strap#2207]
I have created a bsPopover using the directive bs-popover, data-container "body" and data-target is the element click on which the popover will be shown.

Note: I have used this for a column in angular ui-grid.

This is working fine, but when the popover size changes, it is getting distorted from its position.
Do we have a way to re position it to stick to its element in any way irrespective window resize or the popover size changes.

**Comment by DaleWebb** [comment]
I'm not sure that there is a native [to the browser] way of detecting the element size changing (without a defined width or/and height).

However, there is a protected method called `$applyPlacement` that should be on the `$popover` object.  This method is used to position the popover (and tooltip) when it is initially shown.  Perhaps if you call that method manually when you think that the size of the popover could change, maybe it would reposition it.
