### ISSUE TITLE
OnSelect does not work for typeahead directive

### ISSUE THREAD

**Issue by graphicsxp** [mgcrea/angular-strap#2208]
The following code binds the input to the correct model and data options. However when selecting an item from the list, the onSelect function is never calls.

I'm on angular 1.6 and angular-strap 2.3.8

```
           <input type="text" style="width: 200px" data-ng-model="model.selectedUser" placeholder="Start typing to choose a user" id="User" bs-typeahead bs-options="u.userName for u in model.allUsers| filter:$viewValue |orderBy:'fakeUserName'" bs-on-select="onSelect" />
```

**Comment by DaleWebb** [comment]
I don't believe this library has been tested against Angular 1.6.

You could try downgrading to 1.5 briefly (assuming you can) to see if it works?

**Comment by graphicsxp** [comment]
I have rolled back to 1.5 and it still does not work. The onSelect method is never called.

In my controller it is defined like this : 

$scope.onSelect = function(){
console.log('on select called');
}

**Comment by DaleWebb** [comment]
Thanks.  Could you create a plunkr to re-create the issue for someone to pick up when they try to fix (should be simple to duplicate a plunkr from the docs page)?

**Comment by graphicsxp** [comment]
Forgot to get back to you. Today I figured out I was still on a older version of angular-strap. That's why it was not working. All is fine now.
