### ISSUE TITLE
Typeahead buggy initial location

### ISSUE THREAD

**Issue by Mysame** [mgcrea/angular-strap#2210]
The "typahead" dropdown appears bottom-left of where it should be initially.
It jumps to where it should be when typing a secnod character, or when reselecting the field. At that point, it works as expected. This only occurs after an initial page load.

Tested in latest versions of Chrome and Firefox.

Reproducable on live demo page;

![2017-02-22_17-15-13](https://cloud.githubusercontent.com/assets/1966231/23220548/a1cdc8e6-f922-11e6-8022-f887dc4d8791.png)

**Comment by DaleWebb** [comment]
That's strange! It works for me on the latest (v56) Chrome on Mac.
