### ISSUE TITLE
IE edge browser - datepicker month names not displaying properly

### ISSUE THREAD

**Issue by ganeshkumar** [mgcrea/angular-strap#2211]
Please find the attached screenshot. In IE edge (IE14) browser the month names are not displaying properly. Any solutions/suggestions ? Thanks in advance.
<img width="1000" alt="screen shot 2017-02-23 at 6 02 42 pm" src="https://cloud.githubusercontent.com/assets/160764/23266370/9d49b3d4-fa0d-11e6-82bf-026fa0179baa.png">

**Comment by aaronmallen** [comment]
Steps to reproduce:
1. goto [datepicker demo](http://mgcrea.github.io/angular-strap/#/datepickers) in IE-14 browser
2. Click the date picker to open
3. Click the year number

**Comment by aaronmallen** [comment]
additionally, this seems to only occur on the initial state. If you open the datepicker and then click the month year you'll see the bug; however, if you close out of the datepicker and reopen it you'll see that is styled correctly, you'll have to recycle through the panes so see it occur again.
