### ISSUE TITLE
ocLazyLoad加载angular-strap找不到组件模版路径404

### ISSUE THREAD

**Issue by xlyren** [mgcrea/angular-strap#2212]
.state("index", {
                        url: "/index",
                        views: {
                            'main': {
                                templateUrl: 'main.html',
                                controller: "mainCtrl"
                            }
                        },
                        resolve: {
                            loadPlugin: function ($ocLazyLoad) {
                                return $ocLazyLoad.load([
                                    {
                                        serie: true,
                                        name: 'mgcrea.ngStrap',
                                        files: [
                                            configService.projectName+'/framework/angular-strap-2.3.10/angular-strap.js',
                                            configService.projectName+'/framework/angular-strap-2.3.10/angular-strap.tpl.min.js'
                                        ]
                                    },
                                ]);
                            }
                        }
                    })

这个是代码中的一部分，通过ocLazyLoad，提前加载angular-strap.js和angular-strap.tpl.min.js，运行后，
angular-strap中的个组件模版都是404，如日期模版、提示模版等都找不到路径，

但是如果通过页面script标签来引用，就都能找到，我测试了好几遍，angular-strap.tpl.min.js，
为什么通过ocLazyLoad加载的都找不到模版路径呢？

**Comment by non-player** [comment]
查看页面，组件都已注入到页面了，脚本也出现再了页面，页面不报错，就是模版路径找不到

**Comment by non-player** [comment]
![image](https://cloud.githubusercontent.com/assets/12228967/23328730/2c03ebe2-fb64-11e6-81d2-b08981df1454.png)
