### ISSUE TITLE
Angular 1.5 $onInit and $onDestroy lifecycle hooks are not triggered for Modal dialogs

### ISSUE THREAD

**Issue by Karankang007** [mgcrea/angular-strap#2213]
Modal dialog controllers currently do not trigger $onInit and $onDestroy life cycles hooks.

**Comment by DaleWebb** [comment]
Are these life cycle hooks part of Angular 1.5? Or does it exist in 1.4 too?

**Comment by Karankang007** [comment]
These life cycle hooks are part of Angular 1.5. You can read more about them here: https://docs.angularjs.org/api/ng/service/$compile#life-cycle-hooks
 or
https://blog.thoughtram.io/angularjs/2016/03/29/exploring-angular-1.5-lifecycle-hooks.html

**Comment by Karankang007** [comment]
For now, I am using this a workaround. This work around only works if the modal controller is using the controllerAs syntax:

```
$modal({
	...,
	onShow: function ($modal) {
		// Angular 1.5 $onInit and $onDestroy life cycle event support
		if ($modal.$options.controllerAs) {
			var modalElementData = $modal.$element.data();
			var modalScope = modalElementData && modalElementData.$scope;
			if (modalScope) {
				var controller = modalScope[$modal.$options.controllerAs];
				if (controller) {
					// Manually trigger $onInit callback
					if (angular.isFunction(controller.$onInit)) {
						controller.$onInit();
					}
					// Manually trigger $onDestroy callback on scope destroy
					if (angular.isFunction(controller.$onDestroy)) {
						modalScope.$on('$destroy', controller.$onDestroy);
					}
				}
			}
		}
	}
})

```

**Comment by DaleWebb** [comment]
Are you able to figure out where the changes could be natively for Angular-Strap?

If so, a PR would be welcome 👍

**Comment by Karankang007** [comment]
I just discovered that the workaround provided by me does not work if debug information is disabled.
```
$compileProvider.debugInfoEnabled(false)
```

This can be solved if someone has another way to get the modal controller instance via the $modal object.

**Comment by cstuncsik** [comment]
You can [decorate](https://docs.angularjs.org/guide/decorators) the $modal service generally not just the actual instance (based on @Karankang007's solution)

https://gist.github.com/cstuncsik/4b6da0b2df0e02e1c842c28ddace344a

**Comment by neekersMF** [comment]
Is there an example of how to call the $modal with a component?
