### ISSUE TITLE
Datepicker - can't set tomorrow date as default

### ISSUE THREAD

**Issue by claubanu** [mgcrea/angular-strap#2215]
Hi there! 
My issue: the user must select two dates, the beginning and the end of the interval. By default, first option is today and the second option (the end of the interval) should be tomorrow (by default, for a better user experience).
Can somebody, please, help me set tomorrow as default value for the second date option?
Thanks in advance!

**Comment by DaleWebb** [comment]
What happens when you try to set tomorrow as the default value?

**Comment by claubanu** [comment]
Hi Dale,

In view (html) I have:
					<div class="form-group">
						<p>First date:<br>
							<input type="text" class="inputbox input-sm" style="width: 165px;" ng-model="firstDate" name="firstDate" bs-datepicker>
						</p>
					</div>
					<div class="form-group">
						<p>Second date:<br>
							 <input type="text" class="inputbox input-sm" style="width: 165px;" ng-model="secondDate" name="secondDate" bs-datepicker>
						</p>
					</div>
					<div class="form-group">
						<button style="width: 165px;" type="button" class="btn btn-success" ng-click="getResults(firstDate, secondDate)">GET RESULTS</button>
					</div>

In the controller I set the datepicker and dates as following:

angular.module('myApp')
.config(function($datepickerProvider) {
  angular.extend($datepickerProvider.defaults, {
    dateFormat: 'dd/MM/yyyy',
    startWeek: 1
  });
});	

$scope.firstDate = new Date();	

And for the secondDate I've tryed different combinations like:
var today = new Date();	
$scope.secondDate = new Date(today+1); 
or
$scope.secondDate = new Date($scope.firstDate+1); 
		
The idea is that I want firstDate to be today and secondDate to be tomorrow by default.

Any advice is welcome!
Thank you very much.

**Comment by DaleWebb** [comment]
If you create a plunkr that recreates the problem, we can start from there :)

**Comment by claubanu** [comment]
Well, first time with plunkr...Maybe you can understand why isn't working the bs-datepicker directive plus the desired behaviour from those two date inputs,.
https://plnkr.co/edit/TasV5U3jPZXBwjkDBZ9p?p=preview

**Comment by DaleWebb** [comment]
I modified the body of the controller to this:

```
$scope.data1 = new Date();
$scope.data2 = new Date();
$scope.data2.setDate($scope.data1.getDate() + 1);
```

This worked.

**Comment by claubanu** [comment]
Also workoed for me. Thank you very much!
