### ISSUE TITLE
scrollspy bug

### ISSUE THREAD

**Issue by dbstudent** [mgcrea/angular-strap#2217]
tested with chrome 56.
on the strap webpage http://mgcrea.github.io/angular-strap/, click on a menu item, then start scrolling. the menu item that was clicked will remain highlighted even when focus is on another section. Giving focus to the address bar of the browser "fixes" the issue.

**Comment by DaleWebb** [comment]
This doesn't happen to me.  I'm on Chrome 56 too, on a Macbook.  Which OS are you using?

**Comment by dbstudent** [comment]
I am on Macbook, El Capitan. Same thing with Firefox, but not with safari. With further testing, I can see that clicking on the main content also "fixes" the issue.
Here's with firefox:
![image](https://cloud.githubusercontent.com/assets/5463184/24081025/0a3de0fa-0cab-11e7-97c7-a3f836c7f0cb.png)

**Comment by DaleWebb** [comment]
The element is focussed in that image. Isn't that the style to be applied when it's focussed (and now thinking about it, when you're hovered over it but also scrolling)?

**Comment by dbstudent** [comment]
Yes, but it shouldn't stay focused once you're starting to scroll out of this scope

**Comment by DaleWebb** [comment]
This would be a CSS option.  So you would define different styling or no styling for `:focus`'d elements to differentiate.
