### ISSUE TITLE
bs-modal OnHide not firing

### ISSUE THREAD

**Issue by robpolak** [mgcrea/angular-strap#2232]
Per the documentation the bs-modal should fire an event on hide.. this seems to be broken:

Plunkr: http://plnkr.co/edit/ExK84TXrQxxBKEPO1MYz

**Comment by madflow** [comment]
It works when you open the aside component differently:

https://plnkr.co/edit/Fqpk4H2pjyBk7UX30OoQ?p=preview

**Comment by ViieeS** [comment]
Works for 2.3.8 via bs-on-show / bs-on-hide: [example](http://plnkr.co/edit/moPOCvuyjf1E98qypUxL?p=preview).

Anyway, it doesn't work for me in version 2.3.12...

**Comment by ViieeS** [comment]
I found out what was wrong! I have defined cb function in directive on postLink state. After I defined cb on preLink state it became to work!

**Comment by ViieeS** [comment]
```html
<button bs-dropdown
            data-bs-on-hide="toggleActive"
            data-bs-on-show="toggleActive"
```
