### ISSUE TITLE
Select doesn't work with getterSetter:true

### ISSUE THREAD

**Issue by fbjon** [mgcrea/angular-strap#2235]
In this example, the button content will not update when an item is selected:
```html
<button data-ng-model="selection.settlementPeriod"
        ng-model-options="{getterSetter:true}"
        bs-options="..."
        bs-select>
</button>
```

The reason is that bsSelect `$watch`es the value of the ngModel attribute, which doesn't work when ngModel points to a getter-setter function instead of the changed value.

[Plunkr](http://plnkr.co/edit/IYke4u?p=preview)

**Comment by roded** [comment]
I suspect the same is true for the datepicker.
