### ISSUE TITLE
Invalid bower.json for main

### ISSUE THREAD

**Issue by mintuhouse** [mgcrea/angular-strap#2236]
Bower spec [says](https://github.com/bower/spec/blob/master/json.md#main)
````
The entry-point files necessary to use your package. Only one file per filetype.
````
It currently has both
angular-strap.js & angular-strap.tpl.js

**Comment by mikejr83** [comment]
FYI, bower is now suggesting that you move to Yarn and Webpack. 

Our internal control suite (which inherits Angular-Strap) suffers the same warning. I haven't narrowed down any direct issues to this warning. I thought it may affect us with our usage of gathering files in our Gulp build, but the main-bower-files package seems to pick up both ours and Angular-Strap's js files just fine.

Can you provide some scenario where there is a break down?
