### ISSUE TITLE
bs-typeahead IE11 - clicking on scroller hides dropdown

### ISSUE THREAD

**Issue by jackfishwick** [mgcrea/angular-strap#2237]
This is related to #1202, I am having the exact same issue with but with Typeaheads.

I have updated to the latest version of the code and it still is not working.

[Plunker example](http://plnkr.co/edit/f8akLhQ6KCERKyxlrcb9?p=preview)

If you type '1' into the search box and try to use the scrollbar in IE11/Edge the dropdown will close. In Chrome it works fine.

**Comment by NickzArora** [comment]
+1
