### ISSUE TITLE
Async dropdown?

### ISSUE THREAD

**Issue by jamespsterling** [mgcrea/angular-strap#2240]
Any way to implement an async dropdown, similar to the async [typeahead](http://mgcrea.github.io/angular-strap/#/typeaheads)? 

When I try doing the same using an angular scope variable with `http.get()`, it ends up generating an endless loop.

**Comment by DaleWebb** [comment]
How would you like this async dropdown to behave?

**Comment by jamespsterling** [comment]
@DaleWebb  Click the dropdown, throw up a spinner while the async operation happens, load the data into the dropdown list, boom.

**Comment by DaleWebb** [comment]
It feels like `bs-typeahead` functionality combined with `bs-select`...

Anyway, it's probably worth debugging this endless loop.  Are you able to produce a plunkr to show us what you're doing?

**Comment by jamespsterling** [comment]
@DaleWebb try this, http://plnkr.co/edit/Q3KWTF5833M7HAb6wFPL?p=preview

**Comment by jamespsterling** [comment]
@DaleWebb try this, http://plnkr.co/edit/Q3KWTF5833M7HAb6wFPL?p=preview
