### ISSUE TITLE
datepicker 'onBeforeShow', 'onShow', 'onBeforeHide', 'onHide' dont work

### ISSUE THREAD

**Issue by dmngu9** [mgcrea/angular-strap#2241]
Hi all, I use bs-datepicker with on-hide option. But it seems not work (never get called). Can anyone verify if this is a bug?

**Comment by dmngu9** [comment]
close this issue as the answer is provided in this link

https://stackoverflow.com/questions/44277614/angular-strap-bs-datepicker-event-onshow-onhide/44295972#44295972

**Comment by DaleWebb** [comment]
it's `bs-on-hide`
