### ISSUE TITLE
Dropdown doesn't close inside Popover

### ISSUE THREAD

**Issue by jamespsterling** [mgcrea/angular-strap#2244]
I have a dropdown inside of a popover, and it won't close. 

Plunker: http://plnkr.co/edit/vVdv0HjhBJtRiW2x4BMB?p=preview

**Comment by DaleWebb** [comment]
I was able to close it by clicking the button again.

**Comment by jamespsterling** [comment]
@DaleWebb It closes when you 'select' an item when not inside of a popover, but when you're inside of a popover it only closes when you click the initiator again. It's inconsistent behavior.
