### ISSUE TITLE
Popover Styling Option

### ISSUE THREAD

**Issue by drveresh** [mgcrea/angular-strap#2250]
Hi,

I am trying to build two(silver and black colored) versions/styles of Popover, but we are unable to achieve it because it won't work if we use a different(system/default) attributes names other than: "popover" and "arrow".

So, what is the alternative approach we have to take to fix this issue?

- Thanks

**Comment by DaleWebb** [comment]
You could write CSS that will target the `bs-popover` element, by having a rule that targets the popover parent and popover itself.  For example, `.parent .popover { } `.

Or

You can specify you write your HTML template (just take the default and tweak it to your needs).
