### ISSUE TITLE
how to set templateUrl dynamiclly for dropdown?

### ISSUE THREAD

**Issue by ericWenjp** [mgcrea/angular-strap#2268]
i try this:
`<span class="tag ui-select" ng-repeat="item in ctrl.dimenList track by $index" 
                          data-animation="am-flip-x" bs-dropdown data-auto-close="false" aria-haspopup="true" aria-expanded="false"
                          data-template-url="{{item.url}}"
                          >
                       {{item.indexName}}
                        <i class="bdp-icon ico-triangle-down1" ng-if="item.indexCd=='D' || item.indexCd=='Y'"></i>
                    </span>`
but console show error like this:
![image](https://user-images.githubusercontent.com/25905832/34478179-6c079fde-efda-11e7-86c1-7149bd6cda86.png)

how to solve this? Could you show me some example?

**Comment by stubbzarelli** [comment]
Have you tried without the curls braces? E.g.

data-template-url="item.url"
