### ISSUE TITLE
Typeahead - strange issue in ios - cursor remains at first position on editing a field

### ISSUE THREAD

**Issue by sugisha-sukumaran** [mgcrea/angular-strap#2282]
Scenario is like this.

We have a typeahead field which is listing countries. There is no issue while we enter the text in field for the first time. After saving the data, go to the same screen to edit the country.. Then on typing cursor remains at first position. This is happening only in iOS devices. Attaching a screenshot for the same 
![screen shot 2019-02-28 at 12 51 19 pm](https://user-images.githubusercontent.com/24225150/53548683-22e36700-3b58-11e9-9280-c8ef9bd56b84.png)

Can anyone help on this?

**Comment by SERGEES** [comment]
still an issue
