### ISSUE TITLE
Popover to be displayed only on visible screen.

### ISSUE THREAD

**Issue by hchagger** [mgcrea/angular-strap#254]
Is there a way to make the popover display on the visible screen?

For example, if the popover has a data-placement = "left" but it is on the edge of the screen it wont be visible entirely.

In this case, it may be better to display it on the right, Similarly, if the data-placement is on the bottom, but you are on the bottom of page, it should display on the top.

I believe this is possible with bootstrap 3.0, but not 2.x with the data-placement="auto".

http://getbootstrap.com/javascript/#popovers

"how to position the popover - top | bottom | left | right | auto.
When "auto" is specified, it will dynamically reorient the popover. For example, if placement is "auto left", the tooltip will display to the left when possible, otherwise it will display right. "

**Comment by alanmoo** [comment]
Any update on this? Using the plunkr link from http://mgcrea.github.io/angular-strap/#/popovers it seems like auto still doesn't work.

**Comment by alanmoo** [comment]
For anyone else that comes across this, it looks like the behavior of auto only supports left/right decision making logic, not top/bottom (as in, switching from top to bottom). That is to say, the popover will only shift up and down within the left/right placement and jump left/right as necessary.

**Comment by vmlf01** [comment]
I believe @bstruthers did a big part of auto-placement code, and I seem to recall it did top/bottom also, but he might provide more info on this.

**Comment by bstruthers** [comment]
Auto does work with up and down, but it's tied to its container.  It does not take the viewport into consideration.  I matched bootstrap's implementation when I coded the auto code.  Has it changed recently?

**Comment by bstruthers** [comment]
Here's an example plnkr demonstrating: http://plnkr.co/edit/slaWKVGFbF2HUx2ruqAm

**Comment by alanmoo** [comment]
I'm not sure about Bootstrap's implementation, but I couldn't get the example to switch from the bottom to the top of the container when the popover appears past the bottom of the viewport. Is that supported and perhaps I'm just doing something wrong in the plunkr? (I'm opening the live demo at http://mgcrea.github.io/angular-strap/#/popovers and setting `data-placement="auto top-right"` on the data-attrs button.)

**Comment by alanmoo** [comment]
Ok, I think the expected behavior isn't what I expected :smiley:

Just to clarify (and this is probably Bootstrap's implementation, but you seem familiar with it), auto seems to check if the popover fits in the parent container using the specified placement, and if not, it goes to the opposite side. Viewport only comes in when shifting up/down within the left/right placement. Is that all correct?

**Comment by bstruthers** [comment]
Yep!  I agree that it's a little confusing.  `auto` is tied to the container, and viewport changes are for shifting (viewport would shift left or right when the placement is top/bottom).  

If you look at the source, the docs have an example that show the viewport placements in action (popover-viewport.html).

**Comment by alanmoo** [comment]
I did come across that example page earlier, but couldn't make sense of it. Thanks for the clarification!
