### ISSUE TITLE
[popover] Click outside to hide popover.

### ISSUE THREAD

**Issue by missinglink** [mgcrea/angular-strap#309]
It is pretty annoying to close a popover, at the moment you have 2 options:
- Click the trigger link / button again to toggle it.
- Hit the `esc` key to make it go away.

Here is a bit of jQuery code I am using to hide all the popovers when the user click elsewhere on the page:

``` javascript
// A hacky bit of code to close popovers when clicking away
$('html').on('click', function(e) {
  $('.popover').each( function() {
    if( $(e.target).get(0) !== $(this).prev().get(0) ) {
      $(this).popover('hide');
    }
  });
});
```

Not sure if this belongs here or should be feature request against bootstrap, left here for anyone else trying to do the same thing.

**Comment by roopkt** [comment]
Hi, I downloaded angular ui bootstrap 2.4.0
On escape it is closing the popover. However, my requirement is to not hide popover on escape key press.
I checked 1.3.3 version do not hide popover on escape key press.

I would suggest to create one Boolean property on popover option object to check if hide on escape is required or not. Like jQuery dialog has an property called **closeOnEscape**  which I can pass false if I do not want dialog to close on escape key-press.

Please advice.
