### ISSUE TITLE
bs-dropdown should allow inline html

### ISSUE THREAD

**Issue by tindzk** [mgcrea/angular-strap#340]
I am trying to use bs-dropdown in a navbar as follows:

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" bs-dropdown>Tags <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                  <li role="presentation" class="dropdown-header">Tags</li>
                  <li ng-repeat="tag in tags"><a href="#/browse/$tag.id$">$tag.tag$</a></li>
                  <li role="presentation" class="divider"></li>
                  <li role="presentation" class="dropdown-header">Settings</li>
                  <li><a href="#/tags">Manage tags</a></li>
                </ul>
                <ul class="dropdown-menu">
                </ul>
              </li>

When clicking the element, an empty menu opens. Could you provide an example on how to use bs-dropdown correctly?

--Tim

**Comment by seiyria** [comment]
+1

**Comment by JetFault** [comment]
@tomekp solution worked for me! Thanks!

**Comment by slyedoc** [comment]
+1, plz merge

**Comment by tibor-kulcar** [comment]
+1

**Comment by makzumi** [comment]
I made this simple directive if anyone needs it still...
https://bitbucket.org/snippets/aalmakzumi/4LRjK/angularstrap-dropdown

**Comment by mgcrea** [comment]
Finally landed in 89f9608f1c7578689d098b9b592f85b1dd52e492. Will push a new release soon.
