### ISSUE TITLE
Selects droplist inside ngTable loses its scope

### ISSUE THREAD

**Issue by shojib** [mgcrea/angular-strap#362]
If I put the Selects (select.js) droplist inside ngTable, and try to show the selection from outside the table, it loses its scope and doesn't show the selection. Hopefully, I was able to explain this. 

Here's the preview. In the preview, you will see a select droplist which has two output locations. One inside the table which works and another outside the table which doesn't.

http://plnkr.co/edit/tQYmRrTjXOhTohsESpNo?p=preview

**Comment by ValentinBragaru** [comment]
Found the cause:
In Documentation is wrote :
$scope.selectedIcon = "Globe";
$scope.selectedIcons = "[]";
$scope.icons = "[{"value":"Gear","label":"<i class=\"fa fa-gear\"></i> Gear"},{"value":"Globe","label":"<i class=\"fa fa-globe\"></i> Globe"},{"value":"Heart","label":"<i class=\"fa fa-heart\"></i> Heart"},{"value":"Camera","label":"<i class=\"fa fa-camera\"></i> Camera"}]";

But should be:
$scope.selectedIcons = [];
	    $scope.icons = [
	       {value: 'Gear', label: 'Gear'},
	       {value: 'Globe', label: 'Globe'},
	       {value: 'Heart', label: 'Heart'},
	       {value: 'Camera', label: 'Camera'}
	     ];

NO DOUBLE QUOTES !!
