### ISSUE TITLE
bs-dropdown with the "hover" trigger doesn't stay open long enough

### ISSUE THREAD

**Issue by naderchehab** [mgcrea/angular-strap#367]
When using the bs-dropdown with the "hover" trigger, the menu doesn't stay visible long enough to allow the user to click on a menu item:

http://plnkr.co/edit/Fi39BdCOqHXnPAgITD01?p=preview

Using a delay makes it behave in unexpected ways:

http://plnkr.co/edit/Y2Q63DDJEyP9CTPMUfYD?p=preview

Ideally the dropdown should remain visible as long as the mouse is on the menu, and disappear when the mouse leaves the menu.

**Comment by leayingly** [comment]
Coming back at this issue, container:"self" works perfectly in most browsers, but click events on dropdown items don't work in IE. Is this expected behavior? Thanks.
