### ISSUE TITLE
[$sce:unsafe] Attempting to use an unsafe value in a safe context.

### ISSUE THREAD

**Issue by ProdigyView** [mgcrea/angular-strap#369]
I'm trying to use the bs-alert, and I keep getting the error:

[$sce:unsafe] Attempting to use an unsafe value in a safe context.

When I try the following:

$alert({title: 'Holy guacamole!', content: 'Best check yo self,  not looking too good.', placement: 'top', type: 'info', show: true});

**Comment by dsultan** [comment]
I have got a problem using <code>bs-dropdown</code> from the documentation example. I disabled <code>html:true</code> so as to get rid of <code>unsafe</code> problem. Then it displayed all items of the dropdown.  It is not binding a function <code>alert</code>. Help please.

**Comment by maheshkajale** [comment]
I get solved this error by changing initialization of variable to null.

$scope.visitors_data = {}; 
This line was causing the error [$sce:unsafe] Attempting to use an unsafe value in a safe context.

Then I changed variable initialization.
` $scope.visitors_data = ''; `
