### ISSUE TITLE
bs-checkbox does not support ng-checked

### ISSUE THREAD

**Issue by nicolasmoise51** [mgcrea/angular-strap#385]
I cannot use ng-checked on bs-checkbox.

**Comment by ekaradon** [comment]
I can reproduce the issue here:
http://plnkr.co/edit/BevI5GV3gkoBjFArbTQy?p=preview

**Comment by ekaradon** [comment]
I get the same trouble using bootstrap checkbox button. 
I think it may be a duplicate of issue  #4516
https://github.com/angular/angular.js/issues/4516

**Comment by vmlf01** [comment]
So what I notice is that ng-model is not updated when ng-checked value changes, is that the problem?
If so, that seems to be the behaviour of Angular (see https://github.com/angular/angular.js/pull/1057).

**Comment by ekaradon** [comment]
In fact, we have a difference between the input of type checkbox (which works with ng-checked) and the bs-checkbox (which does not work with ng-checked).
My example shows it. Try to check all the checkboxes before the button "ALL", you will see the difference.
