### ISSUE TITLE
[question] cannot get styling locally on calendar, timepicker popups  

### ISSUE THREAD

**Issue by dukehoops-zz** [mgcrea/angular-strap#398]
After following quick start steps in docs (as well as adding [Font Awesome](http://fortawesome.github.io/Font-Awesome/)) I cannot get [proper styling](https://drive.google.com/file/d/0B6eh_nTDYvxSQzNlSXZIaEN0NG8/edit?usp=sharing) to appear on timepicker and calendar popups. Instead day and hour/min selectors render as bordered buttons. Which CSS file (or JS?) - though it does work correctly on plunker demos. need help tracking down what's missing. which css/js file(s) are responsible for this styling?

thank you,
-nikita

**Comment by dara0418** [comment]
Well this style never work for me. The datepicker keeps the default style, don't know why. I've imported my less file to the index page.
