### ISSUE TITLE
When bound content changes inside a popup causing it to resize, the arrow is not repositioned correctly

### ISSUE THREAD

**Issue by jwheeler79** [mgcrea/angular-strap#399]
The original bootstrap popover wasn't really designed for this use case, but the enhancements you've made in this project to support loading a bound template would make this a useful feature. For example, if using an ng-repeat in the popover template on a UL, and the size of the list change, the arrow is redrawn incorrectly.

**Comment by jamespsterling** [comment]
What about enabling the popover arrow to be sticky to the original location. I have dynamic content that can be added or removed and while the popover arrow adjusts to the center, ideally it would stay anchored to the clicked element. 

Example,
![popover](https://cloud.githubusercontent.com/assets/6403652/26740724/537d529c-479c-11e7-9bb7-037a7cd4cf03.gif)
