### ISSUE TITLE
bs-navbar don't add active class when the menu is dynamically generated?

### ISSUE THREAD

**Issue by yahyaKacem** [mgcrea/angular-strap#40]
hi, when the navigation elements are created dynamically the `addClass("active")` method stop working. for more detailed information check the code on [**plnkr**](http://plnkr.co/HLO4zd).

**Comment by edmocosta** [comment]
Hi, you  should remove the $watch and use the  $location event '$locationChangeSuccess' in $rootScope, Example:

```javascript
    $rootScope.$on('$locationChangeSuccess', function() {
        element.find('li[data-match-route]').each(function(k, li) {
            var $li = angular.element(li),
                pattern = $li.attr('data-match-route'),
                regexp = new RegExp('^' + pattern + '$', ["i"]);
            if (regexp.test($location.path())) {
                $li.addClass('active');
            } else {
                $li.removeClass('active');
            }
        });
    });
````

http://plnkr.co/edit/wdx5pWKOFBPKGj94McDr?p=preview

**Comment by weeman1337** [comment]
I can confirm this issue when adding the nav in a view and using dynamic menu items (ng-repeat) with AngularJS 1.3.15. For now I'll use the ui-router's ```ui-sref-active```

**Comment by stanleyxu2005** [comment]
+1 reproducible with Angular 1.4.8 and AngularStrap 2.3.6

**Comment by drKnoxy** [comment]
+1 @edmocosta this fixes a bug i was having with rewriting routes but not changing the urls for seo.

**Comment by drKnoxy** [comment]
fyi none of these plunkers work anymore

**Comment by armensg** [comment]
was this ever resolved? I seem to have this issue with latest version..
