### ISSUE TITLE
Module mgcrea.ngStrap.alert not available!

### ISSUE THREAD

**Issue by melcher** [mgcrea/angular-strap#414]
I'm getting "[$injector:nomod] Module 'mgcrea.ngStrap.alert' is not available!" in angular-strap#2.0.0-rc.2 with bootstrap #3.1.0 when adding the  "mgcrea.ngStrap" module to my angular app. So it's definitely seeing the mgcrea.ngStrap module, but failing to include the alert submodule.

I'm requiring the full angular-strap.js (and .min.js) and checked that ngStrap.alert does exist in my local file.

I've started to dig into the module/include code but thought I'd post an issue since I don't think it's something unique to my setup.

**Comment by colares** [comment]
+1

**Comment by jon-choi** [comment]
+1

**Comment by cbojaca** [comment]
+1
