### ISSUE TITLE
Having the datepicker inline 

### ISSUE THREAD

**Issue by bhamde** [mgcrea/angular-strap#430]
Hi, I wanted to ask if the datepicker can be added in as a whole table to select from instead of having to use an input element for it to popup.

**Comment by paulflo150** [comment]
Is there a way to subscribe to an open/ close event?

For instance, in the case of the plunker joshuajabbour posted, if you open the calendar by clicking the button 'show' becomes true, then you focus the input box, and finally you click outside, the calendar closes, however the variable does not get updated to false as it should.

Any thoughts on how to get this fixed?

Thanks!

**Comment by vmlf01** [comment]
You can use datepicker show/hide events for that, have a look at commit https://github.com/mgcrea/angular-strap/commit/ac42c304cbed4259d8b1d817a47a9136d65a11b4.

**Comment by paulflo150** [comment]
That did the trick - any plans on syncing bs-show with the state of the dropdown? (unless I have it setup incorrectly).

Very happy with the performance of my views now with several datepickers, thanks a bunch!

**Comment by vmlf01** [comment]
You don't have it setup incorrectly, its just not implemented that way :)
I guess if someone made a PR it would be merged.

**Comment by paulflo150** [comment]
Understood :) Something else that might be kinda cool would be if you could bind the start date, or perhaps make both min and start be the same.

**Comment by mmouterde** [comment]
@joshuajabbour from your use-case that meets mine, I tryed to define a directive to get an inline datepicker :
http://embed.plnkr.co/pqCDidMAkolLljj7CyFy/preview

Do you have some suggestions to make it cleaner ?? (cf TODO in code)

**Comment by stfoo** [comment]
I have this error and broken datepicker with bs-show="true" when i navigate through ui-states. But datepicker works alright when I refresh the page. What's wrong?
```
TypeError: tipLinker is not a function
    at angular.module.provider.$get.$tooltip.show (angular-strap.js:4713)
    at Object.angular.module.provider.$get.$datepicker.show (angular-strap.js:1157)
    at Object.<anonymous> (angular-strap.js:1211)
    at Object.constantListener [as fn] (angular.js:12836)
    at Scope.$get.Scope.$digest (angular.js:14243)
    at Scope.$get.Scope.$apply (angular.js:14506)
    at HTMLDocument.<anonymous> (angular.js:11364)
    at HTMLDocument.jQuery.event.dispatch (jquery.js:4430)
    at HTMLDocument.jQuery.event.add.elemData.handle (jquery.js:4116)
```

```
<div class="datepicker"
          bs-datepicker
          ng-model="period.from"
          data-date-type="string"
          data-trigger="manual"
          bs-show="true"
          data-disabled-dates="disableddates"></div>
```

**Comment by weeman1337** [comment]
+1

**Comment by kenyus** [comment]
+1

**Comment by rzschech** [comment]
+1

**Comment by alalonde** [comment]
@joshuajabbour's suggestion above works pretty well.  I just made a simple wrapper directive demonstrating it:
http://jsfiddle.net/alalonde/gh9La92p/

**Comment by VictorBlasman** [comment]
How can I change the regional in the html-line? Can I add the hours? Thx!
