### ISSUE TITLE
(docs) Aside is hidden on animation complete in Safari

### ISSUE THREAD

**Issue by ehunter** [mgcrea/angular-strap#445]
After opening & closing an aside 3 or 4 times in Safari the aside is hidden when it's open animation completes. I can repro the issue using the documentation site here: http://mgcrea.github.io/angular-strap/#/page-one#asides
1. Navigate to the asides demo
2. Click to toggle aside
3. Click away from the aside to close it and repeat 3 or 4 times.
4. Eventually the aside will disappear once it finishes animating in. It reappears quickly before closing.

This only happens is Safari (I'm on v6.1). Anyone else see this? Maybe this an ngAnimate issue?

**Comment by SolStis86** [comment]
Yes this is still happening
