### ISSUE TITLE
Problem with show()

### ISSUE THREAD

**Issue by ibraelillo** [mgcrea/angular-strap#450]
Hello, I want to post the error I'm having after a fews days ago. this is my code, just like it's  showed at the doc page. 

var UserController = function ($rootScope, $scope, Api, $modal)
{
            // Pre-fetch an external template populated with a custom scope
            var myModal = $modal({scope: $scope, template: 'user/login.html'});

```
        $scope.open = function(){
            myModal.$promise.then(function() {
                myModal.show();
            });
        };
```

};

The error shown is in the show() method. 

Error: element.style is undefined .css@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:2402 JQLite.prototype[name]@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:2524 this.$get</j/j.show@http://localhost/annimmo/annimmo/vendor/ui/bootstrap/angular-strap.min.js?1391777376241:8 this.$get</j/j.init/<@http://localhost/annimmo/annimmo/vendor/ui/bootstrap/angular-strap.min.js?1391777376241:8 $RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:11574 $RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:11773 bootstrap/doBootstrap/<@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:1297 invoke@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:3638 bootstrap/doBootstrap@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:1296 bootstrap@http://localhost/annimmo/annimmo/vendor/angular/angular.js?1391777376241:1309 @http://localhost/annimmo/annimmo/app.js?1391777376241:197 ha/i.execCb@http://localhost/annimmo/annimmo/vendor/require/require.js:29 ha/X.prototype.check@http://localhost/annimmo/annimmo/vendor/require/require.js:18 ha/X.prototype.enable@http://localhost/annimmo/annimmo/vendor/require/require.js:23 ha/X.prototype.init@http://localhost/annimmo/annimmo/vendor/require/require.js:17 D@http://localhost/annimmo/annimmo/vendor/require/require.js:14 ha/i.completeLoad@http://localhost/annimmo/annimmo/vendor/require/require.js:28 ha/i.onScriptLoad@http://localhost/annimmo/annimmo/vendor/require/require.js:29

**Comment by ri0t** [comment]
Hmm. I have the same, but producing a plunker would be a non-trivial task, here. I use webpack and could provide other info/details. The source is not-done-yet™ but is GPLv3 so you can have a look, when i can push it - milestone release is 23.5. ;)
