### ISSUE TITLE
Tooltip animations question

### ISSUE THREAD

**Issue by overloadnn** [mgcrea/angular-strap#459]
I noticed that in the example you are linking to //mgcrea.github.io/angular-strap/static/styles/libraries.min.css so as to activate tooltip animations. I can't find any info about that. If I don't use this file, animation are disabled and some bugs occurs (for example, sometimes the tooltip is not hidden).
![screenhunter_01 feb 10 12 07](https://f.cloud.github.com/assets/5198846/2126677/20b82714-9265-11e3-99ac-4b7b34e337cf.jpg)

Thx!

**Comment by smartytwiti** [comment]
HI this is very similar to my problem: http://stackoverflow.com/questions/30654621/aside-is-conflicting-with-modal-ngstrap

Apparently  mgcrea.github.io/angular-strap/static/styles/libraries.min.css is conflicting with the ngStrap.modal.
Please can you check this ?

**Comment by vmlf01** [comment]
It probably is not caused by this css itself, because the docs pages are using the same CSS files and there is no problem there. It might be some CSS conflict with other css definitions in the project.
Maybe you can open a new issue with a test case showing your problem?

**Comment by smartytwiti** [comment]
https://github.com/mgcrea/angular-strap/issues/1722
