### ISSUE TITLE
typeahead with headers

### ISSUE THREAD

**Issue by gsferreira** [mgcrea/angular-strap#482]
Hi!

There's any option available to create Headers on typeahead like in Multiple Sections with Headers example [here](http://twitter.github.io/typeahead.js/examples/).
I can't find in Docs the option "highlight"

Thanks

**Comment by glauberramos** [comment]
any update on this? It would be really nice to be able to add headers into the typeahead component.

**Comment by glauberramos** [comment]
=/

**Comment by kefengdeng-ibboost** [comment]
It would be great if we have this feature!!!
