### ISSUE TITLE
Using a template with comments in a modal causes a crash

### ISSUE THREAD

**Issue by JoshuaJWilborn** [mgcrea/angular-strap#492]
Uncaught TypeError: Object #<Text> has no method 'focus' angular-strap.tpl.js:91
(anonymous function) angular-strap.tpl.js:91
Error: [ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <div class="element ng-scope" ng-transclude="">

**Comment by mgwidmann** [comment]
I have the same problem with a tooltip with a custom template using an `ngIf` on the root DOM element of the custom template (which creates a comment).

**Comment by boogie4eva** [comment]
Thanks this forum solved it for me i was actually very curios
