### ISSUE TITLE
modalElement of an Alert within a Modal is undefined

### ISSUE THREAD

**Issue by BarryThePenguin** [mgcrea/angular-strap#498]
After spending more time on #473 I figured out my problem and found a new one.

When animating Alerts within a Modal the modalElement passed into $animate.leave or $animate.enter is undefined.

This means an Alert cannot be used within a Modal.

Plunker ~~http://plnkr.co/edit/i97fugU3wMAZ8Yy4Wc60~~

http://plnkr.co/edit/q99mvTNvNGPkjZCXdpuc

Unless I'm doing something wrong again...

**Comment by DaleWebb** [comment]
Problem no longer exists in current version `v2.3.8`
