### ISSUE TITLE
bs-checkbox-group with ngRepeat

### ISSUE THREAD

**Issue by keaplogik** [mgcrea/angular-strap#501]
I have been enjoying using Angular Strap as I've found it easier to use then the AngularUI teams version. I was wondering if there was support for using an ng-repeat with your checkbox button directive. I want to build my radio buttons from an array like:

``` html
<div class="btn-group" ng-repeat="app in applications" ng-model="appCheckModel" bs-checkbox-group>
    <label class="btn btn-primary">
        <input type="checkbox" ng-value="{{app.name}}"> {{app.formatted_name}}
    </label>
</div>﻿
```

The problem is that the end result yields `ng-model='appCheckModel.undefined'` on the resulting inputs.

**Comment by mmadson** [comment]
+1

**Comment by just-boris** [comment]
@simonh1000 you have overlapping variables in your plunk:
![image](https://cloud.githubusercontent.com/assets/812240/10482097/2b1feade-727e-11e5-9e02-4acf5243a56f.png)
They should has different variables.
Fixed this and your plunk is working fine
http://plnkr.co/edit/0GA4dMGZlsP2YxKDefDk?p=preview

**Comment by just-boris** [comment]
`bs-radio-group` can't see interpolated `ng-value` because it executed before. So if you want to generate list of check/radio buttons, you should get rid of `bs-radio-group` and add `bs-checkbox` for each input manually.

**Comment by simonh1000** [comment]
I've moved on from this code since then, but thanks for digging in
