### ISSUE TITLE
alerts array usage in v1 versus v2

### ISSUE THREAD

**Issue by aldas** [mgcrea/angular-strap#502]
Angular strap had nice way to create alerts from array in v1 

```
<div class="alerts">
  <div class="alert fade" ng-repeat="alert in alerts" bs-alert="alert"></div>
</div>
```

but using v2 it seems to me that alerts directive does not support similar functionality.  Is this intentional and is there a workaround?

**Comment by baileyspace** [comment]
Any updates on how this is easy to accomplish? I'm having trouble getting it to work.

**Comment by vmlf01** [comment]
Have a look at https://github.com/mgcrea/angular-strap/issues/890, maybe that will help.
