### ISSUE TITLE
Tooltip and title baloon

### ISSUE THREAD

**Issue by moisesbaddini** [mgcrea/angular-strap#534]
When adding a title in a button, the hint baloon is displayed along with the tooltip.

Plunker is not necessary, just stop your mouse over the button 'click me' in the example on AngularStrap main page, and hint "Hello Tooltip&lt;br /&gt;This is a multiline message!" appears.

**Comment by k-funk** [comment]
+1 for data-title. Yay easy fixes!

**Comment by andras-tim** [comment]
Yap!

/Off:
But sometimes, the balloon color is not customizable... e.g. on a checkbox label works properly, however not on a button - there is always black
