### ISSUE TITLE
Multiline tooltips near edge of containers may not be positioned correctly

### ISSUE THREAD

**Issue by sunild** [mgcrea/angular-strap#540]
I've created two plunkers to demonstrate this. Using font awesome icons w/tooltips that are being pulled-left/right such that they are at the edge of the page.

Pure Bootstrap: http://plnkr.co/edit/Ignlls2HGBXtvcSKiJh0?p=preview
Angular Strap: http://plnkr.co/edit/Lu8lYCLmei4fq5zfRgyM?p=preview

When pulled to the right, the Angular strap tooltip seems to be positioned too low, and the "arrow" part of the tooltip is mis placed. This makes it difficult to mouse over the icon and show the tooltip: If you mouse near the top of the icon, the tooltip will appear underneath the mouse pointer thus ending the hover state over the icon and causing the tooltip to disappear quickly.

In IE11, the above problem is more than just a nuisance. In IE11 it's possible to mouse over the tooltip in the above way and for the tooltip to remain on screen.

With Bootstrap's Javascript, the above issues do not exist :) I haven't been able to figure out where to start investigating this other than looking at the code for the dimensions service. Happy to help w/a pull request if someone can point me in the right direction.

![screen shot from IE11 where tooltip remains open permanently](https://f.cloud.github.com/assets/283872/2378225/4e1da0e8-a88c-11e3-9f81-7f5454fbc712.png)

**Comment by xak2000** [comment]
I have the same issue but "pre-defined-way" is not working for me as my tooltips are one the table cells. The table with horizontal scrollbar. So every cell at any moment can be at any position of the browser viewport. How can I address this without 'auto' option?

Another issue that even without 'auto' opiton tooltip position itself wrong.
At this plunker http://plnkr.co/edit/l3is7Cy0xJqSDxatAeW8?p=preview scroll the table right. Any tooltip for cell that hasn't been on the screen until scrolling positioned incorrectly and with too many line breaks.

**Comment by vmlf01** [comment]
Looks like positioning on the edge is fixed on latest version, but the case where the page scrolls is still wrong.
