### ISSUE TITLE
Alert, 'animate' not working from JS.

### ISSUE THREAD

**Issue by k-funk** [mgcrea/angular-strap#554]
added

```
animation: 'am-flip-x'
```

to the constructor of my $alert object, seems to have no effect although it does work if I use it on a directive with data-animate.

**Comment by amahfouz** [comment]
I am having this same problem. I am using the $alert service, which does work and show the alert. However, any animation that I add is ignored. I thought that not including ngAnimate is the problem but nothing changed after I added it.

**Comment by adam-marshall** [comment]
I have the same problem. I notice on the modal container it adds a class "alert-with-am-fade" but this does nothing. it isn't mentioned in the css at all. Not really sure how this is working...

**Comment by DaleWebb** [comment]
You need to include the [`angular-motion`](https://github.com/mgcrea/angular-motion) CSS
