### ISSUE TITLE
tipLinker is undefined

### ISSUE THREAD

**Issue by JonnyHeavey** [mgcrea/angular-strap#559]
I was trying to toggle a popover from a directive (created in the same directive), however, when the toggle function executes, I get the following Javascript error:

"Uncaught TypeError: undefined is not a function" in angular-strap.js:3121

The offending line is:

tipElement = $tooltip.$element = tipLinker(scope, function (clonedElement, scope) {

**Comment by mattisdada** [comment]
This should probably be mentioned in the documentation somewhere. I also got tripped out by this at first

**Comment by alalonde** [comment]
This is an open-source project. Yes, the docs can be lacking, but let's be solution-oriented: 

https://github.com/mgcrea/angular-strap/blob/master/src/popover/docs/popover.demo.html
