### ISSUE TITLE
integrate select2

### ISSUE THREAD

**Issue by plandem** [mgcrea/angular-strap#560]
it would be nice to integrate select2 (multiselect + search)

**Comment by dcominottim** [comment]
@mgcrea @isteven Is there any on going effort regarding this topic?

**Comment by isteven** [comment]
Hi @dcominottim, 

From my side, as for now, I can say that there's no on going effort on this. 

Reasons being:
- There are a lot of conceptual & technical differences between the two directives. Just read the manuals and you can easily see the differences: the declaration, models, configs, etc.
- It's going to take some time to incorporate my directive into such a mature project like angular-strap. IMHO, I'm not yet there.
- I'm quite occupied (even for maintaining my own multi-select directive) - big things are happening in my life at the moment.

I am quite sure that, you can always add my multi-select on top of angular-strap whenever you need it. Extra load on the app, but it won't harm anyone, I guess.

In the end, big shout out to @mgcrea for the angular-strap project :)
