### ISSUE TITLE
bsTabs: Directive option to allow a callback when changing tabs

### ISSUE THREAD

**Issue by Cadrach** [mgcrea/angular-strap#566]
Hi,

Is there a way to have something like this available for the tabs directive?

```
<div bs-tabs="tabs" data-onchange="controllerScopeMethod()"></div>
```

The callback would be run when switching tabs.
I did not see anything like it in the docs or the code

**Comment by h4d3s2004** [comment]
+1

**Comment by dmitry-dedukhin** [comment]
> You should watch the bound ngModel to achieve this.

This is not the option when I do not want to know programmatic tab changes but I need to know when user itself clicked the tab.
