### ISSUE TITLE
(tooltip) footer being dropped if content template is turned on? #part2

### ISSUE THREAD

**Issue by stylenclass** [mgcrea/angular-strap#595]
@mgcrea I'm revisiting this question, I just pulled the latest version rc4. And I do see now where you are coming from. I believe the logic is wrong. I just realized this because of the comment you added recently.

// Drop the default footer as you probably don't want it if you use a custom contentTemplate
                if (!config.template)
first, we are talking about content template not template. So the condition should be if (!config.contentTemplate). Because right now it doesn't matter if you configure content template or not because its looking for the template config variable.

Now moving forward, content template is customization of the content block, which is both outside the header and footer block. If I wanted to have a different footer, then I would have change the default template would I?

So dropping the footer doesn't make sense here if you only want to customize the content block (because the user only concerned about customizing the content and not the other elements) and footer is outside of its scope as you have previously mentioned.

If this is acceptable I can prep a pull request.

**Comment by dmig** [comment]
Actually, this line https://github.com/mgcrea/angular-strap/blob/master/src/modal/modal.js#L80 is a dirty hack and should be removed.

I faced this issue trying to use my own dialog template, setting it using
``` 
    angular.extend($modalProvider.defaults, {
        template: 'js/partials/modal-dialog.phtml',
    });
```

If I want to change a footer, I will do that explicitly changing main template.

**Comment by daniel-nalbach** [comment]
Old discussion, but I see this code still in the source, so I think it's still a relevant conversation. 

It seems like dropping the footer should just be a boolean config option, not a hardcoded part of the contentTemplate code. 

Additionally, a footerTemplate would be useful. Sometimes you just want simple text in your modal, but customized buttons that lead to specialized actions.
