### ISSUE TITLE
Change select text

### ISSUE THREAD

**Issue by AlejandroDelRioAlbrechet** [mgcrea/angular-strap#614]
Hi Guys today I have faced problem with changing ng strap select text

I do not want it to be "Choose among the following... " 
I want to have possibility to change it to any another text for example "Choose vegetable"

Maybe such option is already developed but I did not manage to find it.

**Comment by gyss** [comment]
This is not a solution for the multiple items select. The default value is like another more item and you can deselect it. If you deselect all items then you get the same text "Choose among the following...". And if you select 4 or more items then the text "X selected" is displayed.

This is in general a poor solution. I think that there's a need of a internationalization file  for translate all these strings to different locations.

**Comment by AlejandroDelRioAlbrechet** [comment]
Ok we can reopen issue

**Comment by sl0w0rm** [comment]
You can set data-placeholder="My custom text" and it will show this when nothing is selected
