### ISSUE TITLE
Feature / bs-select : keyboard alpha/numeric navigation

### ISSUE THREAD

**Issue by benbenwilde** [mgcrea/angular-strap#619]
Sorry in advance if this is a duplicate.

This is a feature request for keyboard alpha/numeric navigation for bs-select.
Would like to see it work just like the default html select when hitting alpha/numeric keys on the keyboard.

For example, lets say you have 3 options (bob, bill, ali, nick, 103).
- **Scenario 1:** Hitting 'b' on the keyboard selects 'bob'. Then hitting 'b' again selects 'bill'.
- **Scenario 2:** Hitting 'b' on the keyboard selects 'bob'. Then hitting 'o' keeps 'bob' selected. then hitting 'a' starts over because of no match and selects 'ali'. Then hitting '1' starts over and selects '103'.
- **Scenario 3:** Hitting 'b on the keyboard selects 'bob'. Then hitting 'i' selects 'bill'. Then hitting 'l' keeps 'bill' selected.

This is just what I've come up with while using a regular html select. I don't know where the real specifications are, but even something like this would be really nice.

Good use cases: Select box for choosing state, country, month or year. I'm sure theres many more!

**Comment by twogood** [comment]
+1
