### ISSUE TITLE
Modal allowing page scroll

### ISSUE THREAD

**Issue by diego-vieira** [mgcrea/angular-strap#635]
Awesome work you did, thanks.

One issue I notice is that when you open the modal, and you try to scroll, it'll scroll the whole page instead of only the modal.
e.g http://getbootstrap.com/javascript/#modals

http://run.plnkr.co/N6L6VawW7olcaUIL/

**Comment by DaleWebb** [comment]
You can modify the CSS class attached to the body to prevent the body from scrolling
