### ISSUE TITLE
Unable to type in input while using bs-typeahead 

### ISSUE THREAD

**Issue by jdury** [mgcrea/angular-strap#647]
When using a bs-typeahead, it is impossible to type in input on mobile devices.

Reproducible at http://mgcrea.github.io/angular-strap/##typeaheads

Device : Nexus 4 / Android 4.3 / Chrome (last version 04/04/2014)

**Comment by seanmthompson** [comment]
Any work on this? I realize its a more edge case, but affecting us rather significantly. Seems to be an Android 4.X and 5.X Chrome issue.
