### ISSUE TITLE
Typeahead with object as model behaving inconsistently in Firefox

### ISSUE THREAD

**Issue by nnjpp** [mgcrea/angular-strap#652]
This is reproducible on the demo page (used Firefox 28.0 on both Mac OS X and Windows 7).

In the icon selection demo, selecting an icon should set the model to the corresponding object:
{"value":"Globe","label":"<i class=\"fa fa-globe\"></i> Globe"}

This sometimes works as it does in all other browsers, but about 50% of the time the model value is set to the view value, "Globe".

**Comment by Vanitas1440** [comment]
Any update on this? @nnjpp 's workaround is working nicely with v2.1.6 / Angular v1.3.13

**Comment by ranjansatya** [comment]
Is there any update on this ? This bug is still there in 2.2.0

**Comment by MagicIndustries** [comment]
Is anyone working on this? I have the same problem - trying to use three typeaheads making them related, IE select an option in typeahead 3 and it will auto-select the relevant options in typeahead1 and typeahead2. It works great unless I have previously typed into one of the typeaheads.

This works:
1) Load page, all typeaheads are empty
2) start typing in typeahead3, select match 
3) typeahead 1 and 2 are auto-selected with the right options.

But if I do this:
1) Load page, all typeaheads are empty
2) start typing in typeahead1, select match.
3) start typing in typeahead3, select match
4) typeahead 2 is auto-selected with the right option, typeahead 1 remains on my original selection.

OR
1) Load page, all typeaheads are empty
2) start typing in typeahead1, backspace until the text box is empty.
3) start typing in typeahead3, select match
4) typeahead 2 is auto-selected with the right option, typeahead 1 remains empty.

Essentially whatever I try to tweak, it works UNLESS a typeahead has previously had something typed into it. If I just load the page and keep changing typeahead3's selection, the rest update fine, but stop when I manually enter text in, even if I remove it afterward.

I'm assuming it's something to do with checking whether there was a previously stored value, but I can't seem to find the right bit of underlying code to fiddle with.

**Comment by just-boris** [comment]
I think that would be better to get rid of storing matched value in the ngModel at all. It is counter-intuitive: if you matched a suggested value, you will get an object, if there is no match, you will get a raw string.

It is better to have `ngModel` with input value all time, but suggested object can be caught in the `$typehead.select` listener. It would make things in the code of typeahead more simpler.

**Comment by ansonkao** [comment]
@just-boris FANTASTIC suggestion. I love it. If the developer wants to manually overwrite the ngModel with the matched selection, let them do it at their own discretion! +1
