### ISSUE TITLE
[Tooltip] element is undefined [SOLVED]

### ISSUE THREAD

**Issue by jrschumacher** [mgcrea/angular-strap#682]
Occurrence where [element](https://github.com/mgcrea/angular-strap/blob/master/src/tooltip/tooltip.js#L121-L122) is not defined.

Angular-strap v2.0.1

```
TypeError: undefined is not a function
    at http://localhost:8081/bower_components/angular-strap/dist/angular-strap.js:3178:23
    at Array.forEach (native)
    at Object.q [as forEach] (http://localhost:8081/bower_components/angular/angular.min.js:7:280)
    at Object.angular.module.provider.$get.$tooltip.init (http://localhost:8081/bower_components/angular-strap/dist/angular-strap.js:3174:19)
```

**Comment by nottinhill** [comment]
What if I need both ui-bootstrap and angular-strap in my project?

**Comment by jrschumacher** [comment]
@notinhill so you will want to selectively include UI-Bootstrap and/or Angular-Strap. For instance this specifically had an issue with the modal. So I still use UI-Bootstrap tabs but do not include the modal

```
angular.module('app', ['mgcrea.ngStrap', 'ui.bootstrap.accordion']);
```
_Now you just need to keep in mind that some of these have dependancies which may conflict._

Your other options are to break your app down into smaller modules

```
var appNav = angular.module('app.nav', ['ui.bootstrap']).config();
var appContent = angular.module('app.content', ['mgcrea.ngStrap']).config();
var app = angular.module('app', ['app.nav', 'app.content']).config();
```

In this way the dependancies should only be injected into the various pieces and not cause issues.

**Comment by wired00** [comment]
@jrschumacher, very greatful, that was the problem for me too, in my case this project is using mgcrea.ngStrap.select, when i removed that, popover started working perfectly. Is there a later version of either angular which works?

**Comment by jrschumacher** [comment]
@wired00 I'm not sure I understand your question.

**Comment by wired00** [comment]
@jrschumacher sorry that was terribly worded. I was simply stating that commenting "mgcrea.ngStrap.select" worked for me. However it would be nice if there was some sort of fix in the future.

**Comment by nottinhill** [comment]
To make this fully compatible with `ui.bootstrap` would be on my request list as well.

**Comment by jrschumacher** [comment]
I think the quickest solution would be to make a build script which changed directives like `$modal` to `asModal`. This way the library can remain the same without major breaking change and work with UI bootstrap. Or similarly UI bootstrap could also have a build script to do the same.
