### ISSUE TITLE
Is it possible to use ng-click on a dropdown item?

### ISSUE THREAD

**Issue by samstr** [mgcrea/angular-strap#689]
```
$scope.dropdown = [
  {
    'text': 'Logout',
    'href': 'logout()',
  }
];

$scope.logout = function() {
  console.log('logging you out');
};
```

This doesn't work as I'd expect. I can't seem to call $scope.logout() on that item because we need ng-click, not ng-href. This [http://stackoverflow.com/questions/21001920/calling-angularjs-scope-function-from-href](mad hack) seems ridiculous.

Any thoughts/suggestions?

**Comment by amahfouz** [comment]
Did 'click' ever work for you?
