### ISSUE TITLE
Modal with promise result

### ISSUE THREAD

**Issue by vipetrul** [mgcrea/angular-strap#692]
I'm trying to implement following scenario:

Before record is deleted, a modal window is displayed where user specifies the reason.

In angular-ui this is an easy scenario, because in their implementation I get a promise when modal is created, and then modal window controls how this promise should be resolved.

How would you recommend implementing similar scenario using angularStrap?

Thank You

**Comment by henry74** [comment]
@maxavi Plunker demo doesn't seem to be working for me.  When I click on the Delete User button nothing happens.

**Comment by eporral1** [comment]
@mgcrea, thank you for the plunker

how can I  set this values from my controller ?

scope.title = 'confirm';
scope.content = 'Confirm deletion?';

This would make the service more reusable

Thanks!!!

**Comment by pascalcarmoni** [comment]
How you listen for modal hide?
This not working...


`    $scope.$on('modal.hide', function (m) {

                            console.log('close it!');

                        });`

**Comment by guzhiji** [comment]
http://embed.plnkr.co/C1FemAYqjWK3rBReGaCD/

```
  $scope.delete = function() {
    $confirm({
      title: 'Confirm',
      content: 'Are you sure?'
    }).then(function(res) {
      console.log(res);
      $scope.answer = res;
    });
  };
```


http://embed.plnkr.co/6LTBYBDZFanNqqNiyNU2/

```
  $scope.delete = function() {
    $confirm({
      title: 'Confirm',
      content: 'Are you sure?'
    }).then(
      function() {$scope.answer = 'yes';},
      function() {$scope.answer = 'no';}
    );
  };
```
