### ISSUE TITLE
Typeahead tab keydown event

### ISSUE THREAD

**Issue by terryx** [mgcrea/angular-strap#694]
How to make typeahead select the option when tab of keyboard is detected ?

**Comment by alexborisov** [comment]
Any update on this issue? It's been in review since November. It's a blocking issue so my choice it to fork and patch or seek an alternative library.

**Comment by vmlf01** [comment]
I don't think there have been any pull requests for this. Anyway, you can select using the ENTER key, which for me personally is more of an action key than the TAB, which is a navigation key.
