### ISSUE TITLE
Global App Config

### ISSUE THREAD

**Issue by brab** [mgcrea/angular-strap#72]
It would be great if configs could be set globally for the app instead of individually for each instance. For example, setting the date format for datepickers. Angular-UI does this and I find it very convenient.

``` javascript
var myApp = angular.module('myApp', ['$strap'])
  .value('$strap.config', {
    datepicker: {
      format: 'M d, yyyy'
    }
  });
```

**Comment by shanoy** [comment]
I think this is still not possible. It just provides $datepickerProvider which is not sufficient enough. Usecase: user wants to change global date format on all inputs with datepicker. It should use format from server (api call). How would you solve this? Thx
