### ISSUE TITLE
Documentation on how to use trigger=manual is missing

### ISSUE THREAD

**Issue by denisvmedia** [mgcrea/angular-strap#723]
I was going to use trigger=manual for $datepicker and $timepicker, but found no information on this. Assume, that I have an input with bs-datepicker attribute and the trigger . How can I manually show/hide the datepicker (using a button attached to the input, for example)?

Here is the markup:

``` html
<input ng-model="sharedDate" data-autoclose="1" data-trigger="manual" placeholder="Date" bs-datepicker type="text" />
<button>Trigger it!</button>
```

What should I do with the button?

**Comment by c-johnson** [comment]
Was this ever resolved?

**Comment by billyaraujo** [comment]
Is this in the current release?

**Comment by Tibfib** [comment]
This is quite a bit later, but I'm seeing the same issue that @billyaraujo talked about. Manual tooltip appears in different spot than 'hover' trigger.
