### ISSUE TITLE
Accept template string modal

### ISSUE THREAD

**Issue by activars** [mgcrea/angular-strap#732]
Do you think that `template` options should also accept template string like `"<div>....</div>"`.

This would be useful, use-case would be options of using other template cache instead of the builtin $templateCache.

Option line:
https://github.com/mgcrea/angular-strap/blob/master/src/modal/modal.js#L13

**Comment by scottopherson** [comment]
+1

I was hoping to have this functionality with a Browserify project I was working on recently:

    var modal = $modal({ template: require('path/to/template.html'), ... });

**Comment by mgcrea** [comment]
Finally took the time to backport the `bsCompiler` from angular-material's project. You can now use `controller`, `controllerAs`, `templateUrl` and `template` options in your modal and derivatives. Hope it solves most of the issues you encountered with AngularStrap's modals.

**Comment by scottopherson** [comment]
Awesome :+1:

**Comment by stas-o** [comment]
@scottopherson  It it possible to do something like this? I am using a webpack and looks like this doesn't work.

`$modal({
	template:  require('./template.html'),
	show: true
});`

**Comment by stas-o** [comment]
Sorry for disturbing. I have update angular-strap and now it works perfect. Thank you anyway.
