### ISSUE TITLE
Navbar active element

### ISSUE THREAD

**Issue by sahat** [mgcrea/angular-strap#738]
**Home** link should not be active when navigating to **Page 1** and **Page 2**.

Instead of:
```
<li data-match-route="/?(navbar)?"><a href="#/">Home</a></li>
```

documentaton should be updated to:
```
<li data-match-route="/$"><a href="#/">Home</a></li>
```

I am not even sure what is `?(navbar)?` supposed to do in this case?

**Comment by vmlf01** [comment]
Submiting PR #1465 to change docs according to comments. Please bear in mind that the route rules used will depend on your own routes and you can use whatever test conditions you want.
