### ISSUE TITLE
bs-select => cannot set property 'top' of undefined

### ISSUE THREAD

**Issue by davisford** [mgcrea/angular-strap#759]
Using bs-select from angular-strap 2.0.2

![screen shot 2014-05-12 at 12 55 49 pm](https://cloud.githubusercontent.com/assets/186677/2947452/68ded14a-d9f6-11e3-8b68-67cf1b90f79d.png)

I hit this stack trace.  I'm loading the full library, not individual directives.  Am I missing some other dependency?

Here is where it blows up:

![screen shot 2014-05-12 at 12 59 10 pm](https://cloud.githubusercontent.com/assets/186677/2947487/cf4d675c-d9f6-11e3-80e3-b1b1a715cbb3.png)

JQLite index 0 `this[0]` appears to be a comment

The bs-select directive does display correctly when the page loads.  It correctly shows the multiply selected elements, but when I click to drop-down, it blows up here.

The HTML for the select element is as follows:

``` html
<button bs-select="bs-select" type="button" ng-model="user.roles" data-html="1" data-multiple="1" ng-options="i for i in roles.roles" class="btn btn-default ng-pristine ng-valid">user, admin, superuser&nbsp;<span class="caret"></span></button>
```

**Comment by ekaram** [comment]
I also saw this error, but on popover, not select.  I had no comments in my template file, but found it was caused by an extra </div> tag
