### ISSUE TITLE
mousedown on select element prevents touch scroll

### ISSUE THREAD

**Issue by nnjpp** [mgcrea/angular-strap#780]
$select.onMouseDown prevents default and fires a click. If you are using a select with a large amount of elements and want to use a height limit + overflow-y:scroll , you will run into issues scrolling on touch devices without a selection being made. 

I haven't tested this extensively, but the iOS emulator seems to work fine without onMouseDown. I'm not sure if there's a specific issue it is trying to resolve, or if it's just there to make the selection feel quicker, but my current workaround is to remove it completely.

edit: I'm currently keeping preventDefault on non-touch to prevent blur issues.

```
$select.$onMouseDown = function (evt) {
  // Prevent blur on mousedown on .dropdown-menu
  if (!isTouch) {
    evt.preventDefault();
    evt.stopPropagation();
  }
};
```

**Comment by gkontokotsios** [comment]
@nnjpp  I am also experiencing this exact same issue.

**Comment by juliepranger** [comment]
:+1:  I had this same issue. Regardless of the CSS workarounds that suggested adding overflow: auto, I found that the issue was more closely linked to the touch versus click event handling in the $onMouseDown method. I used the same solution above (full method used below):
```
        $select.$onMouseDown = function(evt) {
          if (isTouch) {
            var targetEl = angular.element(evt.target);
            targetEl.triggerHandler('click');
          } else {
            evt.preventDefault();
            evt.stopPropagation();
          }
        };
```
