### ISSUE TITLE
Dropdown autoposition on screen bounds

### ISSUE THREAD

**Issue by overloadnn** [mgcrea/angular-strap#784]
When the drop-down is triggered by an element on the right edge of the viewport, the drop-down is out of screen. It would be nice to auto-detect the screen bound and display the down-down accordingly.

![screenhunter_05 may 23 07 38](https://cloud.githubusercontent.com/assets/5198846/3065690/60e5bb98-e266-11e3-93a9-75f667b5f6ad.jpg)

**Comment by vmlf01** [comment]
I think this is fixed in latest version, no?
