### ISSUE TITLE
proposal(datepicker): split into two components: datepicker and calendar

### ISSUE THREAD

**Issue by g00fy-** [mgcrea/angular-strap#789]
I am the author of [angular-datepicker](https://github.com/g00fy-/angular-datepicker) and I wanted to rewrite the whole component from the ground up, but I found that most of the things I wanted to implement are already in angular-strap. Some features are missing though. The main reason for this is that the datepickear and the clendar inside it are actually a one component.

Woud it be possible refactor some code in order to:

1.  split datepicker into two components
2.  add hour and minute view 
3.  refactor datepicker/calendar in the way that it would allow providing custom templates during config time - not runtime. Example:

```javascript
angular.module('custom',[])
  .directive('customDatepicker', function(datePickerDirective){
    return angular.extend({},datePickerDirective[0],{templateUrl:'myTemplate.html'});
  })
```

**Comment by rzschech** [comment]
This is a duplicate of #430
