### ISSUE TITLE
Hard coded separator in time picker

### ISSUE THREAD

**Issue by danielAtAditro** [mgcrea/angular-strap#794]
Separator for time format is hard coded to colon. There are cultures that uses other (see angular\i18n\angular-locale_fi-fi.js where period is used), this causes exception and non functioning time picker.

**Comment by vmlf01** [comment]
Can anyone confirm if this still is the case? I think recent versions of Angular Strap might have fixed this. I see from looking at code that date formatter seems to be looking for both ':' and '.' as separator.
