### ISSUE TITLE
bootstrap confilct

### ISSUE THREAD

**Issue by drtobal** [mgcrea/angular-strap#796]
i use bootstrap.js and angular-strap.js on my page, but when i include bootstrap.js they have conflicts, example

http://stackoverflow.com/questions/23613450/angular-strap-radio-button-wont-update-model

how to solve it?
thanks

**Comment by dedlfix** [comment]
Documentation only says "no external dependency except the Bootstrap CSS styles," but that is only half of the truth. You should warn to not load bootstrap.js. This can safe hours of troubleshooting!
