### ISSUE TITLE
Using typeahead updater to capture item selection event during type ahead

### ISSUE THREAD

**Issue by divyakumarjain** [mgcrea/angular-strap#81]
Need a way to capture updater event of bootstrap typeahead so that custom event handling can be added.

element.typeahead({
        source: function(query) { return angular.isFunction(value) ? value.apply(null, arguments) : value; },
        minLength: attrs.minLength || 1,
        items: attrs.items,
        <b>updater</b>: function(value) {
          // If we have a controller (i.e. ngModelController) then wire it up
          if(modelController) {
            scope.$apply(function () {
                modelController.$setViewValue(value);
            });
          }
          return value;
        }
      });

**Comment by shafi-shaikat** [comment]
@mschering thanks mate. That works well. Is there any way to do this for multiple typeahead on a single form?

**Comment by vmlf01** [comment]
The typeahead has an updated event signature, where it will pass the typeahead instance as a third parameter, so it would be like:
```
$scope.$on('$typeahead.select', function(value, index, senderInstance){
    console.log(value);
    console.log(index);
    console.log(senderInstance.$id);
 });
```

That combined with the ```id``` attribute allows you to check which instance is calling the event handler.

**Comment by Freezystem** [comment]
Actually, as of version 2.2.2, attributes are like :

$scope.$on('$typeahead.select', function(event, value, index, elem){
        console.log(event); // event properties
        console.log(value); // value of select
        console.log(index); // index of ... something ?
        console.log(elem); // properties of calling element ($id to get the id)
});

**Comment by vmlf01** [comment]
Sorry, my mistake. It always had the ```event``` param in first place, it is angular's listener signature.

**Comment by angelxmoreno** [comment]
@Freezystem that `index` seems to be the index of the dropdown when selected.

**Comment by Freezystem** [comment]
@angelxmoreno  Yeah precisely. I'll update my post. Thanks

**Comment by seanmthompson** [comment]
I would suggest putting the events in the docs. Great library, and thanks!

**Comment by navid-dada** [comment]
but what if i have multi type head in my form??? how can create different between those?
in modal we have event-prefix but we dont have this in typehead. :(
