### ISSUE TITLE
error Cannot read property 'toLowerCase' of undefined in line 3124 when i use bspopover

### ISSUE THREAD

**Issue by Alirz** [mgcrea/angular-strap#826]
Hi
I am use bspopover with tamplate like your sample but when call tooltip module in line 3124 first time element[0] has an object but second time element = "popover"

**Comment by bsigalov** [comment]
+1 for renaming $tooltip to $bsTooltip.
And it's working great.

**Comment by Maangs** [comment]
I'm having the same problem, using angular-strap with ui-bootstrap. But I tried to change $tooltip to $bsTooltip but it won't work for me.
I've only the min.js included and as far as I can see, $tooltip is use twice, so I changed it on those two places. Is there anything else I need to do?

**Comment by tjsail33** [comment]
@Maangs you should use the source file, CMD/CTRL-F to find all uses of $tooltip, and then rebuild from the source. Minification will change some instances of $tooltip to regular variables in certain cases.

**Comment by Maangs** [comment]
Ok... But I have only the minified tooltip in my project?

**Comment by tjsail33** [comment]
https://github.com/mgcrea/angular-strap/blob/master/src/tooltip/tooltip.js

**Comment by Maangs** [comment]
I really like that you're helping me, but just giving me the link dosen't help much. Do I have to include that file too?

**Comment by jbmyid** [comment]
+1 for renaming $tooltip to $bsTooltip.
And it's working great.

**Comment by sistemanick** [comment]
+1 for renaming $tooltip to $bsTooltip. Not a big change to port over to future upgrades, and hopefully I can wean off ui.bootstrap al-together in the near future.

**Comment by rcrodrigues** [comment]
+1 fore renaming $tooltip to $bsTooltip. This works great for me.

**Comment by rcrodrigues** [comment]
+1 for renaming $tooltip to $bsTooltip. This works great for me.

**Comment by idoo** [comment]
+1

**Comment by agustinjlopez** [comment]
+1

**Comment by RedDude** [comment]
+1

**Comment by serdarbasol** [comment]
+1

**Comment by lluiscanals** [comment]
+1

**Comment by mwiley63** [comment]
+1

**Comment by flouc001** [comment]
+1 - I've found a few conflicts between ui-bootstrap and angular-strap and they are not always trivial. Luckily Github has managed to save me some time on this occasion :+1:

**Comment by dacsy** [comment]
I have the same issues when I use bs-tooltip.
Could you explain more about the way you all resolved this issues ?

**Comment by flouc001** [comment]
@dacsy go to your source file (for example `angular-strap.min.js`) and use your favourite text editor to find and replace all of the occurrences of "$tooltip" to "$bsTooltip". Then when you want to use the tooltip on one of your pages make sure to use the syntax $bsTooltip instead of $tooltip. This fix basically ensures there are no conflicts going on between loaded libraries. Hope I have explained it clearly enough :)

**Comment by dacsy** [comment]
@flouc001 thank you for your response, it's clear enough for me. But currently, I am using tooltip of angularstrap:
`<span data-title="{{item.id}}" bs-tooltip delay="500"> </span>`
I don't really touch the $tooltip variable.
I also did try replaced $tooltip by $bstooltip in my ` angular-strap.js ` file but it doesn't effect anything. Seems it's not the same case with other :(

**Comment by flouc001** [comment]
@dacsy what you are using is the angular strap directive for the tooltip. I think what may have gone wrong is the casing you used when you was doing a find and replace. The syntax of angularjs dictates that when a directive is defined in the code, if you use camel casing it will become hyphenated in the html code. For example if I declared `$bsTooltip` In the code I would use it as `bs-tooltip` In the html. Can you check that when you did the find and replace you used the correct cased replacements?

**Comment by livertonli12** [comment]
Thank you very much . Changing $tooltip to $bstooltip worked for me.
