### ISSUE TITLE
Angular strap modal popup does not stop tabbing on the background 

### ISSUE THREAD

**Issue by yogeshp** [mgcrea/angular-strap#839]
Hi,

We are using angular-strap(v 2.0.0) with bootstrap css. In our application we are allowing user to use tab key to navigate UI. However tab focus goes in background when user pressing TAB key on modal popup i.e. modal does not stop tabbing on the background.

We found same behavior in samples provided on "http://mgcrea.github.io/angular-strap/" when popup opened and user press TAB key after some tabbing it goes in background.

Any suggestions on that ?

**Comment by mnemanja** [comment]
So, it's been a year, and still no solution for this problem?

Have any of you guys fixed this issue? I can still see it on the website http://mgcrea.github.io/angular-strap/#/modals

**Comment by upasana-shah** [comment]
Any solution for this issue?
