### ISSUE TITLE
bsDatepicker - digest loop when typing in invalid date

### ISSUE THREAD

**Issue by jkjustjoshing** [mgcrea/angular-strap#844]
To reproduce this bug, create a min-date or max-date defined on a datepicker, and have no initial value bound via ng-model, Focus on the datepicker and manually type in a date that falls outside the min-date/max-date range.

There will be a "10 $digest iterations reached" error".

This only happens once after load. Once a valid date has been selected once or the digest error happens once it won't happen again until a refresh is performed.

Visible at http://plnkr.co/edit/AzLF1t3wSU1nLaLs1qyf?p=preview (try entering date "18/06/2014")

**Comment by vmlf01** [comment]
This problem seems to be fixed in Angular 1.2.23.
