### ISSUE TITLE
Datepicker with data-type=string and range

### ISSUE THREAD

**Issue by jgoux** [mgcrea/angular-strap#865]
Hi,
I want to set up a range of date between two inputs, but I have an issue when I want to select the same date in my inputs.
With data-type=date, I am able to select the same date, but with data-type=string, I can't.
How can I select the same date with data-type=string ? 
Thanks in advance.

EDIT : After several test, it sounds that the problem comes from the 'min-date' attribute, because I am able to select the same date from the input which have the "max-date" property.

**Comment by equilerex** [comment]
Seems to be an issue if you mix together data-type=string and  model-date-format="dd-MM-yyyy" (or what ever else)
the min/max range seems to ignore the model-date-format and treats the date as if it was MM-dd-yyyy (which obviously makes the daterange go nuts)

**Comment by equilerex** [comment]
since theres still no fix, heres a rough work-around for those in need:

```
.filter('dateRangeFix', function() {
        return function(input, type) { 
            var output = input;
            //select format
            if(type === 'timestamp') { 
                output = moment(input, "DD-MM-YYYY hh:mm:ss").format("MM.DD.YYYY hh:mm:ss");
            } else if (type === 'date') { 
                output = moment(input, "DD-MM-YYYY").format("MM.DD.YYYY");
            } 
            return output;
        }
    });
``` 
and then in html:
``` 
data-max-date="{{tab.data.maxTimestamp | dateRangeFix : 'timestamp'}}"
``` 
(using moment.js in there since i already had it included but should be a simple to use split or regex to just shuffle the MM/DD/YYYY around dependent on your format
