### ISSUE TITLE
typeahead - load data and open dropdown on focus

### ISSUE THREAD

**Issue by robotnic** [mgcrea/angular-strap#878]
Hi all

I want to load data from server when the the input gets focus and open the typeahead dropdown.

http://plnkr.co/edit/FFCQzLdhP8oaw9xvPERn?p=preview

It nearly works, but the first click does not open the dropdown.
How to open the dropdown when the http response is available?

**Comment by DaleWebb** [comment]
There was a built-in filter that would only show results that had a partial match on the input.  You can disable this by specifying the attribute `data-filter="false"`.

That will give you the behaviour that you want.
