### ISSUE TITLE
No refference to the input field in $typeahead.select

### ISSUE THREAD

**Issue by Maidomax** [mgcrea/angular-strap#879]
If I have several typeahead inputs in the same template/$scope, I have no way of figuring out which input triggered the event from the event listener.

```
$rootScope.$on('$typeahead.select', function(evt, value, index) {
        // in here I have no idea which typeahead emitted the event
});
```

Maybe it's just because the documentation is incomplete, that I'm missing something obvious...

**Comment by vmlf01** [comment]
Added in 635600c.
