### ISSUE TITLE
Datepicker on Mobile Device

### ISSUE THREAD

**Issue by rbinsztock** [mgcrea/angular-strap#882]
I use Datepicker with view open to year, he works nice on desktop, but on mobile device when I click on item inside the datepicker it's always do a twice click. I think the problem come from here : https://github.com/mgcrea/angular-strap/blob/master/src/datepicker/datepicker.js#L147 . I use Phonegap to build my project for mobile device.

**Comment by noldotar** [comment]
Still buggy…

**Comment by dragan-mirkovic** [comment]
I have the same problem, is there any solution for this?
