### ISSUE TITLE
Positioning alert inside modal

### ISSUE THREAD

**Issue by AlexAbraham1** [mgcrea/angular-strap#896]
Hey I am having a little bit of trouble and was hoping someone could help me out,

I have a modal with a form inside it and if there is am error with the form I want to display an alert. Right now if there is an error i create an alert object in the controller and show it. That works fine, but the alert is displayed at the top-right of the page. I want it to be displayed in the top-right of the modal window. I tried using containers but they didn't seem to work for me.

Does anyone have a similar issue or know how to solve it?

Thanks!

**Comment by DaleWebb** [comment]
I believe this would be to do with the CSS, where the `.alert` will have a `position: fixed;`.  You should change that to `position: static;` for it to stay within the bounds of the container
