### ISSUE TITLE
Datepicker doesn't accept zero-less dates

### ISSUE THREAD

**Issue by smuellerus** [mgcrea/angular-strap#901]
Datepicker does not accept input dates like "1.7.2014" with a format of 'dd.MM.yyyy'.

Also, how can I get rid of the leading zero in the month view - all days < 10 are prefixed with a 0.

Thanks.

**Comment by Zacharias3690** [comment]
+1

**Comment by joaoborsoi** [comment]
+1

**Comment by joaoborsoi** [comment]
I think the parser should accept all variations. If you put yy it should accept 4 digit years when typing. Iff you put yyyy it should accept 2 digit years also. It should be flexible for people who wants to type instead of use the picker.

**Comment by sistemanick** [comment]
+1

Something similar to ExtJS's "altFormats" feature would be really nice. It allows you to configure the datepicker to accept as many formats as you want, for e.g. you can set the display format to "dd/MM/yyyy", and specify alternate input formats like ddMMyyyy, dd.MM.yyyy, dd-MM-yyyy, etc.
