### ISSUE TITLE
$select hides selection popup on mousedown preventing value selection

### ISSUE THREAD

**Issue by ptMuta** [mgcrea/angular-strap#916]
Creating a select from an input with trigger set to `focus` creates an issue where the value selection popup hides on mousedown before setting the selected value causing the element to become inoperable.

The $select fuctions well with `click` but without a off-element click hook to compensate for the lack of hiding popup on selection event or off-element click makes the element for a bad user experience.

**Comment by vmlf01** [comment]
I cannot replicate this, really needs a test case.
