### ISSUE TITLE
Update directive on locale change

### ISSUE THREAD

**Issue by frapontillo** [mgcrea/angular-strap#919]
If the `$locale` is dinamically re-injected (see https://github.com/lgalfaso/angular-dynamic-locale), I'd like the datepicker to be able to update itself. This could easily be done by watching `$locale.id` and refreshing the model/view.

**Comment by linslin** [comment]
A solution: http://stackoverflow.com/questions/42162394/how-to-change-dynamic-language-in-angular-strap-datepicker But I recommend that angular-strap should watch the locale change and make all directives, which support `$locale`, rerendered when the locale changed.
