### ISSUE TITLE
datePicker and timePicker show calendar when ng-readonly="true"

### ISSUE THREAD

**Issue by Gillardo** [mgcrea/angular-strap#946]
as the title says, the datePicker and timePicker both show the calendar controls even if they are using ng-readonly="true".  And upon selecting a value, it is actually set in the textbox which uses ng-model.

I believe the calendars should not disable at all.  The inputs are correctly not allowing a user to type which is correct

**Comment by gnicol-bzh** [comment]
Similar problem with:
```html
<input bs-datepicker disabled [...] >
```
The date chosen in the calendar changes the date in the disabled input. It shouldn't when it's disabled :)
