### ISSUE TITLE
Modal content is not getting the focus

### ISSUE THREAD

**Issue by anilali83** [mgcrea/angular-strap#962]
When the modal is open, the focus stays on the element that started the modal. Due to this one can continue to hit enter and see the content template getting appended repeatedly.

Steps To Reproduce:
Open plnkr: http://plnkr.co/edit/E9xAm8QJmpZalLBFDYXz?p=preview
Click on the button
Hit enter repeatedly

**Comment by FindBoat** [comment]
@anilali83 Did you figure this out? I'm having the same issue that when modal is open, the focus stays on the element that triggers the modal.

**Comment by kchima** [comment]
Any progress on this? I'm having the same problem as well. 

http://newsbrute.com/#/?pageNumber=0

I know it's not a plunkr, but click on any of the articles. The modal/aside comes up, but you must click on the modal before ESC keyboard input will close the modal/aside. I un-minified/uglified the angular-strap code. I've tried to remove every unnecessary element but I just can't get a working example from scratch where the modal/aside gets focus automatically.
