### ISSUE TITLE
typeahead-editable="false"

### ISSUE THREAD

**Issue by spj** [mgcrea/angular-strap#984]
does angular-strap typeahead has a similar feature as typeahead-editable="false" does in angular-ui boostrap typeahead?

if no, how to implement one?

thanks,

**Comment by georgebarbarosie** [comment]
selectMode=false does part of the job but it does not invalidate the input.

Adapted from the plunker in the docs: http://plnkr.co/edit/zYL1z5eeMirO2MBsIFqx?p=preview

**Comment by georgebarbarosie** [comment]
I've updated the example from the previous plunker with a modified typeahead directive that implements the correct (IMHO) directive for selectMode=true:

http://plnkr.co/edit/zPxHvtmfvGeSD6GG3EaK?p=preview

The changes in the direcive: 
- setting the view value to delete last character when selectMode=true and no options available applied with scope.$applyAsync() to prevent infinite digest loop
- expose $typeahead.getActiveIndex() to be used in bsTypeAhead
- if selectMode=true bind a function on element blur to either select the active option or set the view model to empty

**Comment by dmitriz** [comment]
Angular UI `typeahead` with `typeahead-editable="false"` does not prevent user from typing. It can only invalidate the model and set it to `undefined`. I've submitted a PR to update the description there:

https://github.com/angular-ui/bootstrap/pull/3572/files#diff-0b60ff012eac4dea7d219af42bc78977L27

**Comment by jukkasi** [comment]
+1
