### ISSUE TITLE
Add search for select directive, for long lists.

### ISSUE THREAD

**Issue by rodrigolima-7** [mgcrea/angular-strap#985]
Please, add search to the select directive. Some of my select list have thousands of entries. A good example is the Bootstrap-Select (http://silviomoreto.github.io/bootstrap-select/).

**Comment by kinnrot** [comment]
+1

**Comment by gizbo** [comment]
Hi,
     I'm looking for the same feature. I added a text input the select template and bind the value to scope variable and apply a filter on ng-repeat li element.  If I allow the default behaviour while stopping propagation (~lines 3015-17) and set a break point it seem to work but I can't get it to close after... 
Help help 
Thanks so much,
Yves

**Comment by rzschech** [comment]
+1
