### ISSUE TITLE
Dropdown documentation & example is misleading / Doesn't work as shown

### ISSUE THREAD

**Issue by ee-usgs** [mgcrea/angular-strap#998]
The docs for the Dropdown have some issues:
http://mgcrea.github.io/angular-strap/##dropdowns

First, the example that is shown uses HTML in the text of the buttons, which displays correctly on the docs page, but will not display correctly if you copy and paste the html and js.  The example should either not use html in the text field (the best option), or, include the html="true" flag in the list of attributes.  The reason this works in the example is that the docs page sets html:true for the dropdown provider globally.  Also, it looks like html:true requires ngSanitize to be loaded, again making this likely to fail for someone trying it for the first time.

Second, the Dropdown docs state that the tooltip plugin is required, but the link for that goes to the Tooltip directive.  I don't think that is correct, or at least there are no notes there about how to include Tooltip as a plugin.  More confusingly, the Tooltip directive states that it requires the helpers.dimensions plugin.  Does Dropdown require both?  Clicking on the link for helpers.dimensions takes me to the source code for it, which is not helpful for finding out how to include the plugin.  

As a solution to the second issue, I would suggest that each reference to a required plugin include a general link for how to include a plugin and a second link to the source code of that plugin.

Thanks,

ee

**Comment by dwelch2344** [comment]
+1 to this. Just spent a fair amount of time trying to get the demo to work correctly. Coming from Angular-UI's declarative dropdowns this was a major PITA -- though this project is still waaaay better :)
